<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Paypal\Block\Logo
 */
?>

<div class="block paypal acceptance">
    <div class="block-content">
        <a href="#" title="<?php echo __('Additional Options') ?>"
           onclick="javascript:window.open('<?php echo $block->getAboutPaypalPageUrl() ?>','paypal','width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"
           class="action paypal additional">
            <img src="<?php echo $block->escapeHtml($block->getLogoImageUrl()) ?>"
                 alt="<?php echo $block->escapeHtml(__('Additional Options')) ?>"
                 title="<?php echo $block->escapeHtml(__('Additional Options')) ?>" />
        </a>
    </div>
</div>
