<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


/**
 * @var \Magento\Paypal\Block\Logo $block
 * @see \Magento\Paypal\Block\Logo
 */
?>

<div class="block paypal acceptance">
    <div class="block-content">
        <a href="#" title="<?= $block->escapeHtml(__('Additional Options')) ?>"
           onclick="javascript:window.open(
               '<?= $block->escapeUrl($block->getAboutPaypalPageUrl()) ?>',
               'paypal',
               'width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'
               ); return false;"
           class="action paypal additional">
            <img src="<?= $block->escapeUrl($block->getLogoImageUrl()) ?>"
                 alt="<?= $block->escapeHtml(__('Additional Options')) ?>"
                 title="<?= $block->escapeHtml(__('Additional Options')) ?>" />
        </a>
    </div>
</div>
