<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block block-banner">
    <div class="block-content">
        <?php if (strtolower(substr($block->getLinkUrl(), 0, 4)) === 'http'): ?>
            <a href="<?php echo /* @escapeNotVerified */ $block->getLinkUrl() ?>" title="<?php echo /* @escapeNotVerified */ __($block->getImgAlt()) ?>">
        <?php elseif ($block->getLinkUrl()): ?>
            <a href="<?php echo /* @escapeNotVerified */ $block->getUrl($block->getLinkUrl()) ?>" title="<?php echo /* @escapeNotVerified */ __($block->getImgAlt()) ?>">
        <?php endif; ?>
            <img src="<?php echo /* @escapeNotVerified */ $block->getViewFileUrl($block->getImgSrc()) ?>"<?php if (!$block->getLinkUrl()): ?> title="<?php echo /* @escapeNotVerified */ __($block->getImgAlt()) ?>"<?php endif; ?> alt="<?php echo /* @escapeNotVerified */ __($block->getImgAlt()) ?>" />
        <?php if ($block->getLinkUrl()): ?>
        </a>
        <?php endif ?>
    </div>
</div>
