<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */
?>
<div class="block block-banner">
    <div class="block-content">
        <?php if ($block->getLinkUrl() && strtolower(substr($block->getLinkUrl(), 0, 4)) === 'http'): ?>
            <a href="<?= $escaper->escapeUrl($block->getLinkUrl()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__($block->getImgAlt())) ?>">
        <?php elseif ($block->getLinkUrl()): ?>
            <a href="<?= $escaper->escapeUrl($block->getUrl($block->getLinkUrl())) ?>"
               title="<?= $escaper->escapeHtmlAttr(__($block->getImgAlt())) ?>">
        <?php endif; ?>
            <img src="<?= $escaper->escapeUrl($block->getViewFileUrl($block->getImgSrc())) ?>"
                <?php if (!$block->getLinkUrl()): ?>
                    title="<?= $escaper->escapeHtmlAttr(__($block->getImgAlt())) ?>"
                <?php endif; ?>
                 alt="<?= $escaper->escapeHtmlAttr(__($block->getImgAlt())) ?>" />
        <?php if ($block->getLinkUrl()): ?>
        </a>
        <?php endif ?>
    </div>
</div>
