<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Ui\Component\Form\Fieldset $this
 */
$children = $this->getChildren();
$content = $this->getContent();
$ajaxUrl = $this->getAjaxUrl();
?>

<div class="fieldset-wrapper-title" tabindex="3" data-bind="click: onClick, keyboard: { 13: toggle }">
    <strong class="title">
        <span data-bind="text: label"><?php echo $this->getData('config/label'); ?></span>
    </strong>
</div>

<div class="fieldset-wrapper-content">
    <fieldset id="<?php echo $this->getData('index'); ?>" class="fieldset">
        <?php if (!empty($content)): ?>
            <?php echo $content; ?>
        <?php endif; ?>
        <?php if (is_array($children) && !$ajaxUrl): ?>
            <?php foreach ($children as $childName): ?>
                <?php $childElement = $this->getLayoutElement($childName);?>
                <p><?php echo $this->renderElement('group', $childElement); ?></p>
            <?php endforeach; ?>
        <?php endif; ?>
    </fieldset>
</div>
