<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "storage-manager": {
                            "component": "Magento_Catalog/js/storage-manager",
                            "appendTo": "<?php echo /* @escapeNotVerified */ $block->getParentComponentName() ?>",
                            "storagesConfiguration" :
                                         <?php echo /* @escapeNotVerified */ $block->getConfigurationJson() ?>
                        }
                    }
                }
            }
        }
</script>
