<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Catalog\Block\FrontendStorageManager;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var FrontendStorageManager $block */
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "storage-manager": {
                            "component": "Magento_Catalog/js/storage-manager",
                            "appendTo": "<?= $escaper->escapeJs($block->getParentComponentName()) ?>",
                            "storagesConfiguration" : <?= /* @noEscape */ $block->getConfigurationJson() ?>
                        }
                    }
                }
            }
        }
</script>
