<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Payflow\Link\Iframe $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<html>
<head>
</head>
<body>
<?php $scriptString= <<<script

    (function() {
        'use strict';

        function redirect(cartUrl, errorMessage, goToSuccessPage, successUrl) {
            if (!!errorMessage.message) {
                alert(errorMessage.message);
                window.location = cartUrl;
            } else if (!!goToSuccessPage) {
                window.location = successUrl;
            } else {
                window.location = cartUrl;
            }
        }

        var cartUrl = '{$escaper->escapeJs($block->getUrl('checkout/cart'))}',
            successUrl = '{$escaper->escapeJs($block->getUrl('checkout/onepage/success'))}',
            goToSuccessPage = '{$escaper->escapeJs($block->getGotoSuccessPage())}',
            require = window.top.require,
            windowContext = window,
            errorMessage = {
                message: '{$escaper->escapeJs($block->getErrorMsg())}'
            };

        if(typeof(require) == "undefined") {
            redirect(cartUrl, errorMessage, goToSuccessPage, successUrl);
        } else {
            require([
                'underscore',
                'Magento_Paypal/js/model/iframe-redirect'
            ], function(_, iframeRedirect) {
                _.bind(iframeRedirect, windowContext)(cartUrl, errorMessage, goToSuccessPage, successUrl);
            })
        }

    })();

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
</body>
</html>
