<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($block->getChildHtml()): ?>
<div class="admin__fieldset-wrapper order-gift-options">
    <div class="admin__fieldset-wrapper-title"><strong class="title"><?php echo __('Gift Options') ?></strong></div>
    <?php echo $block->getChildHtml() ?>
</div>
<?php endif ?>
