<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if (sizeof($this->getTotals()) > 0): ?>
<table cellspacing="0" class="items-to-invoice">
    <tr>
    <?php foreach ($this->getTotals() as $_total): ?>
        <td <?php if ($_total['grand']): ?>class="grand-total"<?php endif; ?>>
            <?php echo $_total['label'] ?><br />
            <?php echo $_total['value'] ?>
        </td>
    <?php endforeach; ?>
    </tr>
</table>
<?php endif; ?>
