<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!doctype html>
<html <?php echo /* @escapeNotVerified */ $htmlAttributes ?>>
    <head <?php echo /* @escapeNotVerified */ $headAttributes ?>>
        <?php echo /* @escapeNotVerified */ $requireJs ?>
        <?php echo /* @escapeNotVerified */ $headContent ?>
        <?php echo /* @escapeNotVerified */ $headAdditional ?>
    </head>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?php echo /* @escapeNotVerified */ $loaderIcon ?>"}}' <?php echo /* @escapeNotVerified */ $bodyAttributes ?>>
        <?php echo /* @escapeNotVerified */ $layoutContent ?>
    </body>
</html>
