<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
$schema = ($block->getZone() == 'item_view') ? true : false;
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
?>

<?php if ($block->hasSpecialPrice()) : ?>
    <?php
    /** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
    $priceModel = $block->getPriceType('regular_price');

    $finalPriceModel = $block->getPriceType('final_price');
    ?>
    <p class="price-as-configured">
        <span class="special-price">
            <?= $block->escapeHtml(
                $block->renderAmount(
                    $finalPriceModel->getAmount(),
                    [
                        'display_label'     => __('Special Price'),
                        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                        'price_type'        => 'finalPrice',
                        'include_container' => true,
                        'schema' => $schema
                    ]
                ),
                ['span']
            ); ?>
        </span>
        <span class="old-price">
            <?= $block->escapeHtml(
                $block->renderAmount(
                    $priceModel->getAmount(),
                    [
                        'display_label'     => __('Regular Price'),
                        'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                        'price_type'        => 'oldPrice',
                        'include_container' => true,
                        'skip_adjustments'  => true
                    ]
                ),
                ['span']
            ); ?>
        </span>
    </p>
<?php else : ?>
    <?php
    /** @var \Magento\Catalog\Pricing\Price\ConfiguredPrice $configuredPrice */
    $configuredPrice = $block->getPrice();
    $priceLabel = ($block->getPriceLabel() !== null)
        ? $block->getPriceLabel()
        : '';
    ?>
    <p class="price-as-configured">
        <?= $block->escapeHtml(
            $block->renderAmount(
                $configuredPrice->getAmount(),
                [
                    'display_label'     => $priceLabel,
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]
            ),
            ['span']
        ); ?>
    </p>
<?php endif; ?>
