<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
/** @var \Magento\Catalog\Pricing\Price\ConfiguredPrice $configuredPrice */
$configuredPrice = $block->getPrice();
$schema = ($block->getZone() == 'item_view') ? true : false;
$priceLabel = ($block->getPriceLabel() !== null)
    ? $block->getPriceLabel()
    : '';
?>
<p class="price-as-configured">
    <?php if ($configuredPrice->getAmount()->getValue() !== null): ?>
        <?php /* @noEscape */
        echo $block->renderAmount($configuredPrice->getAmount(), [
            'display_label' => $priceLabel,
            'price_id' => $block->getPriceId('product-price-'),
            'price_type' => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    <?php endif; ?>
</p>
