<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


/**
 * @var \Magento\Paypal\Block\Checkout\Onepage\Success\BillingAgreement $block
 */
?>
<p data-mage-init='{"Magento_Paypal/js/in-context/billing-agreement": {"invalidateOnLoad" : true}}'>
    <?= $escaper->escapeHtml(__('Your billing agreement # is: ')) ?>
    <a href="<?= $escaper->escapeUrl($block->getAgreementUrl()) ?>">
        <?= $escaper->escapeHtml($block->getAgreementRefId()) ?>
    </a>.
</p>
