<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link" data-label="<?php echo $block->escapeHtml(__('or')) ?>">
    <a <?php echo /* @noEscape */ $block->getLinkAttributes() ?><?php echo /* @noEscape */ $dataPostParam ?>>
        <?php echo $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
