<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($pageData->getPageMetaKeywords()): ?>
<meta name="keywords" content="<?php /* @escapeNotVerified */ echo $pageData->getPageMetaKeywords() ?>"/>
<?php endif; ?>
<?php if ($pageData->getPageMetaDescription()): ?>
<meta name="description" content="<?php /* @escapeNotVerified */ echo $pageData->getPageMetaDescription() ?>"/>
<?php endif; ?>
