<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $this->getItem() ?>
<?php $_item->setStoreId($_item->getInvoice()->getStoreId()) ?>
<?php $this->setPriceDataObject($_item) ?>
<tr>
    <td class="col-product"><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td class="col-price">
        <?php echo $this->getColumnHtml($_item, 'price'); ?>
    </td>
    <td class="col-qty"><?php echo $_item->getQty()*1 ?></td>
    <td class="col-subtotal">
        <?php echo $this->getColumnHtml($_item, 'subtotal'); ?>
    </td>
    <td class="col-tax"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discount"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?php echo $this->getColumnHtml($_item, 'total'); ?>
    </td>
</tr>
