<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($this->getRating() && $this->getRating()->getSize()): ?>
    <div class="ratings-container">
        <?php foreach ($this->getRating() as $_rating): ?>
        <?php if ($_rating->getPercent()): ?>
            <div class="ratings">
               <?php echo $this->escapeHtml($_rating->getRatingCode()) ?>
                <div class="rating-box">
                    <div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
                </div>
            </div>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <?php echo __("Rating isn't Available") ?>
<?php endif; ?>
