<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/**
 * @var \Magento\Review\Block\Adminhtml\Rating\Summary $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if ($block->getRatingSummary()->getCount()): ?>
    <div class="rating-box">
        <div class="rating"></div>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "width:" . /* @noEscape */ ceil($block->getRatingSummary()->getSum() /
            ($block->getRatingSummary()->getCount())) . "%;",
        'div.rating-box div.rating'
    ) ?>
<?php else: ?>
    <?= $block->escapeHtml(__("Rating isn't Available")) ?>
<?php endif; ?>
