<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Adminhtml\Rating\Summary $block */
?>
<?php if ($block->getRatingSummary()->getCount()): ?>
    <div class="rating-box">
        <div class="rating" style="width:<?php /* @noEscape */ echo ceil($block->getRatingSummary()->getSum() / ($block->getRatingSummary()->getCount())) ?>%;"></div>
    </div>
<?php else: ?>
    <?php echo $block->escapeHtml(__("Rating isn't Available")) ?>
<?php endif; ?>
