<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Files.LineLength, Generic.Files.LineLength

?>

<div class="media-gallery-container">
    <?= $block->getChildHtml(); ?>
</div>

<script type="text/x-magento-init">
    {
        ".media-gallery-container": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "media_gallery_container": {
                        "component": "Magento_MediaGalleryUi/js/container",
                        "containerSelector": ".media-gallery-container",
                        "masonryComponentPath": "media_gallery_listing.media_gallery_listing.media_gallery_columns"
                    }
                }
            }
        }
    }
</script>
