<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var \Magento\Catalog\Block\Category\View $block
 */
?>
<?php if ($_description = $block->getCurrentCategory()->getDescription()) :?>
    <div class="category-description">
        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $_description,
            'description'
        ) ?>
    </div>
<?php endif; ?>
