<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Catalog\Block\Category\Rss\Link;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Link $block */
?>
<?php if ($block->isRssAllowed() && $block->getLink() && $block->isTopCategory()) :?>
    <a href="<?= $escaper->escapeUrl($block->getLink()) ?>"
       class="action link rss"><span><?= $escaper->escapeHtml($block->getLabel()) ?></span></a>
<?php endif; ?>
