<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="nav-bar-outer-actions">
    <div class="outer-actions-inner-wrap">
        <div class="btn-wrap btn-wrap-triangle-right btn-wrap-next">
            <button
                type="button"
                class="btn btn-prime"
                ng-click="nextState()"
                ng-disabled="hasErrors"
                >Next</button>
        </div>
        <div class="btn-wrap btn-wrap-triangle-left btn-wrap-prev">
            <button
                type="button"
                class="btn"
                disabled
                >Back</button>
        </div>
    </div>
</div>

<h2 class="page-title">{{$state.current.header}}</h2>

<div ng-show="$state.is('root.component-grid')" class="accent-box">
    <p>Component Picker information here.</p>
</div>

<div ui-view></div>
