<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="nav-bar-outer-actions">
    <div class="outer-actions-inner-wrap">
        <div class="btn-wrap btn-wrap-triangle-right btn-wrap-next">
            <button
                type="button"
                class="btn btn-prime"
                ng-click="takeBackup()"
                >Next</button>
        </div>
        <div class="btn-wrap btn-wrap-triangle-left btn-wrap-prev">
            <button
                type="button"
                class="btn"
                ng-click="previousState()"
                >Back</button>
        </div>
    </div>
</div>

<h2 class="page-title">{{$state.current.header}}</h2>

<div
    class="message message-error"
    ng-show="takeBackup.result.success === false && takeBackup.result !== undefined"
    >
    <span class="message-text">{{takeBackup.result.error}}</span>
</div>
<div
    class="message message-error"
    ng-show="testConnection.failed !== undefined"
    >
    <span class="message-text">{{takeBackup.failed}}</span>
</div>
<div class="message message-spinner" ng-show="loading">
                <span class="spinner">
                    <span></span><span></span><span></span><span></span>
                    <span></span><span></span><span></span><span></span>
                </span>
    <span class="message-text">Taking backup...</span>
</div>

<form
    novalidate
    name="backup"
    role="form"
    >
    <fieldset class="form-fieldset">
        <label class="form-label" color="#FF8000">
            <b>We will put your store into maintenance mode to protect your shoppers during upgrade </b>
        </label>
        <div class="row form-row">
            <div class="col-m-3">
                <label class="form-label">
                    Backup Options
                </label>
            </div>
            <div class="col-m-4">
                <div class="form-row">
                    <input
                        id="optionsCode"
                        class="form-el-checkbox"
                        type="checkbox"
                        ng-model="backupInfo.options.code"
                        ng-checked="backupInfo.options.code"
                        >
                    <label class="form-label" for="optionsCode">
                        Code
                    </label>
                </div>
                <div class="form-row">
                    <input
                        id="optionsMedia"
                        class="form-el-checkbox"
                        type="checkbox"
                        ng-model="backupInfo.options.media"
                        ng-checked="backupInfo.options.media"
                        >
                    <label class="form-label" for="optionsMedia">
                        Media
                    </label>
                </div>
                <div class="form-row">
                    <input
                        id="optionsDb"
                        class="form-el-checkbox"
                        type="checkbox"
                        ng-model="backupInfo.options.db"
                        ng-checked="backupInfo.options.db"
                        >
                    <label class="form-label" for="optionsDb">
                        Database
                    </label>
                </div>
            </div>
        </div>
    </fieldset>
</form>
