<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="step-controls">
    <a href="" class="btn btn-primary" ng-click="previousState()">Previous</a>
    <a href="" class="btn btn-primary" ng-click="nextState()">Next</a>
</div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<form class="form-horizontal" role="form">
    <div class="form-group">
        <label class="col-md-3 control-label">Sample Data</label>
        <div class="col-md-6">
            <p class="form-control-static text-muted">
                Select “Use Sample Data" to create a sample store with sample products, customers, and payment settings. Our <a target="_blank" href="http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html">Guide to Using Sample Data</a> can help you get started.</p>
        </div>
    </div>

    <div class="form-group">
        <div class="checkbox col-md-4 col-md-offset-3">
            <label>
                <input type="checkbox" ng-model="store.useSampleData" <?php echo $this->isSampledataEnabled ? '' : 'disabled' ?>>&nbsp;<span class="text-muted">Use Sample Data</span>
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-3 control-label">Store Default Time Zone&nbsp;<span class="required">*</span></label>
        <div class="col-md-6">
            <select class="form-control"
                    ng-model="store.timezone"
                    tooltip-placement="right"
                    tooltip-html-unsafe="The time zone in which your online store operates. You can change this later in Magento Admin."
                    tooltip-trigger="focus"
                    tooltip-append-to-body="true">
            <?php foreach ($this->timezone as $value => $label): ?>
                <?php echo "<option value=\"" . $value . "\">" . $label . "</option>"; ?>
            <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-3 control-label">Store Default Currency&nbsp;<span class="required">*</span></label>
        <div class="col-md-5">
            <select class="form-control"
                    ng-model="store.currency"
                    tooltip-placement="right"
                    tooltip-html-unsafe="The currency your store uses for price labeling, checkout, returns, credit and gift cards. You can change this later in Magento Admin."
                    tooltip-trigger="focus"
                    tooltip-append-to-body="true">
            <?php foreach ($this->currency as $value => $label): ?>
                <?php echo "<option value=\"" . $value . "\">" . $label . "</option>"; ?>
            <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-3 control-label">Store Default Language&nbsp;<span class="required">*</span></label>
        <div class="col-md-4">
            <select class="form-control"
                    ng-model="store.language"
                    tooltip-placement="right"
                    tooltip-html-unsafe="The language customers will see in your store. You can change this later in Magento Set Up Tool."
                    tooltip-trigger="focus"
                    tooltip-append-to-body="true">
            <?php foreach ($this->language as $value => $label): ?>
                <?php echo "<option value=\"" . $value . "\">" . $label . "</option>"; ?>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
</form>

<div class="step-controls">
    <a href="" class="btn btn-primary" ng-click="previousState()">Previous</a>
    <a href="" class="btn btn-primary" ng-click="nextState()">Next</a>
</div>
