<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<h2 class="page-title">{{$state.current.header}}</h2>

<div class="message message-error" ng-show="syncError">
            <span class="message-text">
                {{ErrorMessage}}
            </span>
</div>
<div ng-show="$root.isMarketplaceAuthorized" class="extension-manager-wrap">
    <div class="extension-manager-title">
        Magento Marketplace Account
        <div class="extension-manager-account">
            <a ng-click="reset()" href="#" class="sign-in-out">Disconnect</a>
        </div>
    </div>
    <div class="extension-manager-content">
        <ul class="extension-manager-items row">
            <li class="item col-m-4">
                <div class="item-number">{{countOfUpdate}}</div>
                <div class="item-title">Updates<br />Available</div>
                <button ui-sref="root.update" href="#update-extension-grid"
                        ng-class="{'disabled' : !countOfUpdate}"
                        type="button" class="btn">
                    Review Updates
                </button>
            </li>
            <li class="item col-m-4">
                <div class="item-number">{{countOfInstall}}</div>
                <div class="item-title">Products<br />Ready to Install</div>
                <div class="item-install">
                    <button ui-sref="root.install" href="#install-extension-grid"
                            ng-class="{'disabled' : !enabledInstall}"
                            type="button" class="btn">
                        Review and Install
                    </button>
                </div>
            </li>
            <li class="item col-m-4">
                <div ng-hide="isOutOfSync" class="item-title">Last Refresh at {{lastSyncTime}} on </div>
                <div ng-hide="isOutOfSync" class="item-date">
                    {{lastSyncDate}}
                </div>
                <span ng-show="isOutOfSync">No sync history</span>
                <button type="button" ng-click="sync()" class="btn">Refresh</button>
            </li>
        </ul>
    </div>
</div>

<div ng-show="logout===true" id="messages">
    <div class="messages">
        <div class="message message-success success">
            <div data-ui-id="messages-message-success">
                You have logged out
            </div>
        </div>
    </div>
</div>

<div class="row" ng-show="$root.isMarketplaceAuthorized && extensionsProcessed && total == 0">
    <label class="form-label">
        <b>We didn't find any extensions to update at this time. Please try later.</b><br/>
    </label>
</div>
<div class="admin__data-grid-outer-wrap" ng-show="$root.isMarketplaceAuthorized && extensionsProcessed && total > 0">
    <div class="admin__data-grid-header">
        <div class="admin__data-grid-header-row row row-gutter">
            <div class="col-xs-3">
                <div class="extension-manager-title">
                    Installed Products
                    <span>{{total}}</span> products
                </div>
            </div>
            <div class="col-xs-9 admin__data-grid-pager-wrap">
                <select id="perPage" class="admin__control-select" ng-model="rowLimit">
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="200">200</option>
                </select>
                <label class="admin__control-support-text" for="perPage">per page</label>
                <div class="admin__data-grid-pager">
                    <button class="action-previous"
                            ng-disabled="currentPage == 1"
                            ng-click="currentPage = currentPage - 1; start = start - rowLimit"
                            type="button"
                    >
                        <span>Previous page</span>
                    </button>
                    <input id="pageCurrent" class="admin__control-text" type="number" value="{{currentPage}}">
                    <label class="admin__control-support-text" for="pageCurrent">
                        of {{numberOfPages}}
                    </label>
                    <button class="action-next"
                            ng-disabled="currentPage >= numberOfPages"
                            ng-click="currentPage = currentPage + 1; start = start + rowLimit"
                            type="button"
                    >
                        <span>Next page</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="admin__data-grid-wrap" ng-show="$state.is('root.extension')">
        <table class="data-grid">
            <thead data-part="head">
            <tr>
                <th ng-click="order('name')" ng-class="{'_ascend' : predicate === 'name'
                && !reverse,'_descend' : predicate === 'name' && reverse}" class="data-grid-th _sortable">
                    <span>Product Name</span>
                </th>
                <th ng-click="order('type')" ng-class="{'_ascend' : predicate === 'type'
                && !reverse,'_descend' : predicate === 'type' && reverse}" class="data-grid-th  _sortable">
                    <span>Type</span>
                </th>
                <th ng-click="order('version')" ng-class="{'_ascend' : predicate === 'version' &&
                !reverse,'_descend' : predicate === 'version' && reverse}" class="data-grid-th  _sortable">
                    <span>Version</span>
                </th>
                <th ng-click="order('vendor')" ng-class="{'_ascend' : predicate === 'vendor'
                && !reverse,'_descend' : predicate === 'vendor' && reverse}" class="data-grid-th  _sortable">
                    <span>Vendor</span>
                </th>
                <th class="data-grid-actions-cell data-grid-th">
                    <span>Actions</span>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="extension in extensions | orderBy:predicate:reverse
                | startFrom:(currentPage - 1) * rowLimit | limitTo:rowLimit"
            >
                <td>
                    <span class="component-indicator"
                          ng-show="isAvailableUpdatePackage(extension.name)"
                          ng-class="getIndicatorInfo(extension, 'icon')"
                          data-label="{{getIndicatorInfo(extension, 'label')}}"
                    ><span>{{getIndicatorInfo(extension, 'label')}}</span>
                    </span>
                    <span class="data-grid-data">{{extension.name}}</span>
                </td>
                <td>
                    <span class="data-grid-data">{{extension.type}}</span>
                </td>
                <td>
                    <span class="data-grid-data" data-type="version">{{extension.version}}</span>
                </td>
                <td>
                    <span class="data-grid-data">{{extension.vendor}}</span>
                </td>
                <td class="data-grid-actions-cell">
                    <!-- "_active" class should be added when .action-select button clicked to the -->
                    <!-- wrapper and .action-menu to show actions                                  -->
                    <div class="action-select-wrap" ng-class="{'_active' : isActiveActionsCell(extension)}">
                        <button class="action-select"
                                ng-click="toggleActiveActionsCell(extension)"
                                ng-blur="closeActiveActionsCell(extension)">
                            <span>Select</span>
                        </button>
                        <ul class="action-menu" ng-class="{'_active' : isActiveActionsCell(extension)}">
                            <li ng-class="{'disabled': !isAvailableUpdatePackage(extension.name)}"
                                ng-mousedown="isAvailableUpdatePackage(extension.name) && update(extension)">
                                <a class="action-menu-item">Update</a>
                            </li>
                            <li ng-class="{'hide': !extension.uninstall}"
                                ng-mousedown="uninstall(extension)">
                                <a class="action-menu-item">Uninstall</a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<div ng-show="!isHiddenSpinner || $root.saveAuthProccessed ||
(!$root.extensionsProcessed)" class="loading-mask ng-scope" data-role="loader">
    <div class="popup popup-loading">
        <div class="popup-inner">
            <img alt="Loading..." src="<?php echo $this->basePath() ?>/pub/images/loader-1.gif">
            Please wait...
        </div>
    </div>
</div>
