<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<section class="home-page-inner-wrap ng-scope">
    <p class="upgrade-home-title">
        Hello <?php echo $this->userName;?>, welcome to the Magento Setup Tool. Please choose a task below.
    </p>

    <div class="row" style="padding-left: 145px;" >
        <div class="col-m-5">
            <a class="upgrade-home-item upgrade-home-item-component" ui-sref="root.cm">
                <span class="upgrade-home-item-title">Component Manager</span>
                <span class="upgrade-home-item-description">I want to manage my packages and modules.</span>
            </a>
        </div>
        <div class="col-m-5">
            <a class="upgrade-home-item upgrade-home-item-upgrade" ui-sref="root.su">
                <span class="upgrade-home-item-title">System Upgrade</span>
                <span class="upgrade-home-item-description">I want to upgrade my Magento Admin version.</span>
            </a>
        </div>
    </div>
</section>