<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<div class="container">
    <main id="anchor-content" class="page-content">
        <?= /* @noEscape */ $this->render('navigation/menu.phtml') ?>
        <div
            id="main"
            ng-controller="mainController"
            >
            <div ui-view="root">
                <div ui-view></div>
            </div>
        </div>
    </main>
</div>
