<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<section class="page-landing">
    <img class="logo" src="<?= $this->basePath() ?>/pub/images/magento-logo.svg" alt="Magento"/>
    <p class="text-version">
        <?= 'Version' . ' ' . $this->version ?>
    </p>
    <p class="text-welcome">
        Welcome to Magento Admin, your online store headquarters.
        <br>
        Please review <a href="" ng-click="previousState()">Terms & Agreement</a> and read <a href="https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli.html" target="_blank">Getting Started</a> to learn how to install Magento using the command line.
    </p>
</section>
