<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<div class="col-xs-9">
    <br/>
    <a href="#" class="btn btn-primary" ng-click="nextState()"> Go Back</a>
    <br/><br/>
    <?php echo nl2br(htmlspecialchars($this->license, ENT_COMPAT, 'UTF-8')); ?>
    <br/><br/><br/>
    <a href="#" class="btn btn-primary" ng-click="nextState()"> Go Back</a>
    <br/><br/>
</div>
