<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<div class="step-controls" ng-show="$state.is('root.readiness-check.progress')">
    <a href="" class="btn btn-primary" ng-click="$state.forceReload()" ng-disabled="checkingInProgress()">Try Again</a>
    <a href="" class="btn btn-primary" ng-click="nextState()" ng-disabled="checkingInProgress() || hasErrors">Next</a>
</div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<div ng-show="$state.is('root.readiness-check')" class="readiness-check-landing">
    <p>Let's check your environment for the correct PHP version, PHP extensions, file permissions and compatibility.</p>
    <div>
        <a href="" ng-click="$state.go('.progress')" class="btn btn-primary">Start Readiness Check</a>
    </div>
</div>

<div ui-view></div>

<div class="step-controls" ng-show="$state.is('root.readiness-check.progress')">
    <a href="" class="btn btn-primary" ng-click="$state.forceReload()" ng-disabled="checkingInProgress()">Try Again</a>
    <a href="" class="btn btn-primary" ng-click="nextState()" ng-disabled="checkingInProgress() || hasErrors">Next</a>
</div>
