<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<h2 class="page-title">{{$state.current.header}}</h2>

<div class="admin__data-grid-outer-wrap">
    <div class="admin__data-grid-header"></div>
</div>

<div class="form-wrap">
    <div ng-hide="!processed">
        <span class="spinner side">
            <span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span>
        </span>
        <h3 class="select-version-title">Checking for a new version...</h3>
    </div>
    <div class="row" ng-hide="processed">
        <div class="col-m-4">
            <select
                id="selectVersion"
                class="form-el-select"
                ng-model="package.version"
                ng-options="item.id as item.name for item in versions"
                ng-model="selected"
                ng->
            </select>
        </div>
    </div>
</div>

<button
    class="btn btn-large btn-prime"
    ng-click="update()"
    type="button">Continue</button>
