<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="nav-bar-outer-actions">
    <div class="outer-actions-inner-wrap">
        <div class="btn-wrap btn-wrap-triangle-right btn-wrap-next">
            <button
                type="button"
                class="btn btn-prime"
                ng-click="nextState()"
                >Next</button>
        </div>
    </div>
</div>

<h2 class="page-title">{{$state.current.header}}</h2>

<div class="admin__data-grid-outer-wrap">
    <div class="admin__data-grid-header">
        </div>
    </div>

<section class="home-page-inner-wrap ng-scope">
    <p class="upgrade-home-title">
       System upgrade placeholder
    </p>
</section>