<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="content-success">

    <h1 class="jumbo-title">
        <span class="jumbo-icon icon-success-round"></span>
        Success
    </h1>

    <p>Please keep this information for your records:</p>

    <p><strong>Magento Admin Info:</strong></p>

    <dl class="list-definition" id="admin-info">
        <dt>Username:</dt>
        <dd>{{admin.username}}</dd>

        <dt>Email:</dt>
        <dd>{{admin.email}}</dd>

        <dt>Password:</dt>
        <dd>******</dd>

        <dt>Your Store Address:</dt>
        <dd>
            <a href="{{url.front}}" target="_blank">{{url.front}}</a>
        </dd>

        <dt>Magento Admin Address:</dt>
        <dd>
            <a href="{{url.admin}}" target="_blank">{{url.admin}}</a>
        </dd>

        <div class="message message-notice">
        <span class="message-text">
            Be sure to bookmark your unique URL and record it offline.
        </span>
        </div>

        <dt>Encryption Key:</dt>
        <dd>{{config.encrypt.key}}</dd>
    </dl>

    <p>
        <strong>Database Info:</strong>
    </p>

    <dl id="db-info" class="list-definition">
        <dt>Database Name:</dt>
        <dd>{{db.name}}</dd>

        <dt>Username:</dt>
        <dd>{{db.user}}</dd>

        <dt>Password:</dt>
        <dd>******</dd>
    </dl>

    <p class="bold" ng-repeat="message in messages">{{message}}</p>
    <?php if ($this->isSampleDataErrorInstallation) : ?>
        <div class="message message-warning">
            <span class="message-text"><strong>Something went wrong while installing sample data.</strong> Please check <code>var/log/system.log</code> for details. You can retry installing the data now or just start using Magento.</span>
        </div>
    <?php endif; ?>
    <div ng-show="config.address.actual_base_url">
        <a
            class="btn btn-large btn-prime"
            href="{{url.admin}}"
            target="_blank"
            >
            Launch Magento Admin
        </a>
    </div>

</div>
