<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Csp\Block\Sri\Hashes $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
//phpcs:ignore Magento2.GraphQL
?>

<?php $sriHashes = /* @noEscape */ $block->getSerialized();
//@codingStandardsIgnoreStart
$scriptString = <<<script
        window.sriHashes = {$sriHashes};
script;
//@codingStandardsIgnoreStart
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

