<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\OfflinePayments\Block\Form\Banktransfer;

/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Banktransfer $block */
$instructions = $block->getInstructions();
?>
<?php if ($instructions): ?>
    <?php $methodCode = $escaper->escapeHtml($block->getMethodCode());?>
    <div class="items <?= /* @noEscape */ $methodCode ?> instructions agreement checkout-agreement-item-content"
         id="payment_form_<?= /* @noEscape */ $methodCode ?>">
        <?= /* @noEscape */ nl2br($escaper->escapeHtml($instructions)) ?>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "display:none",
        'div#payment_form_' . /* @noEscape */ $methodCode
    ) ?>
<?php endif; ?>
