<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($instructions = $this->getInstructions()): ?>
    <div class="items <?php echo $this->getMethodCode() ?> instructions agreement content" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display: none;">
        <?php echo nl2br($instructions) ?>
    </div>
<?php endif; ?>
