<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @see \Magento\OfflinePayments\Block\Form\Cashondelivery
 */
?>
<?php if ($block->getInstructions()): ?>
    <div class="items <?php echo $block->getMethodCode() ?> instructions agreement" id="payment_form_<?php echo $block->getMethodCode() ?>" style="display: none;">
        <?php echo nl2br($block->getInstructions()) ?>
    </div>
<?php endif; ?>
