<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Magento\OfflinePayments\Block\Form\Cashondelivery
 */
?>
<?php if ($this->getInstructions()): ?>
    <div class="items <?php echo $this->getMethodCode() ?> instructions agreement" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display: none;">
        <?php echo nl2br($this->getInstructions()) ?>
    </div>
<?php endif; ?>
