<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/**
 * @var $block \Magento\OfflinePayments\Block\Form\Cashondelivery
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$instructions = $block->getInstructions();
?>
<?php if ($instructions): ?>
    <?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
    <div class="items <?= /* @noEscape */ $methodCode ?> instructions agreement"
         id="payment_form_<?= /* @noEscape */ $methodCode ?>">
        <?= /* @noEscape */ nl2br($block->escapeHtml($instructions)) ?>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "display:none",
        'div#payment_form_' . /* @noEscape */ $methodCode
    ) ?>
<?php endif; ?>
