<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<fieldset class="fieldset items <?php echo $this->getMethodCode() ?>" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display: none">
    <div class="field number required">
        <label for="po_number" class="label"><span><?php echo __('Purchase Order Number') ?></span></label>
        <div class="control">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo __('Purchase Order Number') ?>" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getInfoData('po_number')) ?>" />
        </div>
    </div>
</fieldset>
