<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $this \Magento\Checkout\Block\Item\Price\Renderer */

$_item = $this->getItem();
?>
<?php $_incl = $this->helper('Magento\Checkout\Helper\Data')->getPriceInclTax($_item); ?>
<span class="cart-price">
    <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_incl) ?>
</span>
