<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Checkout\Block\Item\Price\Renderer;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Renderer $block */
$_item = $block->getItem();

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php $_incl = $this->helper(Magento\Checkout\Helper\Data::class)->getPriceInclTax($_item); ?>
<span class="cart-price">
    <?= $escaper->escapeHtml(
        $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($_incl),
        ['span']
    ) ?>
</span>
