<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Catalog\Block\Product\View\AbstractView;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var AbstractView $block */
$_product = $block->getProduct();
?>
<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
