<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var Magento\ProductVideo\Block\Adminhtml\Product\Edit\NewVideo $block */
?>
<div id="<?php echo $block->getNameInLayout();?>" style="display:none">
    <?php echo $block->getFormHtml();?>
    <script>
        require(["jquery","mage/mage"],function($) {
            $(function(){
                $('#new-video').mage('newVideoDialog', <?php echo $block->getWidgetOptions();?>);
            });
        });
    </script>
</div>
