<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\NewCategory */
?>
<div id="<?=$block->getNameInLayout();?>" style="display:none">
    <?=$block->getFormHtml();?>
    <script>
        require(["jquery","mage/mage"],function($) {
            $(function(){
                $('#new-video').mage('newVideoDialog', <?=$block->getWidgetOptions();?>);
            });
        });
    </script>
</div>
