<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Mustishipping state
 *
 * @see \Magento\Multishipping\Block\Checkout\State
 */
?>
<ol class="block multicheckout progress items" id="checkout-progress-state">
    <?php foreach ($this->getSteps() as $_step): ?>
        <li title="<?php echo $_step->getLabel() ?>" class="item<?php echo($_step->getIsActive()) ? ' active' : ''?>"><span><?php echo $_step->getLabel() ?></span></li>
    <?php endforeach; ?>
</ol>
