<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Cms\Block\Widget\Page\Link;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Link $block */
?>
<span class="widget block block-cms-link-inline">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <span><?= $escaper->escapeHtml($block->getLabel()) ?></span>
    </a>
</span>
