<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 /** @var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files */

$_width  = $block->getImagesWidth();
$_height = $block->getImagesHeight();

?>
<?php if ($block->getFilesCount() > 0): ?>
    <?php foreach ($block->getFiles() as $file): ?>
    <div data-row="file" class="filecnt" id="<?php echo $block->getFileId($file) ?>">
        <p class="nm" style="height:<?php echo $_height ?>px;width:<?php echo $_width ?>px;">
        <?php if ($block->getFileThumbUrl($file)):?>
            <img src="<?php echo $block->getFileThumbUrl($file) ?>" alt="<?php echo $block->getFileName($file) ?>"/>
        <?php endif; ?>
        </p>
        <?php if ($block->getFileWidth($file)): ?>
            <small><?php echo $block->getFileWidth($file) ?>x<?php echo $block->getFileHeight($file) ?> <?php echo __('px.') ?></small><br/>
        <?php endif; ?>
        <small><?php echo $block->getFileShortName($file); ?></small>
    </div>
    <?php endforeach; ?>
<?php else: ?>
    <div class="empty"><?php echo __('No files found') ?></div>
<?php endif; ?>
