<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Item\configure $block */
?>

<div class="product-addto-links" data-role="add-to-links">
    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
        <a href="#" data-post='<?php /* @noEscape */ echo $block->getUpdateParams(); ?>' class="action towishlist updated" data-action="add-to-wishlist">
            <span><?php echo $block->escapeHtml(__('Update Wish List')) ?></span>
        </a>
    <?php endif; ?>
    <?php $_product = $block->getProduct(); ?>
    <?php $_compareUrl = $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddUrl($_product); ?>
    <?php if ($_compareUrl) : ?>
        <a href="<?php echo $block->escapeUrl($_compareUrl) ?>" class="action tocompare">
            <span><?php echo $block->escapeHtml(__('Add to Compare')) ?></span>
        </a>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
        }
    }
</script>
