<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var \Magento\Tax\Pricing\Render\Adjustment $this */ ?>
<?php if ($this->displayPriceIncludingTax()): ?>
    <?php echo $this->getDisplayAmount() ?>
<?php elseif ($this->displayPriceExcludingTax()): ?>
    <?php echo $this->getDisplayAmountExclTax() ?>
<?php elseif ($this->displayBothPrices()): ?>
    <?php echo $this->getDisplayAmount() ?>
    <?php if ($this->getDisplayAmountExclTax() !== $this->getDisplayAmount()): ?>
        (+<?php echo $this->getDisplayAmountExclTax() ?> Excl. Tax)
    <?php endif; ?>
<?php endif; ?>
