<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var \Magento\Tax\Pricing\Render\Adjustment $block */ ?>
<?php if ($block->displayPriceIncludingTax()) : ?>
    <?= /* @noEscape */ $block->getDisplayAmount() ?>
<?php elseif ($block->displayPriceExcludingTax()) : ?>
    <?= /* @noEscape */ $block->getDisplayAmountExclTax() ?>
<?php elseif ($block->displayBothPrices()) : ?>
    <?= /* @noEscape */ $block->getDisplayAmount() ?>
    <?php if ($block->getDisplayAmountExclTax() !== $block->getDisplayAmount()) : ?>
        (+<?= /* @noEscape */ $block->getDisplayAmountExclTax() ?> <?= $block->escapeHtml(__('Excl. Tax')) ?>)
    <?php endif; ?>
<?php endif; ?>
