<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$partners = $block->getPartners();
?>
<?php if ($partners) : ?>
    <?php foreach ($partners as $partner) : ?>
        <div class="partner">
            <img
                class="partner-image"
                src="<?= $block->escapeUrl($partner['img']) ?>"
                alt="<?= $block->escapeHtmlAttr($partner['title']) ?>"/>
            <h3 class="partner-title"><?= $block->escapeHtml($partner['title']) ?></h3>
            <p class="partner-description">
                <?= $block->escapeHtml($partner['description']) ?>
                <br />
                <a href="<?= $block->escapeUrl($partner['url_page']) ?>" target="_blank">
                    <?= $block->escapeHtml(__('Read More')) ?>
                </a>
                <br />
                <a href="<?= $block->escapeUrl($partner['url_partner_page']) ?>" target="_blank">
                    <?= $block->escapeHtml(__('Partner Page')) ?>
                </a>
            </p>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    <p>
        <?= $block->escapeHtml(__('No partners were found')) ?>
    </p>
<?php endif; ?>
