<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
$_product = $block->getProduct();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$image = 'product_page_main_image';

$_resizedWidth = $block->getVar("{$image}:width");
$_resizedHeight = $block->getVar("{$image}:height") ?: $_resizedWidth;

$_hasImage = ($_product->getImage() && $_product->getImage() != "no_selection") ? true : false;

$whiteBorders =  $block->getVar("product_image_white_borders");
$thumbWidth =  $block->getVar("product_page_more_views:width");
$thumbHeight =  $block->getVar("product_page_more_views:height") ?: $thumbWidth;
?>
<div data-role="media-gallery">
    <div class="product photo main">
        <div data-role="gallery-base-image-container">
            <a <?php echo($_hasImage) ? 'href="#" class="product photo magento-zoom"' : ' class="placeholder"'; ?>
               id="base-image" data-role="zoom-image"
               data-large="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image'); ?>">
                <?php echo $block->getChildBlock('product.image.main')->setAddAttribute('itemprop="image"')->init($_product, $image)->toHtml() ?>
            </a>
        </div>
        <div data-role="gallery-notice-container">
            <p class="notice" data-role="notice"></p>
        </div>
    </div>
    <?php if (count($block->getGalleryImages()) > 0): ?>

        <div class="product photo thumbs">
            <strong class="title"><?php echo __('More Views') ?></strong>
            <ul class="items thumbs">
                <?php foreach ($block->getGalleryImages() as $_image): ?>
                <?php
                $imageSmall = $block->getImageUrl($_image, 'thumbnail', $whiteBorders, $thumbWidth, $thumbHeight);
                $imageMedium = $block->getImageUrl($_image, 'image', $whiteBorders, $_resizedWidth, $_resizedHeight);
                $imageLarge = $block->getImageUrl($_image, 'image');
                ?>
                <li class="item thumb">
                    <a class="magento-zoom" data-role="gallery-thumb"
                         href ="<?php echo $imageLarge ?>"
                         data-image-small="<?php echo $imageSmall; ?>"
                         data-image-medium="<?php echo $imageMedium; ?>"
                         data-image-large="<?php echo $imageLarge; ?>"
                        <?php if ($block->isMainImage($_image)): ?>
                             data-image-selected="true"
                        <?php endif; ?>
                         title="<?php echo $block->escapeHtml($_image->getLabel()) ?>">
                        <span class="img"
                              style="position:relative; z-index:1; display:block; width:<?php echo $thumbHeight; ?>px; height:<?php echo $thumbHeight; ?>px;">
                            <img itemprop="image"
                                 src="<?php echo $imageSmall; ?>"
                                 alt="<?php echo $block->escapeHtml($_image->getLabel()) ?>"/>
                        </span>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
</div>
<?php if ($_hasImage): ?>
    <script data-template="gallery-wrapper" type="text/x-magento-template">
        <div class="product photo main" style="bottom: <?php echo $thumbWidth ?>px;">
            <div data-role="gallery-base-image-container"></div>
            <div data-role="gallery-notice-container"></div>
        </div>
        <div class="product photo thumbs" data-role="gallery-thumbs-container">
        </div>
        <div class="product photo buttons" data-role="gallery-buttons-container">
        </div>
    </script>
    <script data-template="gallery-buttons" type="text/x-magento-template">
        <a class="gallery control prev" data-role="gallery-prev" href="#"></a>
        <a class="gallery control next" data-role="gallery-next" href="#"></a>
    </script>
    <script data-template="gallery-base-image" type="text/x-magento-template">
        <a class="product photo<% if (typeof data.hasImg !== 'undefined') { %> placeholder<% } %>" href="<%- data.large %>">
            <span class="img photo container">
                <img
                    data-role="zoom-image"
                    class="photo image"
                    itemprop="image"
                    <% if (!data.fullSizeMode) { %>
                    data-large="<%- data.large %>" src="<%- data.medium %>"
                    <% } else { %>
                    src="<%- data.large %>"
                    <% } %>
                    alt="<%- data.title %>"/>
            </span>
        </a>
    </script>
    <script data-template="gallery-thumbs" type="text/x-magento-template">
        <% if (data.tumbsTitle) { %>
        <strong class="title"><%- data.tumbsTitle %></strong>
        <% } %>
        <ul class="items thumbs">
            <% _.each(data.images, function(img, index){ %>
             <li class="item thumb">
                <a title="<%- img.title %>" <% if (img.selected) { %>class="active"<% } %> data-index="<%- index %>" data-role="gallery-thumb" href="#">
                    <span class="img">
                        <img alt="<%- img.title %>" src="<%- img.small %>" itemprop="image" width="<%- data.size.width %>">
                    </span>
                </a>
            </li>
            <% });%>
        </ul>
    </script>
    <script data-template="zoom-display" type="text/x-magento-template">
        <div class="zoom lense" data-role="zoom-container">
            <div data-role="zoom-inner" class="zoom inner"></div>
        </div>
    </script>
    <script data-template="zoom-enlarged-image" type="text/x-magento-template">
        <img data-role="enlarged-image" src="<%- data.img %>" />
    </script>
    <script data-template="zoom-track" type="text/x-magento-template">
        <div data-role="zoom-track"></div>
    </script>
    <script data-template="zoom-lens" type="text/x-magento-template">
        <div data-role="zoom-lens"></div>
    </script>
    <script data-template="notice" type="text/x-magento-template">
        <p class="notice" data-role="notice"><%- data.text %></p>
    </script>
    <script type="text/x-magento-init">
        {
            "[data-role=media-gallery]": {
                "gallery": {
                    "sizes": {
                        "small": {
                            "width": <?php echo $thumbWidth ?>,
                            "height": <?php echo $thumbHeight ?>
                        },
                        "medium": {
                            "width": <?php echo $_resizedWidth ?>,
                            "height": <?php echo $_resizedHeight ?>
                        }
                    },
                    "controls": {
                        "notice": {
                            "text": "<?php echo $block->escapeJsQuote(__('Click to see a larger image.')) ?>"
                        }
                    }
                },
                "zoom": {
                    "controls": {
                        "display": {
                            "left": 20,
                            "top": 65
                        },
                        "notice": {
                            "text": "<?php echo $block->escapeJsQuote(__('Click to see zoomed image.')) ?>"
                        }
                    }
                },
                "galleryFullScreen": {}
            }
        }
    </script>
<?php endif; ?>
