<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<div class="gallery-placeholder"></div>

<script type="text/x-magento-init">
    {
        ".gallery-placeholder": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": {
                    "enabled": true,
                    "thumb": ".fotorama__img",
                    "zoom": 1,
                    "largeWrapper": "#preview",
                    "eventType": "click",
                    "zoomable": false,
                    "width": "<?php echo $block->getVar("magnifier_width"); ?>",
                    "height": "<?php echo $block->getVar("magnifier_height"); ?>"
                },
                "data": <?php echo $block->getGalleryImagesJson(); ?>,
                "options": {
                    "nav": "<?php echo $block->getVar("gallery_nav"); ?>",
                    "loop": <?php echo $block->getVar("gallery_loop"); ?>,
                    "keyboard": true,
                    "allowfullscreen": false,
                    "width": "100%",
                    "height": 400,
                    "showCaption": true,
                    "targetblank": true
                },
                "breakpoints": {
                    "mobile": {
                        "conditions": {
                            "max-width": "767px"
                        },
                        "options": {
                            "nav": false,
                            "magnifierOpts": {
                                "enabled": false
                            }
                        }
                    },
                    "tablet": {
                        "conditions": {
                            "min-width": "768px",
                            "max-width": "1023px"
                        },
                        "options": {
                            "nav": "dots",
                            "magnifierOpts": {
                                "enabled": true
                            }
                        }
                    },
                    "desktop": {
                        "conditions": {
                            "min-width": "1024px"
                        },
                        "options": {
                            "nav": "thumbs",
                            "magnifierOpts": {
                                "enabled": true
                            }
                        }
                    }
                }
            }
        }
    }
</script>
