<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<div class="gallery-placeholder"></div>

<script type="text/x-magento-init">
    {
        ".gallery-placeholder": {
            "mage/gallery/gallery": {
                 "nav": "<?php echo $block->getVar("gallery_nav"); ?>",
                 "width": "100%",
                 "height": 400,
                 "loop": <?php echo $block->getVar("gallery_loop"); ?>,
                 "keyboard": true,
                 "allowfullscreen": false,
                 "showCaption": true,
                 "click": false,
                 "data": <?php echo $block->getGalleryImagesJson(); ?>
            }
        }
    }
</script>
