<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<div class="gallery-placeholder"></div>
<script type="text/x-magento-init">
    {
        ".gallery-placeholder": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": {
                    "enabled": <?php echo $block->getVar("magnifier:enabled"); ?>,
                    "eventType": "<?php echo $block->getVar("magnifier:action"); ?>",
                    "width": "<?php echo $block->getVar("magnifier:width"); ?>",
                    "height": "<?php echo $block->getVar("magnifier:height"); ?>",
                    "top": "<?php echo $block->getVar("magnifier:top"); ?>",
                    "left": "<?php echo $block->getVar("magnifier:left"); ?>"
                },
                "data": <?php echo $block->getGalleryImagesJson(); ?>,
                "options": {
                    "nav": "<?php echo $block->getVar("gallery:navigation"); ?>",
                    "loop": <?php echo $block->getVar("gallery:loop"); ?>,
                    "keyboard": <?php echo $block->getVar("gallery:keyboard"); ?>,
                    "arrows": <?php echo $block->getVar("gallery:arrows"); ?>,
                    "allowfullscreen": <?php echo $block->getVar("gallery:allowfullscreen"); ?>,
                    "showCaption": <?php echo $block->getVar("gallery:show_caption"); ?>,
                    "width": <?php echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    "thumbwidth": <?php echo $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    "thumbheight": <?php echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    "height": <?php echo $block->getImageAttribute('product_page_image_medium', 'height')
                        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>
                    "transitionduration": <?php echo $block->getVar("gallery:transition:duration"); ?>,
                    "transition": "<?php echo $block->getVar("gallery:transition:effect"); ?>"
                },
                "fullscreen": {
                    "nav": "<?php echo $block->getVar("gallery:fullscreen:navigation"); ?>",
                    "loop": <?php echo $block->getVar("gallery:fullscreen:loop"); ?>,
                    "arrows": <?php echo $block->getVar("gallery:fullscreen:arrows"); ?>,
                    "showCaption": <?php echo $block->getVar("gallery:fullscreen:show_caption"); ?>,
                    "transitionduration": <?php echo $block->getVar("gallery:fullscreen:transition:duration"); ?>,
                    "transition": "<?php echo $block->getVar("gallery:fullscreen:transition:effect"); ?>"
                },
                "breakpoints": {
                    "mobile": {
                        "conditions": {
                            "max-width": "767px"
                        },
                        "options": {
                            "options": {
                                "nav": "dots"
                            },
                            "magnifierOpts": {
                                "enabled": false
                            }
                        }
                    }
                }
            }
        }
    }
</script>
