<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_product = $this->getProduct() ?>
<?php if ($this->canEmailToFriend()): ?>
    <a title="<?php echo __('Email') ?>"
       href="<?php echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
       class="action mailto friend"><span><?php echo __('Email') ?></span></a>
<?php endif; ?>
