<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()) :?>
    <a href="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product::class)->getEmailToFriendUrl($_product)) ?>"
       class="action mailto friend"><span><?= $block->escapeHtml(__('Email')) ?></span></a>
<?php endif; ?>
