<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Catalog\Block\Product\AbstractProduct $this */ ?>
<?php $_product = $this->getProduct() ?>
<?php echo $this->getProductPriceHtml(
    $_product,
    \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
    \Magento\Framework\Pricing\Render::ZONE_ITEM_VIEW,
    [
        'price_id_suffix' => '_clone'
    ]
) ?>
