<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var \Magento\Catalog\Block\Product\AbstractProduct $block */ ?>
<?php $_product = $block->getProduct() ?>
<?php echo $block->getProductPriceHtml(
    $_product,
    \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
    \Magento\Framework\Pricing\Render::ZONE_ITEM_VIEW,
    [
        'price_id_suffix' => '_clone'
    ]
) ?>
