<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<form action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="design-edit-form">
    <?php echo $block->getBlockHtml('formkey')?>
</form>
<script>
require([
    "jquery",
    "mage/mage"
], function($){

    $('#design-edit-form').mage('form').mage('validation');

});
</script>
