<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn $block */

$_item = $block->getItem();
?>

<div class="price-excl-tax">
    <?php /* @escapeNotVerified */ echo $block->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
</div>
