<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\Composite */ ?>
<?php
/** @var $element \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Element\Composite\AbstractComposite|\Magento\DesignEditor\Block\Adminhtml\Editor\Form\Element\Logo|\Magento\DesignEditor\Block\Adminhtml\Editor\Form\Element\Background */
$element = $this->getElement();

$containerId = $element->getFieldsetContainerId();
$id = $element->getHtmlId();
$isCollapsable = $element->getCollapsable();
$isWrapped = $containerId || $element->getHeaderBar() || $isCollapsable;
$titleActions = $element->getHeaderBar() ? '<div class="actions">' . $element->getHeaderBar() . '</div>' : '';
?>

<?php if ($isWrapped): ?>
    <div class="fieldset-wrapper" id="<?php echo $containerId ? $containerId : $id . '-wrapper';?>">
        <div class="fieldset-wrapper-title">
            <strong class="title"<?php echo($isCollapsable) ? ' data-toggle="collapse" data-target="#' . $id . '-content"' : ''; ?>>
                <span><?php echo $element->getLegend() ?></span>
            </strong>
            <?php echo $titleActions; ?>
        </div>
        <div class="fieldset-wrapper-content<?php echo($isCollapsable) ? ' collapse' : ''; ?>" id="<?php echo $id ?>-content">
<?php endif; ?>

<?php echo $this->getHtml() ?>

<?php if ($isWrapped): ?>
        </div>
    </div>
<?php endif; ?>
