<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Form\Container
 */
?>
<?php echo $block->getFormInitScripts() ?>
<form id="edit_form" class="admin__scope-old" action="<?php echo $block->escapeHtml($block->getSaveUrl()) ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $block->escapeHtml($block->getFormKey()) ?>" />
    <?php echo $block->getChildHtml('form') ?>
</form>

<div data-mage-init='{"floatingHeader": {}}' class="page-actions attribute-popup-actions" <?php echo $block->getUiId('content-header') ?>>
    <?php echo $block->getButtonsHtml('header') ?>
</div>

<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#edit_form').mage('form').mage('validation', {validationUrl: '<?php echo $block->getValidationUrl() ?>'});

});
</script>
<?php echo $block->getFormScripts() ?>
