<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $this \Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\Labels  */
?>

<div class="fieldset-wrapper collapsable-wrapper opened" id="manage-titles-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="title" data-toggle="collapse" data-target="#manage-titles-content">
            <span><?php echo __('Manage Titles (Size, Color, etc.)') ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="manage-titles-content">
        <fieldset class="fieldset">
            <table class="data-table" id="attribute-labels-table">
                <thead>
                <tr>
                    <?php foreach ($this->getStores() as $_store): ?>
                        <th class="col-store-view"><?php echo $_store->getName() ?></th>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <?php $_labels = $this->getLabelValues() ?>
                    <?php foreach ($this->getStores() as $_store): ?>
                        <td class="col-store-view">
                            <input class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>" type="text" name="frontend_label[<?php echo $_store->getId() ?>]" value="<?php echo $this->escapeHtml($_labels[$_store->getId()]) ?>"<?php if ($this->getReadOnly()):?> disabled="disabled"<?php endif;?>/>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </tbody>
            </table>
        </fieldset>
    </div>
</div>
