<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Container for product link widget chooser
 *
 * @see \Magento\Catalog\Block\Adminhtml\Product\Widget\Chooser\Container
 */
?>
<div class="columns">
    <div class="side-col"><?php echo $this->getTreeHtml() ?></div>
    <div class="main-col"><?php echo $this->getGridHtml() ?></div>
</div>
