<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $element \Magento\Framework\Data\Form\Element\Fieldset */
$element = $this->getElement();
$containerId = $element->getFieldsetContainerId();
$id = $element->getHtmlId();
$isCollapsable = $element->getCollapsable();
$isWrapped = $containerId || $element->getHeaderBar() || $isCollapsable;
$titleActions = '<div class="actions">' . $element->getHeaderBar() . '</div>';
$isField = $element->getFieldsetType() == 'field';
$advancedAfter = $element->getAdvancedPosition() == 'after'; // To place advanced options inside or after fieldset
$advancedLabel = $element->getAdvancedLabel();
if (!isset($advancedLabel)) {
    $advancedLabel = __('Additional Settings');
}

$cssClass = ($isField) ? 'field ' . $element->getClass() : 'fieldset ' . $element->getClass();

if ($isField) {
    $count = $element->getCountBasicChildren();
    $cssClass .= ($element->hasAdvanced()) ? ' complex' : '';
}
?>

<?php
/**
* @todo investigate situations, when the following is needed:
* echo $element->getHeaderBar();
* echo $element->getSubFieldsetHtml();
*/ ?>

<?php if ($isWrapped): ?>
    <div class="fieldset-wrapper <?php echo($isCollapsable) ? 'collapsable-wrapper ' : ''; ?>"
        id="<?php echo $containerId ? $containerId : $id . '-wrapper';?>"
        data-role="<?php echo $id ?>-wrapper">
        <div class="fieldset-wrapper-title">
            <strong class="title"<?php echo($isCollapsable) ? ' data-toggle="collapse" data-target="#' . $id . '-content"' : ''; ?>>
                <span><?php echo $element->getLegend() ?></span>
            </strong>
            <?php echo $titleActions; ?>
        </div>
        <div class="fieldset-wrapper-content<?php echo($isCollapsable) ? ' collapse' : ''; ?>"
            id="<?php echo $id ?>-content"
            data-role="<?php echo $id ?>-content">
<?php endif; ?>

    <?php if (!$element->getNoContainer()): ?>
        <fieldset class="<?php echo $cssClass ?>" id="<?php echo $id ?>">
        <?php if ($element->getLegend() && !$isWrapped): ?>
            <legend class="<?php echo $isField ? 'label' : 'legend'?>">
                <span><?php echo $element->getLegend() ?></span>
            </legend><br />
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($element->getComment() && !$isField): ?>
        <div class="comment"><?php echo $this->escapeHtml($element->getComment()) ?></div>
    <?php endif; ?>

    <?php echo($isField) ? '<div class="control">' : ''; ?>

    <?php if ($element->hasHtmlContent() && !$isField): ?>
        <?php echo $element->getHtmlContent(); ?>
    <?php else: ?>

        <?php if ($isField && $count > 1):?>
            <div class="fields-group-<?php echo $count?>">
        <?php endif; ?>

        <?php echo $element->getBasicChildrenHtml(); ?>

        <?php echo($isField && $count > 1) ? '</div>' : '' ?>

        <?php if ($element->getComment() && $isField): ?>
            <div class="note"><?php echo $this->escapeHtml($element->getComment()) ?></div>
        <?php endif; ?>

        <?php if ($element->hasAdvanced() && !$isField): ?>
            <?php echo(!$element->getNoContainer() && $advancedAfter)  ? '</fieldset>' : ''?>
            <details class="details" id="details<?php echo $id ?>">
                <summary class="details-summary" id="details-summary<?php echo $id ?>">
                    <span><?php echo $advancedLabel ?></span>
                </summary>
                <div class="details-content" id="details-content<?php echo $id ?>">
                    <?php echo $element->getAdvancedChildrenHtml(); ?>
                </div>
            </details>
        <?php elseif ($element->hasAdvanced() && $isField): ?>
            <div class="nested" id="nested<?php echo $id ?>">
                <?php echo $element->getAdvancedChildrenHtml(); ?>
            </div>
        <?php endif; ?>

        <?php echo($isField) ? '</div>' : ''; ?>

    <?php endif; ?>


    <?php if (!$element->getNoContainer() && !$advancedAfter): ?>
        </fieldset>
    <?php endif; ?>

<?php if ($isWrapped): ?>
        </div>
    </div>
<?php endif; ?>
