<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper" >
    <a class="action showcart" href="<?php echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php echo __('My Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }">
            <span class="counter-number"><!-- ko text: cart().summary_count --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: cart().summary_count -->
                <!-- ko text: cart().summary_count --><!-- /ko -->
                <!-- ko text: $t('items') --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script>
        // TODO: MAGETWO-34827: adapt for new configuration mechanism
        window.checkout = {
            displaySubtotalInclTax: <?=$block->getDisplaySubtotalInclTax()?>,
            displaySubtotalExclTax: <?=$block->getDisplaySubtotalExclTax()?>,
            shoppingCartUrl: '<?=$this->getShoppingCartUrl()?>',
            checkoutUrl: '<?=$this->getCheckoutUrl()?>',
            updateItemQtyUrl: '<?=$this->getUpdateItemQtyUrl()?>',
            removeItemUrl: '<?=$this->getRemoveItemUrl()?>'
        };
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php echo $this->getJsLayout();?>
        }
    }
    </script>
</div>


