<?php
/**
 * Popup container template.
 *
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var \Magento\Backend\Block\Template $this
 */
?>
<script type="text/javascript">
require([
    "jquery",
    "jquery/ui",
	"Magento_Integration/js/integration"
], function($){

    window.integration = new Integration(
        '<?php echo $this->getUrl('*/*/permissionsDialog', ['id' => ':id', 'reauthorize' => ':isReauthorize']); ?>',
        '<?php echo $this->getUrl('*/*/tokensDialog', ['id' => ':id', 'reauthorize' => ':isReauthorize']); ?>',
        '<?php echo $this->getUrl('*/*/tokensExchange', ['id' => ':id', 'reauthorize' => ':isReauthorize']); ?>',
        '<?php echo $this->getUrl('*/*'); ?>',
        '<?php echo $this->getUrl('*/*/loginSuccessCallback'); ?>'
    );

    /**
     * Confirm dialog for delete integration action
     */
    $(function () {
        $('div#integrationGrid').on('click', 'button#delete', function (e) {
            $('#integration-delete-container').dialog({
                modal: true,
                autoOpen: true,
                resizable: false,
                minHeight: 200,
                minWidth: 300,
                dialogClass: "no-close",
                position: {at: 'center'},
                buttons: {
                    Cancel: function () {
                        $(this).dialog("close");
                    },
                    Delete: function () {
                        $(this).dialog("close");
                        window.location.href = $(e.target).data('url');
                    }
                }
            });
            e.stopPropagation();
        });
    });

});
</script>
<div id="integration-popup-container" style="display:none;"></div>
<div id="integration-delete-container" style="display:none;" title="<?php echo __('Are you sure ?'); ?>">
    <p><?php echo __("Are you sure you want to delete this integration? You can't undo this action."); ?></p>
</div>
