<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\OfflinePayments\Block\Info\Checkmo
 */
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>
<?php if ($block->getInfo()->getAdditionalInformation()) : ?>
    <?php if ($block->getPayableTo()) : ?>
        <br /><?= $block->escapeHtml(__('Make Check payable to: %1', $block->getPayableTo())) ?>
    <?php endif; ?>
    <?php if ($block->getMailingAddress()) : ?>
        <label><?= $block->escapeHtml(__('Send Check to:')) ?></label>
        <div class="checkmo-mailing-address">
            <?= /* @noEscape */ nl2br($block->escapeHtml($block->getMailingAddress())) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
