<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @deprecated
 * @var $block \Magento\Backend\Block\Page\System\Config\Robots\Reset
 */
?>

<script>
    require([
        'jquery'
    ], function ($) {
        window.resetRobotsToDefault = function(){
            $('#design_search_engine_robots_custom_instructions').val(<?=
                /* @noEscape */ $block-getViewModel()->serialize($block->getRobotsDefaultCustomInstructions())
            ?>);
        }
    });
</script>

<?= $block->getButtonHtml() ?>
