<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<button class="scalable" type="button" id="<?php echo $block->getHtmlId() ?>" data-mage-init='{"testConnection":{
    "url": "<?php echo /* @escapeNotVerified */ $block->getAjaxUrl() ?>",
    "elementId": "<?php echo $block->getHtmlId() ?>",
    "successText": "<?php echo /* @escapeNotVerified */ __('Successful! Test again?') ?>",
    "failedText": "<?php echo /* @escapeNotVerified */ __('Connection failed! Test again?') ?>",
    "fieldMapping": "<?php echo /* @escapeNotVerified */ $block->getFieldMapping() ?>"}, "validation": {}}'>
    <span><span><span id="<?php echo $block->getHtmlId() ?>_result"><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
</button>
