<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    tests
 * @package     static
 * @subpackage  Legacy
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
return array(
    '__get' => array('class_scope' => 'Varien_Object'),
    '__set' => array('class_scope' => 'Varien_Object'),
    '_addMinimalPrice' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product_Collection'),
    '_addTaxPercents' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product_Collection'),
    '_addToXml' => array('class_scope' => 'Mage_XmlConnect_Block_Checkout_Payment_Method_List'),
    '_afterSaveCommit' => array('class_scope' => 'Mage_Core_Model_Abstract'),
    '_afterSetConfig' => array('class_scope' => 'Mage_Eav_Model_Entity_Abstract'),
    '_aggregateByOrderCreatedAt' => array('class_scope' => 'Mage_SalesRule_Model_Resource_Report_Rule'),
    '_amountByCookies' => array('class_scope' => 'Mage_Sendfriend_Model_Sendfriend'),
    '_amountByIp' => array('class_scope' => 'Mage_Sendfriend_Model_Sendfriend'),
    '_applyCustomDesignSettings',
    '_applyCustomDesignSettings',
    '_applyDesign' => array('class_scope' => 'Mage_Catalog_Model_Design'),
    '_applyDesignRecursively' => array('class_scope' => 'Mage_Catalog_Model_Design'),
    '_avoidDoubleTransactionProcessing',
    '_beforeChildToHtml',
    '_calculatePrice' => array('class_scope' => 'Mage_Sales_Model_Quote_Item_Abstract'),
    '_checkUrlSettings' => array('class_scope' => 'Mage_Adminhtml_Controller_Action'),
    '_collectOrigData' => array('class_scope' => 'Mage_Catalog_Model_Resource_Abstract'),
    '_decodeInput' => array('class_scope' => 'Mage_Adminhtml_Catalog_ProductController'),
    '_emailOrderConfirmation' => array('class_scope' => 'Mage_Checkout_Model_Type_Abstract'),
    '_escapeValue' => array('class_scope' => 'Mage_Adminhtml_Block_Widget_Grid_Column_Filter_Abstract'),
    '_formatAddress' => array('class_scope' => 'Mage_XmlConnect_Block_Customer_Order_Details'),
    '_getAddressTaxRequest' => array('class_scope' => 'Mage_Tax_Model_Sales_Total_Quote_Shipping'),
    '_getAggregationPerStoreView',
    '_getAttributeFilterBlockName' => array('class_scope' => 'Mage_Catalog_Block_Layer_View'),
    '_getAttributeFilterBlockName' => array('class_scope' => 'Mage_CatalogSearch_Block_Layer'),
    '_getAttributeFilterBlockName',
    '_getAvailable' => array('class_scope' => 'Mage_GiftMessage_Model_Observer'),
    '_getCacheId' => array('class_scope' => 'Mage_Core_Model_App'),
    '_getCacheKey' => array('class_scope' => 'Mage_Catalog_Model_Layer_Filter_Price'),
    '_getCacheTags' => array('class_scope' => 'Mage_Core_Model_App'),
    '_getChildHtml',
    '_getCollectionNames' => array('class_scope' => 'Mage_Adminhtml_Report_SalesController'),
    '_getConnenctionType' => array('class_scope' => 'Mage_Install_Model_Installer_Db'),
    '_getDateFromToHtml' => array('class_scope' => 'Mage_ImportExport_Block_Adminhtml_Export_Filter'),
    '_getExistingBasePopularity',
    '_getFieldTableAlias' => array('class_scope' => 'Mage_Newsletter_Model_Resource_Subscriber_Collection'),
    '_getForeignKeyName' => array('class_scope' => 'Varien_Db_Adapter_Pdo_Mysql'),
    '_getGiftmessageSaveModel' => array('class_scope' => 'Mage_Adminhtml_Block_Sales_Order_Create_Search_Grid'),
    '_getGlobalAggregation',
    '_getGroupByDateFormat' => array('class_scope' => 'Mage_Log_Model_Resource_Visitor_Collection'),
    '_getInputHtml' => array('class_scope' => 'Mage_ImportExport_Block_Adminhtml_Export_Filter'),
    '_getLabelForStore' => array('class_scope' => 'Mage_Catalog_Model_Resource_Eav_Attribute'),
    '_getMultiSelectHtml' => array('class_scope' => 'Mage_ImportExport_Block_Adminhtml_Export_Filter'),
    '_getNumberFromToHtml' => array('class_scope' => 'Mage_ImportExport_Block_Adminhtml_Export_Filter'),
    '_getPriceFilter' => array('class_scope' => 'Mage_Catalog_Block_Layer_View'),
    '_getProductQtyForCheck' => array('class_scope' => 'Mage_CatalogInventory_Model_Observer'),
    '_getRangeByType' => array('class_scope' => 'Mage_Log_Model_Resource_Visitor_Collection'),
    '_getRecentProductsCollection',
    '_getSelectHtml' => array('class_scope' => 'Mage_ImportExport_Block_Adminhtml_Export_Filter'),
    '_getSetData' => array('class_scope' => 'Mage_Adminhtml_Block_Catalog_Product_Attribute_Set_Main'),
    '_getSHAInSet' => array('suggestion' => 'Mage_Ogone_Model_Api::getHash'),
    '_getStoreTaxRequest' => array('class_scope' => 'Mage_Tax_Model_Sales_Total_Quote_Shipping'),
    '_importAddress' => array('class_scope' => 'Mage_Paypal_Model_Api_Nvp'),
    '_inheritDesign' => array('class_scope' => 'Mage_Catalog_Model_Design'),
    '_initOrder' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    '_initShipment' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    '_inludeControllerClass' => array('suggestion' => '_includeControllerClass'),
    '_isApplyDesign' => array('class_scope' => 'Mage_Catalog_Model_Design'),
    '_isApplyFor' => array('class_scope' => 'Mage_Catalog_Model_Design'),
    '_isPositiveDecimalNumber' => array('class_scope' => 'Mage_Shipping_Model_Resource_Carrier_Tablerate'),
    '_loadOldRates' => array('class_scope' => 'Mage_Tax_Model_Resource_Setup'),
    '_needSubtractShippingTax',
    '_needSubtractTax',
    '_needToAddDummy',
    '_needToAddDummyForShipment',
    '_parseDescription' => array('class_scope' => 'Mage_Sales_Model_Order_Pdf_Items_Abstract'),
    '_parseXmlTrackingResponse' => array('class_scope' => 'Mage_Usa_Model_Shipping_Carrier_Fedex'),
    '_prepareCondition' => array('class_scope' => 'Mage_CatalogSearch_Model_Advanced'),
    '_prepareConfigurableProductData' => array('class_scope' => 'Mage_ImportExport_Model_Export_Entity_Product'),
    '_prepareConfigurableProductPrice' => array('class_scope' => 'Mage_ImportExport_Model_Export_Entity_Product'),
    '_prepareOptionsForCart' => array('class_scope' => 'Mage_Catalog_Model_Product_Type_Abstract'),
    '_preparePackageTheme' => array('class_scope' => 'Mage_Widget_Model_Widget_Instance'),
    '_processItem' => array('class_scope' => 'Mage_Weee_Model_Total_Quote_Weee'),
    '_processShippingAmount',
    '_processValidateCustomer' => array('class_scope' => 'Mage_Checkout_Model_Type_Onepage'),
    '_putCustomerIntoQuote' => array('class_scope' => 'Mage_Adminhtml_Model_Sales_Order_Create'),
    '_quoteRow' => array('class_scope' => 'Mage_Backup_Model_Resource_Db'),
    '_recollectItem' => array('class_scope' => 'Mage_Tax_Model_Sales_Total_Quote_Subtotal'),
    '_resetItemPriceInclTax',
    '_saveCustomerAfterOrder' => array('class_scope' => 'Mage_Adminhtml_Model_Sales_Order_Create'),
    '_saveCustomers' => array('class_scope' => 'Mage_Adminhtml_Model_Sales_Order_Create'),
    '_sendUploadResponse' => array('class_scope' => 'Mage_Adminhtml_CustomerController'),
    '_sendUploadResponse' => array('class_scope' => 'Mage_Adminhtml_Newsletter_SubscriberController'),
    '_setAttribteValue',
    'addBackupedFilter',
    'addConfigField' => array('class_scope' => 'Mage_Core_Model_Resource_Setup'),
    'addConstraint' => array('class_scope' => 'Varien_Db_Adapter_Pdo_Mysql'),
    'addCustomersToAlertQueueAction',
    'addCustomerToSegments',
    'addGroupByTag' => array('class_scope' => 'Mage_Reports_Model_Resource_Tag_Collection'),
    'addKey' => array('class_scope' => 'Varien_Db_Adapter_Pdo_Mysql'),
    'addSaleableFilterToCollection',
    'addSearchQfFilter',
    'addStoresFilter' => array('class_scope' => 'Mage_Poll_Model_Resource_Poll_Collection'),
    'addSummary' => array('class_scope' => 'Mage_Tag_Model_Resource_Tag'),
    'addSummary' => array('class_scope' => 'Mage_Tag_Model_Tag'),
    'addTemplateData' => array('class_scope' => 'Mage_Newsletter_Model_Queue'),
    'addToAlersAction',
    'addToChildGroup',
    'addVisibleFilterToCollection' => array('class_scope' => 'Mage_Catalog_Model_Product_Status'),
    'addVisibleInCatalogFilterToCollection' => array('suggestion' =>
        '$collection->setVisibility(Mage_Catalog_Model_Product_Visibility->getVisibleInCatalogIds());'
    ),
    'addVisibleInSearchFilterToCollection' => array('suggestion' =>
        '$collection->setVisibility(Mage_Catalog_Model_Product_Visibility->getVisibleInSearchIds());'
    ),
    'addVisibleInSiteFilterToCollection' => array('suggestion' =>
        '$collection->setVisibility(Mage_Catalog_Model_Product_Visibility->getVisibleInSiteIds());'
    ),
    'addWishlistLink' => array('class_scope' => 'Mage_Wishlist_Block_Links'),
    'addWishListSortOrder' => array('class_scope' => 'Mage_Wishlist_Model_Resource_Item_Collection'),
    'aggregate' => array('class_scope' => 'Mage_Tag_Model_Resource_Tag'),
    'aggregate' => array('class_scope' => 'Mage_Tag_Model_Tag'),
    'applyDesign' => array('class_scope' => 'Mage_Catalog_Model_Design'),
    'authAdmin',
    'authFailed' => array('suggestion' => 'Mage_Core_Helper_Http::failHttpAuthentication()'),
    'authFrontend',
    'authValidate' => array('suggestion' => 'Mage_Core_Helper_Http::getHttpAuthCredentials()'),
    'bundlesAction' => array('class_scope' => 'Mage_Adminhtml_Catalog_ProductController'),
    'calcTaxAmount' => array('class_scope' => 'Mage_Sales_Model_Quote_Item_Abstract'),
    'canPrint' => array('class_scope' => 'Mage_Checkout_Block_Onepage_Success'),
    'catalogCategoryChangeProducts' => array('class_scope' => 'Mage_Catalog_Model_Product_Flat_Observer'),
    'catalogEventProductCollectionAfterLoad' => array('class_scope' => 'Mage_GiftMessage_Model_Observer'),
    'catalogProductLoadAfter' => array('class_scope' => 'Mage_Bundle_Model_Observer'),
    'chechAllowedExtension',
    'checkConfigurableProducts' => array('class_scope' => 'Mage_Eav_Model_Resource_Entity_Attribute_Collection'),
    'checkDatabase' => array('class_scope' => 'Mage_Install_Model_Installer_Db'),
    'checkDateTime' => array('class_scope' => 'Mage_Core_Model_Date'),
    'cleanDbRow' => array('class_scope' => 'Mage_Core_Model_Resource'),
    'cloneIndexTable' => array('class_scope' => 'Mage_Index_Model_Resource_Abstract'),
    'convertOldTaxData' => array('class_scope' => 'Mage_Tax_Model_Resource_Setup'),
    'convertOldTreeToNew' => array('class_scope' => 'Mage_Catalog_Model_Resource_Setup'),
    'countChildren' => array('class_scope' => 'Mage_Core_Block_Abstract'),
    'crear',
    'createOrderItem' => array('class_scope' => 'Mage_CatalogInventory_Model_Observer'),
    'debugRequest' => array('class_scope' => 'Mage_Paypal_Model_Api_Standard'),
    'deleteProductPrices' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product_Attribute_Backend_Tierprice'),
    'displayFullSummary' => array('class_scope' => 'Mage_Tax_Model_Config'),
    'displayTaxColumn' => array('class_scope' => 'Mage_Tax_Model_Config'),
    'displayZeroTax' => array('class_scope' => 'Mage_Tax_Model_Config'),
    'drawItem' => array('class_scope' => 'Mage_Catalog_Block_Navigation'),
    'dropKey' => array('class_scope' => 'Varien_Db_Adapter_Pdo_Mysql'),
    'editAction' => array('class_scope' => 'Mage_Tag_CustomerController'),
    'exportOrderedCsvAction',
    'exportOrderedExcelAction',
    'fetchItemsCount' => array('class_scope' => 'Mage_Wishlist_Model_Resource_Wishlist'),
    'fetchRuleRatesForCustomerTaxClass',
    'forsedSave',
    'generateBlocks' => array('suggestion' => 'generateElements()'),
    'getAccount' => array('class_scope' => 'Mage_GoogleAnalytics_Block_Ga'),
    'getAddNewButtonHtml' => array('class_scope' => 'Mage_Adminhtml_Block_Catalog_Product'),
    'getAddToCartItemUrl' => array('class_scope' => 'Mage_Wishlist_Block_Customer_Sidebar'),
    'getAddToCartUrlBase64' => array('suggestion' => '_getAddToCartUrl'),
    'getAllEntityIds' => array('class_scope' => 'Mage_Rss_Model_Resource_Order'),
    'getAllEntityTypeCommentIds' => array('class_scope' => 'Mage_Rss_Model_Resource_Order'),
    'getAllOrderEntityIds' => array('class_scope' => 'Mage_Rss_Model_Resource_Order'),
    'getAllOrderEntityTypeIds' => array('class_scope' => 'Mage_Rss_Model_Resource_Order'),
    'getAnonSuffix',
    'getBaseTaxAmount' => array('class_scope' => 'Mage_Sales_Model_Quote_Item_Abstract'),
    'getCheckoutMehod' => array('class_scope' => 'Mage_Checkout_Model_Type_Onepage'),
    'getChild' => array('directory' => 'app', 'suggestion' => 'Mage_Core_Block_Abstract::getChildBlock()'),
    'getChildGroup' => array('suggestion' => 'Mage_Core_Block_Abstract::getGroupChildNames()'),
    'getConfig' => array('class_scope' => 'Mage_Eav_Model_Entity_Attribute_Abstract'),
    'getCustomerData' => array('class_scope' => 'Mage_Adminhtml_Block_Sales_Order_Create_Form_Account'),
    'getDataForSave' => array('class_scope' => 'Mage_Wishlist_Model_Item'),
    'getDebug' => array('class_scope' => 'Mage_Ogone_Model_Api'),
    'getDebug' => array('class_scope' => 'Mage_Paypal_Model_Api_Abstract'),
    'getDirectOutput' => array('class_scope' => 'Mage_Core_Model_Layout'),
    'getEntityIdsToIncrementIds' => array('class_scope' => 'Mage_Rss_Model_Resource_Order'),
    'getEntityTypeIdsToTypes' => array('class_scope' => 'Mage_Rss_Model_Resource_Order'),
    'getFacets',
    'getFallbackTheme',
    'getFormated' => array(
        'suggestion' => 'getFormated(true) -> format(\'html\'), getFormated() -> format(\'text\')'
    ),
    'getFormObject' => array('class_scope' => 'Mage_Adminhtml_Block_Widget_Form'),
    'getGiftmessageHtml' => array('class_scope' => 'Mage_Adminhtml_Block_Sales_Order_View_Tab_Info'),
    'getHtmlFormat' => array('class_scope' => 'Mage_Customer_Model_Address_Abstract'),
    'getIsActiveAanalytics' => array('suggestion' => 'getOnsubmitJs'),
    'getIsAjaxRequest' => array('class_scope' => 'Mage_Core_Model_Translate_Inline'),
    'getIsAnonymous',
    'getIsEngineAvailable',
    'getIsGlobal' => array('class_scope' => 'Mage_Eav_Model_Entity_Attribute_Abstract'),
    'getIsInStock' => array('class_scope' => 'Mage_Checkout_Block_Cart_Item_Renderer'),
    'getItemRender' => array('class_scope' => 'Mage_Checkout_Block_Cart_Abstract'),
    'getJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Customer_Collection'),
    'getJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Product_Collection'),
    'getJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Tag_Collection'),
    'getKeyList' => array('class_scope' => 'Varien_Db_Adapter_Pdo_Mysql'),
    'getLanguages' => array('class_scope' => 'Mage_Install_Block_Begin'),
    'getLayoutFilename' => array('suggestion' => 'getFilename'),
    'getLifeTime' => array('class_scope' => 'Mage_Core_Model_Resource_Session'),
    'getLocaleBaseDir' => array('class_scope' => 'Mage_Core_Model_Design_Package'),
    'getMail' => array('class_scope' => 'Mage_Newsletter_Model_Template'),
    'getMaxQueryLenght',
    'getMergedCssUrl',
    'getMergedJsUrl',
    'getMinQueryLenght',
    'getOneBalanceTotal',
    'getOrderHtml' => array('class_scope' => 'Mage_GoogleAnalytics_Block_Ga'),
    'getOrderId' => array('class_scope' => 'Mage_Checkout_Block_Onepage_Success'),
    'getOrderId' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'getOriginalHeigh' => array('suggestion' => 'getOriginalHeight'),
    'getParentProductIds' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product'),
    'getPriceFormatted' => array('class_scope' => 'Mage_Adminhtml_Block_Customer_Edit_Tab_View_Sales'),
    'getPrices' => array('class_scope' => 'Mage_Bundle_Model_Product_Price'),
    'getPricesDependingOnTax' => array('class_scope' => 'Mage_Bundle_Model_Product_Price'),
    'getPrintUrl' => array('class_scope' => 'Mage_Checkout_Block_Onepage_Success'),
    'getPrintUrl' => array('class_scope' => 'Mage_Sales_Block_Order_Info'),
    'getProductCollection' => array('class_scope' => 'Mage_Wishlist_Helper_Data'),
    'getProductCollection' => array('class_scope' => 'Mage_Wishlist_Model_Wishlist'),
    'getProductsNotInStoreIds',
    'getProfile' => array('class_scope' => 'Varien_Convert_Container_Abstract'),
    'getQuoteItem' => array('class_scope' => 'Mage_Catalog_Model_Product_Option_Type_Default'),
    'getQuoteItemOption' => array('class_scope' => 'Mage_Catalog_Model_Product_Option_Type_Default'),
    'getQuoteOrdersHtml' => array('class_scope' => 'Mage_GoogleAnalytics_Block_Ga'),
    'getRemoveItemUrl' => array('class_scope' => 'Mage_Wishlist_Block_Customer_Sidebar'),
    'getReorderUrl' => array('class_scope' => 'Mage_Sales_Block_Order_Info'),
    'getRowId' => array('class_scope' => 'Mage_Adminhtml_Block_Sales_Order_Create_Customer_Grid'),
    'getRowId' => array('class_scope' => 'Mage_Adminhtml_Block_Widget_Grid'),
    'getSaveTemplateFlag' => array('class_scope' => 'Mage_Newsletter_Model_Queue'),
    'getSelectionFinalPrice' => array('class_scope' => 'Mage_Bundle_Model_Product_Price'),
    'getShipId' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'getSortedChildren' => array('suggestion' => 'getChildNames'),
    'getSortedChildBlocks' => array('suggestion' => 'getChildNames() + $this->getLayout()->getBlock($name)'),
    'getStatrupPageUrl',
    'getStoreCurrency' => array('class_scope' => 'Mage_Sales_Model_Order'),
    'getSuggestedZeroDate',
    'getSuggestionsByQuery',
    'getSuggestionsByQuery',
    'getTaxAmount' => array('class_scope' => 'Mage_Sales_Model_Quote_Item_Abstract'),
    'getTaxRatesByProductClass' => array('suggestion' => '_getAllRatesByProductClass'),
    'getTemplateFilename' => array('suggestion' => 'getFilename'),
    'getTotalModels' => array('class_scope' => 'Mage_Sales_Model_Quote_Address'),
    'getTrackId' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'getTrackingInfoByOrder' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'getTrackingInfoByShip' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'getTrackingInfoByTrackId' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'getTrackingPopUpUrlByOrderId' => array('suggestion' => 'getTrackingPopupUrlBySalesModel'),
    'getTrackingPopUpUrlByShipId' => array('suggestion' => 'getTrackingPopupUrlBySalesModel'),
    'getTrackingPopUpUrlByTrackId' => array('suggestion' => 'getTrackingPopupUrlBySalesModel'),
    'getUseCacheFilename' => array('class_scope' => 'Mage_Core_Model_App'),
    'getValidator' => array('class_scope' => 'Mage_SalesRule_Model_Observer'),
    'getValidatorData' => array(
        'class_scope' => 'Mage_Core_Model_Session_Abstract',
        'suggestion' => 'use _getSessionEnvironment method'
    ),
    'getValueTable',
    'getViewOrderUrl' => array('class_scope' => 'Mage_Checkout_Block_Onepage_Success'),
    'getWidgetSupportedBlocks' => array('class_scope' => 'Mage_Widget_Model_Widget_Instance'),
    'getWidgetSupportedTemplatesByBlock' => array('class_scope' => 'Mage_Widget_Model_Widget_Instance'),
    'hasItems' => array('class_scope' => 'Mage_Wishlist_Helper_Data'),
    'htmlEscape' => array('suggestion' => 'escapeHtml'),
    'imageAction' => array('class_scope' => 'Mage_Catalog_ProductController'),
    'importFromTextArray',
    'initLabels' => array('class_scope' => 'Mage_Catalog_Model_Resource_Eav_Attribute'),
    'insertProductPrice' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product_Attribute_Backend_Tierprice'),
    'isAllowedGuestCheckout' => array('class_scope' => 'Mage_Sales_Model_Quote'),
    'isAutomaticCleaningAvailable' => array('class_scope' => 'Varien_Cache_Backend_Eaccelerator'),
    'isCheckoutAvailable' => array('class_scope' => 'Mage_Checkout_Model_Type_Multishipping'),
    'isFulAmountCovered',
    'isLeyeredNavigationAllowed',
    'isReadablePopupObject',
    'isTemplateAllowedForApplication',
    'loadLabel' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product_Type_Configurable_Attribute'),
    'loadParentProductIds' => array('class_scope' => 'Mage_Catalog_Model_Product'),
    'loadPrices' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product_Type_Configurable_Attribute'),
    'loadProductPrices' => array('class_scope' => 'Mage_Catalog_Model_Resource_Product_Attribute_Backend_Tierprice'),
    'lockOrderInventoryData' => array('class_scope' => 'Mage_CatalogInventory_Model_Observer'),
    'logEncryptionKeySave',
    'logInvitationSave',
    'mergeFiles' => array('class_scope' => 'Mage_Core_Helper_Data'),
    'order_success_page_view' => array('class_scope' => 'Mage_GoogleAnalytics_Model_Observer'),
    'orderedAction' => array('class_scope' => 'Mage_Adminhtml_Report_ProductController'),
    'parse' => array('class_scope' => 'Mage_Catalog_Model_Convert_Parser_Product'),
    'parse' => array('class_scope' => 'Mage_Customer_Model_Convert_Parser_Customer'),
    'parseDateTime' => array('class_scope' => 'Mage_Core_Model_Date'),
    'postDispatchMyAccountSave',
    'prepareCacheId' => array('class_scope' => 'Mage_Core_Model_App'),
    'prepareGoogleOptimizerScripts',
    'preprocess' => array('class_scope' => 'Mage_Newsletter_Model_Template'),
    'processBeacon',
    'processBeforeVoid' => array('class_scope' => 'Mage_Payment_Model_Method_Abstract'),
    'processSubst' => array('class_scope' => 'Mage_Core_Model_Store'),
    'productEventAggregate',
    'rebuildCategoryLevels' => array('class_scope' => 'Mage_Catalog_Model_Resource_Setup'),
    'regenerateSessionId' => array('class_scope' => 'Mage_Core_Model_Session_Abstract'),
    'refundOrderItem' => array('class_scope' => 'Mage_CatalogInventory_Model_Observer'),
    'removeCustomerFromSegments',
    'removeCustomerFromSegments',
    'revalidateCookie' => array('class_scope' => 'Mage_Core_Model_Session_Abstract_Varien'),
    'sales_order_afterPlace',
    'sales_quote_address_discount_item',
    'salesOrderPaymentPlaceEnd',
    'saveRow__OLD',
    'saveAction' => array('class_scope' => 'Mage_Tag_CustomerController'),
    'saveSegmentCustomersFromSelect',
    'send' => array('class_scope' => 'Mage_Newsletter_Model_Template'),
    'sendNewPasswordEmail',
    'setAnonSuffix',
    'setBlockAlias',
    'setCustomerId' => array('class_scope' => 'Mage_Customer_Model_Resource_Address'),
    'setIsAjaxRequest' => array('class_scope' => 'Mage_Core_Model_Translate_Inline'),
    'setIsAnonymous',
    'setJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Customer_Collection'),
    'setJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Product_Collection'),
    'setJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Tag_Collection'),
    'setOrderId' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'setWatermarkHeigth' => array('suggestion'  => 'setWatermarkHeight'),
    'getWatermarkHeigth' => array('suggestion'  => 'getWatermarkHeight'),
    'setParentBlock',
    'setProfile' => array('class_scope' => 'Varien_Convert_Container_Abstract'),
    'setSaveTemplateFlag' => array('class_scope' => 'Mage_Newsletter_Model_Queue'),
    'setShipId' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'setTaxGroupFilter',
    'setTrackId' => array('class_scope' => 'Mage_Shipping_Block_Tracking_Popup'),
    'shaCrypt' => array('suggestion' => 'Mage_Ogone_Model_Api::getHash'),
    'shaCryptValidation' => array('suggestion' => 'Mage_Ogone_Model_Api::getHash'),
    'shouldCustomerHaveOneBalance',
    'shouldShowOneBalance',
    'sortChildren',
    'toOptionArray' => array('class_scope' => 'Mage_Cms_Model_Resource_Page_Collection'),
    'toOptionArray' => array('class_scope' => 'Mage_Sendfriend_Model_Sendfriend'),
    'truncate' => array('class_scope' => 'Varien_Db_Adapter_Pdo_Mysql'),
    'unsetBlock',
    'unsetJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Customer_Collection'),
    'unsetJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Product_Collection'),
    'unsetJoinFlag' => array('class_scope' => 'Mage_Tag_Model_Resource_Tag_Collection'),
    'useValidateRemoteAddr' => array('class_scope' => 'Mage_Core_Model_Session_Abstract'),
    'useValidateHttpVia' => array('class_scope' => 'Mage_Core_Model_Session_Abstract'),
    'useValidateHttpXForwardedFor' => array('class_scope' => 'Mage_Core_Model_Session_Abstract'),
    'useValidateHttpUserAgent' => array('class_scope' => 'Mage_Core_Model_Session_Abstract'),
    'updateCofigurableProductOptions' => array(
        'class_scope' => 'Mage_Weee_Model_Observer',
        'suggestion' => 'updateConfigurableProductOptions'
    ),
    'updateTable' => array('class_scope' => 'Mage_Core_Model_Resource_Setup'),
    'urlEscape' => array('suggestion' => 'escapeUrl'),
    'validateDataArray' => array('class_scope' => 'Varien_Convert_Container_Abstract'),
    'validateFile' => array('class_scope' => 'Mage_Core_Model_Design_Package'),
    'validateOrder' => array('class_scope' => 'Mage_Checkout_Model_Type_Onepage'),
);
