<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tabs */
?>
<?php if (!empty($tabs)): ?>
<?php $tabGroups = [
    \Magento\Catalog\Block\Adminhtml\Product\Edit\Tabs::BASIC_TAB_GROUP_CODE,
    \Magento\Catalog\Block\Adminhtml\Product\Edit\Tabs::ADVANCED_TAB_GROUP_CODE,
];?>
<div id="<?php echo $block->getId() ?>"
    data-mage-init='{"tabs":{
        "active": "<?php echo $block->getActiveTabId() ?>",
        "destination": "#<?php echo $block->getDestElementId() ?>",
        "shadowTabs": "<?php echo $block->getAllShadowTabs()?>",
        "tabsBlockPrefix": "<?php echo $block->getId() ?>_",
        "tabIdArgument": "active_tab",
        "groups": "ul.tabs"
    }}'>
    <?php foreach ($tabGroups as $tabGroupCode): ?>
    <?php $tabGroupId = $block->getId() . '-' . $tabGroupCode; ?>
    <?php $isBasic = $tabGroupCode == \Magento\Catalog\Block\Adminhtml\Product\Edit\Tabs::BASIC_TAB_GROUP_CODE; ?>
    <div id="<?php echo $tabGroupId ?>"
        <?php if (!$isBasic): ?>
            data-mage-init='{"collapsible":{"active": <?php echo $block->isAdvancedTabGroupActive() ? 'true' : 'false' ?>, "collapsible": true}}'
        <?php endif;?>>
        <h3 <?php echo $block->getUiId('title') ?> data-role="title" <?php if (!$isBasic): ?>class="ui-accordion-header"<?php endif;?>>
            <span data-role="trigger"> <?php echo $isBasic ? __('Basic Settings') : __('Advanced Settings') ?></span>
        </h3>
        <ul <?php echo $block->getUiId('tab', $tabGroupId) ?> class="tabs" data-role="content">
            <?php foreach ($tabs as $_tab): ?>
            <?php if (!$block->canShowTab($_tab) || $_tab->getParentTab()
                || ($_tab->getGroupCode() && $_tab->getGroupCode() != $tabGroupCode)
                || (!$_tab->getGroupCode() && $isBasic)): continue; endif;?>
            <?php $_tabClass = 'tab-item-link ' . $block->getTabClass($_tab) . ' ' . (preg_match('/\s?ajax\s?/', $_tab->getClass()) ? 'notloaded' : '') ?>
            <?php $_tabType = (!preg_match('/\s?ajax\s?/', $_tabClass) && $block->getTabUrl($_tab) != '#') ? 'link' : '' ?>
            <?php $_tabHref = $block->getTabUrl($_tab) == '#' ? '#' . $block->getTabId($_tab) . '_content' : $block->getTabUrl($_tab) ?>
            <li <?php if ($block->getTabIsHidden($_tab)): ?> class="no-display"<?php endif; ?><?php echo $block->getUiId('tab', 'item', $_tab->getId()) ?>>
                <a href="<?php echo $_tabHref ?>" id="<?php echo $block->getTabId($_tab) ?>"
                   name="<?php echo $block->getTabId($_tab, false) ?>" title="<?php echo $block->getTabTitle($_tab) ?>"
                   class="<?php echo $_tabClass;?>"
                   data-tab-type="<?php echo $_tabType;?>" <?php echo $block->getUiId('tab', 'link', $_tab->getId()) ?>>
                    <span>
                        <span class="changed" title="<?php echo __('The information in this tab has been changed.') ?>"></span>
                        <span class="error" title="<?php echo __('This tab contains invalid data. Please solve the problem before saving.') ?>"></span>
                        <span class="loader" title="<?php echo __('Loading...') ?>"></span>
                        <?php echo $block->escapeHtml($block->getTabLabel($_tab)); ?>
                    </span>
                </a>
                <div id="<?php echo $block->getTabId($_tab) ?>_content" class="no-display"
                     data-tab-panel="<?=$_tab->getTabId() ?>"
                     <?php echo $block->getUiId('tab', 'content', $_tab->getId()) ?>>
                    <?php echo $block->getTabContent($_tab); ?>
                    <?php foreach ($tabs as $childTab): ?>
                        <?php if ($childTab->getParentTab() === $_tab->getId()):?>
                            <div id="<?php echo $block->getTabId($childTab) ?>_content"
                                <?php echo $block->getUiId('tab', 'content', $childTab->getId()) ?>>
                            <?php echo $block->getTabContent($childTab); ?>
                        <?php endif;?>
                    <?php endforeach; ?>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
