<?php
/**
 * Obsolete namespaces
 *
 * Format: array(<namespace>[, <replacement>])
 *
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
return [
    ['Magento\App', 'Magento\Framework\App'],
    ['Magento\Data', 'Magento\Framework\Data'],
    ['Magento\Filesystem', 'Magento\Framework\Filesystem'],
    ['Magento\Config', 'Magento\Framework\Config'],
    ['Magento\Model', 'Magento\Framework\Model'],
    ['Magento\View', 'Magento\Framework\View'],
    ['Magento\DB', 'Magento\Framework\DB'],
    ['Magento\Event', 'Magento\Framework\Event'],
    ['Magento\Acl', 'Magento\Framework\Acl'],
    ['Magento\Archive', 'Magento\Framework\Archive'],
    ['Magento\Session', 'Magento\Framework\Session'],
    ['Magento\Cache', 'Magento\Framework\Cache'],
    ['Magento\ObjectManager', 'Magento\Framework\ObjectManager'],
    ['Magento\Exception', 'Magento\Framework\Exception'],
    ['Magento\Autoload', 'Magento\Framework\Autoload'],
    ['Magento\Translate', 'Magento\Framework\Translate'],
    ['Magento\Code', 'Magento\Framework\Code'],
    ['Magento\Stdlib', 'Magento\Framework\Stdlib'],
    ['Magento\Phrase', 'Magento\Framework\Phrase'],
    ['Magento\Locale', 'Magento\Framework\Locale'],
    ['Magento\Message', 'Magento\Framework\Message'],
    ['Magento\Logger', 'Psr\Log\LoggerInterface'],
    ['Magento\Error', 'Magento\Framework\Error'],
    ['Magento\Filter', 'Magento\Framework\Filter'],
    ['Magento\DomDocument', 'Magento\Framework\DomDocument'],
    ['Magento\Module', 'Magento\Framework\Module'],
    ['Magento\Css', 'Magento\Framework\Css'],
    ['Magento\Pear', 'Magento\Framework\Pear'],
    ['Magento\Pricing', 'Magento\Framework\Pricing'],
    ['Magento\Profiler', 'Magento\Framework\Profiler'],
    ['Magento\Simplexml', 'Magento\Framework\Simplexml'],
    ['Magento\Controller', 'Magento\Framework\Controller'],
    ['Magento\Convert', 'Magento\Framework\Convert'],
    ['Magento\Shell', 'Magento\Framework\Shell'],
    ['Magento\Encryption', 'Magento\Framework\Encryption'],
    ['Magento\Option', 'Magento\Framework\Option'],
    ['Magento\Service', 'Magento\Framework\Api'],
    ['Magento\System', 'Magento\Framework\System'],
    ['Magento\Url', 'Magento\Framework\Url'],
    ['Magento\Mview', 'Magento\Framework\Mview'],
    ['Magento\Validator', 'Magento\Framework\Validator'],
    ['Magento\Xml', 'Magento\Framework\Xml'],
    ['Magento\Interception', 'Magento\Framework\Interception'],
    ['Magento\Json', 'Magento\Framework\Json'],
    ['Magento\Less', 'Magento\Framework\Less'],
    ['Magento\File', 'Magento\Framework\File'],
    ['Magento\Flag', 'Magento\Framework\Flag'],
    ['Magento\Io', 'Magento\Framework\Io'],
    ['Magento\Mail', 'Magento\Framework\Mail'],
    ['Magento\HTTP', 'Magento\Framework\HTTP'],
    ['Magento\Math', 'Magento\Framework\Math'],
    ['Magento\Gdata', 'Magento\Framework\Gdata'],
    ['Magento\Image', 'Magento\Framework\Image'],
    ['Magento\Oauth', 'Magento\Framework\Oauth'],
    ['Magento\Object', 'Magento\Framework\Object'],
    ['Magento\Connect'],
    ['Magento\Framework\Connect'],
    ['Magento\Bundle\Service'],
    ['Magento\Tax\Service'],
    ['Magento\RecurringPayment'],
    ['Magento\PayPalRecurringPayment'],
    ['Magento\ConfigurableProduct\Service'],
    ['Magento\Catalog\Service']
];
