<?php
/**
 * Obsolete classes
 *
 * Format: array(<class_name>[, <replacement>])
 *
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2013 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
return array(
    array('Mage_Admin_Helper_Data', 'Magento\Backend\Helper\Data'),
    array('Mage_Admin_Model_Acl', 'Magento_Acl'),
    array('Mage_Admin_Model_Acl_Role'),
    array('Mage_Admin_Model_Acl_Resource', 'Magento\Acl\Resource'),
    array('Mage_Admin_Model_Acl_Role_Registry', 'Magento\Acl\Role\Registry'),
    array('Mage_Admin_Model_Acl_Role_Generic', 'Magento\User\Model\Acl\Role\Generic'),
    array('Mage_Admin_Model_Acl_Role_Group', 'Magento\User\Model\Acl\Role\Group'),
    array('Mage_Admin_Model_Acl_Role_User', 'Magento\User\Model\Acl\Role\User'),
    array('Mage_Admin_Model_Resource_Acl', 'Magento\User\Model\Resource\Acl'),
    array('Mage_Admin_Model_Observer'),
    array('Mage_Admin_Model_Session', 'Magento\Backend\Model\Auth\Session'),
    array('Mage_Admin_Model_Resource_Acl_Role'),
    array('Mage_Admin_Model_Resource_Acl_Role_Collection'),
    array('Mage_Admin_Model_User', 'Magento\User\Model\User'),
    array('Mage_Admin_Model_Config'),
    array('Mage_Admin_Model_Resource_User', 'Magento\User\Model\Resource\User'),
    array('Mage_Admin_Model_Resource_User_Collection', 'Magento\User\Model\Resource\User\Collection'),
    array('Mage_Admin_Model_Role', 'Magento\User\Model\Role'),
    array('Mage_Admin_Model_Roles', 'Magento\User\Model\Roles'),
    array('Mage_Admin_Model_Rules', 'Magento\User\Model\Rules'),
    array('Mage_Admin_Model_Resource_Role', 'Magento\User\Model\Resource\Role'),
    array('Mage_Admin_Model_Resource_Roles', 'Magento\User\Model\Resource\Roles'),
    array('Mage_Admin_Model_Resource_Rules', 'Magento\User\Model\Resource\Rules'),
    array('Mage_Admin_Model_Resource_Role_Collection', 'Magento\User\Model\Resource\Role\Collection'),
    array('Mage_Admin_Model_Resource_Roles_Collection', 'Magento\User\Model\Resource\Roles\Collection'),
    array('Mage_Admin_Model_Resource_Roles_User_Collection',
        'Magento\User\Model\Resource\Roles\User\Collection'),
    array('Mage_Admin_Model_Resource_Rules_Collection', 'Magento\User\Model\Resource\Rules\Collection'),
    array('Mage_Admin_Model_Resource_Permissions_Collection',
        'Magento\User\Model\Resource\Permissions\Collection'),
    array('Mage_Adminhtml_Block_Abstract', 'Magento\Backend\Block\AbstractBlock'),
    array('Mage_Adminhtml_Block_Backup_Grid'),
    array('Mage_Adminhtml_Block_Cache_Grid'),
    array('Mage_Adminhtml_Block_Catalog'),
    array('Mage_Adminhtml_Block_Catalog_Product_Attribute_Set_Grid'),
    array('Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config_Grid'),
    array('Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Group_Grid'),
    array('Mage_Adminhtml_Block_Catalog_Search_Grid'),
    array('Mage_Adminhtml_Block_Cms_Block_Grid'),
    array('Mage_Adminhtml_Block_Customer_Group_Grid'),
    array('Mage_Adminhtml_Block_Customer_Online_Grid'),
    array('Mage_Adminhtml_Block_Newsletter_Problem_Grid'),
    array('Mage_Adminhtml_Block_Newsletter_Queue'),
    array('Mage_Adminhtml_Block_Newsletter_Queue_Grid'),
    array('Mage_Adminhtml_Block_Page_Menu', 'Magento\Backend\Block\Menu'),
    array('Mage_Adminhtml_Block_Permissions_User'),
    array('Mage_Adminhtml_Block_Permissions_User_Grid'),
    array('Mage_Adminhtml_Block_Permissions_User_Edit'),
    array('Mage_Adminhtml_Block_Permissions_User_Edit_Tabs'),
    array('Mage_Adminhtml_Block_Permissions_User_Edit_Tab_Main'),
    array('Mage_Adminhtml_Block_Permissions_User_Edit_Tab_Roles'),
    array('Mage_Adminhtml_Block_Permissions_User_Edit_Form'),
    array('Mage_Adminhtml_Block_Permissions_Role'),
    array('Mage_Adminhtml_Block_Permissions_Buttons'),
    array('Mage_Adminhtml_Block_Permissions_Role_Grid_User'),
    array('Mage_Adminhtml_Block_Permissions_Grid_Role'),
    array('Mage_Adminhtml_Block_Permissions_Grid_User'),
    array('Mage_Adminhtml_Block_Permissions_Tab_Roleinfo'),
    array('Mage_Adminhtml_Block_Permissions_Tab_Rolesedit'),
    array('Mage_Adminhtml_Block_Permissions_Tab_Rolesusers'),
    array('Mage_Adminhtml_Block_Permissions_Tab_Useredit'),
    array('Mage_Adminhtml_Block_Permissions_Editroles'),
    array('Mage_Adminhtml_Block_Permissions_Roles'),
    array('Mage_Adminhtml_Block_Permissions_Users'),
    array('Mage_Adminhtml_Block_Permissions_Edituser'),
    array('Mage_Adminhtml_Block_Permissions_Tab_Userroles'),
    array('Mage_Adminhtml_Block_Permissions_Usernroles'),
    array('Mage_Adminhtml_Block_Promo_Catalog_Grid'),
    array('Mage_Adminhtml_Block_Promo_Quote_Grid'),
    array('Mage_Adminhtml_Block_Rating_Grid'),
    array('Mage_Adminhtml_Block_System_Store_Grid'),
    array('Mage_Adminhtml_Permissions_UserController'),
    array('Mage_Adminhtml_Permissions_RoleController'),
    array('Mage_Adminhtml_Block_Report_Grid', 'Magento\Reports\Block\Adminhtml\Grid'),
    array('Mage_Adminhtml_Block_Report_Customer_Accounts',
        'Magento\Reports\Block\Adminhtml\Customer\Accounts'),
    array('Mage_Adminhtml_Block_Report_Customer_Accounts_Grid'),
    array('Mage_Adminhtml_Block_Report_Customer_Totals', 'Magento\Reports\Block\Adminhtml\Customer\Totals'),
    array('Mage_Adminhtml_Block_Report_Customer_Totals_Grid'),
    array('Mage_Adminhtml_Block_Report_Product_Sold', 'Magento\Reports\Block\Adminhtml\Product\Sold'),
    array('Mage_Adminhtml_Block_Report_Product_Sold_Grid'),
    array('Mage_Adminhtml_Block_Report_Review_Customer_Grid'),
    array('Mage_Adminhtml_Block_Report_Customer_Orders', 'Magento\Reports\Block\Adminhtml\Customer\Orders'),
    array('Mage_Adminhtml_Block_Report_Customer_Orders_Grid'),
    array('Mage_Adminhtml_Block_Report_Product_Ordered'),
    array('Mage_Adminhtml_Block_Report_Product_Ordered_Grid'),
    array('Mage_Adminhtml_Block_Report_Review_Product_Grid'),
    array('Mage_Adminhtml_Block_Report_Refresh_Statistics', 'Magento\Reports\Block\Adminhtml\Refresh\Statistics'),
    array('Mage_Adminhtml_Block_Report_Refresh_Statistics_Grid'),
    array('Mage_Adminhtml_Block_Report_Search_Grid'),
    array('Mage_Adminhtml_Block_Sales'),
    array('Mage_Adminhtml_Block_Sales_Order_Create_Customer_Grid'),
    array('Mage_Adminhtml_Block_Sales_Order_Create_Search_Grid_Renderer_Giftmessage'),
    array('Mage_Adminhtml_Block_Sales_Order_Status_Grid'),
    array('Mage_Adminhtml_Block_Sitemap_Grid'),
    array('Mage_Adminhtml_Block_System_Config_Edit', 'Magento\Backend\Block\System\Config\Edit'),
    array('Mage_Adminhtml_Block_System_Config_Form', 'Magento\Backend\Block\System\Config\Form'),
    array('Mage_Adminhtml_Block_System_Config_Tabs', 'Magento\Backend\Block\System\Config\Tabs'),
    array('Mage_Adminhtml_Block_System_Config_System_Storage_Media_Synchronize',
        'Magento\Backend\Block\System\Config\System\Storage\Media\Synchronize'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Fieldset_Modules_DisableOutput',
        'Magento\Backend\Block\System\Config\Form\Fieldset\Modules\DisableOutput'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Regexceptions',
        'Magento\Backend\Block\System\Config\Form\Field\Regexceptions'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Notification',
        'Magento\Backend\Block\System\Config\Form\Field\Notification'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Heading',
        'Magento\Backend\Block\System\Config\Form\Field\Heading'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Datetime',
        'Magento\Backend\Block\System\Config\Form\Field\Datetime'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Array_Abstract',
        'Magento\Backend\Block\System\Config\Form\Field\Array\AbstractArray'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Fieldset',
        'Magento\Backend\Block\System\Config\Form\Fieldset'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field',
        'Magento\Backend\Block\System\Config\Form\Field'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Import',
        'Magento\Backend\Block\System\Config\Form\Field\Import'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Image',
        'Magento\Backend\Block\System\Config\Form\Field\Image'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Export',
        'Magento\Backend\Block\System\Config\Form\Field\Export'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Select_Allowspecific',
        'Magento\Backend\Block\System\Config\Form\Field\Select\Allowspecific'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_File',
        'Magento\Backend\Block\System\Config\Form\Field\File'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Select_Flatproduct',
        'Magento\Catalog\Block\Adminhtml\System\Config\Form\Field\Select\Flatproduct'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Field_Select_Flatcatalog',
        'Magento\Catalog\Block\Adminhtml\System\Config\Form\Field\Select\Flatcatalog'
    ),
    array('Mage_Adminhtml_Block_System_Config_Form_Fieldset_Order_Statuses',
        'Magento\Sales\Block\Adminhtml\System\Config\Form\Fieldset\Order\Statuses'
    ),
    array('Mage_Adminhtml_Block_System_Config_Dwstree', 'Magento\Backend\Block\System\Config\Dwstree'),
    array('Mage_Adminhtml_Block_System_Config_Switcher', 'Magento\Backend\Block\System\Config\Switcher'),
    array('Mage_Adminhtml_Block_System_Design_Grid'),
    array('Mage_Adminhtml_Block_System_Email_Template_Grid'),
    array('Mage_Adminhtml_Block_System_Variable_Grid'),
    array('Mage_Adminhtml_Block_Store_Switcher', 'Magento\Backend\Block\Store\Switcher'),
    array('Mage_Adminhtml_Block_Store_Switcher_Form_Renderer_Fieldset',
        'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset'
    ),
    array('Mage_Adminhtml_Block_Store_Switcher_Form_Renderer_Fieldset_Element',
        'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
    ),
    array('Mage_Adminhtml_Block_Tag_Tag_Edit'),
    array('Mage_Adminhtml_Block_Tag_Tag_Edit_Form'),
    array('Mage_Adminhtml_Block_Tax_Rate_Grid'),
    array('Mage_Adminhtml_Block_Tax_Rule_Grid'),
    array('Mage_Adminhtml_Block_Tree'),
    array('Mage_Adminhtml_Block_Urlrewrite_Grid'),
    array('Mage_Adminhtml_Helper_Rss'),
    array('Mage_Adminhtml_Model_Config', 'Magento\Backend\Model\Config\Structure'),
    array('Mage_Adminhtml_Model_Config_Data', 'Magento\Backend\Model\Config'),
    array('Mage_Adminhtml_Model_Extension'),
    array('Mage_Adminhtml_Model_System_Config_Source_Shipping_Allowedmethods'),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Password_Link_Expirationperiod',
        'Magento\Backend\Model\Config\Backend\Admin\Password\Link\Expirationperiod'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Custom',
        'Magento\Backend\Model\Config\Backend\Admin\Custom'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Custompath',
        'Magento\Backend\Model\Config\Backend\Admin\Custompath'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Observer',
        'Magento\Backend\Model\Config\Backend\Admin\Observer'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Robots',
        'Magento\Backend\Model\Config\Backend\Admin\Robots'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Usecustom',
        'Magento\Backend\Model\Config\Backend\Admin\Usecustom'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Usecustompath',
        'Magento\Backend\Model\Config\Backend\Admin\Custompath'
    ),
    array('Magento\Backend\Model\Config\Backend\Admin\Usecustompath',
        'Magento\Backend\Model\Config\Backend\Admin\Custompath'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Admin_Usesecretkey',
        'Magento\Backend\Model\Config\Backend\Admin\Usesecretkey'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Catalog_Inventory_Managestock',
        'Magento\CatalogInventory\Model\Config\Backend\Managestock'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Catalog_Search_Type',
        'Magento\CatalogSearch\Model\Config\Backend\Search\Type'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Currency_Abstract',
        'Magento\Backend\Model\Config\Backend\Currency\AbstractCurrency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Currency_Allow',
        'Magento\Backend\Model\Config\Backend\Currency\Allow'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Currency_Base',
        'Magento\Backend\Model\Config\Backend\Currency\Base'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Currency_Cron',
        'Magento\Backend\Model\Config\Backend\Currency\Cron'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Currency_Default',
        'Magento\Backend\Model\Config\Backend\Currency\DefaultCurrency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Customer_Address_Street',
        'Magento\Customer\Model\Config\Backend\Address\Street'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Customer_Password_Link_Expirationperiod',
        'Magento\Customer\Model\Config\Backend\Password\Link\Expirationperiod'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Customer_Show_Address',
        'Magento\Customer\Model\Config\Backend\Show\Address'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Customer_Show_Customer',
        'Magento\Customer\Model\Config\Backend\Show\Customer'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Design_Exception',
        'Magento\Backend\Model\Config\Backend\Design\Exception'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Email_Address',
        'Magento\Backend\Model\Config\Backend\Email\Address'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Email_Logo',
        'Magento\Backend\Model\Config\Backend\Email\Logo'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Email_Sender',
        'Magento\Backend\Model\Config\Backend\Email\Sender'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Image_Adapter',
        'Magento\Backend\Model\Config\Backend\Image\Adapter'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Image_Favicon',
        'Magento\Backend\Model\Config\Backend\Image\Favicon'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Image_Pdf',
        'Magento\Backend\Model\Config\Backend\Image\Pdf'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Locale_Timezone',
        'Magento\Backend\Model\Config\Backend\Locale\Timezone'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Log_Cron',
        'Magento\Backend\Model\Config\Backend\Log\Cron'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Price_Scope'),
    array('Mage_Adminhtml_Model_System_Config_Backend_Product_Alert_Cron',
        'Magento\Cron\Model\Config\Backend\Product\Alert'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Seo_Product',
        'Magento\Catalog\Model\Config\Backend\Seo\Product'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Serialized_Array',
        'Magento\Backend\Model\Config\Backend\Serialized\Array'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Shipping_Tablerate',
        'Magento\Shipping\Model\Config\Backend\Tablerate'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Sitemap_Cron',
        'Magento\Cron\Model\Config\Backend\Sitemap'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Storage_Media_Database',
        'Magento\Backend\Model\Config\Backend\Storage\Media\Database'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Baseurl',
        'Magento\Backend\Model\Config\Backend\Baseurl'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Cache',
        'Magento\Backend\Model\Config\Backend\Cache'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Category',
        'Magento\Catalog\Model\Config\Backend\Category'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Cookie',
        'Magento\Backend\Model\Config\Backend\Cookie'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Datashare',
        'Magento\Backend\Model\Config\Backend\Datashare'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Encrypted',
        'Magento\Backend\Model\Config\Backend\Encrypted'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_File',
        'Magento\Backend\Model\Config\Backend\File'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Filename',
        'Magento\Backend\Model\Config\Backend\Filename'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Image',
        'Magento\Backend\Model\Config\Backend\Image'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Locale',
        'Magento\Backend\Model\Config\Backend\Locale'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Secure',
        'Magento\Backend\Model\Config\Backend\Secure'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Serialized',
        'Magento\Backend\Model\Config\Backend\Serialized'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Sitemap',
        'Magento\Sitemap\Model\Config\Backend\Priority'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Store',
        'Magento\Backend\Model\Config\Backend\Store'
    ),
    array('Mage_Adminhtml_Model_System_Config_Backend_Translate',
        'Magento\Backend\Model\Config\Backend\Translate'
    ),
    array('Mage_Adminhtml_Model_System_Config_Clone_Media_Image',
        'Magento\Catalog\Model\Config\CatalogClone\Media\Image'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Admin_Page',
        'Magento\Backend\Model\Config\Source\Admin\Page'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Catalog_Search_Type',
        'Magento\CatalogSearch\Model\Config\Source\Search\Type'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Catalog_GridPerPage',
        'Magento\Catalog\Model\Config\Source\GridPerPage'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Catalog_ListMode',
        'Magento\Catalog\Model\Config\Source\ListMode'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Catalog_ListPerPage',
        'Magento\Catalog\Model\Config\Source\ListPerPage'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Catalog_ListSort',
        'Magento\Catalog\Model\Config\Source\ListSort'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Catalog_TimeFormat',
        'Magento\Catalog\Model\Config\Source\TimeFormat'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Cms_Wysiwyg_Enabled',
        'Magento\Cms\Model\Config\Source\Wysiwyg\Enabled'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Cms_Page',
        'Magento\Cms\Model\Config\Source\Page'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Country_Full',
        'Magento\Directory\Model\Config\Source\Country\Full'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Cron_Frequency',
        'Magento\Cron\Model\Config\Source\Frequency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Currency_Service',
        'Magento\Backend\Model\Config\Source\Currency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Customer_Address_Type',
        'Magento\Customer\Model\Config\Source\Address\Type'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Customer_Group_Multiselect',
        'Magento\Customer\Model\Config\Source\Group\Multiselect'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Customer_Group',
        'Magento\Customer\Model\Config\Source\Group'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Date_Short',
        'Magento\Backend\Model\Config\Source\Date\Short'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Design_Package'),
    array('Mage_Adminhtml_Model_System_Config_Source_Design_Robots',
        'Magento\Backend\Model\Config\Source\Design\Robots'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Dev_Dbautoup',
        'Magento\Backend\Model\Config\Source\Dev\Dbautoup'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Email_Identity',
        'Magento\Backend\Model\Config\Source\Email\Identity'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Email_Method',
        'Magento\Backend\Model\Config\Source\Email\Method'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Email_Smtpauth',
        'Magento\Backend\Model\Config\Source\Email\Smtpauth'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Email_Template',
        'Magento\Backend\Model\Config\Source\Email\Template'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Image_Adapter',
        'Magento\Backend\Model\Config\Source\Image\Adapter'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Locale_Country',
        'Magento\Backend\Model\Config\Source\Locale\Country'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Locale_Currency_All',
        'Magento\Backend\Model\Config\Source\Locale\Currency\All'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Locale_Currency',
        'Magento\Backend\Model\Config\Source\Locale\Currency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Locale_Timezone',
        'Magento\Backend\Model\Config\Source\Locale\Timezone'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Locale_Weekdays',
        'Magento\Backend\Model\Config\Source\Locale\Weekdays'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Notification_Frequency',
        'Magento\AdminNotification\Model\Config\Source\Frequency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Order_Status_New',
        'Magento\Sales\Model\Config\Source\Order\Status\NewStatus'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Order_Status_Newprocessing',
        'Magento\Sales\Model\Config\Source\Order\Status\Newprocessing'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Order_Status_Processing',
        'Magento\Sales\Model\Config\Source\Order\Status\Processing'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Order_Status',
        'Magento\Sales\Model\Config\Source\Order\Status'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Payment_Allmethods',
        'Magento\Payment\Model\Config\Source\Allmethods'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Payment_Allowedmethods',
        'Magento\Payment\Model\Config\Source\Allowedmethods'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Payment_Allspecificcountries',
        'Magento\Payment\Model\Config\Source\Allspecificcountries'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Payment_Cctype',
        'Magento\Payment\Model\Config\Source\Cctype'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Price_Scope',
        'Magento\Catalog\Model\Config\Source\Price\Scope'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Price_Step',
        'Magento\Catalog\Model\Config\Source\Price\Step'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Product_Options_Price',
        'Magento\Catalog\Model\Config\Source\Product\Options\Price'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Product_Options_Type',
        'Magento\Catalog\Model\Config\Source\Product\Options\Type'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Product_Thumbnail',
        'Magento\Catalog\Model\Config\Source\Product\Thumbnail'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Reports_Scope',
        'Magento\Backend\Model\Config\Source\Reports\Scope'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Shipping_Allmethods',
        'Magento\Shipping\Model\Config\Source\Allmethods'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Shipping_Allspecificcountries',
        'Magento\Shipping\Model\Config\Source\Allspecificcountries'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Shipping_Flatrate',
        'Magento\Shipping\Model\Config\Source\Flatrate'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Shipping_Tablerate',
        'Magento\Shipping\Model\Config\Source\Tablerate'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Shipping_Taxclass',
        'Magento\Tax\Model\Config\Source\TaxClass\Product'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Storage_Media_Database',
        'Magento\Backend\Model\Config\Source\Storage\Media\Database'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Storage_Media_Storage',
        'Magento\Backend\Model\Config\Source\Storage\Media\Storage'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Tax_Apply_On',
        'Magento\Tax\Model\Config\Source\Apply\On'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Tax_Basedon',
        'Magento\Tax\Model\Config\Source\Basedon'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Tax_Catalog',
        'Magento\Tax\Model\Config\Source\Catalog'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Watermark_Position',
        'Magento\Catalog\Model\Config\Source\Watermark\Position'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Web_Protocol',
        'Magento\Backend\Model\Config\Source\Web\Protocol'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Web_Redirect',
        'Magento\Backend\Model\Config\Source\Web\Redirect'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Allregion',
        'Magento\Directory\Model\Config\Source\Allregion'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Category',
        'Magento\Catalog\Model\Config\Source\Category'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Checktype',
        'Magento\Backend\Model\Config\Source\Checktype'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Country',
        'Magento\Directory\Model\Config\Source\Country'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Currency',
        'Magento\Backend\Model\Config\Source\Currency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Enabledisable',
        'Magento\Backend\Model\Config\Source\Enabledisable'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Frequency',
        'Magento\Sitemap\Model\Config\Source\Frequency'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Locale',
        'Magento\Backend\Model\Config\Source\Locale'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Nooptreq',
        'Magento\Backend\Model\Config\Source\Nooptreq'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Store',
        'Magento\Backend\Model\Config\Source\Store'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Website',
        'Magento\Backend\Model\Config\Source\Website'
    ),
    array('Mage_Adminhtml_Model_System_Config_Source_Yesno', 'Magento\Backend\Model\Config\Source\Yesno'),
    array('Mage_Adminhtml_Model_System_Config_Source_Yesnocustom',
        'Magento\Backend\Model\Config\Source\Yesnocustom'
    ),
    array('Mage_Adminhtml_Model_System_Store', 'Magento\Core\Model\System\Store'),
    array('Mage_Adminhtml_Model_Url', 'Magento\Backend\Model\Url'),
    array('Mage_Adminhtml_Rss_CatalogController'),
    array('Mage_Adminhtml_Rss_OrderController'),
    array('Mage_Adminhtml_SystemController', 'Magento\Backend\Controller\Adminhtml\System'),
    array('Mage_Adminhtml_System_ConfigController', 'Magento\Backend\Controller\Adminhtml\System\Config'),
    array('Magento\Backend\Model\Config\Source\Currency\Service',
        'Magento\Directory\Model\Currency\Import\Source\Service'),
    array('Mage_Backend_Model_Menu_Config_Menu'),
    array('Mage_Backend_Model_Menu_Director_Dom'),
    array('Mage_Backend_Model_Menu_Factory', 'Mage_Backend_Model_MenuFactory'),
    array('Mage_Bundle_Product_EditController', 'Mage_Bundle_Controller_Adminhtml_Bundle_Selection'),
    array('Mage_Bundle_SelectionController', 'Mage_Bundle_Controller_Adminhtml_Bundle_Selection'),
    array('Mage_Catalog_Model_Category_Limitation'),
    array('Mage_Catalog_Model_Convert'),
    array('Mage_Catalog_Model_Convert_Adapter_Catalog'),
    array('Mage_Catalog_Model_Convert_Adapter_Product'),
    array('Mage_Catalog_Model_Convert_Parser_Product'),
    array('Mage_Catalog_Model_Entity_Product_Attribute_Frontend_Image'),
    array('Mage_Catalog_Model_Product_Limitation'),
    array('Mage_Catalog_Model_Resource_Product_Attribute_Frontend_Image'),
    array('Mage_Catalog_Model_Resource_Product_Attribute_Frontend_Tierprice'),
    array('Mage_Checkout_Block_Links'),
    array('Mage_Core_Block_Flush'),
    array('Mage_Core_Block_Template_Facade'),
    array('Mage_Core_Block_Template_Smarty'),
    array('Mage_Core_Block_Template_Zend'),
    array('Mage_Core_Controller_Magento_Router_Admin', 'Magento\Backend\Controller\Router\DefaultRouter'),
    array('Mage_Core_Model_Convert'),
    array('Mage_Core_Model_Config_Fieldset', 'Magento\Core\Model\Fieldset\Config'),
    array('Mage_Core_Model_Config_Options', 'Magento\App\Dir'),
    array('Mage_Core_Model_Config_Module'),
    array('Mage_Core_Model_Config_System'),
    array('Mage_Core_Model_Design_Source_Apply'),
    array('Mage_Core_Model_Language'),
    array('Mage_Core_Model_Resource_Language'),
    array('Mage_Core_Model_Resource_Language_Collection'),
    array('Mage_Core_Model_Resource_Setup_Query_Modifier'),
    array('Mage_Core_Model_Session_Abstract_Varien'),
    array('Mage_Core_Model_Session_Abstract_Zend'),
    array('Mage_Core_Model_Store_Group_Limitation'),
    array('Mage_Core_Model_Store_Limitation'),
    array('Magento\Core\Model\Variable\Observer'),
    array('Mage_Core_Model_Website_Limitation'),
    array('Mage_Core_Model_Layout_Data', 'Magento\Core\Model\Layout\Update'),
    array('Mage_Core_Model_Theme_Customization_Link'),
    array('Mage_Customer_Block_Account'),
    array('Mage_Customer_Block_Account_Navigation'),
    array('Mage_Customer_Model_Convert_Adapter_Customer'),
    array('Mage_Customer_Model_Convert_Parser_Customer'),
    array('Mage_Customer_Model_Resource_Address_Attribute_Backend_Street',
        'Mage_Eav_Model_Entity_Attribute_Backend_Default'),
    array('Mage_DesignEditor_Block_Page_Html_Head_Vde'),
    array('Mage_DesignEditor_Block_Page_Html_Head'),
    array('Mage_Directory_Model_Resource_Currency_Collection'),
    array('Mage_Downloadable_FileController', 'Magento\Downloadable\Controller\Adminhtml\Downloadable\File'),
    array('Mage_Downloadable_Product_EditController', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('Mage_Eav_Model_Convert_Adapter_Entity'),
    array('Mage_Eav_Model_Convert_Adapter_Grid'),
    array('Mage_Eav_Model_Convert_Parser_Abstract'),
    array('Mage_Eav_Model_Entity_Collection'),
    array('Mage_GiftMessage_Block_Message_Form'),
    array('Mage_GiftMessage_Block_Message_Helper'),
    array('Mage_GiftMessage_IndexController'),
    array('Mage_GiftMessage_Model_Entity_Attribute_Backend_Boolean_Config'),
    array('Mage_GiftMessage_Model_Entity_Attribute_Source_Boolean_Config'),
    array('Mage_GoogleOptimizer_IndexController', 'Magento\GoogleOptimizer\Adminhtml\Googleoptimizer\IndexController'),
    array('Mage_GoogleShopping_Block_Adminhtml_Types_Grid'),
    array('Mage_GoogleShopping_Helper_SiteVerification', 'Mage_GoogleShopping_Block_SiteVerification'),
    array('Mage_ImportExport_Model_Import_Adapter_Abstract', 'Mage_ImportExport_Model_Import_SourceAbstract'),
    array('Mage_ImportExport_Model_Import_Adapter_Csv', 'Mage_ImportExport_Model_Import_Source_Csv'),
    array('Mage_Install_Model_Installer_Env'),
    array('Mage_Ogone_Model_Api_Debug'),
    array('Mage_Ogone_Model_Resource_Api_Debug'),
    array('Mage_Page_Block_Html_Toplinks'),
    array('Mage_Page_Block_Html_Wrapper'),
    array('Mage_Page_Block_Template_Links'),
    array('Mage_Paypal_Block_Adminhtml_Settlement_Report_Grid'),
    array('Mage_ProductAlert_Block_Price'),
    array('Mage_ProductAlert_Block_Stock'),
    array('Mage_Reports_Model_Resource_Coupons_Collection'),
    array('Mage_Reports_Model_Resource_Invoiced_Collection'),
    array('Mage_Reports_Model_Resource_Product_Ordered_Collection'),
    array('Mage_Reports_Model_Resource_Product_Viewed_Collection',
        'Magento\Reports\Model\Resource\Report\Product\Viewed\Collection'),
    array('Mage_Reports_Model_Resource_Refunded_Collection'),
    array('Mage_Reports_Model_Resource_Shipping_Collection'),
    array('Mage_Reports_Model_Report'),
    array('Mage_Reports_Model_Test'),
    array('Mage_Rss_Model_Observer'),
    array('Mage_Rss_Model_Session', 'Magento_Backend_Model_Auth and \Magento\Backend\Model\Auth\Session'),
    array('Mage_Sales_Block_Order_Details'),
    array('Mage_Sales_Block_Order_Tax'),
    array('Mage_Sales_Block_Guest_Links'),
    array('Mage_Sales_Model_Entity_Order'),
    array('Mage_Sales_Model_Entity_Order_Address'),
    array('Mage_Sales_Model_Entity_Order_Address_Collection'),
    array('Mage_Sales_Model_Entity_Order_Attribute_Backend_Billing'),
    array('Mage_Sales_Model_Entity_Order_Attribute_Backend_Child'),
    array('Mage_Sales_Model_Entity_Order_Attribute_Backend_Parent'),
    array('Mage_Sales_Model_Entity_Order_Attribute_Backend_Shipping'),
    array('Mage_Sales_Model_Entity_Order_Collection'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo_Attribute_Backend_Child'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo_Attribute_Backend_Parent'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo_Collection'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo_Comment'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo_Comment_Collection'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo_Item'),
    array('Mage_Sales_Model_Entity_Order_Creditmemo_Item_Collection'),
    array('Mage_Sales_Model_Entity_Order_Invoice'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Child'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Item'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Order'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Parent'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Collection'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Comment'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Comment_Collection'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Item'),
    array('Mage_Sales_Model_Entity_Order_Invoice_Item_Collection'),
    array('Mage_Sales_Model_Entity_Order_Item'),
    array('Mage_Sales_Model_Entity_Order_Item_Collection'),
    array('Mage_Sales_Model_Entity_Order_Payment'),
    array('Mage_Sales_Model_Entity_Order_Payment_Collection'),
    array('Mage_Sales_Model_Entity_Order_Shipment'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Attribute_Backend_Child'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Attribute_Backend_Parent'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Collection'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Comment'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Comment_Collection'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Item'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Item_Collection'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Track'),
    array('Mage_Sales_Model_Entity_Order_Shipment_Track_Collection'),
    array('Mage_Sales_Model_Entity_Order_Status_History'),
    array('Mage_Sales_Model_Entity_Order_Status_History_Collection'),
    array('Mage_Sales_Model_Entity_Quote'),
    array('Mage_Sales_Model_Entity_Quote_Address'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend_Child'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend_Parent'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend_Region'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Custbalance'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Discount'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Grand'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Shipping'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Subtotal'),
    array('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Tax'),
    array('Mage_Sales_Model_Entity_Quote_Address_Collection'),
    array('Mage_Sales_Model_Entity_Quote_Address_Item'),
    array('Mage_Sales_Model_Entity_Quote_Address_Item_Collection'),
    array('Mage_Sales_Model_Entity_Quote_Address_Rate'),
    array('Mage_Sales_Model_Entity_Quote_Address_Rate_Collection'),
    array('Mage_Sales_Model_Entity_Quote_Collection'),
    array('Mage_Sales_Model_Entity_Quote_Item'),
    array('Mage_Sales_Model_Entity_Quote_Item_Collection'),
    array('Mage_Sales_Model_Entity_Quote_Payment'),
    array('Mage_Sales_Model_Entity_Quote_Payment_Collection'),
    array('Mage_Sales_Model_Entity_Sale_Collection'),
    array('Mage_Sales_Model_Entity_Setup'),
    array('Mage_Shipping_ShippingController'),
    array('Mage_Tag_Block_Adminhtml_Report_Customer_Detail_Grid'),
    array('Mage_Tag_Block_Adminhtml_Report_Customer_Grid'),
    array('Mage_Tag_Block_Adminhtml_Report_Popular_Detail_Grid'),
    array('Mage_Tag_Block_Adminhtml_Report_Product_Detail_Grid'),
    array('Mage_Tag_Block_Adminhtml_Report_Product_Grid'),
    array('Mage_Tag_Block_Customer_Edit'),
    array('Mage_Theme_Block_Adminhtml_System_Design_Theme_Grid'),
    array('Mage_User_Block_Role_Grid'),
    array('Mage_User_Block_User_Grid'),
    array('Mage_User_Model_Roles'),
    array('Mage_User_Model_Resource_Roles'),
    array('Mage_User_Model_Resource_Roles_Collection'),
    array('Mage_User_Model_Resource_Roles_User_Collection'),
    array('Mage_Widget_Block_Adminhtml_Widget_Instance_Grid'),
    array('Magento\Widget\Model\Observer'),
    array('Mage_Wishlist_Model_Resource_Product_Collection'),
    array('Varien_Convert_Action'),
    array('Varien_Convert_Action_Abstract'),
    array('Varien_Convert_Action_Interface'),
    array('Varien_Convert_Adapter_Abstract'),
    array('Varien_Convert_Adapter_Db_Table'),
    array('Varien_Convert_Adapter_Http'),
    array('Varien_Convert_Adapter_Http_Curl'),
    array('Varien_Convert_Adapter_Interface'),
    array('Varien_Convert_Adapter_Io'),
    array('Varien_Convert_Adapter_Soap'),
    array('Varien_Convert_Adapter_Std'),
    array('Varien_Convert_Adapter_Zend_Cache'),
    array('Varien_Convert_Adapter_Zend_Db'),
    array('Varien_Convert_Container_Collection'),
    array('Varien_Convert_Container_Generic'),
    array('Varien_Convert_Container_Interface'),
    array('Varien_Convert_Mapper_Abstract'),
    array('Varien_Convert_Parser_Abstract'),
    array('Varien_Convert_Parser_Csv'),
    array('Varien_Convert_Parser_Interface'),
    array('Varien_Convert_Parser_Serialize'),
    array('Varien_Convert_Parser_Xml_Excel'),
    array('Varien_Convert_Profile'),
    array('Varien_Convert_Profile_Abstract'),
    array('Varien_Convert_Profile_Collection'),
    array('Varien_Convert_Validator_Abstract'),
    array('Varien_Convert_Validator_Column'),
    array('Varien_Convert_Validator_Dryrun'),
    array('Varien_Convert_Validator_Interface'),
    array('Mage_File_Uploader_Image'),
    array('Varien_Profiler', 'Magento_Profiler'),
    array('Mage_Adminhtml_Block_Notification_Window', 'Magento\AdminNotification\Block\Window'),
    array('Mage_Adminhtml_Block_Notification_Toolbar'),
    array('Mage_Adminhtml_Block_Notification_Survey'),
    array('Mage_Adminhtml_Block_Notification_Security'),
    array('Mage_Adminhtml_Block_Notification_Inbox'),
    array('Mage_Adminhtml_Block_Notification_Grid', 'Magento\AdminNotification\Block\Notification\Grid'),
    array('Mage_Adminhtml_Block_Notification_Baseurl'),
    array('Mage_Adminhtml_Block_Notification_Grid_Renderer_Severity',
        'Magento\AdminNotification\Block\Grid\Renderer\Severity'),
    array('Mage_Adminhtml_Block_Notification_Grid_Renderer_Notice',
        'Magento\AdminNotification\Block\Grid\Renderer\Notice'),
    array('Mage_Adminhtml_Block_Notification_Grid_Renderer_Actions',
        'Magento\AdminNotification\Block\Grid\Renderer\Actions'),
    array('Mage_Adminhtml_Block_Cache_Notifications'),
    array('Mage_AdminNotification_Block_Grid'),
    array('Mage_Core_Model_Design_Package'),
    array('Mage_Core_Model_Design_PackageInterface'),
    array('Mage_Core_Model_Resource_Type_Db_Mysqli_Setup'),
    array('Mage_Core_Model_Resource_Type_Db_Mysqli'),
    array('Varien_Db_Adapter_Mysqli'),
    array('Mage_DB_Mysqli'),
    array('Mage_DB_Exception'),
    array(
        'Magento\Catalog\Block\Product\View\Media',
        'Decomposed into \Magento\Catalog\Block\Product\View\Gallery'
            . ' and \Magento\Catalog\Block\Product\View\BaseImage classes'
    ),
    array('Magento\Wishlist\Block\Links', 'Magento\Wishlist\Block\Link'),
    array('Mage_Adminhtml_Block_Api_Tab_Userroles'),
    array('Mage_Adminhtml_Block_Api_Tab_Roleinfo'),
    array('Mage_Adminhtml_Block_Api_Tab_Rolesusers'),
    array('Mage_Adminhtml_Block_Api_Tab_Rolesedit'),
    array('Mage_Adminhtml_Block_Api_Editroles'),
    array('Mage_Adminhtml_Block_Api_Buttons'),
    array('Mage_Adminhtml_Block_Api_Users'),
    array('Mage_Adminhtml_Block_Api_Role_Grid_User'),
    array('Mage_Adminhtml_Block_Api_Grid_Role'),
    array('Mage_Adminhtml_Block_Api_Roles'),
    array('Mage_Adminhtml_Block_Api_User_Edit_Tab_Main'),
    array('Mage_Adminhtml_Block_Api_User_Edit_Tab_Roles'),
    array('Mage_Adminhtml_Block_Api_User_Edit_Tabs'),
    array('Mage_Adminhtml_Block_Api_User_Edit_Form'),
    array('Mage_Adminhtml_Block_Api_User_Grid'),
    array('Mage_Adminhtml_Block_Api_User_Edit'),
    array('Mage_Adminhtml_Block_Api_Role'),
    array('Mage_Adminhtml_Block_Api_User'),
    array('Mage_Adminhtml_Block_Api_Edituser'),
    array('Mage_Api_Exception'),
    array('Mage_Api_Controller_Action'),
    array('Mage_Api_Model_Acl_Role_Generic'),
    array('Mage_Api_Model_Acl_Role_Group'),
    array('Mage_Api_Model_Acl_Role_Registry'),
    array('Mage_Api_Model_Acl_Role_User'),
    array('Mage_Api_Model_Acl_Assert_Ip'),
    array('Mage_Api_Model_Acl_Assert_Time'),
    array('Mage_Api_Model_Acl_Role'),
    array('Mage_Api_Model_Acl_Resource'),
    array('Mage_Api_Model_Rules'),
    array('Mage_Api_Model_Wsdl_Config'),
    array('Mage_Api_Model_Wsdl_Config_Base'),
    array('Mage_Api_Model_Wsdl_Config_Element'),
    array('Mage_Api_Model_Server'),
    array('Mage_Api_Model_Mysql4_Acl_Role_Collection'),
    array('Mage_Api_Model_Mysql4_Acl_Role'),
    array('Mage_Api_Model_Mysql4_Rules'),
    array('Mage_Api_Model_Mysql4_Role_Collection'),
    array('Mage_Api_Model_Mysql4_Rules_Collection'),
    array('Mage_Api_Model_Mysql4_Roles'),
    array('Mage_Api_Model_Mysql4_Permissions_Collection'),
    array('Mage_Api_Model_Mysql4_User_Collection'),
    array('Mage_Api_Model_Mysql4_Roles_Collection'),
    array('Mage_Api_Model_Mysql4_Roles_User_Collection'),
    array('Mage_Api_Model_Mysql4_Role'),
    array('Mage_Api_Model_Mysql4_Acl'),
    array('Mage_Api_Model_Mysql4_User'),
    array('Mage_Api_Model_Session'),
    array('Mage_Api_Model_Config'),
    array('Mage_Api_Model_Server_V2_Adapter_Soap'),
    array('Mage_Api_Model_Server_V2_Handler'),
    array('Mage_Api_Model_Server_Adapter_Soap'),
    array('Mage_Api_Model_Server_Adapter_Xmlrpc'),
    array('Mage_Api_Model_Server_WSI_Adapter_Soap'),
    array('Mage_Api_Model_Server_WSI_Handler'),
    array('Mage_Api_Model_Server_Handler'),
    array('Mage_Api_Model_Roles'),
    array('Mage_Api_Model_Role'),
    array('Mage_Api_Model_Acl'),
    array('Mage_Api_Model_Resource_Acl_Role_Collection'),
    array('Mage_Api_Model_Resource_Acl_Role'),
    array('Mage_Api_Model_Resource_Rules'),
    array('Mage_Api_Model_Resource_Role_Collection'),
    array('Mage_Api_Model_Resource_Rules_Collection'),
    array('Mage_Api_Model_Resource_Roles'),
    array('Mage_Api_Model_Resource_Permissions_Collection'),
    array('Mage_Api_Model_Resource_User_Collection'),
    array('Mage_Api_Model_Resource_Roles_Collection'),
    array('Mage_Api_Model_Resource_Roles_User_Collection'),
    array('Mage_Api_Model_Resource_Role'),
    array('Mage_Api_Model_Resource_Acl'),
    array('Mage_Api_Model_Resource_Abstract'),
    array('Mage_Api_Model_Resource_User'),
    array('Mage_Api_Model_User'),
    array('Mage_Api_Helper_Data'),
    array('Mage_Api_XmlrpcController'),
    array('Mage_Api_V2_SoapController'),
    array('Mage_Api_SoapController'),
    array('Mage_Api_IndexController'),
    array('Mage_Catalog_Model_Api_Resource'),
    array('Mage_Catalog_Model_Api2_Product_Website'),
    array('Mage_Catalog_Model_Api2_Product_Website_Rest_Admin_V1'),
    array('Mage_Catalog_Model_Api2_Product_Website_Validator_Admin_Website'),
    array('Mage_Catalog_Model_Api2_Product_Rest_Customer_V1'),
    array('Mage_Catalog_Model_Api2_Product_Rest_Guest_V1'),
    array('Mage_Catalog_Model_Api2_Product_Rest_Admin_V1'),
    array('Mage_Catalog_Model_Api2_Product_Category'),
    array('Mage_Catalog_Model_Api2_Product_Image'),
    array('Mage_Catalog_Model_Api2_Product_Category_Rest_Customer_V1'),
    array('Mage_Catalog_Model_Api2_Product_Category_Rest_Guest_V1'),
    array('Mage_Catalog_Model_Api2_Product_Category_Rest_Admin_V1'),
    array('Mage_Catalog_Model_Api2_Product_Image_Rest_Customer_V1'),
    array('Mage_Catalog_Model_Api2_Product_Image_Rest_Guest_V1'),
    array('Mage_Catalog_Model_Api2_Product_Image_Rest_Admin_V1'),
    array('Mage_Catalog_Model_Api2_Product_Image_Validator_Image'),
    array('Mage_Catalog_Model_Api2_Product_Validator_Product'),
    array('Mage_Catalog_Model_Api2_Product'),
    array('Mage_Catalog_Model_Product_Api_V2'),
    array('Mage_Catalog_Model_Product_Api'),
    array('Mage_Catalog_Model_Product_Option_Api_V2'),
    array('Mage_Catalog_Model_Product_Option_Value_Api_V2'),
    array('Mage_Catalog_Model_Product_Option_Value_Api'),
    array('Mage_Catalog_Model_Product_Option_Api'),
    array('Mage_Catalog_Model_Product_Type_Api_V2'),
    array('Mage_Catalog_Model_Product_Type_Api'),
    array('Mage_Catalog_Model_Product_Attribute_Tierprice_Api_V2'),
    array('Mage_Catalog_Model_Product_Attribute_Tierprice_Api'),
    array('Mage_Catalog_Model_Product_Attribute_Media_Api_V2'),
    array('Mage_Catalog_Model_Product_Attribute_Media_Api'),
    array('Mage_Catalog_Model_Product_Attribute_Api_V2'),
    array('Mage_Catalog_Model_Product_Attribute_Set_Api_V2'),
    array('Mage_Catalog_Model_Product_Attribute_Set_Api'),
    array('Mage_Catalog_Model_Product_Attribute_Api'),
    array('Mage_Catalog_Model_Product_Link_Api_V2'),
    array('Mage_Catalog_Model_Product_Link_Api'),
    array('Mage_Catalog_Model_Category_Api_V2'),
    array('Mage_Catalog_Model_Category_Api'),
    array('Mage_Catalog_Model_Category_Attribute_Api_V2'),
    array('Mage_Catalog_Model_Category_Attribute_Api'),
    array('Mage_Checkout_Model_Api_Resource'),
    array('Mage_Checkout_Model_Api_Resource_Customer'),
    array('Mage_Checkout_Model_Api_Resource_Product'),
    array('Mage_Checkout_Model_Cart_Api_V2'),
    array('Mage_Checkout_Model_Cart_Payment_Api'),
    array('Mage_Checkout_Model_Cart_Customer_Api_V2'),
    array('Mage_Checkout_Model_Cart_Customer_Api'),
    array('Mage_Checkout_Model_Cart_Api'),
    array('Mage_Checkout_Model_Cart_Product_Api_V2'),
    array('Mage_Checkout_Model_Cart_Product_Api'),
    array('Mage_Checkout_Model_Cart_Shipping_Api_V2'),
    array('Mage_Checkout_Model_Cart_Shipping_Api'),
    array('Mage_Checkout_Model_Cart_Coupon_Api_V2'),
    array('Mage_Checkout_Model_Cart_Coupon_Api'),
    array('Mage_Core_Model_Store_Api_V2'),
    array('Mage_Core_Model_Store_Api'),
    array('Mage_Core_Model_Magento_Api_V2'),
    array('Mage_Core_Model_Magento_Api'),
    array('Mage_Customer_Model_Group_Api_V2'),
    array('Mage_Customer_Model_Group_Api'),
    array('Mage_Customer_Model_Api_Resource'),
    array('Mage_Customer_Model_Customer_Api_V2'),
    array('Mage_Customer_Model_Customer_Api'),
    array('Mage_Customer_Model_Api2_Customer'),
    array('Mage_Customer_Model_Api2_Customer_Address'),
    array('Mage_Customer_Model_Api2_Customer_Rest_Customer_V1'),
    array('Mage_Customer_Model_Api2_Customer_Rest_Admin_V1'),
    array('Mage_Customer_Model_Api2_Customer_Address_Validator'),
    array('Mage_Customer_Model_Api2_Customer_Address_Rest_Customer_V1'),
    array('Mage_Customer_Model_Api2_Customer_Address_Rest_Admin_V1'),
    array('Mage_Customer_Model_Address_Api_V2'),
    array('Mage_Customer_Model_Address_Api'),
    array('Mage_Directory_Model_Region_Api_V2'),
    array('Mage_Directory_Model_Region_Api'),
    array('Mage_Directory_Model_Country_Api_V2'),
    array('Mage_Directory_Model_Country_Api'),
    array('Mage_Downloadable_Model_Link_Api_V2'),
    array('Mage_Downloadable_Model_Link_Api_Validator'),
    array('Mage_Downloadable_Model_Link_Api_Uploader'),
    array('Mage_Downloadable_Model_Link_Api'),
    array('Mage_GiftMessage_Model_Api_V2'),
    array('Mage_GiftMessage_Model_Api'),
    array('Mage_Sales_Model_Api_Resource'),
    array('Mage_Sales_Model_Api2_Order_Item_Rest_Customer_V1'),
    array('Mage_Sales_Model_Api2_Order_Item_Rest_Admin_V1'),
    array('Mage_Sales_Model_Api2_Order_Comment_Rest_Customer_V1'),
    array('Mage_Sales_Model_Api2_Order_Comment_Rest_Admin_V1'),
    array('Mage_Sales_Model_Api2_Order_Item'),
    array('Mage_Sales_Model_Api2_Order_Comment'),
    array('Mage_Sales_Model_Api2_Order_Address'),
    array('Mage_Sales_Model_Api2_Order_Rest_Customer_V1'),
    array('Mage_Sales_Model_Api2_Order_Rest_Admin_V1'),
    array('Mage_Sales_Model_Api2_Order_Address_Rest_Customer_V1'),
    array('Mage_Sales_Model_Api2_Order_Address_Rest_Admin_V1'),
    array('Mage_Sales_Model_Api2_Order'),
    array('Mage_Sales_Model_Order_Api_V2'),
    array('Mage_Sales_Model_Order_Shipment_Api_V2'),
    array('Mage_Sales_Model_Order_Shipment_Api'),
    array('Mage_Sales_Model_Order_Invoice_Api_V2'),
    array('Mage_Sales_Model_Order_Invoice_Api'),
    array('Mage_Sales_Model_Order_Api'),
    array('Mage_Sales_Model_Order_Creditmemo_Api_V2'),
    array('Mage_Sales_Model_Order_Creditmemo_Api'),
    array('Magento\ImportExport\Model\Config'),
    array('Magento\Data\Collection\Factory', 'Magento\Data\CollectionFactory'),
    array('Magento\Adminhtml\Block\Customer\System\Config\ValidatevatFactory'),
    array('Magento\Customer\Model\Attribute\Data'),
    array('Magento\Eav\Model\Attribute\Data'),
    array('Magento\Log\Model\Resource\Helper\Mysql4', 'Magento\Log\Model\Resource\Helper'),
    array('Magento\CatalogSearch\Model\Resource\Helper\Mysql4', 'Magento\CatalogSearch\Model\Resource\Helper'),
    array('Magento\ImportExport\Model\Resource\Helper\Mysql4', 'Magento\ImportExport\Model\Resource\Helper'),
    array('Magento\Reports\Model\Resource\Helper\Mysql4', 'Magento\Reports\Model\Resource\Helper'),
    array('Magento\Backup\Model\Resource\Helper\Mysql4', 'Magento\Backup\Model\Resource\Helper'),
    array('Magento\Sales\Model\Resource\Helper\Mysql4', 'Magento\Sales\Model\Resource\Helper'),
    array('Magento\Core\Model\Resource\Helper\Mysql4', 'Magento\Core\Model\Resource\Helper'),
    array('Magento\Catalog\Model\Resource\Helper\Mysql4', 'Magento\Catalog\Model\Resource\Helper'),
    array('Magento\Eav\Model\Resource\Helper\Mysql4', 'Magento\Eav\Model\Resource\Helper'),
    array('Magento\Eav\Model\Entity\Attribute\Backend\Array', 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend'),
    array('Magento\Sales\Model\Resource\Helper\HelperInterface', 'Magento\Sales\Model\Resource\HelperInterface'),
    array('Magento\Reports\Model\Resource\Helper\HelperInterface', 'Magento\Reports\Model\Resource\HelperInterface'),
    array('Magento\Poll\Block\ActivePoll'),
    array('Magento\Poll\Controller\Vote'),
    array('Magento\Poll\Helper\Data'),
    array('Magento\Poll\Model\Poll'),
    array('Magento\Poll\Model\Poll\Answer'),
    array('Magento\Poll\Model\Poll\Vote'),
    array('Magento\Poll\Model\Resource\Poll'),
    array('Magento\Poll\Model\Resource\Poll\Answer'),
    array('Magento\Poll\Model\Resource\Poll\Answer\Collection'),
    array('Magento\Poll\Model\Resource\Poll\Collection'),
    array('Magento\Poll\Model\Resource\Poll\Vote'),
    array('Mage:'),
    array('Magento\Backup', 'Magento\Backup\Factory'),
    array('Magento\Core\Controller\Front\Router', 'Magento\Core\Controller\Request\HttpProxy'),
    array('Magento\Core\Controller\Response\Http', 'Magento\Core\Controller\Varien\Action\Forward'),
    array('Magento\Core\Controller\Varien\Action\Redirect', 'Magento\Core\Controller\Varien\DispatchableInterface'),
    array('Magento\Core\Controller\Varien\Front'),
    array('Magento\Core\Controller\FrontInterface', 'Magento\Core\Model\App\Handler'),
    array('Magento\Core\Model\App\Proxy', 'Magento\Core\Model\Event\Config\SchemaLocator'),
    array('Magento\Core\Controller\Varien\Router\AbstractRouter', 'Magento\Core\Controller\Varien\AbstractAction'),
    array('Magento\Core\Controller\Varien\Exception', 'Magento\HTTP\HandlerFactory'),
    array('Magento\Core\Controller\Request\Http', 'Magento\Core\Controller\Varien\Router\AbstractRouter'),
    array('Magento\Core\Controller\Varien\Router\DefaultRouter', 'Magento\Core\Model\NoRouteHandlerList'),
    array('Magento\Core\Controller\Varien\Action\Factory', 'Magento\Core\Model\Dir'),
    array('Magento\Core\Model\ModuleList', 'Magento\Core\Model\ModuleListInterface'),
    array('Magento\Core\Model\RouterList', 'Magento\Core\Model\App\State'),
    array('Magento\Core\Model\Event\Config\Converter', 'Magento\Core\Model\Event\Config\Data'),
    array('Magento\Core\Model\Event\Config\Reader', 'Magento\Core\Model\Event\Invoker\InvokerDefault'),
    array('Magento\Core\Model\Event\Config', 'Magento\Core\Model\Event\ConfigInterface'),
    array('Magento\Core\Model\Event\InvokerInterface', 'Magento\Core\Model\Event\Manager'),
    array('Magento\HTTP\Handler\Composite', 'Magento\HTTP\HandlerInterface'),
    array('Magento\Backend\Model\Request\PathInfoProcessor', 'Magento\Backend\Model\Router\NoRouteHandler'),
    array('Magento\Core\Model\Request\PathInfoProcessor', 'Magento\Core\Model\Request\RewriteService'),
    array('Magento\Core\Model\Router\NoRouteHandler', 'Magento\Core\Model\Resource\SetupFactory'),
    array('Magento\Core\Model\Dir\Verification', 'Magento\Core\Model\Module\Declaration\Converter\Dom'),
    array('Magento\Core\Model\Module\Declaration\Reader\Filesystem', 'Magento\Core\Model\Module\Dir'),
    array('Magento\Core\Model\Module\Declaration\FileResolver', 'Magento\Core\Model\Module\Declaration\SchemaLocator'),
    array('Magento\Core\Model\Module\Dir\ReverseResolver', 'Magento\Core\Model\Module\ResourceResolver'),
    array('Magento\Core\Model\Module\ResourceResolverInterface', 'Magento\Core\Model\Resource\SetupInterface'),
    array('Magento\Core\Model\Db\UpdaterInterface', 'Magento\Core\Model\Router\NoRouteHandlerInterface'),
    array('Magento\Core\Model\Router\NoRouteHandlerInterface', 'Magento\Core\Model\UrlInterface'),
    array('Magento\Sales\Model\Resource\Order\Attribute\Backend\Parent'),
    array('Magento\Sales\Model\Resource\Order\Creditmemo\Attribute\Backend\Parent'),
    array('Magento\Sales\Model\Resource\Order\Invoice\Attribute\Backend\Parent'),
    array('Magento\Sales\Model\Resource\Order\Shipment\Attribute\Backend\Parent'),
    array('Magento\Sales\Model\Resource\Quote\Address\Attribute\Backend\Parent'),
    array('Magento\Core\Model\ThemeInterface', 'Magento\View\Design\ThemeInterface'),
    array('Magento\Core\Model\View\DesignInterface', 'Magento\View\DesignInterface'),
    array('Magento\Core\Model\Layout\Element', 'Magento\View\Layout\Element'),
);
