<?php
/**
 * Obsolete methods
 *
 * Format: array(<method_name = ''>[, <class_scope> = ''[, <replacement>[, <is_deprecated>]]])
 *
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2013 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
return array(
    array('__get', 'Magento\Object'),
    array('__set', 'Magento\Object'),
    array('_addItem', 'Magento\Page\Block\Html\Head'),
    array('_addLink', 'Magento\Customer\Block\Account\Link'),
    array('_addMinimalPrice', 'Magento\Catalog\Model\Resource\Product\Collection'),
    array('_addTaxPercents', 'Magento\Catalog\Model\Resource\Product\Collection'),
    array('_afterSaveCommit', 'Magento\Core\Model\AbstractModel'),
    array('_afterSetConfig', 'Magento\Eav\Model\Entity\AbstractEntity'),
    array('_aggregateByOrderCreatedAt', 'Magento\SalesRule\Model\Resource\Report\Rule'),
    array('_amountByCookies', 'Magento\Sendfriend\Model\Sendfriend'),
    array('_amountByIp', 'Magento\Sendfriend\Model\Sendfriend'),
    array('_applyClassRewrites', 'Magento\Core\Model\Config'),
    array('_applyCustomDesignSettings'),
    array('_applyCustomizationFiles', 'Magento\Core\Model\Theme'),
    array('_applyDesign', 'Magento\Catalog\Model\Design'),
    array('_applyDesignRecursively', 'Magento\Catalog\Model\Design'),
    array('_avoidDoubleTransactionProcessing'),
    array('_beforeChildToHtml'),
    array('_beforeMove', 'Magento\Catalog\Model\Resource\Category\Tree'),
    array('_bytesToMbytes', 'Magento\Catalog\Model\Product\Option\Type\File'),
    array('_calculatePrice', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('_canBeStoreCodeInUrl', 'Magento\App\Request\Http'),
    array('_canShowField', 'Magento\Backend\Block\System\Config\Form'),
    array('_canUseCacheForInit', 'Magento\Core\Model\Config'),
    array('_canUseLocalModules'),
    array('_checkCookieStore', 'Magento\Core\Model\App'),
    array('_checkGetStore', 'Magento\Core\Model\App'),
    array('_checkUrlSettings', 'Magento\Adminhtml\Controller\Action'),
    array('_collectOrigData', 'Magento\Catalog\Model\Resource\AbstractResource'),
    array('_decodeInput', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('_emailOrderConfirmation', 'Magento\Checkout\Model\Type\AbstractType'),
    array('_escapeValue', 'Magento\Adminhtml\Block\Widget\Grid\Column\Filter\AbstractFilter'),
    array('_extractData', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_filterPostData', 'Magento\Adminhtml\Controller\Catalog\Product\Attribute'),
    array('_generateCssHtml', 'Magento\Page\Block\Html\Head'),
    array('_generateJsHtml', 'Magento\Page\Block\Html\Head'),
    array('_getAddressTaxRequest', 'Magento\Tax\Model\Sales\Total\Quote\Shipping'),
    array('_getAggregationPerStoreView'),
    array('_getAttributeFilterBlockName'),
    array('_getAttributeFilterBlockName', 'Magento\Catalog\Block\Layer\View'),
    array('_getAttributeFilterBlockName', 'Magento\CatalogSearch\Block\Layer'),
    array('_getAvailable', 'Magento\GiftMessage\Model\Observer'),
    array('_getBytesIniValue', 'Magento\Catalog\Model\Product\Option\Type\File'),
    array('_getCacheId', 'Magento\Core\Model\App'),
    array('_getCacheKey', 'Magento\Catalog\Model\Layer\Filter\Price'),
    array('_getCacheLockId', 'Magento\Core\Model\Config'),
    array('_getCacheTags', 'Magento\Core\Model\App'),
    array('_getChildHtml'),
    array('_getConfig', 'Magento\Page\Helper\Layout'),
    array('_getCookie', 'Magento\PageCache\Helper\Data'),
    array('_getCollapseState', 'Magento\Backend\Block\System\Config\Form\Fieldset', '_isCollapseState'),
    array('_getCollectionNames', 'Magento\Adminhtml\Controller\Report\Sales'),
    array('_getConnectionAdapterClassName', 'Magento\Core\Model\Resource'),
    array('_getConnenctionType', 'Magento\Install\Model\Installer\Db'),
    array('_getDateFromToHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getDeclaredModuleFiles', 'Magento\Core\Model\Config'),
    array('_getDesignChange', 'Magento\Core\Model\App\Area'),
    array('_getDom', 'Magento\Backend\Model\Menu\Config'),
    array('_getExistingBasePopularity'),
    array('_getFieldTableAlias', 'Magento\Newsletter\Model\Resource\Subscriber\Collection'),
    array('_getForeignKeyName', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('_getGiftmessageSaveModel', 'Magento\Adminhtml\Block\Sales\Order\Create\Search\Grid'),
    array('_getGlobalAggregation'),
    array('_getGroupByDateFormat', 'Magento\Log\Model\Resource\Visitor\Collection'),
    array('_getIdAttributes', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_getInitialXml', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_getInputHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getLabelForStore', 'Magento\Catalog\Model\Resource\Eav\Attribute'),
    array('_getMultiSelectHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getNumberFromToHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getPathInScope', 'Magento\Core\Model\Config'),
    array('_getPriceFilter', 'Magento\Catalog\Block\Layer\View'),
    array('_getProcessor', 'Magento\Core\Model\Cache'),
    array('_getProductQtyForCheck', 'Magento\CatalogInventory\Model\Observer'),
    array('_getPublicFileUrl', 'Magento\Core\Model\Design\Package', 'Magento_Core_Model_View_Url::getPublicFileUrl'),
    array('_getRangeByType', 'Magento\Log\Model\Resource\Visitor\Collection'),
    array('_getRecentProductsCollection'),
    array('_getRequestModel', 'Magento\Authorizenet\Model\Directpost'),
    array('_getResource', 'Magento\Core\Model\Resource\Setup'),
    array('_getScopeCode', 'Magento\Core\Model\Config'),
    array('_getSectionConfig', 'Magento\Core\Model\Config'),
    array('_getSelectHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getSetData', 'Magento\Adminhtml\Block\Catalog\Product\Attribute\Set\Main'),
    array('_getSession', 'Magento\Paygate\Model\Authorizenet', 'Magento_Paygate_Model_Authorizenet::_session'),
    array('_getSHAInSet', '', 'Magento_Ogone_Model_Api::getHash'),
    array('_getStoreByGroup', 'Magento\Core\Model\App'),
    array('_getStoreByWebsite', 'Magento\Core\Model\App'),
    array('_getStoreTaxRequest', 'Magento\Tax\Model\Sales\Total\Quote\Shipping'),
    array('_getUploadMaxFilesize', 'Magento\Catalog\Model\Product\Option\Type\File'),
    array('_hookQueries', 'Magento\Core\Model\Resource\Setup'),
    array('_importAddress', 'Magento\Paypal\Model\Api\Nvp'),
    array('_inheritDesign', 'Magento\Catalog\Model\Design'),
    array('_initBaseConfig', 'Magento\Core\Model\App'),
    array('_initCache', 'Magento\Core\Model\App'),
    array('_initCurrentStore', 'Magento\Core\Model\App'),
    array('_initFileSystem', 'Magento\Core\Model\App'),
    array('_initLogger', 'Magento\Core\Model\App'),
    array('_initModules', 'Magento\Core\Model\App'),
    array('_initModulesPreNamespaces', 'Magento\Core\Model\Config'),
    array('_initOrder', 'Magento\Shipping\Block\Tracking\Popup'),
    array('_initShipment', 'Magento\Shipping\Block\Tracking\Popup'),
    array('_initStores', 'Magento\Core\Model\App'),
    array('_inludeControllerClass', '', '_includeControllerClass'),
    array('_isApplyDesign', 'Magento\Catalog\Model\Design'),
    array('_isApplyFor', 'Magento\Catalog\Model\Design'),
    array('_isPositiveDecimalNumber', 'Magento\Shipping\Model\Resource\Carrier\Tablerate'),
    array('_isRuntimeValidated', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_loadCache', 'Magento\Backend\Model\Menu\Config'),
    array('_loadCache', 'Magento\Core\Model\Config'),
    array('_loadDeclaredModules', 'Magento\Core\Model\Config'),
    array('_loadInstallDate', 'Magento\Core\Model\Config'),
    array('_loadLocalConfig', 'Magento\Core\Model\Config'),
    array('_loadOldRates', 'Magento\Tax\Model\Resource\Setup'),
    array('_loadSectionCache', 'Magento\Core\Model\Config'),
    array('_needSubtractShippingTax'),
    array('_needSubtractTax'),
    array('_needToAddDummy'),
    array('_needToAddDummyForShipment'),
    array('_parseDescription', 'Magento\Sales\Model\Order\Pdf\Items\AbstractItems'),
    array('_parsePackageTheme', 'Magento\Widget\Model\Widget\Instance'),
    array('_parseXmlTrackingResponse', 'Magento\Usa\Model\Shipping\Carrier\Fedex'),
    array('_prepareCondition', 'Magento\CatalogSearch\Model\Advanced'),
    array('_prepareConfigurableProductData', 'Magento\ImportExport\Model\Export\Entity\Product'),
    array('_prepareConfigurableProductPrice', 'Magento\ImportExport\Model\Export\Entity\Product'),
    array('_prepareOptionsForCart', 'Magento\Catalog\Model\Product\Type\AbstractType'),
    array('_preparePackageTheme', 'Magento\Widget\Model\Widget\Instance'),
    array('_processItem', 'Magento\Weee\Model\Total\Quote\Weee'),
    array('_processShippingAmount'),
    array('_processValidateCustomer', 'Magento\Checkout\Model\Type\Onepage'),
    array('_putCustomerIntoQuote', 'Magento\Adminhtml\Model\Sales\Order\Create'),
    array('_quoteRow', 'Magento\Backup\Model\Resource\Db'),
    array('_recollectItem', 'Magento\Tax\Model\Sales\Total\Quote\Subtotal'),
    array('_removeCache', 'Magento\Core\Model\Config'),
    array('_removeLink', 'Magento\Customer\Block\Account\Link'),
    array('_resetItemPriceInclTax'),
    array('_saveCache', 'Magento\Backend\Model\Menu\Config'),
    array('_saveCache', 'Magento\Core\Model\Config'),
    array('_saveCustomerAfterOrder', 'Magento\Adminhtml\Model\Sales\Order\Create'),
    array('_saveCustomers', 'Magento\Adminhtml\Model\Sales\Order\Create'),
    array('_saveSectionCache', 'Magento\Core\Model\Config'),
    array('_sendUploadResponse', 'Magento\Adminhtml\Controller\Customer'),
    array('_sendUploadResponse', 'Magento\Adminhtml\Controller\Newsletter\Subscriber'),
    array('_setAttribteValue'),
    array('_shouldSkipProcessUpdates', 'Magento\Core\Model\App'),
    array('_sort', 'Magento\Backend\Model\Config\Structure\Converter'),
    array('_toHtml', 'Magento\Backend\Block\Widget\Container'),
    array('_unhookQueries', 'Magento\Core\Model\Resource\Setup'),
    array('_updateMediaPathUseRewrites', 'Magento\Core\Model\Store', '_getMediaScriptUrl'),
    array('_usePriceIncludeTax'),
    array('addAccountLink', 'Magento\Customer\Block\Account\Link'),
    array('addAllowedModules', 'Magento\Core\Model\Config'),
    array('addAuthLink', 'Magento\Customer\Block\Account\Link'),
    array('addBackupedFilter'),
    array('addCartLink', 'Magento\Checkout\Block\Links'),
    array('addCheckoutLink', 'Magento\Checkout\Block\Links'),
    array('addColumnInputName', 'Magento\Backend\Block\Widget\Grid\Serializer'),
    array('addConfigField', 'Magento\Core\Model\Resource\Setup'),
    array('addConstraint', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('addCss', 'Magento\Page\Block\Html\Head'),
    array('addCssIe', 'Magento\Page\Block\Html\Head'),
    array('addCustomersToAlertQueueAction'),
    array('addCustomerToSegments'),
    array('addHandle', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('addItemRender', 'Magento\Adminhtml\Block\Sales\Items\AbstractItems'),
    array('addItemRender', 'Magento\Checkout\Block\Cart\AbstractCart'),
    array('addItemRender', 'Magento\Sales\Block\Items\AbstractItems'),
    array('addJs', 'Magento\Page\Block\Html\Head'),
    array('addJsIe', 'Magento\Page\Block\Html\Head'),
    array('addKey', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('addLinkRel', 'Magento\Page\Block\Html\Head'),
    array('addLogInLink', 'Magento\Customer\Block\Account\Link'),
    array('addModule', 'Magento\Core\Controller\Varien\Router\Base'),
    array('addRouter', 'Magento\App\FrontController'),
    array('addOptionRenderer', 'Magento\Catalog\Block\Product\View\Options'),
    array('addPageHandles', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('addPagerLimit', 'Magento\Catalog\Block\Product\ProductList\Toolbar'),
    array('addRegisterLink', 'Magento\Customer\Block\Account\Link'),
    array('addReviewSummaryTemplate', 'Magento\Catalog\Block\Product\AbstractProduct'),
    array('addRowItemRender', 'Magento\Checkout\Block\Multishipping\Overview'),
    array('addSaleableFilterToCollection'),
    array('addSearchQfFilter'),
    array('addTemplateData', 'Magento\Newsletter\Model\Queue'),
    array('addToAlersAction'),
    array('addToChildGroup'),
    array('addUpdate', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('addVisibleFilterToCollection', 'Magento\Catalog\Model\Product\Status'),
    array('addVisibleInCatalogFilterToCollection', '',
        '$collection->setVisibility(\Magento\Catalog\Model\Product\Visibility->getVisibleInCatalogIds());'
    ),
    array('addVisibleInSearchFilterToCollection', '',
        '$collection->setVisibility(\Magento\Catalog\Model\Product\Visibility->getVisibleInSearchIds());'
    ),
    array('addVisibleInSiteFilterToCollection', '',
        '$collection->setVisibility(\Magento\Catalog\Model\Product\Visibility->getVisibleInSiteIds());'
    ),
    array('addWishListSortOrder', 'Magento\Wishlist\Model\Resource\Item\Collection'),
    array('appendBundleSelectionData', 'Magento\Bundle\Model\Observer'),
    array('applyAllDataUpdates', 'Magento\Core\Model\Resource\Setup'),
    array('applyAllUpdates', 'Magento\Core\Model\Resource\Setup'),
    array('applyDesign', 'Magento\Catalog\Model\Design'),
    array('asArray', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('asSimplexml', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('asString', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('authAdmin'),
    array('authFailed', '', 'Magento_Core_Helper_Http::failHttpAuthentication()'),
    array('authFrontend'),
    array('authValidate', '', 'Magento_Core_Helper_Http::getHttpAuthCredentials()'),
    array('baseInit', 'Magento\Core\Model\App'),
    array('bundlesAction', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('calcTaxAmount', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('callbackQueryHook', 'Magento\Core\Model\Resource\Setup'),
    array('calculateSpecialPrice', 'Magento\Bundle\Model\Product\Price'),
    array('canCreateUser', 'Magento\User\Model\Resource\User'),
    array('canPrint', 'Magento\Checkout\Block\Onepage\Success'),
    array(
        'canTestHeaders',
        'Magento\TestFramework\Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::canTestHeaders'
    ),
    array('catalogCategoryChangeProducts', 'Magento\Catalog\Model\Product\Flat\Observer'),
    array('catalog' . 'EventProductCollectionAfterLoad', 'Magento\GiftMessage\Model\Observer'),
    array('catalogProductCompareClean', 'Magento\Catalog\Model\Observer'),
    array('catalogProductLoadAfter', 'Magento\Bundle\Model\Observer'),
    array('changeLocaleAction', 'Magento\Adminhtml\Controller\Index'),
    array('chechAllowedExtension'),
    array('checkConfigurableProducts', 'Magento\Eav\Model\Resource\Entity\Attribute\Collection'),
    array('checkDatabase', 'Magento\Install\Model\Installer\Db'),
    array('checkDateTime', 'Magento\Core\Model\Date'),
    array('chooseTemplate', 'Magento\Checkout\Block\Cart'),
    array('cleanCache', 'Magento\Core\Model\Config'),
    array('cleanDbRow', 'Magento\Core\Model\Resource'),
    array('cleanMergedJsCss', 'Magento\Core\Model\Design\Package', 'Magento\Core\Model\Page\Asset\MergeService'),
    array('cleanMergedJsCss', 'Magento\Core\Model\Design\Package\Proxy', 'Magento\Core\Model\Page\Asset\MergeService'),
    array(
        'cleanMergedJsCss',
        'Magento\Core\Model\Design\PackageInterface',
        'Magento\Core\Model\Page\Asset\MergeService'
    ),
    array('cleanVarFolder', '', 'Magento_Io_File::rmdirRecursive()'),
    array('cleanVarSubFolders', '',
        'glob() on \Magento\App\Dir::getBaseDir(\Magento\Core\Model\App\Dir::VAR_DIR)'),
    array('cloneIndexTable', 'Magento\Index\Model\Resource\AbstractResource'),
    array('collectRoutes', 'Magento\Backend\Controller\Router\DefaultRouter'),
    array('collectRoutes', 'Magento\Core\Controller\Varien\Router\Base'),
    array('composeLocaleHierarchy', 'Magento\Core\Helper\Translate'),
    array('convertOldTaxData', 'Magento\Tax\Model\Resource\Setup'),
    array('convertOldTreeToNew', 'Magento\Catalog\Model\Resource\Setup'),
    array('copyFieldset', 'Magento\Core\Helper\Data', 'copyFieldsetToTarget'),
    array('copyQuoteFilesToOrderFiles', 'Magento\Catalog\Model\Product\Option\Observer'),
    array('countChildren', 'Magento\Core\Block\AbstractBlock'),
    array('crear'),
    array('createDirIfNotExists', '', 'mkdir()'),
    array('createOrderItem', 'Magento\CatalogInventory\Model\Observer'),
    array('debugRequest', 'Magento\Paypal\Model\Api\Standard'),
    array('deleteAction', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('deleteConfig', 'Magento\Core\Model\Config'),
    array('deleteProductPrices', 'Magento\Catalog\Model\Resource\Product\Attribute\Backend\Tierprice'),
    array('display', 'Magento\Image\Adapter\AbstractAdapter', 'getImage()'),
    array('displayFullSummary', 'Magento\Tax\Model\Config'),
    array('displayTaxColumn', 'Magento\Tax\Model\Config'),
    array('displayZeroTax', 'Magento\Tax\Model\Config'),
    array('drawItem', 'Magento\Catalog\Block\Navigation'),
    array('dropKey', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('escapeJs', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config'),
    array('eventClean', 'Magento\Reports\Model\Event\Observer'),
    array('exportOrderedCsvAction'),
    array('exportOrderedExcelAction'),
    array('fetchItemsCount', 'Magento\Wishlist\Model\Resource\Wishlist'),
    array('fetchRuleRatesForCustomerTaxClass'),
    array('fetchUpdatesByHandle', 'Magento\Core\Model\Resource\Layout', 'Magento\Core\Model\Resource\Layout\Update'),
    array('flush', 'Magento\Core\Model\Cache', 'Magento_Cache_FrontendInterface::clean()'),
    array('flush', 'Magento\Core\Model\Cache\Proxy', 'Magento_Cache_FrontendInterface::clean()'),
    array('flush', 'Magento\Core\Model\CacheInterface', 'Magento_Cache_FrontendInterface::clean()'),
    array('forsedSave'),
    array('generateBlocks', '', 'generateElements()'),
    array('getAbsolutePath', '', 'normalizePath'),
    array('getAccount', 'Magento\GoogleAnalytics\Block\Ga'),
    array('getAclAssert', 'Magento\Admin\Model\Config'),
    array('getAclPrivilegeSet', 'Magento\Admin\Model\Config'),
    array('getAclResourceList', 'Magento\Admin\Model\Config'),
    array('getAclResourceTree', 'Magento\Admin\Model\Config'),
    array('getAddNewButtonHtml', 'Magento\Adminhtml\Block\Catalog\Product'),
    array('getAddNewButtonHtml', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getAddToCartItemUrl', 'Magento\Wishlist\Block\Customer\Sidebar'),
    array('getAddToCartUrlBase64', '', '_getAddToCartUrl'),
    array('getAllEntityIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAllEntityTypeCommentIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAllOrderEntityIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAllOrderEntityTypeIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAnonSuffix'),
    array('getAttributeDataModelFactory', 'Magento\Eav\Model\Validator\Attribute\Data'),
    array('getAttributesJson', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config', 'getAttributes'),
    array('getBaseTaxAmount', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('getBlockClassName', 'Magento\Core\Model\Config'),
    array('getButtonsHtml', 'Magento_Bundle_Block_Adminhtml_Catalog_Product_Edit_Tab_Bundle_Option_Search'),
    array('getCache', 'Magento\Core\Model\Config'),
    array('getCacheBetaTypes'),
    array('getCacheControls', 'Magento\PageCache\Helper\Data', 'Magento\PageCache\Model\CacheControlFactory'),
    array('getChangeLocaleUrl', 'Magento\Adminhtml\Block\Page\Footer'),
    array('getCheckoutMehod', 'Magento\Checkout\Model\Type\Onepage'),
    array('getChildGroup', '', 'Magento_Core_Block_AbstractBlock::getGroupChildNames()'),
    array('getConfig', 'Magento\Captcha\Helper\Data'),
    array('getConfig', 'Magento\Cms\Model\Wysiwyg\Images\Storage'),
    array('getConfigAsArray', 'Magento\Cms\Model\Wysiwyg\Images\Storage'),
    array('getConfig', 'Magento\Eav\Model\Entity\Attribute\AbstractAttribute'),
    array('getConfigAsXml','Magento\Widget\Model\Widget'),
    array('getConfigData', 'Magento\Cms\Model\Wysiwyg\Images\Storage'),
    array('getConfigDataModel', 'Magento\Core\Model\Config'),
    array('getConnectionTypeInstance', 'Magento\Core\Model\Resource'),
    array('getContainers', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getCustomerData', 'Magento\Adminhtml\Block\Sales\Order\Create\Form\Account'),
    array('getDataForSave', 'Magento\Wishlist\Model\Item'),
    array('getDataMaxSize'),
    array('getDataMaxSizeInBytes', 'Magento\Adminhtml\Block\Media\Uploader', 'Magento_File_Size::getMaxFileSize()'),
    array('getDbAdapter', 'Magento\Core\Model\Cache'),
    array('getDbAdapter', 'Magento\Core\Model\Cache\Proxy'),
    array('getDbAdapter', 'Magento\Core\Model\CacheInterface'),
    array(
        'getDbVendorName',
        'Magento\TestFramework\Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getDbVendorName'
    ),
    array('getDebug', 'Magento\Ogone\Model\Api'),
    array('getDebug', 'Magento\Paypal\Model\Api\AbstractApi'),
    array('getDefaultBasePath', 'Magento\Core\Model\Store'),
    array('getDeleteUrl', 'Magento\Adminhtml\Block\Catalog\Product\Edit'),
    array('getDirectOutput', 'Magento\Core\Block\Template'),
    array('getDirectOutput', 'Magento\Core\Model\Layout'),
    array('getDirectOutput', 'Magento\View\LayoutInterface'),
    array('getDistroServerVars', 'Magento\Core\Model\Config', 'getDistroBaseUrl'),
    array('getElementClass', 'Magento\Core\Model\Layout\Update'),
    array('getEngineFactory', 'Magento\Core\Block\Template\Context', 'getEnginePool'),
    array('getEntityIdsToIncrementIds', 'Magento\Rss\Model\Resource\Order'),
    array('getEntityTypeIdsToTypes', 'Magento\Rss\Model\Resource\Order'),
    array('getEventConfig', 'Magento\Core\Model\Config'),
    array('getExtensionsForCheck'),
    array('getFacets'),
    array('getFallbackTheme'),
    array('getFileLayoutUpdatesXml', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getFormated', '', "getFormated(true) -> format('html'), getFormated() -> format('text')"),
    array('getFormObject', 'Magento\Adminhtml\Block\Widget\Form'),
    array('getGiftmessageHtml', 'Magento\Adminhtml\Block\Sales\Order\View\Tab\Info'),
    array('getHandles', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getHeaderCssClass', 'Magento_Bundle_Block_Adminhtml_Catalog_Product_Edit_Tab_Bundle_Option_Search'),
    array('getHeaderText', 'Magento_Bundle_Block_Adminhtml_Catalog_Product_Edit_Tab_Bundle_Option_Search'),
    array('getHelperClassName', 'Magento\Core\Model\Config'),
    array('getHtmlFormat', 'Magento\Customer\Model\Address\AbstractAddress'),
    array('getInitParam', 'Magento\Core\Model\App'),
    array(
        'getInitParams',
        'Magento\TestFramework\Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getAppInitParams'
    ),
    array('getInstallDate', 'Magento\Core\Model\Config'),
    array(
        'getInstallDir',
        'Magento\TestFramework\Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getAppInstallDir'
    ),
    array('getInstance', 'Magento\TestFramework\Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::getInstance'),
    array('getIsActiveAanalytics', '', 'getOnsubmitJs'),
    array('getIsAjaxRequest', 'Magento\Core\Model\Translate\Inline'),
    array('getIsEngineAvailable'),
    array('getIsGlobal', 'Magento\Eav\Model\Entity\Attribute\AbstractAttribute'),
    array('getIsInStock', 'Magento\Checkout\Block\Cart\Item\Renderer'),
    array('getItemRender', 'Magento\Checkout\Block\Cart\AbstractCart'),
    array('getItemRendererInfo', 'Magento\Checkout\Block\Cart\AbstractCart'),
    array('getKeyList', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('getLanguages', 'Magento\Install\Block\Begin'),
    array('getLanguageSelect', 'Magento\Adminhtml\Block\Page\Footer'),
    array('getLayoutFilename', '', 'getFilename'),
    array('getLifeTime', 'Magento\Core\Model\Resource\Session'),
    array('getLocaleBaseDir', 'Magento\Core\Model\Design\Package'),
    array('getMail', 'Magento\Newsletter\Model\Template'),
    array('getMaxQueryLenght'),
    array('getMaxUploadSize', 'Magento\ImportExport\Helper\Data', 'getMaxUploadSizeMessage'),
    array('getMenuConfigurationFiles', 'Magento\Backend\Model\Menu\Config'),
    array('getMenuItemLabel', 'Magento\Admin\Model\Config'),
    array('getMergedCssUrl'),
    array('getMergedJsUrl'),
    array('getMessageUserCreationProhibited', 'Magento\User\Model\Resource\User'),
    array('getMinQueryLenght'),
    array('getModelClassName', 'Magento\Core\Model\Config'),
    array('getModuleByName', 'Magento\Core\Controller\Varien\Router\Base'),
    array('getModuleConfigurationFiles', 'Magento\Core\Model\Config'),
    array('getModuleSetup', 'Magento\Core\Model\Config'),
    array('getNeedUsePriceExcludeTax', '', 'Magento_Tax_Model_Config::priceIncludesTax()'),
    array('getOneBalanceTotal'),
    array('getOptimalCssUrls', 'Magento\Core\Model\Design\Package\Proxy', 'Magento\Core\Model\Page\Asset\Merged'),
    array('getOptimalJsUrls', 'Magento\Core\Model\Design\Package\Proxy', 'Magento\Core\Model\Page\Asset\Merged'),
    array('getOptimalCssUrls', 'Magento\Core\Model\Design\Package', 'Magento\Core\Model\Page\Asset\Merged'),
    array('getOptimalJsUrls', 'Magento\Core\Model\Design\Package', 'Magento\Core\Model\Page\Asset\Merged'),
    array('getOption', 'Magento\Captcha\Helper\Data', 'Magento_Core_Model_Dir::getDir()'),
    array('getOptions', 'Magento\Core\Model\Config'),
    array(
        'getOptions',
        'Magento\Core\Model\Design\Source\Design',
        'Magento_Core_Model_Theme::getThemeCollectionOptionArray'
    ),
    array('getOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getOrderHtml', 'Magento\GoogleAnalytics\Block\Ga'),
    array('getOrderId', 'Magento\Checkout\Block\Onepage\Success'),
    array('getOrderId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getOriginalHeigh', '', 'getOriginalHeight'),
    array('getOriginalRequest', 'Magento\App\Request\Http'),
    array('getPackage', 'Magento\Widget\Model\Widget\Instance'),
    array('getPackageTheme', 'Magento\Widget\Model\Widget\Instance', 'getThemeId'),
    array('getPageHandleLabel', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandleParents', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandles', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandlesHierarchy', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandleType', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageTemplateProcessor', 'Magento\Cms\Helper\Data'),
    array('getBlockTemplateProcessor', 'Magento\Cms\Helper\Data'),
    array('getPathAsArray', '', 'direct explode by /'),
    array('getPathFromArray', '', 'direct usage of /'),
    array('getPathVars', 'Magento\Core\Model\Config'),
    array('getParentProductIds', 'Magento\Catalog\Model\Resource\Product'),
    array('getPostMaxSize', 'Magento\Adminhtml\Block\Media\Uploader', 'Magento_File_Size::getPostMaxSize()'),
    array('getPriceFormatted', 'Magento\Adminhtml\Block\Customer\Edit\Tab\View\Sales'),
    array('getPrices', 'Magento\Bundle\Model\Product\Price'),
    array('getPricesDependingOnTax', 'Magento\Bundle\Model\Product\Price'),
    array('getPrintUrl', 'Magento\Checkout\Block\Onepage\Success'),
    array('getPrintUrl', 'Magento\Sales\Block\Order\Info'),
    array('getProduct', 'Magento\Catalog\Model\Product\Type\AbstractType'),
    array('getProductCollectionAttributes', 'Magento\Catalog\Model\Config'),
    array('getProductCollection', 'Magento\Wishlist\Helper\Data'),
    array('getProductCollection', 'Magento\Wishlist\Model\Wishlist'),
    array('getProductsNotInStoreIds'),
    array('getProfile', 'Magento\Convert\Container\AbstractContainer'),
    array('getQuoteItem', 'Magento\Catalog\Model\Product\Option\Type\DefaultType'),
    array('getQuoteItemOption', 'Magento\Catalog\Model\Product\Option\Type\DefaultType'),
    array('getQuoteOrdersHtml', 'Magento\GoogleAnalytics\Block\Ga'),
    array('getRefererParamName', 'Magento\Adminhtml\Block\Page\Footer'),
    array('getRelativePath', 'Magento\Core\Model\Theme\Files'),
    array('getRemoveItemUrl', 'Magento\Wishlist\Block\Customer\Sidebar'),
    array('getReorderUrl', 'Magento\Sales\Block\Order\Info'),
    array(
        'getResourceConfig',
        'Magento\Config\Model\Config',
        'Magento_Config_Model_Config_Resource::getResourceConfig'
    ),
    array('getResourceConfig', 'Magento\Core\Model\Config'),
    array('getResourceConnectionConfig', 'Magento\Config\Model\Config',
        'Magento_Config_Model_Config_Resource::getResourceConnectionConfig'
    ),
    array('getResourceConnectionConfig', 'Magento\Core\Model\Config'),
    array('getResourceConnectionModel', 'Magento\Config\Model\Config',
        'Magento_Config_Model_Config_Resource::getResourceConnectionModel'
    ),
    array('getResourceConnectionModel', 'Magento\Core\Model\Config'),
    array('getResourceModel', 'Magento\Core\Model\Config'),
    array('getResourceModelClassName', 'Magento\Core\Model\Config'),
    array('getResourceTypeConfig', 'Magento\Config\Model\Config',
        'Magento_Config_Model_Config_Resource::getResourceTypeConfig'
    ),
    array('getResourceTypeConfig', 'Magento\Core\Model\Config'),
    array('getResTreeJson', 'Magento\User\Block\Role\Tab\Edit', 'getTree'),
    array('getResTreeJson', 'Magento\Adminhtml\Block\Api\Tab\Rolesedit', 'getTree'),
    array(
        'getRouterByRoute',
        'Magento\App\FrontController',
        'Magento_Core_Model_RouterList::getRouterByFrontName'
    ),
    array('getRouterByFrontName', 'Magento\App\FrontController',
        'Magento_Core_Model_RouterList::getRouterByFrontName'
    ),
    array('getRouters', 'Magento\Core\Model\Config'),
    array('getRowId', 'Magento\Adminhtml\Block\Sales\Order\Create\Customer\Grid'),
    array('getRowId', 'Magento\Adminhtml\Block\Widget\Grid'),
    array('getSaveTemplateFlag', 'Magento\Newsletter\Model\Queue'),
    array('getSectionNode', 'Magento\Core\Model\Config'),
    array('getSecure', 'Magento\Backend\Model\Url', 'isSecure'),
    array('getSecure', 'Magento\Core\Model\Url', 'isSecure'),
    array('getSelectionFinalPrice', 'Magento\Bundle\Model\Product\Price'),
    array('getShipId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getShowTemplateHints', 'Magento\Core\Block\Template'),
    array('getSortedChildBlocks', '', 'getChildNames() + $this->getLayout()->getBlock($name)'),
    array('getSortedChildren', '', 'getChildNames'),
    array('getSortedElements', 'Magento\Data\Form\Element\Fieldset', 'getElements'),
    array('getStateModelClass', 'Magento\Centinel\Model\Config'),
    array('getStatrupPageUrl'),
    array('getStore', 'Magento\Captcha\Helper\Data'),
    array('getStore', 'Magento\Adminhtml\Block\Promo\Widget\Chooser\Sku'),
    array('getStoreButtonsHtml', 'Magento\Backend\Block\System\Config\Tabs'),
    array('getStoreCodeFromPath', 'Magento\App\Request\Http'),
    array('getStoreCurrency', 'Magento\Sales\Model\Order'),
    array('getStoreSelectOptions', 'Magento\Backend\Block\System\Config\Tabs'),
    array('getStores', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getSuggestedZeroDate'),
    array('getSuggestionsByQuery'),
    array('getSysTmpDir'),
    array('getTablePrefix', 'Magento\Core\Model\Config'),
    array('getTagsByType', 'Magento\Core\Model\Cache', 'Magento_Cache_Frontend_Decorator_TagScope::getTag()'),
    array('getTagsByType', 'Magento\Core\Model\Cache\Proxy', 'Magento_Cache_Frontend_Decorator_TagScope::getTag()'),
    array('getTagsByType', 'Magento\Core\Model\CacheInterface', 'Magento_Cache_Frontend_Decorator_TagScope::getTag()'),
    array('getTaxAmount', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('getTaxRatesByProductClass', '', '_getAllRatesByProductClass'),
    array('getTemplateProcessor', 'Magento\Newsletter\Helper\Data',
        'Use directly model \Magento\Newsletter\Model\Template\Filter'),
    array('getTempVarDir', 'Magento\Core\Model\Config', 'Magento_Core_Model_Dir::getDir()'),
    array('getTestsDir', 'Magento\TestFramework\Bootstrap'),
    array('getTheme', 'Magento\Widget\Model\Widget\Instance'),
    array('getThemeOptions', 'Magento\Core\Model\Design\Source\Design',
        'Magento_Core_Model_Theme::getThemeCollectionOptionArray'
    ),
    array('getTotalModels', 'Magento\Sales\Model\Quote\Address'),
    array('getTotalModels', 'Magento\Sales\Model\Quote\Config'),
    array('getTrackId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingInfoByOrder', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingInfoByShip', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingInfoByTrackId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingPopUpUrlByOrderId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getTrackingPopUpUrlByShipId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getTrackingPopUpUrlByTrackId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getUnixProcessMemoryUsage', 'Magento\TestFramework\Helper\Memory', 'getRealMemoryUsage'),
    array('getUnprocessedEvents', 'Magento\Index\Model\Resource\Event',
        'Magento_Index_Model_EventRepository::getUnprocessed()'
    ),
    array('getUnprocessedEventsCollection', 'Magento\Index\Model\Process',
        'Magento_Index_Model_EventRepository::getUnprocessed()'
    ),
    array('getUploadMaxSize', 'Magento\Adminhtml\Block\Media\Uploader', 'Magento_File_Size::getUploadMaxSize()'),
    array('getUrlForReferer', 'Magento\Adminhtml\Block\Page\Footer'),
    array('getUseCacheFilename', 'Magento\Core\Model\App'),
    array('getValidator', 'Magento\SalesRule\Model\Observer'),
    array('getValidatorData', 'Magento\Core\Model\Session\AbstractSession', 'use _getSessionEnvironment method'),
    array('getValueTable'),
    array('getVarDir', 'Magento\Core\Model\Config', 'Magento_Core_Model_Dir::getDir()'),
    array('getViewOrderUrl', 'Magento\Checkout\Block\Onepage\Success'),
    array('getWatermarkHeigth', '', 'getWatermarkHeight'),
    array('getWebsite', 'Magento\Captcha\Helper\Data'),
    array('getWidgetConfig', 'Magento\Widget\Model\Widget\Instance', 'getWidgetConfigAsArray'),
    array('getWidgetsRequiredJsFiles','Magento\Widget\Model\Widget'),
    array('getWidgetsXml','Magento\Widget\Model\Widget', 'getWidgets'),
    array('getWidgetSupportedBlocks', 'Magento\Widget\Model\Widget\Instance'),
    array('getWidgetSupportedTemplatesByBlock', 'Magento\Widget\Model\Widget\Instance'),
    array('getWinProcessMemoryUsage', 'Magento\Test\Helper\Memory', 'getRealMemoryUsage'),
    array('getXmlConfig','Magento\Widget\Model\Widget', 'getWidgets'),
    array('getXmlConfig','Magento\Persistent\Model\Persistent\Config'),
    array('getXmlElementByType','Magento\Widget\Model\Widget', 'getWidgetByClassType'),
    array('hasItems', 'Magento\Wishlist\Helper\Data'),
    array('htmlEscape', '', 'escapeHtml'),
    array('imageAction', 'Magento\Catalog\Controller\Product'),
    array('implodeStreetAddress', 'Magento\Customer\Model\Address\AbstractAddress'),
    array('importFromTextArray'),
    array('init', 'Magento\App\FrontController'),
    array('init', 'Magento\Core\Model\App'),
    array('init', 'Magento\Core\Model\Config'),
    array('init', 'Magento\Webapi\Controller\Front'),
    array('initCache'),
    array('initControllerRouters', 'Magento\Cms\Controller\Router'),
    array('initLabels', 'Magento\Catalog\Model\Resource\Eav\Attribute'),
    array('initSerializerBlock', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Ajax\Serializer'),
    array('initSerializerBlock', 'Magento\Backend\Block\Widget\Grid\Serializer'),
    array('initSpecified', 'Magento\Core\Model\App'),
    array('insertProductPrice', 'Magento\Catalog\Model\Resource\Product\Attribute\Backend\Tierprice'),
    array('isAbsolutePath'),
    array('isAllowedGuestCheckout', 'Magento\Sales\Model\Quote'),
    array('isAutomaticCleaningAvailable', 'Magento\Cache\Backend\Eaccelerator'),
    array('isCheckoutAvailable', 'Magento\Checkout\Model\Type\Multishipping'),
    array('isDirectOutput', 'Magento\Core\Model\Layout'),
    array('isDirectOutput', 'Magento\View\LayoutInterface'),
    array('isFulAmountCovered'),
    array('isInstalled', 'Magento\Core\Model\App'),
    array('isLeyeredNavigationAllowed'),
    array('isLocalConfigLoaded', 'Magento\Core\Model\Config'),
    array('isModuleEnabled', 'Magento\Core\Model\Config', 'Magento_Core_Model_ModuleManager::isEnabled'),
    array('isReadablePopupObject'),
    array('isStaticFilesSigned', 'Magento\Core\Helper\Data'),
    array('isTemplateAllowedForApplication'),
    array('isThemeCompatible', 'Magento\Core\Model\Design\Package', 'Magento_Core_Model_Theme::isThemeCompatible'),
    array('isUserSavingAllowed', 'Magento\User\Model\Resource\User'),
    array('isVerbose', 'Magento_Shell'),
    array('isWindowsOs', 'Magento\TestFramework\Helper\Memory'),
    array('load', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('loadBaseContents', 'Magento\Core\Model\Email\Template'),
    array('loadBase', 'Magento\Core\Model\Config'),
    array('loadDb', 'Magento\Core\Model\Config'),
    array('loadDiConfiguration', 'Magento\Core\Model\Config'),
    array('loadEventObservers', 'Magento\Core\Model\Config'),
    array('loadLabel', 'Magento\Catalog\Model\Resource\Product\Type\Configurable\Attribute'),
    array('loadModules', 'Magento\Core\Model\Config'),
    array('loadModulesCache', 'Magento\Core\Model\Config'),
    array('loadModulesConfiguration', 'Magento\Core\Model\Config'),
    array('loadParentProductIds', 'Magento\Catalog\Model\Product'),
    array('loadPrices', 'Magento\Catalog\Model\Resource\Product\Type\Configurable\Attribute'),
    array('loadProductPrices', 'Magento\Catalog\Model\Resource\Product\Attribute\Backend\Tierprice'),
    array('lockOrderInventoryData', 'Magento\CatalogInventory\Model\Observer'),
    array('logEncryptionKeySave'),
    array('logI' . 'nvitationSave'),
    array('map', 'Magento\ObjectManager\Config\Mapper\Dom', 'Magento_ObjectManager_Config_Mapper_Dom::convert'),
    array('mergeFiles', 'Magento\Core\Helper\Data', 'Magento\Core\Model\Page\Asset\MergeStrategyInterface'),
    array('mergeFiles', 'Magento\Core\Model\Design\Package', 'Magento\Core\Model\Page\Asset\MergeStrategyInterface'),
    array(
        'mergeFiles',
        'Magento\Core\Model\Design\Package\Proxy',
        'Magento\Core\Model\Page\Asset\MergeStrategyInterface'
    ),
    array(
        'mergeFiles',
        'Magento\Core\Model\Design\PackageInterface',
        'Magento\Core\Model\Page\Asset\MergeStrategyInterface'
    ),
    array('order_success_page_view', 'Magento\GoogleAnalytics\Model\Observer'),
    array('orderedAction', 'Magento\Adminhtml\Controller\Report\Product'),
    array('output', 'Magento_Shell'),
    array('pageHandleExists', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('parseDateTime', 'Magento\Core\Model\Date'),
    array('postDispatchMyAccountSave'),
    array('postDispatchSystemImportExportRun'),
    array('prepareAddressInfo', 'Magento\Sales\Block\Recurring\Profile\View'),
    array('prepareAttributesForSave', 'Magento\ImportExport\Model\Import\Entity\Product'),
    array('prepareCacheId', 'Magento\Core\Model\App'),
    array('prepareFeesInfo', 'Magento\Sales\Block\Recurring\Profile\View'),
    array('prepareGoogleOptimizerScripts'),
    array('prepareRedirect', 'Magento\Core\Controller\Varien\Exception'),
    array('prepareItemInfo', 'Magento\Sales\Block\Recurring\Profile\View'),
    array('preparePriceAlertData', 'Magento\ProductAlert\Block\Product\View'),
    array('prepareProfilesGrid', 'Magento\Sales\Block\Recurring\Profiles'),
    array('prepareReferenceInfo', 'Magento\Sales\Block\Recurring\Profile\View'),
    array('prepareRelatedOrdersFrontendGrid', 'Magento\Sales\Block\Recurring\Profile\View'),
    array('prepareScheduleInfo', 'Magento\Sales\Block\Recurring\Profile\View'),
    array('prepareStockAlertData', 'Magento\ProductAlert\Block\Product\View'),
    array('prepareViewData', 'Magento\Sales\Block\Recurring\Profile\View'),
    array('preprocess', 'Magento\Newsletter\Model\Template'),
    array('processBeacon'),
    array('processBeforeVoid', 'Magento\Payment\Model\Method\AbstractMethod'),
    array('processRequest', 'Magento\Core\Model\Cache'),
    array('processSubst', 'Magento\Core\Model\Store'),
    array('productEventAggregate'),
    array('publishRelatedViewFile', 'Magento\Core\Model\View\Publisher', '_publishRelatedViewFile'),
    array('push', 'Magento\Catalog\Model\Product\Image'),
    array('rebuildCategoryLevels', 'Magento\Catalog\Model\Resource\Setup'),
    array('refundOrderItem', 'Magento\CatalogInventory\Model\Observer'),
    array('regenerateSessionId', 'Magento\Core\Model\Session\AbstractSession'),
    array('reinitialize', 'Magento\TestFramework\Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::reinitialize'),
    array('removeAuthLink', 'Magento\Customer\Block\Account\Link'),
    array('removeItem', 'Magento\Page\Block\Html\Head'),
    array('removeCustomerFromSegments'),
    array('removeHandle', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('removeParentCartLink', 'Magento\Checkout\Block\Links'),
    array('removeRegisterLink', 'Magento\Customer\Block\Account\Link'),
    array('renderView', '', 'Magento_Core_Block_Template::_toHtml()'),
    array('revalidateCookie', 'Magento\Core\Model\Session\AbstractSession\Varien'),
    array('runApp', 'Magento\TestFramework\Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::runApp'),
    array('sales_order_afterPlace'),
    array('sales_quote_address_discount_item'),
    array('salesEventConvertQuoteItemToOrderItem', 'Magento\GiftMessage\Model\Observer'),
    array('salesOrderPaymentPlaceEnd'),
    array('saveCache', 'Magento\Core\Model\Config'),
    array('saveConfig', 'Magento\Core\Model\Config'),
    array('saveOptions', 'Magento\Core\Model\Cache'),
    array('saveOptions', 'Magento\Core\Model\Cache\Proxy'),
    array('saveOptions', 'Magento\Core\Model\CacheInterface'),
    array('saveRow__OLD'),
    array('saveSegmentCustomersFromSelect'),
    array('saveUseCache'),
    array('send', 'Magento\Newsletter\Model\Template'),
    array('sendNewPasswordEmail'),
    array('setAnonSuffix'),
    array('setApplyFilters'),
    array('setAttributeDataModelFactory', 'Magento\Eav\Model\Validator\Attribute\Data'),
    array('setAttributeSetExcludeFilter', 'Magento\Eav\Model\Resource\Entity\Attribute\Collection'),
    array('setBlockAlias'),
    array('setConfig', 'Magento\Captcha\Helper\Data'),
    array('setCustomerId', 'Magento\Customer\Model\Resource\Address'),
    array('setDirectOutput', 'Magento\Core\Model\Layout'),
    array('setInstance', 'Magento\TestFramework\Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::setInstance'),
    array('setIsAjaxRequest', 'Magento\Core\Model\Translate\Inline'),
    array('setNeedUsePriceExcludeTax', '', 'Magento_Tax_Model_Config::setPriceIncludesTax()'),
    array('setOption', 'Magento\Captcha\Helper\Data'),
    array('setOptions', 'Magento\Core\Model\Config'),
    array('setOrderId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('setPackageTheme', 'Magento\Widget\Model\Widget\Instance', 'setThemeId'),
    array('setParentBlock'),
    array('setProduct', 'Magento\Catalog\Model\Product\Type\AbstractType'),
    array('setProfile', 'Magento\Convert\Container\AbstractContainer'),
    array('setResourceConfig', 'Magento\Core\Model\Resource'),
    array('setSaveTemplateFlag', 'Magento\Newsletter\Model\Queue'),
    array('setScriptPath'),
    array('setScriptPath', 'Magento\Core\Block\Template'),
    array('setShipId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('setSortElementsByAttribute', 'Magento\Data\Form\Element\Fieldset'),
    array('setStore', 'Magento\Captcha\Helper\Data'),
    array('setTaxGroupFilter'),
    array('setTrackId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('setVarSubFolders'),
    array('setVerbose', 'Magento_Shell'),
    array('setWatermarkHeigth', '', 'setWatermarkHeight'),
    array('setWebsite', 'Magento\Captcha\Helper\Data'),
    array('shaCrypt', '', 'Magento_Ogone_Model_Api::getHash'),
    array('shaCryptValidation', '', 'Magento_Ogone_Model_Api::getHash'),
    array('shouldCustomerHaveOneBalance'),
    array('shouldShowOneBalance'),
    array('sortChildren'),
    array('substDistroServerVars', 'Magento\Core\Model\Config'),
    array('superGroupGridOnlyAction', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('toOptionArray', 'Magento\Cms\Model\Resource\Page\Collection'),
    array('toOptionArray', 'Magento\Sendfriend\Model\Sendfriend'),
    array('truncate', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('unsetBlock'),
    array('updateCofigurableProductOptions', 'Magento\Weee\Model\Observer', 'updateConfigurableProductOptions'),
    array('updateTable', 'Magento\Core\Model\Resource\Setup'),
    array('urlEscape', '', 'escapeUrl'),
    array('useValidateHttpUserAgent', 'Magento\Core\Model\Session\AbstractSession'),
    array('useValidateHttpVia', 'Magento\Core\Model\Session\AbstractSession'),
    array('useValidateHttpXForwardedFor', 'Magento\Core\Model\Session\AbstractSession'),
    array('useValidateRemoteAddr', 'Magento\Core\Model\Session\AbstractSession'),
    array('validateDataArray', 'Magento\Convert\Container\AbstractContainer'),
    array('validateFile', 'Magento\Core\Model\Design\Package'),
    array('validateOrder', 'Magento\Checkout\Model\Type\Onepage'),
    array('_prepareOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('_getOptionValuesCollection', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array(' _prepareSystemAttributeOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array(
        '_prepareUserDefinedAttributeOptionValues',
        'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'
    ),
    array('getLabelValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getStoreOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getAttributeObject', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('substractQtyFromQuotes', 'Magento\Sales\Model\Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogProductQuote::subtractQtyFromQuotes'
    ),
    array('markQuotesRecollectOnCatalogRules', 'Magento\Sales\Model\Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogPriceRule::dispatch'
    ),
    array(
        'catalogProductSaveAfter', 'Magento\Sales\Model\Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogProductQuote::catalogProductSaveAfter'
    ),
    array(
        'catalogProductStatusUpdate', 'Magento\Sales\Model\Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogProductQuote::catalogProductStatusUpdate'
    ),
    array(
        'prepareProductEditFormRecurringProfile', 'Magento\Sales\Model\Observer',
        'Magento_Sales_Model_Observer_Backend_RecurringProfile_FormRenderer::render'
    ),
    array(
        'restrictAdminBillingAgreementUsage', 'Magento\Sales\Model\Observer',
        'Magento_Sales_Model_Observer_Backend_BillingAgreement::dispatch'
    ),
    array(
        'customerSaveAfter', 'Magento\Sales\Model\Observer',
        'Magento_Sales_Model_Observer_Backend_CustomerQuote::dispatch'
    ),
    array('_getUsers', 'Magento\Adminhtml\Block\Api\Role\Grid\User', 'getUsers'),
    array('_getGridHtml', 'Magento\Adminhtml\Block\Api\Tab\Rolesusers', 'getGridHtml'),
    array('_getSelectedRoles', 'Magento\Adminhtml\Block\Api\User\Edit\Tab\Roles', 'getSelectedRoles'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config\Matrix', 'getProduct'),
    array('_getImageUploadUrl', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config\Matrix',
        'getImageUploadUrl'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config\Simple', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Settings', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Crosssell', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Related', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Upsell', 'getProduct'),
    array(
        '_renderCellTemplate',
        'Magento\Backend\Block\System\Config\Form\Field\Array\AbstractArray',
        'renderCellTemplate'
    ),
    array('_showSingle', 'Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option', 'showSingle'),
    array('_getDefaultValues', 'Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option', 'getDefaultValues'),
    array('_isSelected', 'Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option', 'isSelected'),
    array('_getProduct', 'Magento\Catalog\Block\Product\Configurable\AssociatedSelector\Backend\Grid\ColumnSet',
        'getProduct'),
    array('_getProduct', 'Magento\CatalogInventory\Block\Stockqty\AbstractStockqty', 'getProduct'),
    array('_getProduct', 'Magento\CatalogInventory\Block\Qtyincrements', 'getProduct'),
    array('_getPageTrackingCode', 'Magento\GoogleAnalytics\Block\Ga', 'getPageTrackingCode'),
    array('_getOrdersTrackingCode', 'Magento\GoogleAnalytics\Block\Ga', 'getOrdersTrackingCode'),
    array('_toJson', 'Magento\GoogleShopping\Block\Adminhtml\Types\Edit\Attributes', 'jsonFormat'),
    array('_getConfig', 'Magento\GoogleShopping\Controller\Adminhtml\Googleshopping\Items'),
    array('_getSession', 'Magento\GoogleShopping\Model\MassOperations'),
    array('_getStore', 'Magento\GoogleShopping\Block\Adminhtml\Items\Item'),
    array('_createAttribute', 'Magento\GoogleShopping\Model\Type'),
    array('_prepareModelName', 'Magento\GoogleShopping\Model\Type'),
    array('_getUsers', 'Magento\User\Block\Role\Grid\User', 'getUsers'),
    array('_getGridHtml', 'Magento\User\Block\Role\Tab\Users', 'getGridHtml'),
    array('_getSelectedRoles', 'Magento\User\Block\User\Edit\Tab\Roles', 'getSelectedRoles'),
    array('_prepareSelect', 'Magento\Core\Model\Resource\Db\Collection\AbstractCollection'),
    array('_prepareSelect', 'Magento\Data\Collection\Db'),
    array('castField', 'Magento\Core\Model\Resource\Helper'),
    array('getQueryUsingAnalyticFunction', 'Magento\Core\Model\Resource\Helper'),
    array('limitUnion', 'Magento\Core\Model\Resource\Helper'),
    array('_addLoadAttributesSelectFields', 'Magento\Catalog\Model\Resource\AbstractResource'),
    array('attributeSelectFields', 'Magento\Catalog\Model\Resource\Helper'),
    array('_addLoadAttributesSelectFields', 'Magento\Eav\Model\Entity\AbstractEntity'),
    array('attributeSelectFields', 'Magento\Eav\Model\Resource\Helper'),
    array('prepareEavAttributeValue', 'Magento\Eav\Model\Resource\Helper'),
    array('prepareColumn', 'Magento\Eav\Model\Resource\Helper'),
    array('getInsertFromSelectUsingAnalytic', 'Magento\Eav\Model\Resource\Helper'),
    array('setOneRowLimit', 'Magento\Eav\Model\Resource\Helper'),
    array('getCastToIntExpression', 'Magento\Eav\Model\Resource\Helper'),
    array('_initMetaTags', 'Magento\Page\Block\Html\Head'),
    array('addMetaTag', 'Magento\Page\Block\Html\Head'),
    array('getDefaultMetaTags', 'Magento\Page\Block\Html\Head'),
    array('getDefaultTemplates', 'Magento\Core\Model\Email\Template'),
    array('getDefaultTemplatesAsOptionsArray', 'Magento\Core\Model\Email\Template',
        'Magento_Adminhtml_Block_System_Email_Template_Edit::_getDefaultTemplatesAsOptionsArray'),
    array('getMetaTags', 'Magento\Page\Block\Html\Head'),
    array('getMetaTagHtml', 'Magento\Page\Block\Html\Head'),
    array('addLink', 'Magento\Sales\Block\Order\Info'),
    array('checkLinks', 'Magento\Sales\Block\Order\Info'),
    array('getLinks', 'Magento\Sales\Block\Order\Info'),
    array('validate', 'Magento\Core\Model\Session\AbstractSession'),
    array('_validate', 'Magento\Core\Model\Session\AbstractSession'),
    array('_getSessionEnvironment', 'Magento\Core\Model\Session\AbstractSession'),
    array('getValidateHttpUserAgentSkip', 'Magento\Core\Model\Session\AbstractSession'),
    array('addProductAttributes', 'Magento\SalesRule\Model\Observer'),
    array('_helper', 'Magento\Catalog\Model\Product\Type\AbstractType'),
    array('getHelper', 'Magento\Catalog\Model\Resource\Product\Type\Configurable\Attribute\Collection'),
    array('getHelper', 'Magento\Cms\Model\Wysiwyg\Images\Storage'),
    array('getHelper', 'Magento\Core\Model\App'),
    array('getCatalogHelper', 'Magento\Adminhtml\Block\Catalog\Category\Tabs'),
    array('getStabilityOptions', 'Magento\Connect\Model\Extension'),
    array('_getSession', 'Magento\Centinel\Model\Service'),
    array('_getValidationStateModel', 'Magento\Centinel\Model\Service'),
    array('_getIndexer', 'Magento\Index\Model\Shell'),
    array('_getApi', 'Magento\Ogone\Block\Placeform'),
    array('_getResource', 'Magento\Weee\Model\Attribute\Backend\Weee\Tax',
        'Magento_Weee_Model_Attribute_Backend_Weee_Tax::$_attributeTax'),
    array('getCouponMassGenerator', 'Magento\SalesRule\Model\Rule', 'Magento\SalesRule\Model\Coupon\Massgenerator'),
    array('_getHelper', 'Magento\Captcha\Model\DefaultModel'),
    array('getSession', 'Magento\Captcha\Model\DefaultModel'),
    array('_getBackendSession', 'Magento\Captcha\Model\Observer'),
    array('_resetAttempt', 'Magento\Captcha\Model\Observer'),
    array('getProductStatusModel', 'Magento\CatalogInventory\Model\Stock\Status'),
    array('getStorage', 'Magento\Cms\Helper\Wysiwyg\Images'),
    array('_getSession', 'Magento\Review\Helper\Action\Pager'),
    array('_getProductType', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config\Matrix'),
    array('_getProductType', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config'),
    array('_getSession', 'Magento\Adminhtml\Model\Sales\Order'),
    array('setIsSerializable', 'Magento\App\State'),
    array('getIsSerializable', 'Magento\App\State'),
    array('_getInventoryItemResource', 'Magento\Reports\Model\Resource\Product\Lowstock\Collection'),
    array('getMigrationInstance', 'Magento\Customer\Model\Resource\Setup', '$this->_migrationFactory->create()'),
    array('turnOnReadCommittedMode', 'Magento\Backup\Model\Resource\Db'),
    array('turnOnSerializableMode', 'Magento\Backup\Model\Resource\Db', 'prepareTransactionIsolationLevel'),
    array('_getResourceModel', '\Magento\Webapi\Model\Source\Acl\Role', '$this->_resource'),
    array('_getSession', '\Magento\Adminhtml\Model\Giftmessage\Save', '$this->_session'),
    array('_initRequest', '\Magento\Core\Model\App'),
    array('run', '\Magento\Core\Model\App'),
    array('_initFrontController', '\Magento\Core\Model\App'),
    array('_getFrontControllerByCurrentArea', '\Magento\Core\Model\App'),
    array('run', '\Magento\Core\Model\AppInterface'),
    array('setModuleDir', 'Magento\Core\Model\Config\Modules\Reader'),
    array('setModuleDir', 'Magento\Core\Model\Config'),
    array('getAreaConfig', 'Magento\Core\Model\Config'),
    array('getViewConfig', '\Magento\Core\Model\View\Config', 'get'),
);
