<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($_item = $block->getItem()): ?>
<table class="qty-table">
    <tr>
        <th><?= /* @escapeNotVerified */ __('Ordered') ?></th>
        <td><?= /* @escapeNotVerified */ $_item->getQtyOrdered()*1 ?></td>
    </tr>

    <?php if ((float) $_item->getQtyInvoiced()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Invoiced') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyInvoiced()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyShipped()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Shipped') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyShipped()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyRefunded()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Refunded') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyRefunded()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyCanceled()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Canceled') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyCanceled()*1 ?></td>
        </tr>
    <?php endif; ?>

</table>
<?php endif; ?>
