<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($item = $block->getItem()): ?>
<table class="qty-table">
    <tr>
        <th><?php echo $block->escapeHtml(__('Ordered')); ?></th>
        <td><?php echo /* @noEscape */  $item->getQtyOrdered()*1 ?></td>
    </tr>

    <?php if ((float) $item->getQtyInvoiced()): ?>
        <tr>
            <th><?php echo $block->escapeHtml(__('Invoiced')); ?></th>
            <td><?php echo /* @noEscape */  $item->getQtyInvoiced()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $item->getQtyShipped()): ?>
        <tr>
            <th><?php echo $block->escapeHtml(__('Shipped')); ?></th>
            <td><?php echo /* @noEscape */  $item->getQtyShipped()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $item->getQtyRefunded()): ?>
        <tr>
            <th><?php echo $block->escapeHtml(__('Refunded')); ?></th>
            <td><?php echo /* @noEscape */ $item->getQtyRefunded()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $item->getQtyCanceled()): ?>
        <tr>
            <th><?php echo $block->escapeHtml(__('Canceled')); ?></th>
            <td><?php echo /* @noEscape */ $item->getQtyCanceled()*1 ?></td>
        </tr>
    <?php endif; ?>

</table>
<?php endif; ?>
