<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Share\Email\Items */
?>
<?php $l = $block->getWishlistItemsCount() ?>
<div>
    <table>
        <tr>
            <?php $i = 0;
            foreach ($block->getWishlistItems() as $item): $i++ ?>
            <?php /* @var $item \Magento\Wishlist\Model\Item */ ?>
            <?php /* @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $_product = $item->getProduct(); ?>
            <td class="col product">
                <p>
                    <a href="<?= $block->getProductUrl($_product) ?>">
                        <img src="<?= $block->getSmallImageUrl($_product) ?>" height="<?= $block->getSmallImageSize() ?>" alt=""/>
                    </a>
                </p>

                <p>
                    <a href="<?= $block->getProductUrl($_product) ?>">
                        <strong><?= $block->escapeHtml($_product->getName()) ?></strong>
                    </a>
                </p>
                <?php if ($block->hasDescription($item)): ?>
                    <p>
                        <strong><?= __('Comment') ?>:</strong>
                        <br/><?= $block->getEscapedDescription($item) ?>
                    </p>
                <?php endif; ?>
                <p>
                    <a href="<?= $block->getProductUrl($_product) ?>">
                        <?= __('View Product') ?>
                    </a>
                </p>
            </td>
            <?php if ($i % 3 != 0): ?>
                <td></td>
            <?php else: ?>
        </tr>
        <tr>
            <td colspan="5">&nbsp;</td>
        </tr>
            <?php if ($i < $l): ?>
            <tr>
            <?php endif ?>
            <?php endif ?>
            <?php endforeach ?>
    </table>
</div>
