<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Edit $block */
?>
<?php if ($block->isProductVisibleInSiteVisibility()) :?>
    <a class="action action-edit"
       href="<?= $escaper->escapeUrl($block->getConfigureUrl()) ?>"
       title="<?= $escaper->escapeHtmlAttr(__('Edit item parameters')) ?>">
        <span><?= $escaper->escapeHtml(__('Edit')) ?></span>
    </a>
<?php endif ?>
