<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Payment\Form\Billing\Agreement $block
 */
$code = $block->escapeHtml($block->getMethodCode());
?>
<div class="field items required" id="payment_form_<?= /* @noEscape */ $code ?>" style="display:none;">
    <label for="<?= /* @noEscape */ $code ?>_ba_agreement_id" class="label">
        <span><?= $block->escapeHtml(__('Billing Agreement')) ?></span>
    </label>
    <div class="control">
        <select id="<?= /* @noEscape */ $code ?>_ba_agreement_id"
                name="payment[<?= $block->escapeHtml($block->getTransportName()) ?>]" class="select">
            <option value=""><?= $block->escapeHtml(__('-- Please Select Billing Agreement--')) ?></option>
            <?php foreach ($block->getBillingAgreements() as $id => $referenceId) : ?>
                <option value="<?= $block->escapeHtml($id) ?>">
                    <?= $block->escapeHtml($referenceId) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
