<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Template for block \Magento\Log\Block\Adminhtml\Customer\Edit\Tab\View\Status
 */

$lastLoginDateAdmin = $this->getLastLoginDate();
$lastLoginDateStore = $this->getStoreLastLoginDate();
?>
<tr>
    <th><?php echo __('Last Logged In:') ?></th>
    <td><?php echo $lastLoginDateAdmin ?> (<?php echo $this->getCurrentStatus() ?>)</td>
</tr>
<?php if ($lastLoginDateAdmin != $lastLoginDateStore): ?>
<tr>
    <th><?php echo __('Last Logged In (%1):', $this->getStoreLastLoginDateTimezone()) ?></th>
    <td><?php echo $lastLoginDateStore ?> (<?php echo $this->getCurrentStatus() ?>)</td>
</tr>
<?php endif; ?>
