<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $this \Magento\ProductAlert\Block\Product\View */?>
<div class="product alert <?php echo $this->getHtmlClass() ?>">
    <a href="#" data-post='<?php echo $this->getPostAction(); ?>'
       title="<?php echo $this->escapeHtml(__($this->getSignupLabel())); ?>" class="action alert">
        <?php echo $this->escapeHtml(__($this->getSignupLabel())); ?>
    </a>
</div>
