<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\ProductAlert\Block\Product\View;

/** @var Escaper $escaper */
/** @var View $block */
?>
<div class="product alert <?= $block->getHtmlClass() ?>">
    <a href="<?= $escaper->escapeUrl($block->getSignupUrl()) ?>"
       title="<?= $escaper->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert">
        <?= $escaper->escapeHtml(__($block->getSignupLabel())) ?>
    </a>
</div>
