<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php /* @var $this \Magento\ProductAlert\Block\Product\View */?>
<div class="product alert <?php echo $this->getHtmlClass() ?>">
    <a href="<?php echo $this->escapeHtml($this->getSignupUrl()) ?>"
       title="<?php echo $this->escapeHtml(__($this->getSignupLabel())); ?>" class="action alert">
        <?php echo $this->escapeHtml(__($this->getSignupLabel())); ?>
    </a>
</div>
