<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * \Magento\Sales\Block\Adminhtml\Order\Create\Coupons
 *
 */
?>
<div class="box-left">
    <h4><?php echo __('Apply Coupon Code') ?></h4>
    <fieldset>
        <div class="content">
            <input type="text" class="input-text" id="coupons:code" value="" name="coupon_code" />
            <?php echo $block->getButtonHtml(__('Apply'), 'order.applyCoupon($F(\'coupons:code\'))') ?>
            <?php if ($block->getCouponCode()): ?>
            <p><strong><?php echo $block->escapeHtml($block->getCouponCode()) ?></strong> [<a href="#" onclick="order.applyCoupon(''); return false;" title="<?php echo __('Remove Coupon Code') ?>"><?php echo __('Remove') ?></a>]</p>
            <?php endif; ?>
            <script>
            require(["Magento_Sales/order/create/form"], function(){

                order.overlay('shipping-method-overlay', <?php if ($block->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
                order.overlay('address-shipping-overlay', <?php if ($block->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);

            });
</script>
        </div>
    </fieldset>
</div>
