<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Customer\Block\Adminhtml\Edit\Tab\Cart $block */
?>
<?php if ($block->getCartHeader()) : ?>
<div class="content-header skip-header">
    <table>
        <tr>
            <td style="width:50%;"><h4><?= $escaper->escapeHtml($block->getCartHeader()) ?></h4></td>
        </tr>
    </table>
</div>
<?php endif ?>
<?= $block->getGridParentHtml() ?>
<?php if ($block->canDisplayContainer()) : ?>
    <?php $listType = $block->getJsObjectName(); ?>
    <script>
        require([
            "Magento_Ui/js/modal/alert",
            "Magento_Ui/js/modal/confirm",
            "Magento_Catalog/catalog/product/composite/configure"
        ], function(alert, confirm){

        <?= $escaper->escapeJs($block->getJsObjectName()) ?>cartControl = {
            reload: function (params) {
            if (!params) {
                params = {};
            }
            <?= $escaper->escapeJs($block->getJsObjectName()) ?>.reloadParams = params;
            <?= $escaper->escapeJs($block->getJsObjectName()) ?>.reload();
            <?= $escaper->escapeJs($block->getJsObjectName()) ?>.reloadParams = {};
        },

        configureItem: function (itemId) {
            productConfigure.setOnLoadIFrameCallback('<?= $escaper->escapeJs($listType) ?>', this.cbOnLoadIframe.bind(this));
            productConfigure.showItemConfiguration('<?= $escaper->escapeJs($listType) ?>', itemId);
            return false;
        },

        cbOnLoadIframe: function (response) {
            if (!response.ok) {
                return;
            }
            this.reload();
        },

        removeItem: function (itemId) {
            var self = this;

            if (!itemId) {
                alert({
                    content: '<?= $escaper->escapeJs(__('No item specified.')) ?>'
                });

                return false;
            }

            confirm({
                content: '<?= $escaper->escapeJs(__('Are you sure you want to remove this item?')) ?>',
                actions: {
                    confirm: function(){
                        self.reload({'delete':itemId});
                    }
                }
            });
        }
    };

    <?php
    $params = [
        'customer_id' => $block->getCustomerId(),
        'website_id' => $block->getWebsiteId(),
    ];
    ?>
    productConfigure.addListType(
        '<?= $escaper->escapeJs($listType) ?>',
        {
            urlFetch: '<?= $escaper->escapeJs($escaper->escapeUrl($block->getUrl('customer/cart_product_composite_cart/configure', $params))) ?>',
            urlConfirm: '<?= $escaper->escapeJs($escaper->escapeUrl($block->getUrl('customer/cart_product_composite_cart/update', $params))) ?>'
        }
    );

    });
    </script>
<?php endif ?>
<br />
