<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>
<?php $parentItem = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder(); ?>

<?php $items = $block->getChilds($parentItem) ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php if ($_item->getOrderItem()->getParentItem()): ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr>
        <td><strong><?= $attributes['option_label'] ?></strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif; ?>
<?php endif; ?>
<tr id="order-item-row-<?= $_item->getId() ?>">
    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
    <td><strong><?= $block->escapeHtml($_item->getName()) ?></strong></td>
    <?php else: ?>
    <td><?= $block->getValueHtml($_item) ?></td>
    <?php endif; ?>
    <td><?= $block->escapeHtml($_item->getSku()) ?></td>
    <td>
        <?php if ($block->canShowPriceInfo($_item)): ?>
            <?= $_item->getQty() * 1 ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td>
        <?php if ($block->canShowPriceInfo($_item)): ?>
            <?= $block->getItemPrice($_item) ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>

<?php if ($_showlastRow): ?>
<tr>
    <td>
        <?php if ($block->getItemOptions()): ?>
        <dl>
            <?php foreach ($block->getItemOptions() as $option): ?>
            <dt><strong><em><?= $option['label'] ?></em></strong></dt>
            <dd><?= $option['value'] ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif; ?>
