<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\ConfigurableProduct\Block\Product\Configurable\AttributeSelector */
?>
<script>
(function(){
    'use strict';
    
    var $form;

    require([
        "jquery",
        "jquery/ui",
        'Magento_Ui/js/modal/modal'
    ], function($){
        $form = $('#affected-attribute-set-form');

        var resetValidation = function() {
            $form.find('.messages .message.error').hide();
            $form.find('form').validation().data('validator').resetForm();
        };

        $('[data-form=edit-product]').append($('<input>', {
            type: 'hidden',
            name: 'new-variations-attribute-set-id',
            id: 'new-variations-attribute-set-id'
        }));

        $form.modal({
            title: '<?php echo __('Choose Affected Product Template'); ?>',
            type: 'popup',
            closed: function () {
                resetValidation();
            },
            buttons: [{
                text: '<?php echo __('Confirm'); ?>',
                'class': 'action-primary',
                attr: {
                    'id': '<?php echo $block->getJsId('confirm-button') ?>'
                },
                click: function() {
                    if ($form.find('input[name=affected-attribute-set]:checked').val() == 'current') {
                        $('#new-variations-attribute-set-id').val($('#attribute_set_id').val());
                        $form.modal('closeModal')
                            .data('target').click();
                        return;
                    }

                    $form.find('.messages .message.error').hide();
                    if (!$form.find('form').validation().valid()) {
                        $form.find('input[name=new-attribute-set-name]').focus();
                        return false;
                    }

                    $.ajax({
                        type: 'POST',
                        url: '<?php echo $block->getAttributeSetCreationUrl()?>',
                        data: {
                            gotoEdit: 1,
                            attribute_set_name: $form.find('input[name=new-attribute-set-name]').val(),
                            skeleton_set: $('#attribute_set_id').val(),
                            form_key: '<?php echo $block->getFormKey()?>',
                            return_session_messages_only: 1
                        },
                        dataType: 'json',
                        showLoader: true,
                        context: $form
                    })
                        .success(function (data) {
                            if (!data.error) {
                                $('#new-variations-attribute-set-id').val(data.id);
                                $form.modal('closeModal')
                                    .data('target').click();
                            } else {
                                $form.find('.messages .message.error').replaceWith($(data.messages).find('.message.error'));
                            }
                        });

                    return false;
                }
            },{
                text: '<?php echo __('Cancel'); ?>',
                'class': 'action-close',
                attr: {
                    'id': '<?php echo $block->getJsId('close-button') ?>'
                },
                click: function() {
                    this.closeModal();
                }
            }]
        })
        .find('input[name=affected-attribute-set]').on('change', function() {
            $('#affected-attribute-set-new-name-container')[$(this).val() == 'new' ? 'show' : 'hide']();
            resetValidation();
            if ($(this).val() == 'new') {
                $form.find('input[name=new-attribute-set-name]').focus();
            }
        });
    });
    
    require([
        'jquery'
    ], function ($) {

        /**
         * Retrieve list of attributes
         *
         * @return {Array}
         */
        var getAttributes = function ($node) {
            return $.map(
                $node.find('[data-role=configurable-attributes-container] [data-role=attribute-info]') || [],
                function (attribute) {
                    var $attribute = $(attribute);

                    return {
                        id: $attribute.find('[name$="[attribute_id]"]').val(),
                        code: $attribute.find('[name$="[code]"]').val(),
                        label: $attribute.find('[name$="[label]"]').val(),
                        position: $attribute.find('[name$="[position]"]').val()
                    };
                }
            );
        };

        /**
         * This fix was made in order to properly handle 'stopImmediatePropagation'.
         */
        $('#save-split-button .item').on('click', function(event) {
            if ($('#new-variations-attribute-set-id').val() != '') {
                return; // affected attribute set was already chosen
            }

            var extendingAttributes = [];

            $.each(getAttributes($('[data-role=product-variations-matrix]')), function () {
                if (!$('#attribute-' + this.code + '-container').length) {
                    extendingAttributes.push(this.id);
                }
            });
            if (!extendingAttributes.length) {
                $('#new-variations-attribute-set-id').val($('#attribute_set_id').val());
                return; // all selected configurable attributes belong to current attribute set
            }
            if (!$('[data-role=product-variations-matrix] [data-column=entity_id]')
                .closest('tr').has('input[name$="[name]"]').length
            ) {
                return; // no new simple products to save from matrix: uniting attribute set is not needed
            }

            event.stopImmediatePropagation();

            $form.data('target', event.target).modal('openModal');
        });

    });

})();
</script>
