<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\GoogleGtag\ViewModel\Adwords $adsViewModel */
$adsViewModel = $block->getViewModel();
?>

<?php if ($adsViewModel->isGoogleAdwordsConfigurable() && $adsViewModel->isGoogleAdwordsActive()): ?>
    <?php $conversionId = $adsViewModel->getConversionId(); ?>
    <?php $gtagSiteSrc = $adsViewModel->getConversionGtagGlobalSiteTagSrc(); ?>
    <script>
        if (!window.gtag) {
          // Inject Global Site Tag
          var gtagScript = document.createElement('script');
          gtagScript.type = 'text/javascript';
          gtagScript.async = true;
          gtagScript.src = '<?= $block->escapeHtml($gtagSiteSrc) ?>';
          document.head.appendChild(gtagScript);

          window.dataLayer = window.dataLayer || [];

          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('set', 'developer_id.dYjhlMD', true);
        } else {
          gtag('config', '<?= $block->escapeHtml($conversionId) ?>');
        }
      </script>
<?php endif ?>
