<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>
<?php $parentItem = $this->getItem() ?>
<?php $_order = $this->getItem()->getOrderItem()->getOrder() ?>

<?php $items = $this->getChilds($parentItem) ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>
<?php foreach ($items as $_item): ?>

    <?php if ($this->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->getIsMessagesAvailable('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
        <?php $_showlastRow = true ?>
    <?php else: ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $this->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr class="options-label">
                <td class="col label" colspan="5"><div class="option label"><?php echo $attributes['option_label'] ?></div></td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr id="order-item-row-<?php echo $_item->getId() ?>" class="<?php if ($_item->getOrderItem()->getParentItem()): ?>item-options-container<?php else: ?>item-parent<?php endif; ?>"<?php if ($_item->getOrderItem()->getParentItem()): ?> data-th="<?php echo $attributes['option_label'] ?>"<?php endif; ?>>
    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <td class="col name" data-th="<?php echo $this->escapeHtml(__('Product Name')); ?>">
            <strong class="product name product-item-name"><?php echo $this->escapeHtml($_item->getName()) ?></strong>
        </td>
    <?php else: ?>
        <td class="col value" data-th="<?php echo $this->escapeHtml(__('Product Name')); ?>"><?php echo $this->getValueHtml($_item) ?></td>
    <?php endif; ?>
    <td class="col sku" data-th="<?php echo $this->escapeHtml(__('SKU')); ?>"><?php echo $this->escapeHtml($_item->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $this->escapeHtml(__('Price')); ?>">
        <?php if ($this->canShowPriceInfo($_item)): ?>
            <?php echo $this->getItemPriceHtml($_item); ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td class="col qty" data-th="<?php echo $this->escapeHtml(__('Qty Invoiced')); ?>">
        <?php if ($this->canShowPriceInfo($_item)): ?>
            <?php echo $_item->getQty()*1 ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td class="col subtotal" data-th="<?php echo $this->escapeHtml(__('Subtotal')); ?>">
        <?php if ($this->canShowPriceInfo($_item)): ?>
            <?php echo $this->getItemRowTotalHtml($_item); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>

<?php if ($_showlastRow && (($_options = $this->getItemOptions()) || $this->escapeHtml($_item->getDescription()))): ?>
    <tr>
        <td class="col options" colspan="5">
            <?php if ($_options = $this->getItemOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$this->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                                <?php echo $_formatedOptionValue['value'] ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <div class="tooltip content">
                                        <dl class="item options">
                                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd><?php echo $this->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php echo $this->escapeHtml($_item->getDescription()) ?>
        </td>
    </tr>
<?php endif; ?>
