<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $this \Magento\Bundle\Block\Adminhtml\Catalog\Product\Edit\Tab\Bundle */
?>
<script type="text/javascript">

if(typeof Bundle=='undefined') {
    Bundle = {};
}

</script>

<div class="entry-edit form-inline" id="bundle_product_container">
    <div class="fieldset-wrapper collapsable-wrapper" id="bundle_product-wrapper">
        <div class="fieldset-wrapper-title">
            <strong class="title" data-toggle="collapse" data-target="#bundle_product-content">
                <span><?php echo $this->getTabLabel() ?></span>
            </strong>
        </div>
        <div class="fieldset-wrapper-content collapse" id="bundle_product-content">
            <fieldset class="fieldset">
                <div class="field field-ship-bundle-items">
                    <label for="shipment_type" class="label"><?php echo __('Ship Bundle Items') ?></label>
                    <div class="control">
                        <select <?php if ($this->isReadonly()): ?>disabled="disabled" <?php endif;?>
                                id="shipment_type"
                                name="<?php echo $this->getFieldSuffix() ?>[shipment_type]"
                                class="select">
                            <option value="1"><?php echo __('Separately') ?></option>
                            <option value="0"<?php if ($this->getProduct()->getShipmentType() == 0): ?> selected="selected"<?php endif; ?>><?php echo __('Together') ?></option>
                        </select>
                    </div>
                </div>

                <div class="entry-edit custom-options bundle" id="product_bundle_container">
                    <?php echo $this->getOptionsBoxHtml() ?>
                </div>

                <?php echo $this->getAddButtonHtml() ?>
            </fieldset>
        </div>
    </div>
</div>

<input type="hidden" name="affect_bundle_product_selections" value="1" />

<script type="text/javascript">
require(["prototype", "mage/adminhtml/form"], function(){
    // re-bind form elements onchange
    varienWindowOnload(true);

    <?php if ($this->isReadonly()):?>
    $('product_bundle_container').select('input', 'select', 'textarea', 'button').each(function(input){
        input.disabled = true;
        if (input.tagName.toLowerCase() == 'button') {
            input.addClassName('disabled');
        }
    });
    <?php endif; ?>
});
</script>
