<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="locale-switcher col-m-5">
    <label class="label" for="footer_interface_locale"><span><?php /* @escapeNotVerified */ echo __('Interface Locale'); ?></span></label>
    <?php /* @escapeNotVerified */ echo $block->getLocaleSelect(); ?>
    <script>
        (function () {
            'use strict';

            var elem = document.getElementById('footer_interface_locale');

            function onChange() {
                window.location.href = '<?php /* @escapeNotVerified */ echo $block->getChangeLocaleUrl() ?>locale/' + elem.value + '/<?php /* @escapeNotVerified */ echo $block->getUrlForReferer() ?>';
            }

            elem.addEventListener('change', onChange);
        })();
    </script>
</div>
