<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Backend\Block\Page\Notices
 */
?>
<?php if ($block->displayNoscriptNotice()): ?>
    <noscript>
        <div class="messages">
            <div class="message message-warning message-noscript">
                <strong><?php echo __('JavaScript may be disabled in your browser.'); ?></strong>
                <?php echo __('To use this website you must first enable JavaScript in your browser.'); ?>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($block->displayDemoNotice()): ?>
    <div class="messages">
        <div class="message message-warning message-demo-mode">
            <?php echo __('This is only a demo store. You can browse and place orders, but nothing will be processed.') ?>
        </div>
    </div>
<?php endif; ?>
