<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $this \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<p class="toolbar-amount">
    <?php if ($this->getLastPageNum() > 1): ?>
        <?php echo __('Items %1-%2 of %3',
            '<span class="toolbar-number">' . $this->getFirstNum() . '</span>',
            '<span class="toolbar-number">' . $this->getLastNum() . '</span>',
            '<span class="toolbar-number">' . $this->getTotalNum() . '</span>') ?>
    <?php elseif ($this->getTotalNum() == 1): ?>
        <?php echo __('%1 Item',
           '<span class="toolbar-number">' . $this->getTotalNum() . '</span>') ?>
    <?php else: ?>
        <?php echo __('%1 Items',
            '<span class="toolbar-number">' . $this->getTotalNum() . '</span>') ?>
    <?php endif; ?>
</p>
