<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $this \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($this->isEnabledViewSwitcher()): ?>
<div class="modes">
    <?php $_modes = $this->getModes(); ?>
    <?php if ($_modes && count($_modes) > 1): ?>
    <strong class="modes-label"><?php echo __('View as') ?></strong>
    <?php foreach ($this->getModes() as $_code => $_label): ?>
        <?php if ($this->isModeActive($_code)): ?>
            <strong title="<?php echo $_label ?>"
                class="modes-mode active mode-<?php echo strtolower($_code); ?>"
                data-value="<?php echo strtolower($_code); ?>">
                <span><?php echo $_label ?></span>
            </strong>
        <?php else: ?>
            <a class="modes-mode mode-<?php echo strtolower($_code); ?>"
               title="<?php echo $_label ?>"
               href="#"
               data-role="mode-switcher"
               data-value="<?php echo strtolower($_code); ?>">
                <span><?php echo $_label ?></span>
            </a>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<?php endif; ?>
