<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $this \Magento\Backend\Block\Template */ ?>
<div class="field field-store-switcher">
    <label class="label" for="store_switcher"><?php echo __('Current Configuration Scope:') ?></label>
    <div class="control">
        <select id="store_switcher" class="system-config-store-switcher" onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
        <?php foreach ($this->getStoreSelectOptions() as $_value => $_option): ?>
        <?php if (isset($_option['is_group'])): ?>
            <?php if ($_option['is_close']): ?>
                </optgroup>
            <?php else: ?>
                <optgroup label="<?php echo $this->escapeHtml($_option['label']) ?>" style="<?php echo $_option['style'] ?>">
            <?php endif; ?>
            <?php continue ?>
        <?php endif; ?>
          <option value="<?php echo $this->escapeHtml($_value) ?>" url="<?php echo $_option['url'] ?>" <?php echo $_option['selected'] ? 'selected="selected"' : '' ?> style="<?php echo $_option['style'] ?>">
              <?php echo $this->escapeHtml($_option['label']) ?>
          </option>
        <?php endforeach ?>
        </select>
    </div>
    <?php echo $this->getHintHtml() ?>
    <?php if ($this->getAuthorization()->isAllowed('Magento_Adminhtml::store')): ?>
        <div class="actions">
            <a href="<?php echo $this->getUrl('*/system_store') ?>"><?php echo __('Stores') ?></a>
        </div>
    <?php endif; ?>
</div>
