<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Tax\Block\Item\Price\Renderer */
?>
<?php $_item = $block->getItem() ?>
    <?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
        <span class="price-wrapper price-including-tax" data-label="<?= /* @escapeNotVerified */ __('Incl. Tax') ?>">
            <span class="minicart-price">
                <?php $_incl = $_item->getPriceInclTax(); ?>
                <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_incl) ?>
            </span>
        </span>
    <?php endif; ?>
    <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
        <span class="price-wrapper price-excluding-tax" data-label="<?= /* @escapeNotVerified */ __('Excl. Tax') ?>">
            <span class="minicart-price">
                <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_item->getCalculationPrice()) ?>
            </span>
        </span>
    <?php endif; ?>
