<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?= $escaper->escapeHtml(
    __(
        'You added product %1 to the <a href="%2">comparison list</a>.',
        $block->getData('product_name'),
        $block->getData('compare_list_url')
    ),
    ['a']
);
