<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<?= $escaper->escapeHtml(
    __(
        'You added product %1 to the <a href="%2">comparison list</a>.',
        $block->getData('product_name'),
        $block->getData('compare_list_url')
    ),
    ['a']
);
