<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Paypal\Block\Express\InContext\Minicart\SmartButton;

/**
 * @var \Magento\Paypal\Block\Express\InContext\Component $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$configuration = [
    'id' => SmartButton::PAYPAL_BUTTON_ID,
    'path' => $block->getUrl(
        'paypal/express/gettoken',
        [
            '_secure' => $block->getRequest()->isSecure()
        ]
    ),
    'merchantId' => $block->getMerchantId(),
    'button' => $block->isButtonContext(),
    'clientConfig' => [
        'locale' => $block->getLocale(),
        'environment' => $block->getEnvironment(),
        'button' => [
            SmartButton::PAYPAL_BUTTON_ID,
        ]
    ]
];

?>
<div id="<?= /* @noEscape */ SmartButton::PAYPAL_BUTTON_ID ?>"></div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display: none;",
    'div#' . /* @noEscape */ SmartButton::PAYPAL_BUTTON_ID
) ?>

<?php /** @var \Magento\Framework\Json\Helper\Data $jsonHelper */
$jsonHelper = $block->getData('jsonHelper');
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Paypal/js/in-context/express-checkout":
            <?= /* @noEscape */ $jsonHelper->jsonEncode($configuration) ?>
        }
    }
</script>
