<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <form
                action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/refreshStatistics'); ?>"
                method="post">
                <input
                    name="form_key"
                    type="hidden"
                    value="<?php /* @escapeNotVerified */ echo $block->getFormKey(); ?>"/>
                <button
                    class="action-primary"
                    type="submit"
                    title="Refresh Data">
                    <?php /* @escapeNotVerified */ echo __('Reload Data') ?>
                </button>
            </form>
        </div>
    </div>
</div>
