<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\ProductAlert\Block\Email\Email */
?>

<form action="<?= $block->escapeUrl($block->getProductUnsubscribeUrl()) ?>" method="post" id="unsubscription_form">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="text" id="productId" name="product" value="<?= $block->getProductId() ?>" />
</form>
<script>
    require([
        "jquery"
    ], function($){
        $(document).ready(function() {
            $('#unsubscription_form').submit();
        });
    });
</script>
