<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/**
 * @var \Magento\Framework\View\Element\Html\Calendar $block
 * @var \Magento\Framework\Escaper $escaper
 */

/**
 * Calendar localization script. Should be put into page header.
 *
 * @see \Magento\Framework\View\Element\Html\Calendar
 */
?>

<?php $intFirstDay = (int)$firstDay;
$scriptString = <<<script

require([
    'jquery',
], function($){

//<![CDATA[
    $.extend(true, $, {
        calendarConfig: {
            dayNames: {$days['wide']},
            dayNamesMin: {$days['abbreviated']},
            monthNames: {$months['wide']},
            monthNamesShort: {$months['abbreviated']},
            infoTitle: '{$escaper->escapeJs(__('About the calendar'))}',
            firstDay: {$intFirstDay},
            closeText: '{$escaper->escapeJs(__('Close'))}',
            currentText: '{$escaper->escapeJs(__('Go Today'))}',
            prevText: '{$escaper->escapeJs(__('Previous'))}',
            nextText: '{$escaper->escapeJs(__('Next'))}',
            weekHeader: '{$escaper->escapeJs(__('WK'))}',
            timeText: '{$escaper->escapeJs(__('Time'))}',
            hourText: '{$escaper->escapeJs(__('Hour'))}',
            minuteText: '{$escaper->escapeJs(__('Minute'))}',
            dateFormat: "D, d M yy", // $.datepicker.RFC_2822
            showOn: 'button',
            showAnim: '',
            changeMonth: true,
            changeYear: true,
            buttonImageOnly: null,
            buttonImage: null,
            showButtonPanel: true,
            showWeek: true,
            timeFormat: '',
            showTime: false,
            showHour: false,
            showMinute: false
        }
    });

    enUS = {$enUS}; // en_US locale reference
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
