<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var Magento\Framework\View\Element\Template $this
 */
?>

<div id="cookie-status">
    <?= $this->escapeHtml(__('The store will not work correctly in the case when cookies are disabled.')); ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "cookieStatus": {}
        }
    }
</script>
