<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Cookie settings initialization script
 *
 * @var $block \Magento\Framework\View\Element\Js\Cookie
 */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "mage/cookies": {
                "expires": null,
                "path": "<?php echo /* @escapeNotVerified */ $block->getPath() ?>",
                "domain": "<?php echo /* @escapeNotVerified */ $block->getDomain() ?>",
                "secure": false,
                "lifetime": "<?php echo /* @escapeNotVerified */ $block->getLifetime() ?>"
            }
        }
    }
</script>
