<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php  foreach ($types as $type) {
     if ($messages = $this->getMessages($type)) {
         if (!$html) {
             $html .= '<div class="messages">';
         }
         $html .= '<div class="message ' . $type . '">';

         foreach ($messages as $message) {
             $html .= '<div>';
             $html .= $message->getText();
             $html .= '</div>';
         }
         $html .= '</div>';
     }
 }
if ($html) {
    $html .= '</div>';
}
?>
