<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Weee\Block\Item\Price\Renderer
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Weee\Helper\Data $weeeHelper */
$weeeHelper = $block->getData('weeeHelper');

$_item = $block->getItem();
?>
<?php if ($block->displayPriceWithWeeeDetails()): ?>
    <span class="cart-tax-total"
          data-mage-init='{"taxToggle": {"itemTaxId" : "#esubtotal-item-tax-details<?= (int) $_item->getId() ?>"}}'>
<?php else: ?>
    <span class="cart-price">
<?php endif; ?>
<?= /* @noEscape */ $block->formatPrice($block->getRowDisplayPriceExclTax()) ?>
    </span>

<?php if ($weeeHelper->getApplied($_item)): ?>
    <span class="cart-tax-info no-display" id="esubtotal-item-tax-details<?= (int) $_item->getId() ?>">
    <?php if ($block->displayPriceWithWeeeDetails()): ?>
        <?php foreach ($weeeHelper->getApplied($_item) as $tax): ?>
            <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                <?= /* @noEscape */ $block->formatPrice($tax['row_amount'], true, true) ?>
            </span>
        <?php endforeach; ?>
    <?php endif; ?>
    </span>

    <?php if ($block->displayFinalPrice()): ?>
        <span class="cart-tax-total"
              data-mage-init='{"taxToggle": {"itemTaxId" : "#esubtotal-item-tax-details<?= (int) $_item->getId() ?>"}}'>
            <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total')) ?>">
                <?= /* @noEscape */ $block->formatPrice($block->getFinalRowDisplayPriceExclTax()) ?>
            </span>
        </span>
    <?php endif; ?>
<?php endif; ?>
