<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Weee\Block\Item\Price\Renderer */

$_item = $block->getItem();
?>
<?php if ($block->displayPriceWithWeeeDetails()): ?>
    <span class="cart-tax-total" data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"}}'>
<?php else: ?>
    <span class="cart-price">
<?php endif; ?>

<?php /* @escapeNotVerified */ echo $block->formatPrice($block->getUnitDisplayPriceExclTax()); ?>
    </span>

<?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
    <span class="cart-tax-info" id="eunit-item-tax-details<?php /* @escapeNotVerified */ echo $_item->getId(); ?>" style="display:none;">
    <?php if ($block->displayPriceWithWeeeDetails()): ?>
        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
            <span class="weee" data-label="<?php /* @escapeNotVerified */ echo $tax['title']; ?>"><?php /* @escapeNotVerified */ echo $block->formatPrice($tax['amount'], true, true); ?></span>
        <?php endforeach; ?>
    <?php endif; ?>
    </span>

    <?php if ($block->displayFinalPrice()): ?>
        <span class="cart-tax-total" data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"}}'>
            <span class="weee" data-label="<?php /* @escapeNotVerified */ echo __('Total'); ?>">
                <?php /* @escapeNotVerified */ echo $block->formatPrice($block->getFinalUnitDisplayPriceExclTax()); ?>
            </span>
        </span>
    <?php endif; ?>
<?php endif; ?>
