<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Weee\Block\Item\Price\Renderer;
use Magento\Weee\Helper\Data;

/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Renderer $block */
$_item = $block->getItem();

/** @var $_weeeHelper Data */
$_weeeHelper = $block->getData('weeeHelper');
?>
<?php $_incl = $_item->getPriceInclTax(); ?>
<?php if ($block->displayPriceWithWeeeDetails()): ?>
    <span class="cart-tax-total"
          data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int) $_item->getId() ?>"}}'>
<?php else: ?>
    <span class="cart-price">
<?php endif; ?>

<?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceInclTax()) ?>
    </span>

<?php if ($_weeeHelper->getApplied($_item)): ?>
    <span class="cart-tax-info no-display" id="unit-item-tax-details<?= (int) $_item->getId() ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <?php foreach ($_weeeHelper->getApplied($_item) as $tax): ?>
                <span class="weee" data-label="<?= $escaper->escapeHtmlAttr($tax['title']) ?>">
                    <?= /* @noEscape */ $block->formatPrice($tax['amount_incl_tax'], true, true) ?>
                </span>
            <?php endforeach; ?>
        <?php endif; ?>
    </span>

    <?php if ($block->displayFinalPrice()): ?>
        <span class="cart-tax-total"
              data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int) $_item->getId() ?>"}}'>
            <span class="weee" data-label="<?= $escaper->escapeHtmlAttr(__('Total Incl. Tax')) ?>">
                <?= /* @noEscape */ $block->formatPrice($block->getFinalUnitDisplayPriceInclTax()) ?>
            </span>
        </span>
    <?php endif; ?>
<?php endif; ?>
