<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Weee\Block\Item\Price\Renderer
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$_item = $block->getItem();
/** @var $_weeeHelper \Magento\Weee\Helper\Data */
$_weeeHelper = $block->getData('weeeHelper');
?>
<?php $_incl = $_item->getPriceInclTax(); ?>
<?php if ($block->displayPriceWithWeeeDetails()): ?>
    <span class="cart-tax-total"
          data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int) $_item->getId() ?>"}}'>
<?php else: ?>
    <span class="cart-price">
<?php endif; ?>

<?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceInclTax()) ?>
    </span>

<?php if ($_weeeHelper->getApplied($_item)): ?>
    <span class="cart-tax-info no-display" id="unit-item-tax-details<?= (int) $_item->getId() ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <?php foreach ($_weeeHelper->getApplied($_item) as $tax): ?>
                <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                    <?= /* @noEscape */ $block->formatPrice($tax['amount_incl_tax'], true, true) ?>
                </span>
            <?php endforeach; ?>
        <?php endif; ?>
    </span>

    <?php if ($block->displayFinalPrice()): ?>
        <span class="cart-tax-total"
              data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int) $_item->getId() ?>"}}'>
            <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total Incl. Tax')) ?>">
                <?= /* @noEscape */ $block->formatPrice($block->getFinalUnitDisplayPriceInclTax()) ?>
            </span>
        </span>
    <?php endif; ?>
<?php endif; ?>
