<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Type\Date */ ?>
<script id="custom-option-date-type-template" type="text/x-jquery-tmpl">
    <div id="product_option_${option_id}_type_${group}" class="fieldset">
        <table class="data-table" cellspacing="0">
            <thead>
            <tr class="headings">
                <?php if ($this->getCanReadPrice() !== false) : ?>
                <th><?php echo __('Price') ?></th>
                <th><?php echo __('Price Type') ?></th>
                <?php endif; ?>
                <th><?php echo __('SKU') ?></th>
            </tr>
            </thead>
            <tr>
                <?php if ($this->getCanReadPrice() !== false) : ?>
                <td class="opt-price">
                    <input id="product_option_${option_id}_price"
                           name="product[options][${option_id}][price]"
                           class="input-text validate-number product-option-price"
                           type="text" value="${price}" data-store-label="${price}"
                        <?php if ($this->getCanEditPrice() === false) : ?>
                           disabled="disabled"
                        <?php endif; ?>>
                </td>
                <td class="opt-price-type"><?php echo $this->getPriceTypeSelectHtml() ?>{{html checkboxScopePrice}}</td>
                <?php else : ?>
                <input id="product_option_${option_id}_price" name="product[options][${option_id}][price]" type="hidden">
                <input id="product_option_${option_id}_price_type" name="product[options][${option_id}][price_type]" type="hidden">
                <?php endif; ?>
                <td>
                    <input name="product[options][${option_id}][sku]" class="input-text type-sku" value="${sku}" type="text">
                </td>
            </tr>
        </table>
    </div>
</script>
