<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Type\File */ ?>
<script id="custom-option-file-type-template" type="text/x-jquery-tmpl">
    <div id="product_option_${option_id}_type_${group}" class="fieldset">
        <table class="data-table" cellspacing="0">
            <thead>
            <tr>
                <?php if ($this->getCanReadPrice() !== false) : ?>
                <th><?php echo __('Price'); ?></th>
                <th><?php echo __('Price Type'); ?></th>
                <?php endif; ?>
                <th><?php echo __('SKU'); ?></th>
                <th><?php echo __('Allowed File Extensions'); ?></th>
                <th><?php echo __('Maximum Image Size'); ?></th>
            </tr>
            </thead>
            <tr>
                <?php if ($this->getCanReadPrice() !== false) : ?>
                <td class="opt-price">
                    <input name="product[options][${option_id}][price]" data-store-label="${price}"
                           class="input-text validate-zero-or-greater" type="text" value="${price}"
                        <?php if ($this->getCanEditPrice() === false) : ?>
                           disabled="disabled"
                        <?php endif; ?>>
                </td>
                <td class="opt-price-type"><?php echo $this->getPriceTypeSelectHtml() ?>{{html checkboxScopePrice}}</td>
                <?php else : ?>
                <input name="product[options][${option_id}][price]" type="hidden">
                <input id="product_option_${option_id}_price_type" name="product[options][${option_id}][price_type]" type="hidden">
                <?php endif; ?>
                <td>
                    <input name="product[options][${option_id}][sku]" class="input-text" type="text" value="${sku}">
                </td>
                <td>
                    <input name="product[options][${option_id}][file_extension]" class="input-text" type="text" value="${file_extension}">
                </td>
                <td class="col-file"><?php echo __('%1 <span>x</span> %2 <span>px.</span>',
                    '<input class="input-text" type="text" name="product[options][${option_id}][image_size_x]" value="${image_size_x}">',
                    '<input class="input-text" type="text" name="product[options][${option_id}][image_size_y]" value="${image_size_y}">') ?>
                    <div class="note"><?php echo __('Please leave blank if it is not an image.') ?></div>
                </td>
            </tr>
        </table>
    </div>
</script>
