<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php if ($this->canDisplayGiftmessageForm()): ?>
<div id="gift_options_giftmessage" class="giftcard-form giftcard-send-form fieldset">
    <div class="field">
        <label for="current_item_giftmessage_sender"><?php echo __('From'); ?></label>
        <div class="control">
            <input type="text" class="input-text" name="current_item_giftmessage_sender" id="current_item_giftmessage_sender" />
        </div>
    </div>
    <div class="field">
        <label for="current_item_giftmessage_recipient"><?php echo __('To'); ?></label>
        <div class="control">
            <input type="text" class="input-text" name="current_item_giftmessage_recipient" id="current_item_giftmessage_recipient" />
        </div>
    </div>
    <div class="field">
        <label for="current_item_giftmessage_message"><?php echo __('Message'); ?></label>
        <div class="control">
            <textarea class="textarea" cols="15" rows="2" name="current_item_giftmessage_message" id="current_item_giftmessage_message"></textarea>
        </div>
    </div>
</div>
<?php endif; ?>
