<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\DesignEditor\Block\Adminhtml\Theme\Selector\SelectorList\Available */?>

<div class="infinite_scroll">
    <ul class="themes" id="available-themes-container"></ul>
</div>

<script>
require([
    'jquery',
    'Magento_DesignEditor/js/infinitescroll'
], function($){

        $( document ).ready(function( ) {
            <?php if ($block->getTabId()): ?>
                $('.infinite_scroll').infinite_scroll({
                    url : '<?php echo $block->getUrl('*/*/loadthemelist') ?>',
                    loadDataOnCreate : false
                });

                $('a[name="<?php echo $block->getTabId() ?>"]').on("click", function(event) {
                    $('.infinite_scroll').infinite_scroll('loadDataIsContainerEmpty');
                });
            <?php endif; ?>
        });

});
</script>
