<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\DesignEditor\Block\Adminhtml\Theme\Selector\SelectorList\Available */ ?>
<?php echo join("\n", $block->getListItems()) ?>

<script>
require([
	'jquery',
	'Magento_DesignEditor/js/infinitescroll'
], function(jQuery){

    jQuery('.infinite_scroll').infinite_scroll({url :'<?php echo $block->getNextPageUrl() ?>'});

});
</script>
