    <?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Price\Group */
$element = $block->getElement();
$_htmlId = $block->getElement()->getHtmlId();
$_htmlClass = $block->getElement()->getClass();
$_htmlName = $block->getElement()->getName();
$_readonly = $block->getElement()->getReadonly();
$_priceValueValidation = $block->getPriceValidation('validate-zero-or-greater');

$_showWebsite = $block->isMultiWebsites();
?>
<div class="field" id="attribute-<?php echo $_htmlId?>-container" data-attribute-code="<?php echo $_htmlId?>"
     data-apply-to="<?php echo $block->escapeHtml(
         $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(
             $element->hasEntityAttribute() ? $element->getEntityAttribute()->getApplyTo() : []
         )
     )?>">
    <label class="label"><span><?php echo $block->getElement()->getLabel(); ?></span></label>
    <div class="control">
        <table class="admin__control-table" id="group_prices_table">
            <thead>
                <tr>
                    <th <?php if (!$_showWebsite): ?>style="display: none;"<?php endif; ?>><?php echo __('Web Site'); ?></th>
                    <th class="required"><?php echo __('Customer Group'); ?></th>
                    <th class="required"><?php echo $block->getPriceColumnHeader(__('Price')); ?></th>
                    <th class="col-delete"><?php echo __('Action'); ?></th>
                </tr>
            </thead>
            <tbody id="<?php echo $_htmlId; ?>_container"></tbody>
            <tfoot>
                <tr>
                    <td colspan="<?php if (!$_showWebsite): ?>5<?php else: ?>4<?php endif; ?>" class="col-actions-add"><?php echo $block->getAddButtonHtml(); ?></td>
                </tr>
            </tfoot>
        </table>

<script>
require([
    'mage/template',
    "prototype",
    "mage/adminhtml/form"
], function (mageTemplate) {

//<![CDATA[
var groupPriceRowTemplate = '<tr>'
    + '<td<?php if (!$_showWebsite): ?> style="display:none"<?php endif; ?>>'
    + '<select class="<?php echo $_htmlClass; ?> required-entry" name="<?php echo $_htmlName; ?>[<%- data.index %>][website_id]" id="group_price_row_<%- data.index %>_website">'
    <?php foreach ($block->getWebsites() as $_websiteId => $_info) : ?>
    + '<option value="<?php echo $_websiteId; ?>"><?php echo $block->escapeJsQuote($block->escapeHtml($_info['name'])); ?><?php if (!empty($_info['currency'])) : ?> [<?php echo $block->escapeHtml($_info['currency']); ?>]<?php endif; ?></option>'
    <?php endforeach; ?>
    + '</select></td>'
    + '<td><select class="<?php echo $_htmlClass; ?> custgroup required-entry" name="<?php echo $_htmlName; ?>[<%- data.index %>][cust_group]" id="group_price_row_<%- data.index %>_cust_group">'
    <?php foreach ($block->getCustomerGroups() as $_groupId => $_groupName): ?>
    + '<option value="<?php echo $_groupId; ?>"><?php echo $block->escapeJsQuote($block->escapeHtml($_groupName)); ?></option>'
    <?php endforeach; ?>
    + '</select></td>'
    + '<td><input class="<?php echo $_htmlClass; ?> required-entry <?php echo $_priceValueValidation; ?>" type="text" name="<?php echo $_htmlName; ?>[<%- data.index %>][price]" value="<%- data.price %>" id="group_price_row_<%- data.index %>_price" /></td>'
    + '<td class="col-delete"><input type="hidden" name="<?php echo $_htmlName; ?>[<%- data.index %>][delete]" class="delete" value="" id="group_price_row_<%- data.index %>_delete" />'
    + '<button title="<?php echo __('Delete Group Price'); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="group_price_row_<%- data.index %>_delete_button" onclick="return groupPriceControl.deleteItem(event);">'
    + '<span><?php echo __('Delete'); ?></span></button></td>'
    + '</tr>';

var groupPriceControl = {
    template: mageTemplate(groupPriceRowTemplate),
    itemsCount: 0,
    addItem : function () {
        <?php if ($_readonly): ?>
        if (arguments.length < 3) {
            return;
        }
        <?php endif; ?>
        var data = {
            website_id: '<?php echo $block->getDefaultWebsite(); ?>',
            group: '<?php echo $block->getDefaultCustomerGroup(); ?>',
            price: '',
            readOnly: false,
            index: this.itemsCount++
        };

        if(arguments.length >= 3) {
            data.website_id = arguments[0];
            data.group = arguments[1];
            data.price = arguments[2];
        }
        if (arguments.length == 4) {
            data.readOnly = arguments[3];
        }

        Element.insert($('<?php echo $_htmlId; ?>_container'), {
            bottom : this.template({
                data: data
            })
        });

        $('group_price_row_' + data.index + '_cust_group').value = data.group;
        $('group_price_row_' + data.index + '_website').value    = data.website_id;

        <?php if ($block->isShowWebsiteColumn() && !$block->isAllowChangeWebsite()): ?>
        var websiteElement = $('group_price_row_' + data.index + '_website');
        var websiteCaption = websiteElement.options[websiteElement.selectedIndex].text;

        websiteElement.insert({after:'<span class="website-name">' + websiteCaption + '</span>'});
        websiteElement.hide();
        <?php endif;?>

        if (data.readOnly == '1') {
            ['website', 'cust_group', 'price', 'delete'].each(function(element_suffix) {
                $('group_price_row_' + data.index + '_' + element_suffix).disabled = true;
            });
            $('group_price_row_' + data.index + '_delete_button').hide();
        }

        <?php if ($_readonly): ?>
        $('<?php echo $_htmlId; ?>_container').select('input', 'select').each(this.disableElement);
        $('<?php echo $_htmlId; ?>_container').up('table').select('button').each(this.disableElement);
        <?php else: ?>
        $('<?php echo $_htmlId; ?>_container').select('input', 'select').each(function(element) {
            Event.observe(element, 'change', element.setHasChanges.bind(element));
        });
        <?php endif; ?>
    },
    disableElement: function(element) {
        element.disabled = true;
        element.addClassName('disabled');
    },
    deleteItem: function(event) {
        var tr = Event.findElement(event, 'tr');
        if (tr) {
            Element.select(tr, '.delete').each(function(element) {
                element.value='1';
            });
            Element.select(tr, ['input', 'select']).each(function(element) {
                element.hide();
            });
            Element.hide(tr);
            Element.addClassName(tr, 'no-display template');
        }
        return false;
    }
};
<?php foreach ($block->getValues() as $_item) : ?>
groupPriceControl.addItem('<?php echo $_item['website_id']; ?>', '<?php echo $_item['cust_group']; ?>', '<?php echo $_item['price']; ?>', <?php echo (int)!empty($_item['readonly']); ?>);
<?php endforeach; ?>
<?php if ($_readonly) : ?>
$('<?php echo $_htmlId; ?>_container').up('table').select('button')
    .each(groupPriceControl.disableElement);
<?php endif; ?>
//]]>

window.groupPriceControl = groupPriceControl;
});
</script>
    </div>
</div>
