<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_order = $this->getOrder() ?>
<div class="actions-toolbar">
    <a href="<?php echo $this->getPrintAllInvoicesUrl($_order) ?>"
       target="_blank"
       class="action print">
        <span><?php echo __('Print All Invoices') ?></span>
    </a>
</div>
<?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>
<div class="order-title">
    <strong><?php echo __('Invoice #') ?><?php echo $_invoice->getIncrementId(); ?></strong>
    <a href="<?php echo $this->getPrintInvoiceUrl($_invoice) ?>"
       onclick="this.target='_blank'"
       class="action print">
        <span><?php echo __('Print Invoice') ?></span>
    </a>
</div>
<div class="table-wrapper table-order-items invoice">
    <table class="data table table-order-items invoice" id="my-invoice-table-<?php echo $_invoice->getId(); ?>">
        <caption class="table-caption"><?php echo __('Items Invoiced') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?php echo __('Product Name') ?></th>
                <th class="col sku"><?php echo __('SKU') ?></th>
                <th class="col price"><?php echo __('Price') ?></th>
                <th class="col qty"><?php echo __('Qty Invoiced') ?></th>
                <th class="col subtotal"><?php echo __('Subtotal') ?></th>
            </tr>
        </thead>
        <?php $_items = $_invoice->getAllItems(); ?>
        <?php $_count = count($_items) ?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getOrderItem()->getParentItem()) {
    continue;
} ?>
        <tbody>
            <?php echo $this->getItemHtml($_item) ?>
        </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?php echo $this->getInvoiceTotalsHtml($_invoice)?>
        </tfoot>
    </table>
</div>
<?php echo $this->getInvoiceCommentsHtml($_invoice)?>
<?php endforeach; ?>
