<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\AttributeValues */
?>
<div data-bind="scope: '<?= $block->getComponentName()?>'">
    <h2 class="steps-wizard-title"><?= __('Attribute Values') ?></h2>
    <div class="steps-wizard-info">
        <span><?= __('Choose options from each attribute to create unique products.') ?></span>
    </div>
    <div data-bind="foreach: attributes, sortableList: attributes" class="steps-wizard-section">

        <div class="attribute-entity">
            <div class="attribute-entity-top">
                <div class="attribute-entity-title-block">
                    <span class="attribute-draggable" data-role="draggable" title="<?= __('Sort Variations') ?>"></span>
                    <div class="attribute-entity-title" data-bind="text: label"></div>

                    <div class="attribute-options-block">
                        <span class="attribute-length" data-bind="text: $data.options().length"></span>
                        <?= __('Options') ?>
                    </div>
                </div>

                <div class="attribute-entity-actions">
                    <button type="button" class="action-select-all action-tertiary" data-bind="click: $parent.selectAllAttributes">
                        <span><?= __('Select All') ?></span>
                    </button>
                    <button class="action-remove"
                            type="button"
                            data-bind="click: $parent.removeAttribute.bind($parent)">
                        <span><?= __('Remove Attribute') ?></span>

                    </button>
                    <button type="button"
                            class="action-toggle"
                            data-bind="click: $parent.toggleOpened, css: {'_expanded': opened}">
                        <span></span>
                    </button>
                </div>
            </div>

            <fieldset class="admin__fieldset admin__fieldset-options" data-bind="visible: opened">
                <ul class="attribute-options" data-bind="foreach: options">
                    <li class="attribute-option">
                        <div class="admin__field admin__field-option">
                            <input
                                type="checkbox"
                                class="admin__control-checkbox"
                                data-bind="checkedValue: value, checked: !value || $parent.chosenOptions" />
                            <label data-bind="text: label, visible: label" class="admin__field-label"></label>
                        </div>

                        <div class="admin__field">
                            <div class="admin__field-control">
                                <input class="admin__control-text"
                                       data-bind="value: label, visible: !label"
                                       type="text" />
                            </div>
                        </div>

                        <a href="#" data-bind="visible: !label, click: $parents[1].saveOption.bind($parent)">-></a>
                        <a href="#" data-bind="visible: !label, click: $parents[1].removeOption.bind($parent)">X</a>
                    </li>
                </ul>
                <a data-action="addOption" href="#" data-bind="click: $parent.createOption">
                    <?= __('Create New Value') ?>
                </a>
            </fieldset>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= $block->getComponentName()?>": {
                        "component": "Magento_ConfigurableProduct/js/variations/steps/attributes_values",
                        "appendTo": "<?= $block->getParentComponentName()?>",
                        "options_url": "<?= $block->getUrl('catalog/product_attribute/getAttributes')?>"
                    }
                }
            }
        }
    }
</script>
