<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\Step1 */
?>
TBD [attributes values step]
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/lib/steps/step1": {
                "content": "<?= $block->getJsonData()?>"
            }
        }
    }
</script>
