<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\SelectAttributes */
?>
<div class="select-attributes-block <?php echo /* @noEscape */ $block->getData('config/dataScope') ?>" data-role="select-attributes-step">
    <div class="select-attributes-actions" data-type="skipKO">
        <?php echo /* @noEscape */  $block->getAddNewAttributeButton() ?>
    </div>
    <h2 class="steps-wizard-title"><?php echo $block->escapeHtml(
            __('Step 1: Select Attributes')
        ); ?></h2>
    <div class="selected-attributes" data-bind="scope: '<?php echo /* @noEscape */  $block->getComponentName() ?>'">
        <?php echo $block->escapeHtml(
            __('Selected Attributes:')
        ); ?>
        <span data-bind="text: selectedAttributes() || '--'"></span>
    </div>
</div>
<?php echo $block->getChildHtml() ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?php echo /* @noEscape */  $block->getComponentName() ?>": {
                        "component": "Magento_ConfigurableProduct/js/variations/steps/select_attributes",
                        "multiselectName": "<?php echo /* @noEscape */ $block->getData('config/multiselectName') ?>",
                        "providerName": "<?php echo /* @noEscape */ $block->getData('config/providerName') ?>",
                        "appendTo": "<?php echo /* @noEscape */  $block->getParentComponentName() ?>"
                    }
                }
            }
        }
    }
</script>
<script>
    require(['jquery'], function ($) {
        $('.<?php echo /* @noEscape */ $block->getData('config/dataScope') ?>[data-role=select-attributes-step]').applyBindings();
        $('body').trigger('contentUpdated');
    })
</script>
