<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\Summary */
?>
<div data-bind="scope: '<?= $block->getComponentName()?>'">
    <h1 class="modal-title" style="padding-bottom: 10px"><?= __('Summary') ?></h1>
    <div style="padding-bottom: 10px">
        <span><?= __('Here are all the products you are going to create. ') ?></span>
    </div>

    <table style="border: 3px solid white;">
        <thead>
            <tr>
                <!-- ko foreach: attributesName -->
                <th style="
                    border: none;
                    text-transform: capitalize;
                    background-color: gray;
                    color: white;
                    padding: 13px;
                    font-size: small;
                " data-bind="text: $data"></th>
                <!-- /ko -->
            </tr>
            <tr style="height: 5px;"></tr>
        </thead>
        <tbody data-bind="foreach: grid">
            <tr data-bind="style: {backgroundColor: $index() % 2 ? 'whitesmoke' : 'white'}">
                <!-- ko foreach: $data -->
                <!-- ko if: $data && $data.preview -->
                <td style="padding: 10px;text-align: center;border-left: 2px solid grey;">
                    <img data-bind='attr: {src: $data.preview}' />
                </td>
                <!-- /ko -->
                <!-- ko ifnot: $data && $data.preview -->
                <td style="padding: 10px;text-align: center;border-left: 2px solid grey;">
                    <span data-bind='text: $data'></span>
                </td>
                <!-- /ko -->
                <!-- /ko -->
            </tr>
        </tbody>
    </table>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= $block->getComponentName()?>": {
                        "component": "Magento_ConfigurableProduct/js/variations/steps/summary",
                        "appendTo": "<?= $block->getParentComponentName()?>"
                    }
                }
            }
        }
    }
</script>
