<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @deprecated
 * @removeCandidate
 */
?>
<?php if (!$block->getQuote()->isVirtual()): ?>
    <?php echo $this->helper('Magento\GiftMessage\Helper\Message')->getInline('onepage_checkout', $block->getQuote(), $block->getDontDisplayContainer()) ?>
<?php endif; ?>
