<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\Checkout\Block\Onepage\Shipping\Method\Available */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if (!$_shippingRateGroups): ?>
    <p><?php echo __('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="items methods-shipping">
    <?php $shippingCodePrice = []; ?>
    <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
        <dt class="item-title <?php echo $code ?>"><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
        <dd class="item-content <?php echo $code ?>">
            <fieldset class="fieldset">
                <legend class="legend"><span><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></span></legend><br>
                <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                    <?php $shippingCodePrice[] = '"'.$_rate->getCode().'":'.(float)$_rate->getPrice(); ?>
                    <div class="field choice">
                       <?php if ($_rate->getErrorMessage()): ?>
                        <div class="message error"><div><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></div></div>
                       <?php else: ?>
                            <?php if ($_sole) : ?>
                            <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                            <?php else: ?>
                            <div class="control">
                                <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>
                            </div>
                            <?php endif; ?>
                            <label class="label" for="s_method_<?php echo $_rate->getCode() ?>"><span><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                            <?php echo $this->getShippingPriceHtml($_rate); ?>
                            </span>
                            </label>
                       <?php endif ?>
                    </div>
                <?php endforeach; ?>
            </fieldset>
        </dd>
    <?php endforeach; ?>
    </dl>
    <div class="no-display" data-shipping-code-price='{<?php echo implode(",",$shippingCodePrice); ?>}'></div>
<?php endif; ?>
