<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<form name="validation_form" id="validation_form" action="<?php echo $this->getAcsUrl();?>" method="post">
    <input type="hidden" name="PaReq" value="<?php echo $this->getPaReq()?>" />
    <input type="hidden" name="TermUrl" value="<?php echo $this->getTermUrl()?>" />
    <input type="hidden" name="MD" value="<?php echo $this->getMd()?>" />
</form>
<script type="text/javascript">
//<![CDATA[
window.onload = function(){
    document.getElementById('validation_form').submit();
};
//]]>
</script>
