<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:schema="http://iplocation.developer.telekom.com/schema/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" xmlns:tns="http://iplocation.developer.telekom.com/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="iplocation" targetNamespace="http://iplocation.developer.telekom.com/wsdl/">
	<wsdl:documentation>
IP Location </wsdl:documentation>
	<wsdl:types>
		<xsd:schema targetNamespace="http://iplocation.developer.telekom.com/wsdl/">
			<xsd:import namespace="http://iplocation.developer.telekom.com/schema/" schemaLocation="IPLocation.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="locateIPRequest">
		<wsdl:part name="parameters" element="schema:LocateIPRequest"/>
	</wsdl:message>
	<wsdl:message name="locateIPResponse">
		<wsdl:part name="parameters" element="schema:LocateIPResponse"/>
	</wsdl:message>
	<wsdl:portType name="IPLocationPortType">
		<wsdl:operation name="locateIP">
			<wsdl:input message="tns:locateIPRequest"/>
			<wsdl:output message="tns:locateIPResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IPLocationHttpBinding" type="tns:IPLocationPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsp:PolicyReference URI="#TransportBindingPolicy"/>
		<wsdl:operation name="locateIP">
			<soap:operation soapAction="http://iplocation.developer.telekom.com/locateIP"/>
			<wsdl:input>
				<wsp:PolicyReference URI="#STSTokenPolicy"/>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IPLocation">
		<wsdl:port name="IPLocation" binding="tns:IPLocationHttpBinding">
			<soap:address location="https://gateway.developer.telekom.com/p3gw-mod-odg-iplocation/services/IPLocation"/>
		</wsdl:port>
	</wsdl:service>
	<wsp:Policy wsu:Id="TransportBindingPolicy">
		<wsp:ExactlyOne>
			<wsp:All>
				<wsaws:UsingAddressing xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl"/>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken RequireClientCertificate="false"/>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:Layout>
							<wsp:Policy>
								<sp:Strict/>
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp/>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256/>
							</wsp:Policy>
						</sp:AlgorithmSuite>
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:Wss11/>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="STSTokenPolicy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SupportingTokens>
					<wsp:Policy>
						<sp:SamlToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssSamlV20Token11/>
							</wsp:Policy>
						</sp:SamlToken>
					</wsp:Policy>
				</sp:SupportingTokens>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
</wsdl:definitions>
