<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\PayPal\Block\Express\Form $block
 * @see \Magento\PayPal\Block\Express\Form
 */
$code = $block->escapeHtml($block->getBillingAgreementCode());
?>
<fieldset class="fieldset paypal items redirect" id="payment_form_<?php /* @noEscape */ echo $block->getMethodCode(); ?>" style="display:none;">
    <div><?php echo $block->escapeHtml($block->getRedirectMessage()); ?></div>
    <?php  ?>
    <?php if ($code): ?>
        <input type="checkbox" id="<?php /* @noEscape */ echo $code; ?>" value="1" name="payment[<?php /* @noEscape */ echo $code; ?>]" class="checkbox">
        <label for="<?php /* @noEscape */ echo $code; ?>" class="label">
            <span><?php echo $block->escapeHtml(__('Sign a billing agreement to streamline further purchases with PayPal.')); ?></span>
        </label>
    <?php endif; ?>
</fieldset>
