<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PayPal\Block\Express\Form $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @see \Magento\PayPal\Block\Express\Form
 */
$code = $escaper->escapeHtml($block->getBillingAgreementCode());
?>
<fieldset class="fieldset paypal items redirect" id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>">
    <div><?= $escaper->escapeHtml($block->getRedirectMessage()) ?></div>
    <?php  ?>
    <?php if ($code): ?>
        <input type="checkbox" id="<?= /* @noEscape */ $code ?>" value="1" class="checkbox"
               name="payment[<?= /* @noEscape */ $code ?>]">
        <label for="<?= /* @noEscape */ $code ?>" class="label">
            <span>
                <?= $escaper->escapeHtml(__('Sign a billing agreement to streamline further purchases  with PayPal.')) ?>
            </span>
        </label>
    <?php endif; ?>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    'fieldset#payment_form_' . $escaper->escapeHtml($block->getMethodCode())
) ?>
