<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Directories tree template
 *
 * @see \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Tree
 */
?>

<div class="categories-side-col">
    <button data-folder="create" class="action-folder-create" title="<?php echo __('Create Folder'); ?>">
        <span><?php echo __('Create Folder'); ?></span>
    </button>
    <button data-folder="delete" class="action-delete">
        <span><?php echo __('Delete Folder'); ?></span>
    </button>
    <p></p>
    <div class="tree-actions">
        <a href="#" id="tree_action_collapse"><?php echo __('Collapse All'); ?></a>
        <span class="separator">|</span>
        <a href="#" id="tree_action_expand"><?php echo __('Expand All'); ?></a>
    </div>
</div>

<div id="tree" style="width:100%; overflow:auto;"></div>

<script type="text/javascript">
require([
    'jquery',
    'Magento_DesignEditor/js/tools-files'
], function(jQuery){

Ext.onReady(function(){
    var Tree = Ext.tree;
    var tree = new Tree.TreePanel('tree', {
        animate:true,
        loader: new Tree.TreeLoader({
            dataUrl:'<?php echo $this->getTreeLoaderUrl() ?>'
        }),
        enableDD:false,
        containerScroll: true
    });

    // set the root node
    var root = new Tree.AsyncTreeNode({
        text: '<?php echo $this->getRootNodeName() ?>',
        draggable:false,
        id:'root'
    });
    tree.setRootNode(root);

    // render the tree
    tree.render();
    root.expand();

    Event.observe($('tree_action_collapse'), 'click', function(){
        tree.collapseAll();
    });

    Event.observe($('tree_action_expand'), 'click', function(){
        tree.expandAll();
    });

    MediabrowserInstance.setTree(tree);
    tree.addListener('click', MediabrowserInstance.selectFolder.bind(MediabrowserInstance));
    tree.expandPath('<?php echo $this->getTreeCurrentPath() ?>','', function(success, node) {
        MediabrowserInstance.selectFolder(node);
    });
});

    (function ($) {
        $('[data-folder="create"]').on('click', function() {
            MediabrowserInstance.newFolder();
        });
    })(jQuery);

});
</script>
