<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\UrlRewrite\Block\Edit;

/** @var Escaper $escaper */
/** @var Edit $block */
?>
<?= $block->getChildHtml() ?>
<?php if ($block->getChildBlock('form')) : ?>
<script type="text/x-magento-init">
    {
        "#edit_form": {
            "Magento_UrlRewrite/js/url-rewrite-validation" : {
                "url": "<?= $escaper->escapeUrl($block->getValidationUrl()) ?>"
            }
        }
    }
</script>
<?php endif; ?>
