<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\UrlRewrite\Block\Edit $block */
?>
<?php echo $block->getChildHtml() ?>
<?php if ($block->getChildBlock('form')): ?>
<script>
require([
    'jquery',
    'mage/backend/form',
    'mage/backend/validation'
], function($){
    $('#edit_form').form()
        .validation({validationUrl: '<?php echo $block->escapeUrl($block->getValidationUrl()) ?>'});
});
</script>
<?php endif; ?>
