<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\UrlRewrite\Block\Selector;

/** @var Escaper $escaper */
/** @var Selector $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>
<div class="form-inline">
    <fieldset class="admin__fieldset fieldset" data-container-for="entity-type-selector">
        <div class="admin__field field field-entity-type-selector">
            <label for="entity-type-selector" class="admin__field-label label">
                <span><?= $escaper->escapeHtml($block->getSelectorLabel()) ?></span>
            </label>
            <div class="admin__field-control control">
                <select data-role="entity-type-selector" class="admin__control-select select" id="entity-type-selector">
                <?php foreach ($block->getModes() as $mode => $label): ?>
                    <option <?= /* @noEscape */ $block->isMode($mode) ? 'selected="selected" ' : '' ?>
                        value="<?= $escaper->escapeUrl($block->getModeUrl($mode)) ?>"><?= $escaper->escapeHtml($label) ?>
                    </option>
                <?php endforeach; ?>
                </select>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onchange',
                    'window.location = this.value;',
                    'select#entity-type-selector'
                ) ?>
            </div>
        </div>
    </fieldset>
</div>
