<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('General Information'); ?></span>
    </div>
    <div class="log-details">
        <table cellspacing="0" class="data-table">
            <tbody>
                <tr>
                    <th><?php echo __('Reference ID'); ?></th>
                    <td><?php echo $this->escapeHtml($this->getReferenceId()) ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Customer'); ?></th>
                    <td>
                        <a href="<?php echo $this->getCustomerUrl(); ?>">
                            <?php echo $this->getCustomerEmail() ?>
                        </a>
                    </td>
                </tr>
                <tr>
                    <th><?php echo __('Status'); ?></th>
                    <td><?php echo $this->getStatus() ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Created At'); ?></th>
                    <td><?php echo $this->getCreatedAt(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Updated At'); ?></th>
                    <td><?php echo $this->getUpdatedAt(); ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
