<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Checkout\Block\Item\Price\Renderer */
?>
<?php $_item = $block->getItem() ?>
<div class="price-container">
    <span class="price-label"><?= $block->escapeHtml(__('Price')) ?></span>
    <span class="price-wrapper">
        <?= $block->escapeHtml(
            $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($_item->getCalculationPrice()),
            ['span']
        ) ?>
    </span>
</div>
