<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_item = $this->getItem() ?>
<tr>
    <td class="col-product"><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td class="col-ordered-qty"><?php echo $this->getColumnHtml($_item, 'qty') ?></td>
    <td class="col-qty <?php if ($this->isShipmentRegular()): ?>last<?php endif; ?>">
        <?php if ($this->canShipPartiallyItem()): ?>
            <input type="text" class="input-text qty-item" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty()*1 ?>" />
        <?php else: ?>
            <?php echo $_item->getQty()*1 ?>
        <?php endif; ?>
    </td>
    <?php if (!$this->canShipPartiallyItem()): ?>
    <td class="col-ship last">
        <input type="hidden" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="0" />
        <input type="checkbox" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty()*1 ?>" checked />
    </td>
    <?php endif; ?>
</tr>
