<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php echo $block->getChildHtml('grid') ?>

<div class="switcher f-left" style="margin: 10px 10px 10px 0px; padding:15px;">
<?php
    echo __('Customers that have wish list: %1%', $block->getCustomerWithWishlist())
?>
</div>

<div class="switcher" style="float: right; margin: 10px 0px 10px 10px; padding:15px;">
    <?php
        echo __('Number of wish lists: %1', $block->getWishlistsCount())
    ?><br />
    <?php
        echo __('Number of items bought from a wish list: %1', $block->getItemsBought())
    ?><br />
    <?php echo __('Number of times wish lists have been shared (emailed): %1', $block->getSharedCount())
    ?><br />
    <?php echo __('Number of wish list referrals: %1', $block->getReferralsCount())
    ?><br />
    <?php echo __('Number of wish list conversions: %1', $block->getConversionsCount())
    ?><br />
</div>
