<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<script>
require([
    "prototype",
    "Magento_Catalog/catalog/product/composite/configure"
], function(){

//<!--
wishlistControl = {
    reload: function (urlParams) {
        if (!urlParams) {
            urlParams = '';
        }
        var url = <?php echo $block->getJsObjectName() ?>.url + '?ajax=true' + urlParams;
        new Ajax.Updater(
            <?php echo $block->getJsObjectName() ?>.containerId,
            url,
            {
                parameters: {form_key: FORM_KEY},
                onComplete: <?php echo $block->getJsObjectName() ?>.initGrid.bind(<?php echo $block->getJsObjectName() ?>),
                evalScripts:true
            }
        );
    },

    configureItem: function (itemId) {
        productConfigure.setOnLoadIFrameCallback('wishlist', this.cbOnLoadIframe.bind(this));
        productConfigure.showItemConfiguration('wishlist', itemId);
        return false;
    },

    cbOnLoadIframe: function (response) {
        if (!response.ok) {
            return;
        }
        this.reload();
    },

    removeItem: function (itemId) {
        if(!confirm('<?php echo __('Are you sure you want to remove this item?') ?>')) {
            return false;
        }
        this.reload('&delete=' + itemId);
        return false;
    }
}

productConfigure.addListType(
    'wishlist',
    {
        urlFetch: '<?php echo $block->getUrl('customer/wishlist_product_composite_wishlist/configure') ?>',
        urlConfirm: '<?php echo $block->getUrl('customer/wishlist_product_composite_wishlist/update') ?>'
    }
);
//-->

});
</script>
