<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var SecureHtmlRenderer $secureRenderer */

$scriptString = <<<script

    require([
            "Magento_Ui/js/modal/confirm",
            "prototype",
            "Magento_Catalog/catalog/product/composite/configure"
        ], function(confirm){

//<!--
            wishlistControl = {
                reload: function (urlParams) {
                    if (!urlParams) {
                        urlParams = '';
                    }
                    var url = {$escaper->escapeJs($block->getJsObjectName())}.url + '?ajax=true' + urlParams;
                    new Ajax.Updater(
                        {$escaper->escapeJs($block->getJsObjectName())}.containerId,
                        url,
                        {
                            parameters: {form_key: FORM_KEY},
                            onComplete: {$escaper->escapeJs($block->getJsObjectName())}.initGrid
                            .bind({$escaper->escapeJs($block->getJsObjectName())}),
                        evalScripts:true
                }
            );
        },

        configureItem: function (itemId) {
        productConfigure.setOnLoadIFrameCallback('wishlist', this.cbOnLoadIframe.bind(this));
        productConfigure.showItemConfiguration('wishlist', itemId);
        return false;
    },

    cbOnLoadIframe: function (response) {
        if (!response.ok) {
            return;
        }
        this.reload();
    },

    removeItem: function (itemId) {
        var self = this;

        confirm({
            content: '{$escaper->escapeJs(__('Are you sure you want to remove this item?'))}',
            actions: {
                confirm: function () {
                    self.reload('&delete=' + itemId);
                }
            }
        });
    }
    }

    productConfigure.addListType(
        'wishlist',
        {
            urlFetch: '{$escaper->escapeJs($block->getUrl('customer/wishlist_product_composite_wishlist/configure'))}',
            urlConfirm: '{$escaper->escapeJs($block->getUrl('customer/wishlist_product_composite_wishlist/update'))}'
        }
    );
    //-->

    });

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
