<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
?>
<?= $block->getFormHtml() ?>

<?php $scriptString = <<<script
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#{$escaper->escapeJs($block->getFormId())}').mage('form').mage('validation');

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
