<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?= $block->getFormHtml() ?>

<?php $scriptString = <<<script
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#{$block->escapeJs($block->getFormId())}').mage('form').mage('validation');

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
