<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="row">
    <div class="add-video-button-container">
        <button
            id="add_video_button"
            title="<?php echo /* @escapeNotVerified */ $addVideoTitle ?>"
            type="button"
            class="action-secondary"
            onclick="jQuery('#new-video').modal('openModal'); jQuery('#new_video_form')[0].reset();"
            data-ui-id="widget-button-1">
            <span><?php echo /* @escapeNotVerified */ __('Add Video') ?></span>
        </button>
    </div>
</div>
<div id="<?php echo /* @escapeNotVerified */ $htmlId ?>-container"
     class="images"
     data-mage-init='{"baseImage":{}}'
     data-max-file-size="<?php echo /* @escapeNotVerified */ $fileMaxSize ?>"
    >
    <div class="image image-placeholder">
        <input type="file" name="image" data-url="<?php echo /* @escapeNotVerified */ $uploadUrl ?>" multiple="multiple" />
        <img class="spacer" src="<?php echo /* @escapeNotVerified */ $spacerImage ?>"/>
        <p class="image-placeholder-text"><?php echo /* @escapeNotVerified */ $imagePlaceholderText ?></p>
    </div>
    <script id="<?php echo /* @escapeNotVerified */ $htmlId ?>-template"
            data-template="image"
            type="text/x-magento-template">
        <div class="image">
            <img class="spacer" src="<?php echo /* @escapeNotVerified */ $spacerImage ?>"/>
            <img
                class="product-image"
                src="<%- data.url %>"
                data-position="<%- data.position %>"
                alt="<%- data.label %>" />
            <div class="actions">
                <button
                    type="button"
                    class="action-delete"
                    data-role="delete-button"
                    title="<?php echo /* @escapeNotVerified */ $deleteImageText ?>">
                    <span><?php echo /* @escapeNotVerified */ $deleteImageText ?></span>
                </button>
                <button
                    type="button"
                    class="action-make-base"
                    data-role="make-base-button"
                    title="<?php echo /* @escapeNotVerified */ $makeBaseText ?>">
                    <span><?php echo /* @escapeNotVerified */ $makeBaseText ?></span>
                </button>
                <div class="draggable-handle"></div>
            </div>
            <div class="image-label"></div>
            <div class="image-fade"><span><?php echo /* @escapeNotVerified */ $hiddenText ?></span></div>
        </div>
    </script>
</div>
<span class="action-manage-images" data-activate-tab="image-management">
    <span><?php echo /* @escapeNotVerified */ $imageManagementText ?></span>
</span>
<script>
    require([
        'jquery'
    ],function($){

        'use strict';

        $('[data-activate-tab=image-management]')
            .on('click.toggleImageManagementTab', function() {
                $('#product_info_tabs_image-management').trigger('click');
            });
    });
</script>
