<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php $_childHtml = trim($this->getChildHtml('', false)); ?>
<?php if ($_childHtml): ?>
<?php $_item = $this->getItem() ?>
<tr>
    <td colspan="10" class="last">
        <a class="action-link" href="#" id="gift_options_link_<?php echo $_item->getId() ?>"><?php echo __('Gift Options') ?></a>
        <script type="text/javascript">
require([
	"Magento_Sales/order/giftoptions_tooltip"
], function(){

	giftOptionsTooltip.addTargetLink('gift_options_link_<?php echo $_item->getId() ?>', <?php echo $_item->getId() ?>);

});
</script>
        <div id="gift_options_data_<?php echo $_item->getId() ?>">
            <?php echo $_childHtml ?>
        </div>
    </td>
</tr>
<?php endif ?>
