<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php if ($block->canDisplayGiftmessage()) : ?>
<div id="gift-message-form-data-<?= (int) $block->getItem()->getId() ?>" class="no-display">
    <form id="<?= $escaper->escapeHtmlAttr($block->getFieldId('form')) ?>"
          action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>">
        <input type="hidden"
               id="<?= $escaper->escapeHtmlAttr($block->getFieldId('type')) ?>"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('type')) ?>"
               value="order_item" />
        <input type="hidden"
               id="<?= $escaper->escapeHtmlAttr($block->getFieldId('sender')) ?>"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('sender')) ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getSender()) ?>" />
        <input type="hidden"
               id="<?= $escaper->escapeHtmlAttr($block->getFieldId('recipient')) ?>"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('recipient')) ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getRecipient()) ?>" />
        <input type="hidden"
               id="<?= $escaper->escapeHtmlAttr($block->getFieldId('message')) ?>"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('message')) ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getMessageText()) ?>" />
    </form>

    <?php if ($block->getMessageText()) : ?>
    <div class="gift-options-tooltip-content">
        <div><strong><?= $escaper->escapeHtml(__('Gift Message')) ?></strong>: </div>
        <div><?= /* @noEscape */ $block->getMessageText() ?></div>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
