<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Customer\Block\Widget\Taxvat;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Taxvat $block */
?>
<div class="field taxvat<?= $block->isRequired() ? ' required' : ''; ?>">
    <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"><span><?= $escaper->escapeHtml($block->getStoreLabel('taxvat')) ?></span></label>
    <div class="control">
        <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>" name="<?= $escaper->escapeHtmlAttr($block->getFieldName('taxvat')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getTaxvat()) ?>" title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('taxvat')) ?>" <?= $block->isRequired() ? ' data-validate="{required:true}"' : '' ?>>
    </div>
</div>
