<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Customer\Block\Widget\Telephone;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Telephone $block */
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $escaper->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <input type="tel"
               name="telephone"
               id="telephone"
               value="<?= $escaper->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $escaper->escapeHtmlAttr(
                   $block->getAttributeValidationClass('telephone')
               ) ?>"
        >
    </div>
</div>
