<?php
/**
 * Copyright 2017 Adobe
 * All Rights Reserved.
 */

/** @var \Magento\Customer\Block\Widget\Telephone $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span><?= $escaper->escapeHtml(__('Phone Number')) ?></span>
    </label>
    <div class="control">
        <input type="tel"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('telephone')) ?>"
               id="<?= $escaper->escapeHtmlAttr($block->getFieldId('telephone')) ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $escaper->escapeHtmlAttr(
                   $block->getAttributeValidationClass('telephone')
               ) ?>"
        >
    </div>
</div>
