<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\AuthorizenetAcceptjs\Block\Payment $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_AuthorizenetAcceptjs/js/payment-form": {
                "config": <?= /* @noEscape */ $block->getPaymentConfig() ?>,
                "formSelector": "#payment_form_<?= $block->escapeJs($block->escapeHtml($block->getMethodCode())) ?>"
            }
        }
    }
</script>