<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\AuthorizenetAcceptjs\Block\Payment $block */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php $scriptString = <<<script
    //<![CDATA[
    require(
        [
            'Magento_AuthorizenetAcceptjs/js/authorizenet',
            'jquery',
            'domReady!'
        ], function(AuthorizenetAcceptjs, $) {
script;
$scriptString .= 'var config = ' . /* @noEscape */ $block->getPaymentConfig() . ',
    form = $(\'#payment_form_' . /* @noEscape */ $block->escapeJs($block->escapeHtml($block->getMethodCode())) . '\');';
$scriptString .= <<<script

            config.active = form.length > 0 && !form.is(':hidden');
            new AuthorizenetAcceptjs(config);
        });
    //]]>
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
