<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
    <div class="block-title <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>-title"><strong><?php /* @escapeNotVerified */ echo $block->getBlockTitle(); ?></strong></div>
    <div class="block-content <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>-content">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
