<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */
?>
<div class="block <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>">
    <div class="block-title <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>-title">
        <strong><?= $escaper->escapeHtml($block->getBlockTitle()) ?></strong>
    </div>
    <div class="block-content <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>-content">
        <?= $block->getChildHtml() ?>
    </div>
</div>
