<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="bugs">
    <span><?= $block->escapeHtml(__('Help Us Keep Magento Healthy')) ?></span>
    <a href="http://www.magentocommerce.com/bug-tracking"
       target="_blank" title="<?= $block->escapeHtmlAttr(__('Report All Bugs')) ?>">
        <?= $block->escapeHtml(__('Report All Bugs')) ?>
    </a>
</small>
