<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="block <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>">
    <div class="title <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>-title"
         data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>", "selectorsToggleClass": "active"}}'>
        <strong>
            <?= $escaper->escapeHtml(__($block->getBlockTitle())) ?>
        </strong>
    </div>
    <div class="content <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>-content"
         id="<?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>">
        <?= $block->getChildHtml() ?>
    </div>
</div>
