<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Theme\Block\Html\Header $this
 */
?>
<?php switch ($this->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome"><?php echo $this->getWelcome() ?></li>
    <?php break; ?>

    <?php case 'other': ?>
        <?php echo $this->getChildHtml(); ?>
    <?php break; ?>

<?php endswitch; ?>
