<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Rss\EmailLink $block */
?>
<?php if ($block->getLink()) : ?>
<p style="font-size:12px; line-height:16px; margin:0 0 16px;">
    <?= $escaper->escapeHtml(__("RSS link to %1's wishlist", $this->helper(\Magento\Wishlist\Helper\Data::class)->getCustomerName())) ?>
    <br />
    <a href="<?= $escaper->escapeUrl($block->getLink()) ?>"><?= $escaper->escapeUrl($block->getLink()) ?></a>
</p>
<?php endif; ?>
