<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Rss\EmailLink $block */
?>
<?php if ($block->getLink()): ?>
<p style="font-size:12px; line-height:16px; margin:0 0 16px;">
    <?php echo __("RSS link to %1's wishlist", $block->escapeHtml($this->helper(\Magento\Wishlist\Helper\Data::class)->getCustomerName())) ?>
    <br />
    <a href="<?php echo $block->escapeUrl($block->getLink()) ?>"><?php echo $block->escapeUrl($block->getLink()) ?></a>
</p>
<?php endif; ?>
