<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/** @var \Magento\Wishlist\Block\Rss\Link $block */
?>
<?php if ($block->isRssAllowed() && $block->getLink() && $this->helper(\Magento\Wishlist\Helper\Data::class)->getWishlist()->getItemsCount()) : ?>
    <a href="<?= $block->escapeUrl($block->getLink()) ?>" class="action rss wishlist">
        <span><?= $block->escapeHtml(__('RSS Feed')) ?></span>
    </a>
<?php endif; ?>
