<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Rss\Link $block */
?>
<?php if ($block->isRssAllowed() && $block->getLink() && $this->helper('Magento\Wishlist\Helper\Data')->getWishlist()->getItemsCount()): ?>
    <a href="<?= $block->escapeUrl($block->getLink()) ?>" class="action rss wishlist">
        <span><?= $block->escapeHtml(__('RSS Feed')) ?></span>
    </a>
<?php endif; ?>
