<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php $parentItem = $block->getItem() ?>
<?php $items = $block->getChilds($parentItem) ?>
<?php $_index = 0 ?>
<?php $_order = $block->getItem()->getOrder(); ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->getIsMessagesAvailable('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php if ($_item->getOrderItem()->getParentItem()): ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr>
        <td align="left" valign="top" style="padding:3px 9px"><strong><em><?php echo $attributes['option_label'] ?></em></strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif; ?>
<?php endif; ?>
<tr id="order-item-row-<?php echo $_item->getId() ?>">
    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
    <td align="left" valign="top" style="padding:3px 9px"><strong><?php echo $block->escapeHtml($_item->getName()) ?></strong></td>
    <?php else: ?>
    <td align="left" valign="top" style="padding:3px 19px"><?php echo $block->getValueHtml($_item)?></td>
    <?php endif; ?>
    <td align="left" valign="top" style="padding:3px 9px"><?php echo $block->escapeHtml($_item->getSku()) ?></td>
    <td align="center" valign="top" style="padding:3px 9px">
        <?php if ($block->canShowPriceInfo($_item)): ?>
            <?php echo $_item->getQty()*1 ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td align="right" valign="top" style="padding:3px 9px">
        <?php if ($block->canShowPriceInfo($_item)): ?>
            <?php echo $block->getItemPrice($_item); ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>

<?php if ($_showlastRow): ?>
<tr>
    <td align="left" valign="top" style="padding:3px 9px">
        <?php if ($block->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($block->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;"><?php echo $option['value'] ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif; ?>
