<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @see \Magento\Backend\Block\Denied
 */

// phpcs:disable Magento2.Security.Superglobal
?>
<hr class="access-denied-hr"/>
<div class="access-denied-page">
    <h2 class="page-heading"><?= $escaper->escapeHtml(__('Sorry, you need permissions to view this content.')) ?></h2>
    <strong><?= $escaper->escapeHtml(__('Next steps')) ?></strong>
    <ul>
        <li><span><?= $escaper->escapeHtml(__('If you think this is an error, try signing out and signing in again.'))  ?></span></li>
        <li><span><?= $escaper->escapeHtml(__('Contact a system administrator or store owner to gain permissions.')) ?></span></li>
        <li>
            <span><?= $escaper->escapeHtml(__('Return to ')) ?>
                <?php if (isset($_SERVER['HTTP_REFERER'])) : ?>
                    <a href="<?= $escaper->escapeUrl($_SERVER['HTTP_REFERER']) ?>">
                        <?= $escaper->escapeHtml(__('previous page')) ?></a><?= $escaper->escapeHtml(__('.')) ?>
                <?php else : ?>
                    <a href="<?= $escaper->escapeHtmlAttr('javascript:history.back()') ?>">
                        <?= $escaper->escapeHtml(__('previous page')) ?></a><?= $escaper->escapeHtml(__('.')) ?>
                <?php endif ?>
            </span>
        </li>
    </ul>
</div>
