<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /* @var $this \Magento\Bundle\Block\Adminhtml\Catalog\Product\Composite\Fieldset\Options\Type\Checkbox */ ?>
<?php $_option = $this->getOption(); ?>
<?php $_selections = $_option->getSelections(); ?>
<?php $_skipSaleableCheck = $this->helper('Magento\Catalog\Helper\Product')->getSkipSaleableCheck(); ?>
<div class="field options<?php if ($_option->getRequired()) {
    echo ' required' ?>">
    <label class="label"><span><?php echo $this->escapeHtml($_option->getTitle()) ?></span></label>
    <div class="control">
        <div class="nested<?php if ($_option->getDecoratedIsLast()):?> last<?php endif;
} ?>">
        <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
            <?php echo $this->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]"
                   value="<?php echo $_selections[0]->getSelectionId() ?>"
                   price="<?php echo $this->getSelectionPrice($_selections[0]) ?>" />
        <?php else:?>
            <?php foreach ($_selections as $_selection): ?>
            <div class="field choice">
                <input
                    class="change-container-classname checkbox bundle-option-<?php echo $_option->getId() ?> <?php if ($_option->getRequired()) {
    echo 'validate-one-required-by-name' ?>"
                    id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"
                    type="checkbox"
                    name="bundle_option[<?php echo $_option->getId() ?>][]"<?php if ($this->isSelected($_selection)) {
    echo ' checked="checked"' ?><?php if (!$_selection->isSaleable() && !$_skipSaleableCheck) {
    echo ' disabled="disabled"' ?>
                    value="<?php echo $_selection->getSelectionId() ?>"
                    onclick="ProductConfigure.bundleControl.changeSelection(this)"
                    price="<?php echo $this->getSelectionPrice($_selection) ?>" />
                <label class="label"
                       for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"><span><?php echo $this->getSelectionQtyTitlePrice($_selection) ?></span></label>
                    <?php if ($_option->getRequired()): ?>
                        <?php echo $this->setValidationContainer('bundle-option-' . $_option->getId() . '-' . $_selection->getSelectionId(), 'bundle-option-' . $_option->getId() . '-container') ?>
                    <?php endif;
}
}
} ?>
                </div>
            <?php endforeach; ?>
            <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
        <?php endif; ?>
        </div>
    </div>
</div>
