<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Ui\Block\Logger */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php if ($block->isLoggingEnabled()): ?>
    <?php $scriptString = <<<script

        window.onerror = function(msg, url, line) {
            var key = "{$block->escapeJs($block->getSessionStorageKey())}";
            var errors = {};
            if (sessionStorage.getItem(key)) {
                errors = JSON.parse(sessionStorage.getItem(key));
            }
            if (!(window.location.href in errors)) {
                errors[window.location.href] = [];
            }
            errors[window.location.href].push("error: \'" + msg + "\' " + "file: " + url + " " + "line: " + line);
            sessionStorage.setItem(key, JSON.stringify(errors));
        };
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
