<?php
/**
 * Copyright 2019 Adobe
 * All Rights Reserved.
 */
declare(strict_types=1);

namespace Magento\TestFramework\CodingStandard\Tool;

use Magento\TestFramework\CodingStandard\ToolInterface;

/**
 * PhpStan tool wrapper.
 */
class PhpStan implements ToolInterface
{
    /**
     * Rule level to be used.
     *
     * @see https://github.com/phpstan/phpstan#rule-levels
     */
    private const RULE_LEVEL = 1;

    /**
     * Memory limit required by PHPStan for full Magento project scan.
     */
    private const MEMORY_LIMIT = '4G';

    /**
     * Error formatter to be used.
     *
     * @see https://github.com/phpstan/phpstan#existing-error-formatters-to-be-used
     */
    private const ERROR_FORMAT = 'filtered';

    /**
     * Composer vendor directory assumed when app/etc/vendor_path.php has not been generated.
     */
    private const DEFAULT_VENDOR_DIR = 'vendor';

    /**
     * Path to the report file.
     *
     * @var string
     */
    private $reportFile;

    /**
     * PHPStan configuration file in neon format.
     *
     * @var string
     */
    private $confFile;

    /**
     * @param string $confFile
     * @param string $reportFile
     */
    public function __construct(string $confFile, string $reportFile)
    {
        $this->reportFile = $reportFile;
        $this->confFile = $confFile;
    }

    /**
     * @inheritdoc
     * @SuppressWarnings(PHPMD.UnusedLocalVariable)
     */
    public function canRun(): bool
    {
        // phpcs:disable Magento2.Security.InsecureFunction
        exec($this->getCommand() . ' --version', $output, $exitCode);
        return $exitCode === 0;
    }

    /**
     * @inheritdoc
     * @SuppressWarnings(PHPMD.UnusedLocalVariable)
     */
    public function run(array $whiteList): int
    {
        if (empty($whiteList)) {
            return 0;
        }

        $command = $this->getCommand() . ' analyse' .
            ' --level ' . self::RULE_LEVEL .
            ' --no-progress' .
            ' --error-format=' . self::ERROR_FORMAT .
            ' --memory-limit=' . self::MEMORY_LIMIT .
            // phpcs:ignore Magento2.Functions.DiscouragedFunction
            ' --configuration ' . escapeshellarg($this->confFile) .
            ' ' . implode(' ', $whiteList) .
            ' > ' . $this->reportFile;

        // phpcs:disable Magento2.Security.InsecureFunction
        exec($command, $output, $exitCode);

        return $exitCode;
    }

    /**
     * Get PHPStan CLI command
     *
     * @return string
     */
    private function getCommand(): string
    {
        return 'php ' . BP . '/' . $this->getVendorDir() . '/bin/phpstan';
    }

    /**
     * Get the path to the Composer vendor directory as configured for the application.
     *
     * The app/etc/vendor_path.php file is generated by magento/magento-composer-installer and is not part of
     * magento/magento2-base, so Composer's default vendor directory is assumed when the file is absent.
     *
     * @return string
     */
    private function getVendorDir(): string
    {
        // phpcs:ignore Magento2.Functions.DiscouragedFunction
        if (!is_readable(VENDOR_PATH)) {
            return self::DEFAULT_VENDOR_DIR;
        }
        // phpcs:ignore Magento2.Security.IncludeFile
        return require VENDOR_PATH;
    }
}
