<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $this \Magento\Backend\Block\Widget\Button\SplitButton */
/** @var $_helper \Magento\Core\Helper\Data */
$_helper = $this->helper('Magento\Core\Helper\Data');
?>

<div <?php echo $this->getAttributesHtml(); ?>>
    <button <?php echo $this->getButtonAttributesHtml(); ?>>
        <span><?php echo $this->escapeHtml($this->getLabel()); ?></span>
    </button>
    <?php if ($this->hasSplit()): ?>
        <button <?php echo $this->getToggleAttributesHtml() ?>>
            <span>Select</span>
        </button>

        <?php if (!$this->getDisabled()): ?>
            <ul class="dropdown-menu" <?php echo $this->getUiId("dropdown-menu"); ?>>
                <?php foreach ($this->getOptions() as $key => $option): ?>
                <li>
                    <span <?php echo $this->getOptionAttributesHtml($key, $option); ?>>
                        <?php echo $this->escapeHtml($option['label']); ?>
                    </span>
                    <?php if (isset($option['hint'])): ?>
                    <div class="tooltip" <?php echo $this->getUiId('item', $key, 'tooltip'); ?>>
                        <a href="<?php echo $this->escapeHtml($option['hint']['href']) ?>" class="help">
                            <?php echo $this->escapeHtml($option['hint']['label']) ?>
                        </a>
                    </div>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endif; ?>
</div>

<script type="text/javascript">
require(['jquery'], function($){
        $('.actions-split')
            .on('click.splitDefault', '.action-default', function() {
                $(this).siblings('.dropdown-menu').find('.item-default').trigger('click');
            });
});
</script>
