<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="message message-notice">
    <div class="message-inner">
        <div class="message-content"><?= $block->escapeHtml(__('Changing address information will not recalculate shipping, tax or other order amount.')) ?></div>
    </div>
</div>

<fieldset class="fieldset admin__fieldset-wrapper admin__fieldset">
    <legend class="legend admin__legend">
        <span><?= $block->escapeHtml($block->getHeaderText()) ?></span>
    </legend>
    <br>
    <div class="form-inline form-order-info" data-mage-init='{"Magento_Sales/order/edit/address/form":{}}'>
        <?= $block->getForm()->toHtml() ?>
    </div>
</fieldset>
