<?php
/**
 * Copyright 2015 Adobe
 * All Rights Reserved.
 */

/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */
$scriptString = '
    var LOCALE = \'' . /* @noEscape */ $block->escapeJs($localeFormatter->getLocaleJs()) .'\';
    var BASE_URL = \'' . /* @noEscape */ $block->escapeJs($block->getBaseUrl()) .'\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->escapeJs($block->getViewFileUrl('/')) . '\'
    };';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
