<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$scriptString = '
    var BASE_URL = \'' . /* @noEscape */ $block->escapeUrl($block->getBaseUrl()) .'\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->escapeUrl($block->getViewFileUrl('/')) . '\'
    };';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
