<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->getSearchTermsLog()->isPageCacheable()) : ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_CatalogSearch/js/search-terms-log": {
                "url": "<?= $escaper->escapeUrl($block->getUrl('catalogsearch/searchTermsLog/save')) ?>"
            }
        }
    }
</script>
<?php endif; ?>
