<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php if ($block->getSearchTermsLog()->isPageCacheable()): ?>
    <script type="text/x-magento-init">
    <?= /* @escapeNotVerified */ json_encode([
            '*' => [
                  'Magento_CatalogSearch/js/search_terms_log' => [
                          'url' => $block->getUrl('catalogsearch/searchTermsLog/save')
                ]
            ]
    ]); ?>
</script>
<?php endif; ?>
