<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php if ($block->getSearchTermsLog()->isPageCacheable()): ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_CatalogSearch/js/search-terms-log": {
                "url": "<?= /* @escapeNotVerified */ $block->getUrl('catalogsearch/searchTermsLog/save') ?>"
            }
        }
    }
</script>
<?php endif; ?>
