<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Model\Item $item */
?>

<?php $children = $this->getChildNames(); ?>
<?php if ($children): ?>
    <div class="<?php echo $this->getCssClass() ?>">
        <?php foreach ($children as $childName):?>
            <?php echo $this->getLayout()->renderElement($childName, false);?>
        <?php endforeach;?>
    </div>
<?php endif; ?>
