<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Comment $block  */

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
?>

<div class="field comment-box">
    <label class="label" for="product-item-comment-<?= $escaper->escapeHtmlAttr($item->getWishlistItemId()) ?>">
        <span><?= $escaper->escapeHtml(__('Comment')) ?></span>
    </label>
    <div class="control">
        <textarea id="product-item-comment-<?= $escaper->escapeHtmlAttr($item->getWishlistItemId()) ?>" placeholder="<?= /* @noEscape */ $this->helper(\Magento\Wishlist\Helper\Data::class)->defaultCommentString() ?>" name="description[<?= $escaper->escapeHtmlAttr($item->getWishlistItemId()) ?>]" title="<?= $escaper->escapeHtmlAttr(__('Comment')) ?>" class="product-item-comment" <?= $item->getProduct()->isSaleable() ? '' : 'disabled="disabled"' ?>><?= ($escaper->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
