<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Comment $block  */

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
?>

<div class="field comment-box">
    <label class="label" for="product-item-comment-<?php echo $block->escapeHtmlAttr($item->getWishlistItemId()) ?>">
        <span><?php echo $block->escapeHtml(__('Comment')) ?></span>
    </label>
    <div class="control">
        <textarea id="product-item-comment-<?php echo $block->escapeHtmlAttr($item->getWishlistItemId()) ?>" placeholder="<?php /* @noEscape */ echo $this->helper('Magento\Wishlist\Helper\Data')->defaultCommentString() ?>" name="description[<?php echo $block->escapeHtmlAttr($item->getWishlistItemId()) ?>]" title="<?php echo $block->escapeHtmlAttr(__('Comment')) ?>" class="product-item-comment"><?php echo($block->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
