<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Edit $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()) : ?>
    <a class="action edit" href="<?= $escaper->escapeUrl($block->getItemConfigureUrl($item)) ?>">
        <span><?= $escaper->escapeHtml(__('Edit')) ?></span>
    </a>
<?php endif ?>
