<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove $block */
?>

<a href="#" data-role="remove" data-post-remove='<?php /* @noEscape */ echo $block->getItemRemoveParams($block->getItem()); ?>' title="<?php echo $block->escapeHtmlAttr(__('Remove Item')) ?>" class="btn-remove action delete">
    <span><?php echo $block->escapeHtml(__('Remove item'));?></span>
</a>
