<?php
/**
 * Copyright © Magento, Inc. All rights reserved. 
 * See COPYING.txt for license details.
 */

 //@codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Ui\Block\Wrapper
 */
?>

<?php /* @escapeNotVerified */ echo $block->renderApp(
    [
        'widget_columns' => [
            'displayMode' => 'grid'
        ],
        'image' => [
            'imageCode' => 'recently_compared_products_grid_content_widget'
        ]
    ]
);
