<?php
/**
 * Copyright 2017 Adobe
 * All Rights Reserved.
 */
?>
<?php
// phpcs:disable Magento2.PHP.ShortEchoSyntax.ShortEchoTag

/** @var \Magento\Ui\Block\Wrapper $block */
?>

<?php /* @noEscape */ echo $block->renderApp(
    [
        'listing' => [
            'displayMode' => 'grid'
        ],
        'image' => [
            'imageCode' => 'recently_compared_products_images_names_widget'
        ]
    ]
);
