<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

namespace Magento\TestFramework\Isolation;

use Magento\TestFramework\Helper\Bootstrap;
use Magento\Framework\App\DeploymentConfig\Reader;

/**
 * A listener that watches for integrity of deployment configuration
 */
class DeploymentConfig
{
    /**
     * Deployment configuration reader
     *
     * @var Reader
     */
    private $reader;

    /**
     * Initial value of deployment configuration
     *
     * @var mixed
     */
    private $config;

    /**
     * Memorizes the initial value of configuration reader and the configuration value
     *
     * Assumption: this is done once right before executing very first test suite.
     * It is assumed that deployment configuration is valid at this point
     *
     * @return void
     */
    public function startTestSuite()
    {
        if (null === $this->reader) {
            $this->reader = Bootstrap::getObjectManager()->get(\Magento\Framework\App\DeploymentConfig\Reader::class);
            $this->config = $this->reader->load();
        }
    }

    /**
     * Checks if deployment configuration has been changed by a test
     *
     * Changing deployment configuration violates isolation between tests, so further tests may become broken.
     * To fix this issue, find out why this test changes deployment configuration.
     * If this is intentional, then it must be reverted to the previous state within the test.
     * After that, the application needs to be wiped out and reinstalled.
     *
     * @param \PHPUnit\Framework\TestCase $test
     * @return void
     */
    public function endTest(\PHPUnit\Framework\TestCase $test)
    {
        $config = $this->reader->load();
        
        // Normalize configs by removing keys that are legitimately regenerated during tests
        $normalizedInitial = $this->normalizeConfig($this->config);
        $normalizedCurrent = $this->normalizeConfig($config);
        
        if ($normalizedInitial != $normalizedCurrent) {
            $error = "\n\nERROR: deployment configuration is corrupted. The application state is no longer valid.\n"
                . 'Further tests may fail.'
                . " This test failure may be misleading, if you are re-running it on a corrupted application.\n"
                . $test->toString() . "\n";
            $test->fail($error);
        }
    }
    
    /**
     * Normalize configuration by removing keys that are expected to change during test execution
     *
     * These keys are regenerated by the test framework during installation/reset
     * and don't indicate test isolation problems:
     * - install/date: Installation timestamp
     * - crypt/key: Encryption key regenerated during installation
     * - cache/graphql/id_salt: GraphQL cache salt regenerated
     * - downloadable_domains: Domains added by tests in setUp() and removed in tearDown()
     *
     * @param array $config
     * @return array
     */
    private function normalizeConfig(array $config): array
    {
        // Remove install date (always changes during test runs)
        if (isset($config['install']['date'])) {
            unset($config['install']['date']);
        }
        
        // Remove crypt key (regenerated during installation)
        if (isset($config['crypt']['key'])) {
            unset($config['crypt']['key']);
        }
        
        // Remove GraphQL cache salt (regenerated during installation)
        if (isset($config['cache']['graphql']['id_salt'])) {
            unset($config['cache']['graphql']['id_salt']);
        }
        
        // Remove downloadable domains (added in setUp, removed in tearDown)
        // The check runs between setUp and tearDown, so we need to ignore these
        if (isset($config['downloadable_domains'])) {
            unset($config['downloadable_domains']);
        }
        
        // Remove cache_types (modified during GraphQL resolver cache tests)
        // Tests properly save/restore this config, but the check runs mid-test
        if (isset($config['cache_types'])) {
            unset($config['cache_types']);
        }
        
        return $config;
    }
}
