<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Weee\Block\Item\Price\Renderer;
use Magento\Weee\Helper\Data;

/** @var Escaper $escaper */
/** @var Renderer $block */

// phpcs:disable Magento2.Templates.ThisInTemplate

$_weeeHelper = $this->helper(Data::class);
$_item = $block->getItem();
?>
<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()) : ?>
    <?php $_rowTotalWithoutDiscount = $block->getRowDisplayPriceExclTax() - $_item->getTotalDiscountAmount(); ?>
    <?php if ($block->displayBothPrices()) : ?>
        <span class="label"><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
    <?php endif; ?>
    <?= /* @noEscape */ $block->formatPrice(max(0, $_rowTotalWithoutDiscount)) ?>


    <?php if ($this->helper(Data::class)->getApplied($_item)) : ?>
        <br />
        <?php if ($block->displayPriceWithWeeeDetails()) : ?>
            <small>
                <?php foreach ($this->helper(Data::class)->getApplied($_item) as $tax) : ?>
                    <span class="nobr"><?= $escaper->escapeHtml($tax['title']) ?>: <?= /* @noEscape */ $block->formatPrice($tax['row_amount'], true, true) ?></span><br />
                <?php endforeach; ?>
            </small>
        <?php endif; ?>

        <?php if ($block->displayFinalPrice()) : ?>
            <br />
            <span class="nobr"><?= $escaper->escapeHtml(__('Total')) ?>:<br />
                <?= /* @noEscape */ $block->formatPrice($block->getFinalRowDisplayPriceExclTax() - $_item->getTotalDiscountAmount()) ?>
            </span>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>


<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()) : ?>
    <?php if ($block->displayBothPrices()) : ?>
        <br /><span class="label"><?= $escaper->escapeHtml(__('Incl. Tax')) ?>:</span>
    <?php endif; ?>
    <?php $_incl = $block->getTotalAmount($_item); ?>
    <?= /* @noEscape */ $block->formatPrice(max(0, $_incl)) ?>
    <?php if ($this->helper(Data::class)->getApplied($_item)) : ?>
        <br />
        <?php if ($block->displayPriceWithWeeeDetails()) : ?>
            <small>
                <?php foreach ($this->helper(Data::class)->getApplied($_item) as $tax) : ?>
                    <span class="nobr"><?= $escaper->escapeHtml($tax['title']) ?>: <?= /* @noEscape */ $block->formatPrice($tax['row_amount_incl_tax'], true, true) ?></span><br />
                <?php endforeach; ?>
            </small>
        <?php endif; ?>

        <?php if ($block->displayFinalPrice()) : ?>
            <span class="nobr"><?= $escaper->escapeHtml(__('Total Incl. Tax')) ?>:<br />
                <?= /* @noEscape */ $block->formatPrice($block->getFinalRowDisplayPriceInclTax() - $_item->getTotalDiscountAmount()) ?>
            </span>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
