<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $this \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($this->getRecentlyViewedProducts() && $this->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'list';

    $type = $type . '-' . $mode;

    $imageBlock =  $this->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    $image = 'recently_viewed_products_list_content_widget';
    $title = __('Recently Viewed');
    $items = $this->getRecentlyViewedProducts();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
}
?>

<?php if ($exist):?>
    <div class="block widget block-viewed-products-<?php echo $mode; ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php echo $title; ?></strong>
        </div>
        <div class="block-content">
            <?php echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                <ol class="product-items <?php echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?php echo $this->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $imageBlock->init($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $this->escapeHtml($_item->getName()) ?>"
                                       href="<?php echo $this->getProductUrl($_item) ?>" class="product-item-link">
                                        <?php echo $this->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php echo $this->getProductPriceHtml(
                                    $_item,
                                    \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                                    \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                                    [
                                        'price_id_suffix' => '-' . $type
                                    ]
                                ) ?>
                                <?php if ($rating): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_item, $rating) ?>
                                <?php endif; ?>
                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?php echo $this->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php echo __('Add to Cart') ?>">
                                                            <span><?php echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Core\Helper\PostData');
                                                            $postData = $postDataHelper->getPostData($this->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php echo $postData; ?>'
                                                                type="button" title="<?php echo __('Add to Cart') ?>">
                                                            <span><?php echo __('Add to Cart') ?></span>
                                                        </button>
                                                        <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       data-post='<?php echo $this->getAddToWishlistParams($_item); ?>'
                                                       title="<?php echo __('Add to Wishlist') ?>">
                                                        <span><?php echo __('Add to Wishlist') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($this->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php  $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
                                                       title="<?php echo __('Add to Compare') ?>">
                                                        <span><?php echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($description):?>
                                    <div class="product-item-description">
                                        <?php echo $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                        <a title="<?php echo $this->escapeHtml($_item->getName()) ?>"
                                           href="<?php echo $this->getProductUrl($_item) ?>"
                                           class="action more"><?php echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $this->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
