<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?php echo __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
    <strong class="logo">
        <img src="<?php echo $block->getLogoSrc() ?>" alt="<?php echo $block->getLogoAlt() ?>" />
    </strong>
<?php else:?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php echo $storeName ?>">
        <img src="<?php echo $block->getLogoSrc() ?>" alt="<?php echo $storeName ?>" />
    </a>
<?php endif?>
