<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
    $logoAlt = $block->getLogoAlt();
    $logoSrc = $block->getLogoSrc();
    $logoSizes = $block->getLogoSizes();
?>

<span data-action="toggle-nav" class="action nav-toggle"><span><?php echo __('Toggle Nav') ?></span></span>

<?php if ($block->isHomePage()):?>
    <strong class="logo">
<?else:?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php echo $logoAlt; ?>">
<?php endif;?>

    <img src="<?php echo $logoSrc ?>"
         width="<?php echo $logoSizes['width']; ?>"
         height="<?php echo $logoSizes['height']; ?>"
         alt="<?php echo $logoAlt; ?>" />

<?php if ($block->isHomePage()):?>
    </strong>
<?else:?>
    </a>
<?endif;?>
