<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Magento\Paypal\Block\Payflow\Link\Iframe
 */
?>
<html>
<head>
</head>
<body>
<form id="token_form" method="POST" action="<?php echo $block->getTransactionUrl() ?>">
    <input type="hidden" name="SECURETOKEN" value="<?php echo $block->getSecureToken(); ?>"/>
    <input type="hidden" name="SECURETOKENID" value="<?php echo $block->getSecureTokenId(); ?>"/>
    <input type="hidden" name="MODE" value="<?php echo $block->isTestMode() ? 'TEST' : 'LIVE'; ?>"/>
</form>
<script>
    document.getElementById('token_form').submit();
</script>
</body>
</html>
