<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Payflow\Link\Iframe $block
 */
?>
<div id="iframe-warning" class="message notice">
    <div><?php echo $block->escapeHtml(__('Please do not refresh the page until you complete payment.')); ?></div>
</div>
<iframe id="hss-iframe" data-container="paypal-iframe" class="paypal iframe" scrolling="no" frameborder="0" border="0"
        src="<?php echo $block->escapeUrl($block->getFrameActionUrl()); ?>" height="610" width="100%"></iframe>
