<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */



/**
 * @var \Magento\Paypal\Block\Payflow\Link\Info $block
 * @see \Magento\Paypal\Block\Payflow\Link\Info
 */
?>
<div id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
     style="display:none" class="hss items">
    <?php echo $block->escapeHtml(__(
        'You will be required to enter your payment details after you place an order.'
    )); ?>
</div>
