<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @see \Magento\Paypal\Block\Iframe
 */
?>
<html>
<head>
</head>
<body>
<script>
    (function() {
        'use strict';

        var cartUrl = '<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart') ?>',
            successUrl = '<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/onepage/success') ?>',
            goToSuccessPage = '<?php /* @escapeNotVerified */ echo $block->getGotoSuccessPage() ?>',
            require = window.top.require,
            windowContext = window,
            errorMessage = {
                message: '<?php /* @escapeNotVerified */ echo $block->getErrorMsg() ?>'
            };

        require([
            'underscore',
            'Magento_Paypal/js/model/iframe-redirect'
        ], function(_, iframeRedirect) {
            _.bind(iframeRedirect, windowContext)(cartUrl, errorMessage, goToSuccessPage, successUrl);
        })
    })();
</script>
</body>
</html>
