<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\CatalogInventory\Block\Qtyincrements;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Qtyincrements $block */
?>
<?php if ($block->getProductQtyIncrements()) : ?>
    <div class="product pricing">
        <?= $escaper->escapeHtml(__('%1 is available to buy in increments of %2', $block->getProductName(), $block->getProductQtyIncrements())) ?>
    </div>
<?php endif ?>
