<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\CatalogInventory\Block\Qtyincrements
 */
?>
<?php if ($block->getProductQtyIncrements()) : ?>
    <div class="product pricing">
        <?php /* @escapeNotVerified */ echo __('%1 is available to buy in increments of %2', $block->getProductName(), $block->getProductQtyIncrements()) ?>
    </div>
<?php endif ?>
