<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<!DOCTYPE html>
<!--[if IE 9]>
<html class="ie9" lang="en">
<![endif]--><!--[if !IE]><!-->
<html lang="en" ng-app="magentoSetup">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Magento Upgrade</title>
    <link href="./styles/css/upgrade.css" rel="stylesheet" type="text/css">
    <link
        rel="icon"
        type="image/x-icon"
        href="./images/favicons/favicon.ico"
        sizes="16x16">
    <link
        rel="icon"
        type="image/png"
        href="./images/favicons/favicon-96x96.png"
        sizes="96x96">
    <link
        rel="icon"
        type="image/png"
        href="./images/favicons/favicon-32x32.png"
        sizes="32x32">
    <link
        rel="icon"
        type="image/png"
        href="./images/favicons/favicon-16x16.png"
        sizes="16x16">
</head>
<body>
