<?php
/**
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Magento\UrlRewrite\Controller\Adminhtml\Url\Rewrite;

use Magento\Backend\App\Action\Context;
use Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator;
use Magento\CatalogUrlRewrite\Model\Products\AppendUrlRewritesToProducts;
use Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator;
use Magento\CmsUrlRewrite\Model\CmsPageUrlPathGenerator;
use Magento\Framework\App\Action\HttpPostActionInterface as HttpPostActionInterface;
use Magento\Framework\Exception\LocalizedException;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;

/**
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class Save extends \Magento\UrlRewrite\Controller\Adminhtml\Url\Rewrite implements HttpPostActionInterface
{
    /**
     * @var \Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator
     */
    protected $productUrlPathGenerator;

    /**
     * @var \Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator
     */
    protected $categoryUrlPathGenerator;

    /**
     * @var \Magento\CmsUrlRewrite\Model\CmsPageUrlPathGenerator
     */
    protected $cmsPageUrlPathGenerator;

    /**
     * @var \Magento\UrlRewrite\Model\UrlFinderInterface
     */
    protected $urlFinder;

    /**
     * @var AppendUrlRewritesToProducts
     */
    protected AppendUrlRewritesToProducts $productAppendRewrites;

    /**
     * @var array
     */
    protected array $missingRewrites = [];

    /**
     * @param Context $context
     * @param ProductUrlPathGenerator $productUrlPathGenerator
     * @param CategoryUrlPathGenerator $categoryUrlPathGenerator
     * @param CmsPageUrlPathGenerator $cmsPageUrlPathGenerator
     * @param UrlFinderInterface $urlFinder
     * @param AppendUrlRewritesToProducts|null $productAppendRewrites
     */
    public function __construct(
        \Magento\Backend\App\Action\Context                       $context,
        \Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator  $productUrlPathGenerator,
        \Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator $categoryUrlPathGenerator,
        \Magento\CmsUrlRewrite\Model\CmsPageUrlPathGenerator      $cmsPageUrlPathGenerator,
        UrlFinderInterface                                        $urlFinder,
        ?AppendUrlRewritesToProducts                              $productAppendRewrites = null
    ) {
        parent::__construct($context);
        $this->productUrlPathGenerator = $productUrlPathGenerator;
        $this->categoryUrlPathGenerator = $categoryUrlPathGenerator;
        $this->cmsPageUrlPathGenerator = $cmsPageUrlPathGenerator;
        $this->urlFinder = $urlFinder;
        $this->productAppendRewrites = $productAppendRewrites ?:
            \Magento\Framework\App\ObjectManager::getInstance()->create(AppendUrlRewritesToProducts::class);
    }

    /**
     * Override urlrewrite data, basing on current category and product
     *
     * @param \Magento\UrlRewrite\Model\UrlRewrite $model
     * @return void
     * @throws LocalizedException
     */
    protected function _handleCatalogUrlRewrite($model)
    {
        $productId = $this->_getProduct()->getId();
        $categoryId = $this->_getCategory()->getId();
        if ($productId || $categoryId) {
            if ($model->isObjectNew()) {
                $model->setEntityType($productId ? self::ENTITY_TYPE_PRODUCT : self::ENTITY_TYPE_CATEGORY)
                    ->setEntityId($productId ?: $categoryId);
                if ($productId && $categoryId) {
                    $model->setMetadata(['category_id' => $categoryId]);
                }
            }
            $model->setTargetPath($this->generateTargetPath($model));
        }
    }

    /**
     * Generate Target Path
     *
     * @param \Magento\UrlRewrite\Model\UrlRewrite $model
     * @throws LocalizedException
     */
    protected function generateTargetPath($model): ?string
    {
        $targetPath = $this->getCanonicalTargetPath();
        if ($model->getRedirectType() && !$model->getIsAutogenerated()) {
            if ($rewrite = $this->urlFinder->findOneByData([
                UrlRewrite::ENTITY_ID => $model->getEntityId(),
                UrlRewrite::TARGET_PATH => $targetPath,
                UrlRewrite::ENTITY_TYPE => $model->getEntityType(),
                UrlRewrite::STORE_ID => $model->getStoreId()
            ])) {
                $targetPath = $rewrite->getRequestPath();
            } else {
                $this->checkEntityAssociations($model);
                if ($model->getEntityType() === self::ENTITY_TYPE_PRODUCT) {
                    $productRewrites = $this->productAppendRewrites->getProductUrlRewrites(
                        $this->_getProduct(),
                        [$this->getRequest()->getParam('store_id', 0)]
                    );
                    $productRewrites = array_merge(...$productRewrites);
                    $targetPath = $this->getAdjustedTargetPath($model, $productRewrites, $targetPath);
                    $this->setMissingRewrites($model, $productRewrites);
                }
            }
        }

        return $targetPath;
    }

    /**
     * Checks for missing product rewrites
     *
     * @param \Magento\UrlRewrite\Model\UrlRewrite $model
     * @param array $rewrites
     * @return void
     */
    private function setMissingRewrites(\Magento\UrlRewrite\Model\UrlRewrite $model, array $rewrites): void
    {
        if (!empty($rewrites)) {
            foreach ($rewrites as $rewrite) {
                if ($rewrite->getRequestPath() != $model->getRequestPath()) {
                    $this->missingRewrites[] = $this->generateRewriteModel($rewrite);
                }
            }
        }
    }

    /**
     * Checks for potential target path adjustments
     *
     * @param \Magento\UrlRewrite\Model\UrlRewrite $model
     * @param array $productRewrites
     * @param string $canonicalTargetPath
     * @return string|null
     */
    private function getAdjustedTargetPath(
        \Magento\UrlRewrite\Model\UrlRewrite $model,
        array                                $productRewrites,
        string                               $canonicalTargetPath
    ): ?string {
        if (empty($productRewrites)) {
            return null;
        }

        foreach ($productRewrites as $rewrite) {
            if ($rewrite->getRequestPath() != $model->getRequestPath()) {
                $this->missingRewrites[] = $this->generateRewriteModel($rewrite);
                if ($rewrite->getTargetPath() == $canonicalTargetPath) {
                    return $rewrite->getRequestPath();
                }
            }
        }

        return $canonicalTargetPath;
    }

    /**
     * Generates rewrite model
     *
     * @param UrlRewrite $rewrite
     * @return \Magento\UrlRewrite\Model\UrlRewrite
     */
    private function generateRewriteModel(UrlRewrite $rewrite): \Magento\UrlRewrite\Model\UrlRewrite
    {
        $rewriteModel = $this->_objectManager->create(\Magento\UrlRewrite\Model\UrlRewrite::class);
        $rewriteModel->setEntityType(self::ENTITY_TYPE_PRODUCT)
            ->setRequestPath($rewrite->getRequestPath())
            ->setTargetPath($rewrite->getTargetPath())
            ->setRedirectType($rewrite->getRedirectType())
            ->setStoreId($rewrite->getStoreId())
            ->setDescription($rewrite->getDescription())
            ->setMetadata($rewrite->getMetadata());

        return $rewriteModel;
    }

    /**
     * Checks if rewrite can be created for product or category
     *
     * @param \Magento\UrlRewrite\Model\UrlRewrite $model
     * @return void
     * @throws LocalizedException
     */
    private function checkEntityAssociations(\Magento\UrlRewrite\Model\UrlRewrite $model): void
    {
        $check = $model->getEntityType() === self::ENTITY_TYPE_PRODUCT ?
            $this->_getProduct()->canBeShowInCategory($this->_getCategory()->getId()) &&
            in_array($model->getStoreId(), $this->_getProduct()->getStoreIds()) :
            $this->_getCategory()->getStoreId() == $model->getStoreId();
        if (false === $check) {
            throw new LocalizedException(
                $model->getEntityType() === self::ENTITY_TYPE_PRODUCT
                    ? __("The selected product isn't associated with the selected store or category.")
                    : __("The selected category isn't associated with the selected store.")
            );
        }
    }

    /**
     * Generate canonical product / category path
     *
     * @return string
     */
    protected function getCanonicalTargetPath()
    {
        $product = $this->_getProduct()->getId() ? $this->_getProduct() : null;
        $category = $this->_getCategory()->getId() ? $this->_getCategory() : null;
        return $product
            ? $this->productUrlPathGenerator->getCanonicalUrlPath($product, $category)
            : $this->categoryUrlPathGenerator->getCanonicalUrlPath($category);
    }

    /**
     * Override URL rewrite data, basing on current CMS page
     *
     * @param \Magento\UrlRewrite\Model\UrlRewrite $model
     * @return void
     */
    private function _handleCmsPageUrlRewrite($model)
    {
        $cmsPage = $this->_getCmsPage();
        if ($cmsPage->getId()) {
            if ($model->isObjectNew()) {
                $model->setEntityType(self::ENTITY_TYPE_CMS_PAGE)->setEntityId($cmsPage->getId());
            }
            if ($model->getRedirectType() && !$model->getIsAutogenerated()) {
                $targetPath = $this->cmsPageUrlPathGenerator->getUrlPath($cmsPage);
            } else {
                $targetPath = $this->cmsPageUrlPathGenerator->getCanonicalUrlPath($cmsPage);
            }
            $model->setTargetPath($targetPath);
        }
    }

    /**
     * Process save URL rewrite request
     *
     * @return void
     */
    public function execute()
    {
        $data = $this->getRequest()->getPostValue();
        if ($data) {
            /** @var $session \Magento\Backend\Model\Session */
            $session = $this->_objectManager->get(\Magento\Backend\Model\Session::class);
            try {
                $model = $this->_getUrlRewrite();

                $requestPath = $this->getRequest()->getParam('request_path');
                $this->_objectManager->get(
                    \Magento\UrlRewrite\Helper\UrlRewrite::class
                )->validateRequestPath($requestPath);

                $model->setEntityType($this->getRequest()->getParam('entity_type') ?: self::ENTITY_TYPE_CUSTOM)
                    ->setRequestPath($requestPath)
                    ->setTargetPath($this->getRequest()->getParam('target_path', $model->getTargetPath()))
                    ->setRedirectType($this->getRequest()->getParam('redirect_type'))
                    ->setStoreId($this->getRequest()->getParam('store_id', 0))
                    ->setDescription($this->getRequest()->getParam('description'));

                $this->_handleCmsPageUrlRewrite($model);
                $this->_handleCatalogUrlRewrite($model);
                $model->save();
                if (!empty($this->missingRewrites)) {
                    foreach ($this->missingRewrites as $missingRewrite) {
                        $missingRewrite->save();
                    }
                }

                $this->messageManager->addSuccess(__('The URL Rewrite has been saved.'));
                $this->_redirect('adminhtml/*/');
                return;
            } catch (LocalizedException $e) {
                $this->messageManager->addError($e->getMessage());
                $session->setUrlRewriteData($data);
            } catch (\Exception $e) {
                $this->messageManager->addException(
                    $e,
                    __('An error occurred while saving the URL rewrite. Please try to save again.')
                );
                $session->setUrlRewriteData($data);
            }
        }
        $this->getResponse()->setRedirect($this->_redirect->getRedirectUrl($this->getUrl('*')));
    }
}
