<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Magento\Payment\Block\Info
 * @var \Magento\Payment\Block\Info $block
 */
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $escaper->escapeHtml($paymentTitle) ?>{{pdf_row_separator}}

<?php if ($specificInfo = $block->getSpecificInformation()) : ?>
    <?php foreach ($specificInfo as $label => $value) : ?>
        <?= $escaper->escapeHtml($label) ?>:
        <?= $escaper->escapeHtml(implode(' ', $block->getValueAsArray($value))) ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif;?>

<?= $escaper->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())) ?>
