<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */
// @deprecated
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div data-mage-init='{"floatingHeader": {}}' class="page-actions">
    <button type="button" id="addNewClass">
        <?= $block->escapeHtml(__('Add New Class')) ?>
    </button>
    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onclick',
        "window.location.href='" . $block->escapeJs($createUrl) . "'",
        'button#addNewClass'
    ) ?>
</div>
