<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-mage-init='{"floatingHeader": {}}' class="page-actions">
    <?php echo $this->getBackButtonHtml() ?>
    <?php echo $this->getResetButtonHtml() ?>
    <?php echo $this->getSaveButtonHtml() ?>
</div>
<?php if ($form): ?>
<?php echo $form->toHtml(); ?>
<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#<?php echo $form->getForm()->getId() ?>').mage('form').mage('validation');

});
</script>
<?php endif; ?>
