<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
$_item = $block->getItem();
$product = $_item->getProduct();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image')
?>
<li class="item product product-item">
    <div class="product">
        <?php if ($block->hasProductUrl()): ?>
            <a href="<?php echo $block->getProductUrl()?>"
               title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php echo $imageBlock->init($block->getProductForThumbnail(), 'mini_cart_product_thumbnail')->toHtml() ?>
            </a>
        <?php else: ?>
            <span class="product-item-photo">
                <?php echo $imageBlock->init($block->getProductForThumbnail(), 'mini_cart_product_thumbnail')->toHtml() ?>
            </span>
        <?php endif; ?>

        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?php echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>

            <?php if ($_options = $block->getOptionList()):?>
                <div class="product options" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
                    <span data-role="title" class="more toggle"><?php echo __('View Details') ?></span>

                    <div data-role="content" class="product options details content">
                        <strong class="subtitle"><?php echo __('Options Details'); ?></strong>
                        <dl class="product options list">
                            <?php foreach ($_options as $_option) : ?>
                            <dt class="label"><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd class="values">
                                <?php if (is_array($_option['value'])): ?>
                                <?php echo nl2br(implode("\n", $_option['value'])) ?>
                                <?php else: ?>
                                <?php echo $_option['value'] ?>
                                <?php endif; ?>
                            </dd>
                            <?php endforeach; ?>
                        </dl>
                    </div>
                </div>
            <?php endif; ?>

            <?php // Prices ?>
            <div class="product-item-pricing">
                <?php if ($canApplyMsrp): ?>

                    <div class="details-map">
                        <span class="label"><?php echo __('Price'); ?></span>
                        <span class="value"><?php echo __('See price before order confirmation.'); ?></span>
                    </div>

                <?php else: ?>
                    <?php echo $block->getSidebarItemPriceHtml($_item); ?>
                <?php endif; //Can apply MSRP ?>

                <div class="details-qty qty">
                    <span class="label"><?php echo __('Qty'); ?></span>
                    <input id="cart-item-<?php echo $_item->getId() ?>-qty"
                           value="<?php echo $block->getQty() ?>"
                           type="number"
                           size="4"
                           class="item-qty cart-item-qty"
                           data-cart-item="<?php echo $_item->getId() ?>"
                           data-item-qty="<?php echo $block->getQty() ?>"
                           maxlength="12"/>
                    <button id="update-cart-item-<?php echo $_item->getId() ?>"
                            class="update-cart-item"
                            data-cart-item="<?php echo $_item->getId() ?>"
                            title="<?php echo $block->escapeHtml(__('Update')); ?>"
                            style="display: none">
                        <span><?php echo __('Update'); ?></span>
                    </button>
                </div>
            </div>

            <div class="product actions">
                <?php if ($product->isVisibleInSiteVisibility()):?>
                <div class="primary">
                    <a href="<?php echo $block->getConfigureUrl() ?>"
                       title="<?php echo $block->escapeHtml(__('Edit item')); ?>"
                       class="action edit">
                       <span><?php echo __('Edit')?></span>
                   </a>
                </div>
                <?php endif ?>
                <div class="secondary">
                    <a href="#"
                       data-cart-item="<?php echo $_item->getId() ?>"
                       title="<?php echo $block->escapeHtml(__('Remove item')); ?>"
                       class="action delete">
                        <span><?php echo __('Remove')?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</li>
