<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="gift-message" data-bind="scope:'giftMessage'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#gift-message": {
                "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.giftMessageConfig = <?php echo $block->getGiftMessageConfigJson(); ?>;
    </script>
</div>
