<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 /** @var \Magento\CatalogSearch\Helper\Data $helper */
$helper = $this->helper('Magento\CatalogSearch\Helper\Data');
?>
<div class="nested">
    <a class="action advanced" href="<?php echo /* @escapeNotVerified */ $helper->getAdvancedSearchUrl() ?>" data-action="advanced-search">
        <?php echo /* @escapeNotVerified */ __('Advanced Search') ?>
    </a>
</div>
