<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * New Customer block template
 *
 * @var $this \Magento\Customer\Block\Form\Login
 */
?>
<?php if ($this->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php echo __('New Customers') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?php echo __('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php echo $this->getCreateAccountUrl() ?>" class="action create primary"><span><?php echo __('Register') ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
