<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>

<?php if ($_item = $block->getItem()) : ?>
    <div class="product-title"><?= $escaper->escapeHtml($_item->getName()) ?></div>
    <div class="product-sku-block">
        <span><?= $escaper->escapeHtml(__('SKU')) ?>:</span>
        <?= /* @noEscape */ implode('<br />', $this->helper(Magento\Catalog\Helper\Data::class)->splitSku($block->getSku())) ?>
    </div>
    <?php if ($block->getOrderOptions()) : ?>
        <dl class="item-options">
        <?php foreach ($block->getOrderOptions() as $_option) : ?>
            <dt><?= $escaper->escapeHtml($_option['label']) ?>:</dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']) : ?>
                <?= $escaper->escapeHtml($_option['value']) ?>
            <?php else : ?>
                <?= $escaper->escapeHtml($block->truncateString($_option['value'], 55, '', $_remainder)) ?>
                <?php if ($_remainder) :?>
                    ... <span id="<?= $escaper->escapeHtmlAttr($_id = 'id' . uniqid()) ?>"><?= $escaper->escapeHtml($_remainder) ?></span>
                    <script>
                        require(['prototype'], function(){
                            <?php $escapedId = $escaper->escapeJs($_id) ?>
                            $('<?= /* @noEscape */ $escapedId ?>').hide();
                            $('<?= /* @noEscape */ $escapedId ?>').up().observe('mouseover', function(){$('<?= /* @noEscape */ $escapedId ?>').show();});
                            $('<?= /* @noEscape */ $escapedId ?>').up().observe('mouseout',  function(){$('<?= /* @noEscape */ $escapedId ?>').hide();});
                        });
                    </script>
                <?php endif;?>
            <?php endif;?>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php if ($block->getLinks()) : ?>
        <dl class="item-options">
            <dt><?= $escaper->escapeHtml($block->getLinksTitle()) ?>:</dt>
            <?php foreach ($block->getLinks()->getPurchasedItems() as $_link) : ?>
                <dd><?= $escaper->escapeHtml($_link->getLinkTitle()) ?> (<?= $escaper->escapeHtml($_link->getNumberOfDownloadsUsed() . ' / ' . ($_link->getNumberOfDownloadsBought() ? $_link->getNumberOfDownloadsBought() : __('U'))) ?>)</dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $escaper->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
