<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($_item = $block->getItem()): ?>
    <div class="product-title"><?php echo $_item->getName() ?></div>
    <div class="product-sku-block">
        <span><?php echo __('SKU') ?>:</span>
        <?php echo implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($block->getSku()))); ?>
    </div>
    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($block->getOrderOptions() as $_option): ?>
            <dt><?php echo $_option['label'] ?>:</dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $_option['value'];?>
            <?php else: ?>
                <?php echo $block->truncateString($_option['value'], 55, '', $_remainder);?>
                <?php if ($_remainder):?>
                    ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                    <script>
require(['prototype'], function(){

    $('<?php echo $_id ?>').hide();
    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});

});
</script>
                <?php endif;?>
            <?php endif;?>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php if ($block->getLinks()): ?>
        <dl class="item-options">
            <dt><?php echo $block->getLinksTitle(); ?>:</dt>
            <?php foreach ($block->getLinks()->getPurchasedItems() as $_link): ?>
                <dd><?php echo $block->escapeHtml($_link->getLinkTitle()) ?> (<?php echo $_link->getNumberOfDownloadsUsed() . ' / ' . ($_link->getNumberOfDownloadsBought() ? $_link->getNumberOfDownloadsBought() : __('U')) ?>)</dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php echo $block->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
