<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<button class="scalable" type="button" id="<?php echo $block->getHtmlId() ?>" data-mage-init='{"elasticTestConnection":{
    "url": "<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>",
    "elementId": "<?php echo $block->getHtmlId() ?>",
    "successText": "<?php /* @escapeNotVerified */ echo __('Successful! Test again?') ?>",
    "failedText": "<?php /* @escapeNotVerified */ echo __('Connection failed! Test again?') ?>"},"validation": {}}'>
    <span><span><span id="connection_test_result_es"><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
</button>