<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Review\Block\Adminhtml\Rating\Edit\Tab\Form;

/** @var Escaper $escaper */
/** @var Form $block */
?>
<div class="messages">
    <div class="message message-notice message-in-rating-edit">
        <div><?= $escaper->escapeHtml(__('Please specify a rating title for a store, or we\'ll just use the default value.')) ?></div>
    </div>
</div>

<?= $block->getFormHtml() ?>
