<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="messages">
    <div class="message message-notice message-in-rating-edit">
        <div><?php /* @escapeNotVerified */ echo __('Please specify a rating title for a store, or we\'ll just use the default value.'); ?></div>
    </div>
</div>

<?php echo $block->getFormHtml() ?>
