<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/** @var \Magento\Review\Block\Adminhtml\Rating\Edit\Tab\Form $block */
?>
<div class="messages">
    <div class="message message-notice message-in-rating-edit">
        <div><?= $block->escapeHtml(__('Please specify a rating title for a store, or we\'ll just use the default value.')) ?></div>
    </div>
</div>

<?= $block->getFormHtml() ?>
