<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @deprecated Not used since export filter grid has been moved to Ui components.
 * @see Magento_ImportExport::view/adminhtml/ui_component/export_filter_grid.xml
 */
?>
<script>
require([
    'mage/adminhtml/grid'
], function(){
    if (window['export_filter_gridJsObject'] != undefined) {
        export_filter_gridJsObject.resetFilter = function () {
            return varienGrid.prototype.resetFilter.call(this, varienExport.modifyFilterGrid);
        };
        export_filter_gridJsObject.doFilter = function () {
            return varienGrid.prototype.doFilter.call(this, varienExport.modifyFilterGrid);
        };
    }
});
</script>
