<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Backend\Block\Template $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php $scriptString = <<<script
require([
    'mage/adminhtml/grid'
], function(){
    if (window['export_filter_gridJsObject'] != undefined) {
        export_filter_gridJsObject.resetFilter = function () {
            return varienGrid.prototype.resetFilter.call(this, varienExport.modifyFilterGrid);
        };
        export_filter_gridJsObject.doFilter = function () {
            return varienGrid.prototype.doFilter.call(this, varienExport.modifyFilterGrid);
        };
    }
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
