<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div data-mage-init='{"floatingHeader": {}}' class="page-actions">
    <?php echo $block->getBackButtonHtml(); ?>
    <?php echo $block->getResetButtonHtml(); ?>
    <?php echo $block->getSaveButtonHtml(); ?>
    <?php echo $block->getDeleteButtonHtml(); ?>
</div>
<?php if ($form): ?>
<?php echo $form->toHtml(); ?>
<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#<?php /* @escapeNotVerified */ echo $form->getForm()->getId() ?>').mage('form').mage('validation');

});
</script>
<?php endif; ?>
