<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_item = $block->getItem() ?>
<?php if ($_item): ?>
    <?php $_childHtml = trim($block->getChildHtml('', false));?>
    <?php if ($_childHtml): ?>
        <tr class="row-gift-options">
            <td colspan="7">
                <a class="action-link" href="#" id="gift_options_link_<?php echo $_item->getId() ?>"><?php echo __('Gift Options') ?></a>
                <script>
require([
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

    giftOptionsTooltip.addTargetLink('gift_options_link_<?php echo $_item->getId() ?>', <?php echo $_item->getId() ?>);

});
</script>
                <div id="gift_options_data_<?php echo $_item->getId() ?>">
                    <?php echo $_childHtml ?>
                </div>
            </td>
        </tr>
    <?php endif ?>
<?php endif ?>
