<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->canDisplayGiftMessage()): ?>
    <div class="no-display">
        <div id="gift-message-form-data-<?php /* @escapeNotVerified */ echo $block->getItem()->getId(); ?>">
            <?php echo $block->getFormHtml();?>
        </div>

        <?php if ($block->getMessageText()): ?>
        <div class="gift-options-tooltip-content">
            <div><strong><?php /* @escapeNotVerified */ echo __('Gift Message')?></strong>:</div>
            <div><?php /* @escapeNotVerified */ echo $block->getMessageText(); ?></div>
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
