<?php
/**
 * Copyright 2019 Adobe
 * All Rights Reserved.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
/**
 * @var \Magento\Paypal\Block\Express\InContext\SmartButton $block
 */
$widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getJsInitParams());
$widgetConfig = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode(
    $widget['Magento_Paypal/js/in-context/product-express-checkout']
);
?>
<div id ="paypal-smart-button" data-mage-init='{"Magento_Paypal/js/in-context/product-express-checkout"
:<?= /* @noEscape */ $widgetConfig ?>}'></div>
