<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Paypal\Block\Express\Shortcut
 */
?>
<?php
$labelPosition = '';
if ($block->isOrPositionBefore()) {
    $labelPosition = ' before';
} elseif ($block->isOrPositionAfter()) {
    $labelPosition = ' after';
}
?>
<?php $shortcutHtmlId = $block->getShortcutHtmlId() ?>
<div data-label="<?php echo $block->escapeHtml(__('or')); ?>"
     class="paypal checkout <?php /* @escapeNotVerified */ echo $labelPosition ?> paypal-logo <?php /* @escapeNotVerified */ echo $shortcutHtmlId ?>">
    <input type="image" data-action="checkout-form-submit" data-checkout-url="<?php /* @escapeNotVerified */ echo $block->getCheckoutUrl() ?>"
           src="<?php /* @escapeNotVerified */ echo $block->getImageUrl() ?>"
           alt="<?php /* @escapeNotVerified */ echo __('Checkout with PayPal'); ?>"
           title="<?php /* @escapeNotVerified */ echo __('Checkout with PayPal'); ?>"/>
    <?php if ($block->getConfirmationUrl() || $block->getIsInCatalogProduct()): ?>
        <?php
        $confirmationUrl = $block->getConfirmationUrl();
        $isInCatalogProduct = $block->getIsInCatalogProduct();
    endif; ?>
    <?php if ($block->getAdditionalLinkImage()): ?>
        <?php $linkImage = $block->getAdditionalLinkImage() ?>
        <a href="<?php /* @escapeNotVerified */ echo $linkImage['href']?>"><img src="<?php /* @escapeNotVerified */ echo $linkImage['src']?>" /></a>
    <?php endif; ?>
<script type="text/x-magento-init">
    {
        ".paypal-logo.<?php /* @escapeNotVerified */ echo $shortcutHtmlId ?>": {
            "paypalCheckout": {
                "confirmMessage": "<?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->getConfirmationMessage())?>",
                "confirmUrl": "<?php /* @escapeNotVerified */ echo !empty($confirmationUrl) ? $confirmationUrl : false ?>",
                "isCatalogProduct": "<?php /* @escapeNotVerified */ echo !empty($isInCatalogProduct) ? $isInCatalogProduct : false ?>",
                "paypalCheckoutSelector": "#pp-checkout-url",
                "shortcutContainerClass": "<?php /* @escapeNotVerified */ echo "." . $shortcutHtmlId ?>"
            }
        }
    }
</script>
</div>
