<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Page;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var Page $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>
<div id="preview" class="cms-revision-preview">
    <iframe name="preview_iframe"
            id="preview_iframe"
            frameborder="0"
            title="<?= $escaper->escapeHtmlAttr(__('Preview')) ?>"
            width="100%"
            sandbox="allow-same-origin allow-pointer-lock"
    ></iframe>
    <form id="preview_form"
          action="<?= $escaper->escapeUrl($block->getUrl('*/*/popup')) ?>"
          method="post"
          target="preview_iframe"
    >
    <input type="hidden" name="form_key" value="<?= /* @noEscape */ $block->getFormKey() ?>" />
    <?php foreach ($block->getPreviewFormViewModel()->getFormFields() as $name => $value): ?>
        <input type="hidden" name="<?= $escaper->escapeHtmlAttr($name) ?>" value="<?= $escaper->escapeHtmlAttr($value) ?>"/>
    <?php endforeach; ?>
    </form>
</div>
<?php $scriptString = <<<script
require([
    'jquery'
], function($) {
    $(document).ready(function() {
        $('#preview_form').trigger('submit');
    });

    $('#preview_iframe').on('load', function() {
        $(this).height($(this).contents().height());
    });
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
