<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="links">
<a class="action-forgotpassword" href="<?= $block->escapeUrl($this->helper(\Magento\Backend\Helper\Data::class)->getUrl('adminhtml/auth/forgotpassword', ['_nosecret' => true])) ?>"><?= $block->escapeHtml(__('Forgot your password?')) ?></a>
</div>
