<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="links">
<a class="action-forgotpassword" href="<?php echo /* @escapeNotVerified */ $this->helper('Magento\Backend\Helper\Data')->getUrl('adminhtml/auth/forgotpassword', ['_nosecret' => true]) ?>"><?php echo /* @escapeNotVerified */ __('Forgot your password?') ?></a>
</div>
