<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form method="post" action="" id="login-form" data-mage-init='{"form": {}, "validation": {}}'>
    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?php /* @escapeNotVerified */ echo __('Password Help'); ?></span></legend><br/>
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey(); ?>" />
        <p class="admin__field-info"><?php /* @escapeNotVerified */ echo __('Enter your email address.  You will receive an email with a link to reset your password.'); ?></p>
        <div class="admin__field _required field-email">
            <label for="email" class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Email address'); ?></span></label>
            <div class="admin__field-control">
                <input type="text" id="email" name="email" value="" data-validate="{required:true, 'validate-email':true}" class="admin__control-text" />
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
        <div class="form-actions">
            <div class="actions">
                <button class="action-retrieve action-primary" type="submit"><span><?php /* @escapeNotVerified */ echo __('Retrieve Password'); ?></span></button>
            </div>
            <div class="links">
                <a class="action-back" href="<?php /* @escapeNotVerified */ echo $block->getUrl('adminhtml', ['_nosecret' => true]); ?>">
                    <?php /* @escapeNotVerified */ echo __('Back to Sign in'); ?>
                </a>
            </div>
        </div>
    </fieldset>
</form>
