<?php
/**
 * Copyright 2012 Adobe
 * All Rights Reserved.
 */

/** @var \Magento\Framework\Escaper $escaper */
?>

<form method="post" data-mage-init='{"form": {}, "validation": {}}'
      action="<?= $escaper->escapeUrl(
          $block->getUrl(
              '*/auth/resetpasswordpost',
              ['_query' => ['id' => $block->getUserId(), 'token' => $block->getResetPasswordLinkToken()]]
          )
      ) ?>" id="reset-password-form" autocomplete="off">
    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?= $escaper->escapeHtml(__('Reset a Password')) ?></span></legend><br />
        <input name="form_key" type="hidden" value="<?= $escaper->escapeHtmlAttr($block->getFormKey()) ?>" />
        <div class="admin__field _required field-password">
            <label class="admin__field-label" for="password">
                <span>
                    <?= $escaper->escapeHtml(__('New Password')) ?>
                </span>
            </label>
            <div class="admin__field-control">
                <input type="password"
                       class="admin__control-text validate-admin-password admin-password-min-<?= $escaper
                           ->escapeHtmlAttr(
                               $block->getViewModel()->getMinimumPasswordLength()
                           ) ?>"
                       data-validate="{required:true}" name="password" id="password"
                       placeholder="new password" autocomplete="off" />
            </div>
        </div>
        <div class="admin__field _required field-confirmation">
            <label class="admin__field-label" for="confirmation">
                <span>
                    <?= $escaper->escapeHtml(__('Confirm New Password')) ?>
                </span>
            </label>
            <div class="admin__field-control">
                <input type="password" class="admin__control-text"
                       data-validate="{required:true, 'validate-cpassword':true}" name="confirmation" id="confirmation"
                       placeholder="confirm new password" autocomplete="off" />
            </div>
        </div>
        <div class="form-actions">
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml(__('Reset Password')) ?>"
                        class="action-reset action-primary">
                    <span><?= $escaper->escapeHtml(__('Reset Password')) ?></span>
                </button>
            </div>
            <div class="links">
                <a class="action-back"
                   href="<?= $escaper->escapeUrl(
                       $block->getUrl('adminhtml', ['_nosecret' => true])
                   ) ?>">
                    <?= $escaper->escapeHtml(__('Back to Sign in')) ?>
                </a>
            </div>
        </div>
    </fieldset>
</form>
