<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo __('Reset a Password'); ?></title>
    <link rel="icon" href="<?php echo $block->getViewFileUrl('Magento_Theme::favicon.ico'); ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $block->getViewFileUrl('Magento_Theme::favicon.ico'); ?>" type="image/x-icon" />
    <link rel="stylesheet" href="<?php echo $block->getViewFileUrl('mui/reset.css') ?>" media="all" />
    <link rel="stylesheet" href="<?php echo $block->getViewFileUrl('mui/base.css') ?>" media="all" />
    <link rel="stylesheet" href="<?php echo $block->getViewFileUrl('mui/elements.css') ?>" media="all" />
    <link rel="stylesheet" href="<?php echo $block->getViewFileUrl('mui/form.css') ?>" media="all" />
    <link rel="stylesheet" href="<?php echo $block->getViewFileUrl('css/admin.css') ?>" media="all" />
    <link rel="stylesheet" href="<?php echo $block->getViewFileUrl('css/pages.css') ?>" media="all" />
    <link rel="stylesheet" href="<?php echo $block->getViewFileUrl('mui/utils.css') ?>" media="all" />

    <script src="<?php echo $block->getViewFileUrl('prototype/prototype.js') ?>"></script>
    <script src="<?php echo $block->getViewFileUrl('scriptaculous/effects.js') ?>"></script>
    <script src="<?php echo $block->getViewFileUrl('mage/captcha.js') ?>"></script>

    <script src="<?php echo $block->getViewFileUrl('requirejs/require.js') ?>"></script>
    <script src="<?php echo $block->getViewFileUrl('jquery/jquery.js') ?>"></script>
    <script src="<?php echo $block->getViewFileUrl('mage/jquery-no-conflict.js') ?>"></script>
    <script src="<?php echo $block->getViewFileUrl('app-config.js') ?>"></script>

<body id="page-login" class="page-login page-resetpass">
    <div class="wrapper">
        <div class="wrapper-inner">
            <div class="form-inline form-login">
                <header class="header">
                    <div class="logo" title="<?php echo __('Magento Admin Panel') ?>"><span><?php echo __('Magento Admin Panel') ?></span></div>
                </header>
                <div id="messages">
                    <?php echo $block->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
                </div>
                <form method="post" action="<?php echo $block->getUrl('*/auth/resetpasswordpost', ['_query' => ['id' => $block->getUserId(), 'token' => $block->getResetPasswordLinkToken()]]); ?>" id="reset-password-form">
                    <fieldset class="fieldset">
                        <legend class="legend"><span><?php echo __('Reset a Password'); ?></span></legend><br />
                        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>" />
                        <div class="field field-password">
                            <label class="label" for="password"><span><?php echo __('New Password'); ?></span></label>
                            <div class="control">
                                <input type="password" class="input-text required-entry validate-admin-password" name="password" id="password" placeholder="new password" />
                            </div>
                        </div>
                        <div class="field field-confirmation">
                            <label class="label" for="confirmation"><span><?php echo __('Confirm New Password'); ?></span></label>
                            <div class="control">
                                <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" placeholder="confirm new password" />
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="actions">
                                <button type="submit" title="<?php echo __('Reset Password'); ?>" class="action-reset primary"><span><?php echo __('Reset Password'); ?></span></button>
                            </div>
                            <div class="links">
                                <a class="action-back" href="<?php echo $block->getUrl('adminhtml', ['_nosecret' => true]) ?>"><?php echo __('Back to Login'); ?></a>
                            </div>
                        </div>
                    </fieldset>
                </form>
                <script>
require([
    "jquery",
    "mage/backend/form",
    "mage/backend/validation"
], function(jQuery){

    jQuery('#reset-password-form').form().validation();

});
</script>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-copyright"><?php echo $block->getChildHtml('copyright');?></div>
        </div>
    </footer>
</body>
</html>
