<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_order = $this->getOrder() ?>
<div class="grid">
  <div class="hor-scroll">
    <table cellspacing="0" class="data-table">
        <thead>
            <tr class="headings">
                <th class="col-product"><span><?php echo __('Product') ?></span></th>
                <th class="col-status"><span><?php echo __('Item Status') ?></span></th>
                <th class="col-price-original"><span><?php echo __('Original Price') ?></span></th>
                <th class="col-price"><span><?php echo __('Price') ?></span></th>
                <th class="col-ordered-qty"><span><?php echo __('Qty') ?></span></th>
                <th class="col-subtotal"><span><?php echo __('Subtotal') ?></span></th>
                <th class="col-tax-amount"><span><?php echo __('Tax Amount') ?></span></th>
                <th class="col-tax-percent"><span><?php echo __('Tax Percent') ?></span></th>
                <th class="col-discont"><span><?php echo __('Discount Amount') ?></span></th>
                <th class="col-total last"><span><?php echo __('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php $i = 0; foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) {
    continue;
} else {
    $i++;
}?>
            <tbody class="<?php echo $i%2 ? 'even' : 'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>
