<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="import-export-tax-rates">
    <?php if (!$this->getIsReadonly()): ?>
    <div class="import-tax-rates">
        <?php if ($this->getUseContainer()): ?>
        <form id="import-form" action="<?php echo $this->getUrl('tax/rate/importPost') ?>" method="post" enctype="multipart/form-data">
        <?php endif; ?>
            <?php echo $this->getBlockHtml('formkey')?>
            <fieldset class="fieldset">
                <legend class="legend"><span><?php echo __('Import Tax Rates') ?></span></legend>
                <input type="file" name="import_rates_file" class="input-file required-entry"/>
                <?php echo $this->getButtonHtml('Import Tax Rates', '', 'import-submit') ?>
            </fieldset>
        <?php if ($this->getUseContainer()): ?>
        </form>
        <?php endif; ?>
        <script type="text/javascript">
require(['jquery', "mage/mage", "js/theme"], function(jQuery){

    jQuery('#import-form').mage('form').mage('validation');
    (function ($) {
        $('.import-submit').click(function(){
            if($(':input[name="import_rates_file"]').val()) {
                $('body').loadingPopup({
                    timeout: false
                });

                $(this.form).submit();
            }
        });
    })(jQuery);

});
</script>
    </div>
    <?php endif; ?>
    <div class="export-tax-rates <?php if ($this->getIsReadonly()): ?>box-left<?php else: ?>box-right<?php endif; ?>">
        <?php if ($this->getUseContainer()): ?>
        <form id="export_form" action="<?php echo $this->getUrl('tax/rate/exportPost') ?>" method="post" enctype="multipart/form-data">
        <?php endif; ?>
            <?php echo $this->getBlockHtml('formkey')?>
            <fieldset class="fieldset">
                <legend class="legend"><span><?php echo __('Export Tax Rates') ?></span></legend>
                <?php echo $this->getButtonHtml('Export Tax Rates', "this.form.submit()") ?>
            </fieldset>
        <?php if ($this->getUseContainer()): ?>
        </form>
        <?php endif; ?>
    </div>
</div>
