<?php
/**
 *
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script type="text/javascript">
require(["jquery", "js/theme", "prototype"], function(){

function checkIsConfigurableVisibility()
{
    if (!$('is_configurable') || !$('is_global') || !$('frontend_input')) return;
    if ($F('is_global')==1 && $F('frontend_input')=='select') {
        setRowVisibility('is_configurable', true);
    } else {
        setRowVisibility('is_configurable', false);
    }
}

switchDefaultValueField = switchDefaultValueField.wrap(function(original) {
    original();
    checkIsConfigurableVisibility();
});

showDefaultRows = showDefaultRows.wrap(function(original) {
    original();
    setRowVisibility('is_configurable', true);
});

if($('frontend_input')){
    Event.observe($('is_global'), 'change', checkIsConfigurableVisibility);
}

window.checkIsConfigurableVisibility = checkIsConfigurableVisibility;

});
</script>
