<?php
/**
 * Copyright 2026 Adobe
 * All Rights Reserved.
 */
declare(strict_types=1);

namespace Magento\CatalogRule\Model\Indexer;

use Magento\Catalog\Model\ProductRepository;
use Magento\Catalog\Test\Fixture\Product as ProductFixture;
use Magento\CatalogRule\Test\Fixture\Rule as CatalogRuleFixture;
use Magento\Framework\Indexer\IndexerRegistry;
use Magento\Indexer\Model\Config;
use Magento\TestFramework\Fixture\AppArea;
use Magento\TestFramework\Fixture\Config as ConfigFixture;
use Magento\TestFramework\Fixture\DataFixture;
use Magento\TestFramework\Fixture\DataFixtureStorage;
use Magento\TestFramework\Fixture\DataFixtureStorageManager;
use Magento\TestFramework\Fixture\DbIsolation;
use Magento\TestFramework\Helper\Bootstrap;

/**
 * Test for special price reindex on product save in case of catalog price scope = website
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class SpecialPriceRealtimeReindexTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var \Magento\Framework\ObjectManagerInterface
     */
    private $objectManager;

    /**
     * @var array
     */
    private $indexersState = [];

    /**
     * @var IndexerRegistry
     */
    private $indexerRegistry;

    /**
     * @var DataFixtureStorage
     */
    private $fixtures;

    /**
     * Indexers that need to be set to real-time mode for the test
     *
     * @var string[]
     */
    private $indexersNeededInRealTime = [
        'catalogrule_rule',
        'catalogrule_product',
        'catalog_product_price'
    ];

    protected function setUp(): void
    {
        $this->objectManager = Bootstrap::getObjectManager();
        $this->indexerRegistry = $this->objectManager->get(IndexerRegistry::class);
        $this->fixtures = DataFixtureStorageManager::getStorage();
        $this->setIndexScheduled();
    }

    protected function tearDown(): void
    {
        $this->restoreIndexMode();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    private function setIndexScheduled(): void
    {
        $indexerListIds = $this->objectManager->get(Config::class)->getIndexers();
        foreach ($indexerListIds as $indexerId) {
            if (in_array($indexerId['indexer_id'], $this->indexersNeededInRealTime)) {
                $indexer = $this->indexerRegistry->get($indexerId['indexer_id']);
                $this->indexersState[$indexerId['indexer_id']] = $indexer->isScheduled();
                $indexer->setScheduled(false);
            }
        }
    }

    private function restoreIndexMode(): void
    {
        foreach ($this->indexersState as $indexerId => $state) {
            $this->indexerRegistry->get($indexerId)->setScheduled($state);
        }
    }

    #[
        DbIsolation(false),
        AppArea('adminhtml'),
        ConfigFixture('catalog/price/scope', '1'),
        DataFixture(CatalogRuleFixture::class, [
            'is_active' => 1,
            'name' => 'Special Price Range 100% off',
            'website_ids' => [1],
            'customer_group_ids' => [1],
            'discount_amount' => 100,
            'conditions' => [
                [
                    'type' => \Magento\CatalogRule\Model\Rule\Condition\Product::class,
                    'attribute' => 'special_price',
                    'operator' => '>',
                    'value' => '15',
                ],
                [
                    'type' => \Magento\CatalogRule\Model\Rule\Condition\Product::class,
                    'attribute' => 'special_price',
                    'operator' => '<',
                    'value' => '50',
                ],
            ],
        ], 'cr1'),
        DataFixture(
            ProductFixture::class,
            ['sku' => 'simple', 'price'=> 100, 'special_price' => 100, 'website_ids' => [1]]
        ),
    ]
    public function testSpecialPriceChange()
    {
        try {
            /** @var ProductRepository $productRepository */
            $productRepository = $this->objectManager->create(ProductRepository::class);
            $product = $productRepository->get('simple', true);
            $product->setSpecialPrice(40); // falls into the rule range
            $product = $productRepository->save($product);
            $product->setSpecialPrice(100); // outside the rule range
            $product = $productRepository->save($product);
            $this->assertEquals(100, $product->getSpecialPrice());
        } catch (\Exception $e) {
            $this->fail('Could not save special price: ' . $e->getMessage());
            return;
        }
    }
}
