<?php
/**
 * Copyright 2015 Adobe
 * All Rights Reserved.
 */

/**
 * @var \Magento\Paypal\Block\Express\InContext\Minicart\SmartButton $block
 */
$widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getJsInitParams());
$widgetConfig = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['Magento_Paypal/js/in-context/button']);
?>
<div data-mage-init='{"Magento_Paypal/js/in-context/button":<?= /* @noEscape */ $widgetConfig ?>}'
     class="paypal checkout paypal-logo <?= $block->escapeHtml($block->getContainerId()) ?>-container">
</div>
