<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<table>
    <thead>
        <tr>
            <th><?= __('Shipped By') ?></th>
            <th><?= __('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php $i = 0; foreach ($_shipment->getAllTracks() as $_item): $i++ ?>
        <tr <?= $i%2 ? ' ' : '' ?>>
            <td><?= $block->escapeHtml($_item->getTitle()) ?></td>
            <td><?= $block->escapeHtml($_item->getNumber()) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
