<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Catalog\Block\Adminhtml\Category\Edit;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var Edit $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>
<div data-id="information-dialog-category" class="messages">
    <div class="message message-notice">
        <div><?= $escaper->escapeHtml(__('This operation can take a long time')) ?></div>
    </div>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag('display: none;', 'div[data-id="information-dialog-category"]') ?>

<script type="text/x-magento-init">
    {
        "*": {
            "categoryForm": {"refreshUrl": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getRefreshPathUrl())) ?>"}
        }
    }
</script>
