<?php
/**
 * Copyright 2026 Adobe
 * All Rights Reserved.
 */
declare(strict_types=1);

namespace Magento\Framework\Data\Collection;

use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Phrase;

/**
 * SQL Injection Validator for Collection Filters
 *
 * This validator detects potentially dangerous SQL patterns in filter values
 * to prevent SQL injection attacks when using the 'string' filter type.
 *
 * SECURITY NOTE: The 'string' filter type is designed for pre-escaped SQL fragments
 * that have been properly sanitized using database connection methods like quoteInto().
 * This validator acts as a defense-in-depth mechanism to catch unsafe usage patterns.
 *
 * @since 2.4.8
 */
class SqlInjectionValidator
{
    /**
     * Patterns indicating potential SQL injection attempts
     *
     * These patterns detect common SQL injection techniques including:
     * - UNION-based attacks
     * - Subquery injection
     * - Comment-based attacks
     * - Stacked queries
     * - Boolean-based blind injection
     * - Time-based blind injection
     * - Information schema access
     *
     * @var array
     */
    private const DANGEROUS_PATTERNS = [
        // UNION-based injection
        '/\bUNION\s+(?:ALL\s+)?SELECT\b/i',
        
        // Comment markers used to bypass filters
        '/--\s*$/',                    // SQL line comment at end
        '/#.*$/',                       // MySQL comment at end  
        '/\/\*.*?\*\//s',              // Block comments
        
        // Stacked queries
        '/;\s*(?:SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|EXECUTE)\b/i',
        
        // Subquery injection patterns
        '/\(\s*SELECT\b/i',
        
        // Information schema access
        '/\bINFORMATION_SCHEMA\b/i',
        '/\bMYSQL\.USER\b/i',
        
        // Common injection keywords in suspicious positions
        '/\bEXEC\s*\(/i',
        '/\bEXECUTE\s*\(/i',
        '/\bCHAR\s*\(/i',              // CHAR() function often used in injection
        
        // Boolean-based blind injection
        '/\b(?:AND|OR)\s+\d+\s*[=<>]/i',
        
        // Time-based blind injection
        '/\bSLEEP\s*\(/i',
        '/\bBENCHMARK\s*\(/i',
        '/\bWAITFOR\s+DELAY\b/i',
        
        // Database modification attempts
        '/\bDROP\s+(?:TABLE|DATABASE|SCHEMA)\b/i',
        '/\bTRUNCATE\s+TABLE\b/i',
        '/\bALTER\s+TABLE\b/i',
        
        // File system access
        '/\bLOAD_FILE\s*\(/i',
        '/\bINTO\s+(?:OUT|DUMP)FILE\b/i',
        
        // Multiple statement separators
        '/;\s*;/',
    ];

    /**
     * Patterns that indicate properly escaped SQL (safe usage)
     *
     * These patterns suggest the SQL was generated by database adapter methods
     * like quoteInto(), quoteIdentifier(), or prepareSqlCondition()
     *
     * @var array
     */
    private const SAFE_PATTERNS = [
        // Properly quoted identifiers (backticks or double quotes)
        '/^[`"][\w\-\.]+[`"]\s*[=<>!]+\s*[\?\d\'"]/',
        
        // Table.column pattern with quoted values
        '/^[\w]+\.[\w]+\s*[=<>!]+\s*[\?\d\'"]/',
        
        // IN clause with quoted values or placeholders
        '/^[\w\.`"]+\s+IN\s*\(\s*[\?,\s\d\'\"]+\s*\)$/i',
        
        // LIKE clause with placeholders
        '/^[\w\.`"]+\s+LIKE\s+[\?\'"]/',
        
        // IS NULL / IS NOT NULL
        '/^[\w\.`"]+\s+IS\s+(?:NOT\s+)?NULL$/i',
        
        // BETWEEN with placeholders
        '/^[\w\.`"]+\s+BETWEEN\s+[\?\d\'\"]\s+AND\s+[\?\d\'\"]$/i',
    ];

    /**
     * Validate SQL string for potential injection attacks
     *
     * @param string $sql The SQL fragment to validate
     * @param bool $throwException Whether to throw exception on detection (default true)
     * @return bool True if safe, false if dangerous (when not throwing exception)
     * @throws LocalizedException If dangerous SQL is detected and $throwException is true
     */
    public function validate(string $sql, bool $throwException = true): bool
    {
        // Empty strings are safe
        if (trim($sql) === '') {
            return true;
        }

        // Check if SQL matches known safe patterns first (optimization)
        foreach (self::SAFE_PATTERNS as $pattern) {
            if (preg_match($pattern, trim($sql))) {
                return true;
            }
        }

        // Check for dangerous patterns
        foreach (self::DANGEROUS_PATTERNS as $pattern) {
            if (preg_match($pattern, $sql)) {
                if ($throwException) {
                    throw new LocalizedException(
                        new Phrase(
                            'Potential SQL injection detected in filter value. ' .
                            'The "string" filter type requires pre-escaped SQL. ' .
                            'Use quoteInto() or addFieldToFilter() instead.'
                        )
                    );
                }
                return false;
            }
        }

        // Additional heuristic: check for suspicious character combinations
        if ($this->containsSuspiciousPatterns($sql)) {
            if ($throwException) {
                throw new LocalizedException(
                    new Phrase(
                        'Suspicious SQL pattern detected in filter value. ' .
                        'The "string" filter type must only contain properly escaped SQL fragments.'
                    )
                );
            }
            return false;
        }

        return true;
    }

    /**
     * Check for suspicious character patterns that may indicate injection
     *
     * @param string $sql SQL fragment to check
     * @return bool True if suspicious patterns found
     */
    private function containsSuspiciousPatterns(string $sql): bool
    {
        // Multiple consecutive SQL operators
        if (preg_match('/[=<>!]{2,}/', $sql)) {
            return true;
        }

        // Unbalanced quotes (possible quote escape attempt)
        $singleQuotes = substr_count($sql, "'") - substr_count($sql, "\\'");
        $doubleQuotes = substr_count($sql, '"') - substr_count($sql, '\\"');
        
        if ($singleQuotes % 2 !== 0 || $doubleQuotes % 2 !== 0) {
            // Allow unbalanced quotes if they appear to be in a properly constructed LIKE clause
            if (!preg_match("/\bLIKE\s+['\"]%?[^'\"]*%?['\"]/i", $sql)) {
                return true;
            }
        }

        // Hexadecimal or unicode escape sequences (often used in injection)
        if (preg_match('/(?:0x[0-9a-f]+|\\\\u[0-9a-f]{4})/i', $sql)) {
            return true;
        }

        return false;
    }

    /**
     * Check if a value appears to be properly escaped by database adapter
     *
     * This method provides a quick check to determine if a SQL fragment
     * was likely generated by proper escaping methods.
     *
     * @param string $sql SQL fragment to check
     * @return bool True if appears properly escaped
     */
    public function looksProperlyEscaped(string $sql): bool
    {
        foreach (self::SAFE_PATTERNS as $pattern) {
            if (preg_match($pattern, trim($sql))) {
                return true;
            }
        }
        return false;
    }
}
