<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\OfflinePayments\Block\Form\Cashondelivery
 */
?>
<?php if ($block->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php /* @escapeNotVerified */ echo $block->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php /* @escapeNotVerified */ echo $block->getMethodCode() ?>-instructions-content agreement-content">
                <?php /* @escapeNotVerified */ echo nl2br($block->getInstructions()) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>
