<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\OfflinePayments\Block\Form\Cashondelivery;

/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Cashondelivery $block */
$instructions = $block->getInstructions();
?>
<?php if ($instructions): ?>
    <?php $methodCode = $escaper->escapeHtml($block->getMethodCode());?>
    <ul class="form-list checkout-agreements" id="payment_form_<?= /* @noEscape */ $methodCode ?>">
        <li>
            <div class="<?= /* @noEscape */ $methodCode ?>-instructions-content checkout-agreement-item-content">
                <?= /* @noEscape */ nl2br($escaper->escapeHtml($instructions)) ?>
            </div>
        </li>
    </ul>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "display:none",
        'ul#payment_form_' . /* @noEscape */ $methodCode
    ) ?>
<?php endif; ?>
