<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\OfflinePayments\Block\Form\Cashondelivery
 */
$instructions = $block->getInstructions();
?>
<?php if ($instructions): ?>
    <?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo /* @noEscape */ $methodCode ?>" style="display:none;">
        <li>
            <div class="<?php echo /* @noEscape */ $methodCode ?>-instructions-content checkout-agreement-item-content">
                <?php echo /* @noEscape */ nl2br($block->escapeHtml($instructions)) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>
