<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\OfflinePayments\Block\Form\Checkmo;

/** @var Escaper $escaper */
/** @var Checkmo $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>" >
    <?php if ($block->getMethod()->getPayableTo()): ?>
        <label class="label"><span><?= $escaper->escapeHtml(__('Make Check payable to:')) ?></span></label>
        <?= $escaper->escapeHtml($block->getMethod()->getPayableTo()) ?>
    <?php endif; ?>
    <?php if ($block->getMethod()->getMailingAddress()): ?>
        <div class="admin__field">
            <label class="admin__field-label"><span><?= $escaper->escapeHtml(__('Send Check to:')) ?></span></label>
            <div class="admin__field-control checkmo-mailing-address">
                <?= /* @noEscape */ nl2br($escaper->escapeHtml($block->getMethod()->getMailingAddress())) ?>
            </div>
        </div>
    <?php endif; ?>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display:none",
    'fieldset#payment_form_' . $escaper->escapeJs($block->getMethodCode())
) ?>
