<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php  $_order = $this->getCreditmemo()->getOrder() ?>
<?php echo $this->getChildHtml('order_info') ?>
<div class="clearfix">
<?php if (!$_order->getIsVirtual()): ?>
<div class="order-payment-method">
<?php else: ?>
<div class="order-payment-method order-payment-method-virtual">
<?php endif; ?>
    <?php /* Billing Address */?>
    <div class="fieldset-wrapper">
        <div class="fieldset-wrapper-title">
            <span class="title"><?php echo __('Payment Information') ?></span>
        </div>
        <div><?php echo $this->getChildHtml('order_payment') ?></div>
        <div class="order-payment-currency"><?php echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
        <div class="order-payment-additional"><?php echo $this->getChildHtml('order_payment_additional'); ?></div>
    </div>
</div>
<?php if (!$_order->getIsVirtual()): ?>
<div class="order-shipping-address">
    <?php /* Shipping Address */ ?>
    <div class="fieldset-wrapper">
        <div class="fieldset-wrapper-title">
            <span class="title"><?php echo __('Shipping Information') ?></span>
        </div>
        <div class="shipping-description-wrapper">
            <div class="shipping-description-title"><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></div>
            <div class="shipping-description-content">
                <?php echo __('Total Shipping Charges'); ?>:

                <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                    <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                <?php else: ?>
                    <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                <?php echo $_excl; ?>
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo __('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
</div>
<?php $_items = $this->getCreditmemo()->getAllItems() ?>

<?php if (count($_items)): ?>
<div id="creditmemo_items_container">
    <?php echo $this->getChildHtml('creditmemo_items') ?>
</div>
<?php else: ?>
<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Items Refunded') ?></span>
    </div>
    <div class="no-items"><?php echo __('No Items') ?></div>
</div>
<?php endif; ?>
<div class="clearfix">
    <div class="order-comments-history">
        <div class="fieldset-wrapper">
            <div class="fieldset-wrapper-title"><span class="title"><?php echo __('Credit Memo History') ?></span></div>
            <fieldset><?php echo $this->getChildHtml('order_comments') ?></fieldset>
        </div>
    </div>
    <div class="order-totals">
        <div class="fieldset-wrapper" id="history_form">
            <div class="fieldset-wrapper-title"><span class="title"><?php echo __('Credit Memo Totals') ?></span></div>
            <div><?php echo $this->getChildHtml('creditmemo_totals') ?></div>
        </div>
    </div>
</div>
