<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\GoogleAdwords\Block\Code */
?>
<!-- Google Code for Sale Conversion Page -->
<script>
    /* <![CDATA[ */
    var google_conversion_id = <?= $escaper->escapeJs($block->getHelper()->getConversionId()) ?>;
    var google_conversion_language = "<?= $escaper->escapeJs($block->getHelper()->getConversionLanguage()) ?>";
    var google_conversion_format = "<?= $escaper->escapeJs($block->getHelper()->getConversionFormat()) ?>";
    var google_conversion_color = "<?= $escaper->escapeJs($block->getHelper()->getConversionColor()) ?>";
    var google_conversion_label = "<?= $escaper->escapeJs($block->getHelper()->getConversionLabel()) ?>";
    var google_conversion_value = <?= $escaper->escapeJs($block->getHelper()->getConversionValue()) ?>;
    <?php if ($block->getHelper()->hasSendConversionValueCurrency() && $block->getHelper()->getConversionValueCurrency()) : ?>
    var google_conversion_currency = "<?= $escaper->escapeJs($block->getHelper()->getConversionValueCurrency()) ?>";
    <?php endif; ?>
    /* ]]> */
</script>
<script src="<?= $escaper->escapeHtmlAttr($block->getHelper()->getConversionJsSrc()) ?>"></script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt=""
             src="<?= $escaper->escapeHtmlAttr($block->getHelper()->getConversionImgSrc()) ?>"/>
    </div>
</noscript>
<!-- END Google Code for Sale Conversion Page -->
