<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\GoogleAdwords\Block\Code */
?>
<!-- Google Code for Sale Conversion Page -->
<script>
    /* <![CDATA[ */
    var google_conversion_id = <?php echo $block->getHelper()->getConversionId() ?>;
    var google_conversion_language = "<?php echo $block->getHelper()->getConversionLanguage() ?>";
    var google_conversion_format = "<?php echo $block->getHelper()->getConversionFormat() ?>";
    var google_conversion_color = "<?php echo $block->getHelper()->getConversionColor() ?>";
    var google_conversion_label = "<?php echo $block->getHelper()->getConversionLabel() ?>";
    var google_conversion_value = <?php echo $block->getHelper()->getConversionValue() ?>;
    /* ]]> */
</script>
<script src="<?php echo $block->getHelper()->getConversionJsSrc()?>"></script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt=""
             src="<?php echo $block->getHelper()->getConversionImgSrc() ?>"/>
    </div>
</noscript>
<!-- END Google Code for Sale Conversion Page -->
