<?php
/** @var \Magento\GoogleAdwords\Helper\Data $helper */
$helper = $block->getHelper();
if ($helper->isGoogleAdwordsActive()) { ?>
<!-- Event snippet for Magento Testing conversion page -->
<script>
console.log("GoogleAdwords - START conversion");
gtag('event', 'conversion', {'send_to': '<?= $helper->getConversionId() ?>' + '/' + '<?= $helper->getConversionLabel() ?>'});
console.log("GoogleAdwords - END conversion");
</script>
<?php } ?>


<!-- END Google Code for Sale Conversion Page -->
