<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var \Magento\Catalog\Block\Adminhtml\Product\Composite\Fieldset\Options $block */ ?>
<?php $option = $block->getOption(); ?>
<div class="admin__field field">
    <label class="admin__field-label label">
        <span>
            <?= $block->escapeHtml($option->getTitle()) ?>
        </span>
    </label>
</div>
