<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Magento\Catalog\Block\Adminhtml\Product\Composite\Fieldset\Options
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $option = $block->getOption(); ?>
<div class="admin__field field">
    <label class="admin__field-label label">
        <span>
            <?= $escaper->escapeHtml($option->getTitle()) ?>
        </span>
    </label>
</div>
