<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $this \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php $_option = $this->getOption(); ?>
<div class="field<?php if ($_option->getIsRequire()) echo ' required' ?>">
	<label class="label"><?php echo  $this->escapeHtml($_option->getTitle()) ?></label>
	<div class="control">
        <?php echo $this->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
	</div>
</div>
