<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $this->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php $options = $this->decorateArray($this->getOptions()); ?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage',
    'Magento_Bundle/js/price-bundle'
], function($){
    $(function() {
        $('#product_addtocart_form').priceBundle({
            optionConfig:<?php echo $this->getJsonConfig()?>,
            controlContainer: '.field.option',
            qtyFieldSelector: '.input-text.qty'
        });
    });
});
</script>
        <fieldset class="fieldset bundle options">
            <legend id="customizeTitle" class="legend title">
                <span><?php echo __('Customize %1', $helper->productAttribute($product, $product->getName(), 'name')) ?></span>
            </legend><br />
            <?php echo $this->getChildHtml('product_info_bundle_options_top');?>
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?php echo $this->getOptionHtml($option) ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?php echo __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
