<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Backend\Block\Widget\Form */
?>
<?php /* @todo replace .form-inline with better class name */?>
<?php /* ToDo UI: check if we need this wrapper in the process of global forms refactoring */ ?>

<div class="entry-edit form-inline">
    <?= $block->getFormHtml() ?>
</div>
<?= $block->getChildHtml('form_after') ?>
