<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for \Magento\Backend\Block\Widget\Grid
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 *
 */
/* @var $block \Magento\Backend\Block\Widget\Grid */
$numColumns = $block->getColumns() !== null ? count($block->getColumns()) : 0;
?>
<?php if ($block->getCollection()) : ?>

    <?php if ($block->canDisplayContainer()) : ?>
<div id="<?= $escaper->escapeHtml($block->getId()) ?>" data-grid-id="<?= $escaper->escapeHtml($block->getId()) ?>">
    <?php else : ?>
        <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
    <?php endif; ?>

        <div class="admin__data-grid-header admin__data-grid-toolbar">
            <?php $massActionAvailable = $block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable() ?>
            <?php if ($block->getPagerVisibility() || $block->getExportTypes() || $block->getChildBlock('grid.columnSet')->getFilterVisibility() || $massActionAvailable) : ?>
            <div class="admin__data-grid-header-row">
                <?php if ($massActionAvailable) : ?>
                    <?= $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : '' ?>
                <?php endif; ?>

                <?php if ($block->getChildBlock('grid.export')) : ?>
                    <?= $block->getChildHtml('grid.export') ?>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <div class="<?php if ($massActionAvailable) { echo '_massaction ';} ?>admin__data-grid-header-row">
                <?php if ($massActionAvailable) : ?>
                    <?= $block->getChildHtml('grid.massaction') ?>
                <?php else : ?>
                    <?= $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : '' ?>
                <?php endif; ?>
                    <?php $countRecords = $block->getCollection()->getSize(); ?>
                    <div class="admin__control-support-text">
                        <span id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>-total-count" <?= /* @noEscape */ $block->getUiId('total-count') ?>>
                            <?= /* @noEscape */ $countRecords ?>
                        </span>
                        <?= $escaper->escapeHtml(__('records found')) ?>
                        <span id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_massaction-count"
                              class="mass-select-info _empty"><strong data-role="counter">0</strong> <span><?= $escaper->escapeHtml(__('selected')) ?></span></span>
                    </div>
                <?php if ($block->getPagerVisibility()) : ?>
                    <div class="admin__data-grid-pager-wrap">
                        <select name="<?= $escaper->escapeHtmlAttr($block->getVarNameLimit()) ?>"
                                id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_page-limit"
                                onchange="<?= /* @noEscape */ $block->getJsObjectName() ?>.loadByElement(this)" <?= /* @noEscape */ $block->getUiId('per-page') ?>
                                class="admin__control-select">
                            <option value="20"<?php if ($block->getCollection()->getPageSize() == 20) : ?>
                                selected="selected"<?php endif; ?>>20
                            </option>
                            <option value="30"<?php if ($block->getCollection()->getPageSize() == 30) : ?>
                                selected="selected"<?php endif; ?>>30
                            </option>
                            <option value="50"<?php if ($block->getCollection()->getPageSize() == 50) : ?>
                                selected="selected"<?php endif; ?>>50
                            </option>
                            <option value="100"<?php if ($block->getCollection()->getPageSize() == 100) : ?>
                                selected="selected"<?php endif; ?>>100
                            </option>
                            <option value="200"<?php if ($block->getCollection()->getPageSize() == 200) : ?>
                                selected="selected"<?php endif; ?>>200
                            </option>
                        </select>
                        <label for="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_page-limit"
                            class="admin__control-support-text"><?= $escaper->escapeHtml(__('per page')) ?></label>
                        <div class="admin__data-grid-pager">
                            <?php $_curPage = $block->getCollection()->getCurPage() ?>
                            <?php $_lastPage = $block->getCollection()->getLastPageNumber() ?>

                            <?php if ($_curPage > 1) : ?>
                                <button class="action-previous"
                                        type="button"
                                        onclick="<?= /* @noEscape */ $block->getJsObjectName() ?>.setPage('<?= /* @noEscape */ ($_curPage - 1) ?>');return false;">
                                            <span><?= $escaper->escapeHtml(__('Previous page')) ?></span>
                                </button>
                            <?php else : ?>
                                <button type="button" class="action-previous disabled"><span><?= $escaper->escapeHtml(__('Previous page')) ?></span></button>
                            <?php endif; ?>

                            <input type="text"
                                   id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_page-current"
                                   name="<?= $escaper->escapeHtmlAttr($block->getVarNamePage()) ?>"
                                   value="<?= $escaper->escapeHtmlAttr($_curPage) ?>"
                                   class="admin__control-text"
                                   onkeypress="<?= /* @noEscape */ $block->getJsObjectName() ?>.inputPage(event, '<?= /* @noEscape */ $_lastPage ?>')" <?= /* @noEscape */ $block->getUiId('current-page') ?> />

                            <label class="admin__control-support-text" for="<?= $escaper->escapeHtml($block->getHtmlId())
                            ?>_page-current">
                                <?= /* @noEscape */ __('of %1', '<span>' . $block->getCollection()->getLastPageNumber() . '</span>') ?>
                            </label>
                            <?php if ($_curPage < $_lastPage) : ?>
                                <button type="button" title="<?= $escaper->escapeHtmlAttr(__('Next page')) ?>"
                                        class="action-next"
                                        onclick="<?= /* @noEscape */ $block->getJsObjectName() ?>.setPage('<?= /* @noEscape */ ($_curPage + 1) ?>');return false;">
                                    <span><?= $escaper->escapeHtml(__('Next page')) ?></span>
                                </button>
                            <?php else : ?>
                                <button type="button" class="action-next disabled"><span><?= $escaper->escapeHtml(__('Next page')) ?></span></button>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </div>
        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <?php if ($block->getGridCssClass()) : ?>
            <table class="<?= $escaper->escapeHtmlAttr($block->getGridCssClass()) ?> data-grid" id="<?= $escaper->escapeHtml($block->getId()) ?>_table">
                <!-- Rendering column set -->
                <?= $block->getChildHtml('grid.columnSet') ?>
            </table>
        <?php else : ?>

            <table class="data-grid" id="<?= $escaper->escapeHtml($block->getId()) ?>_table">
                <!-- Rendering column set -->
                <?= $block->getChildHtml('grid.columnSet') ?>
            </table>

            <?php if ($block->getChildBlock('grid.bottom.links')) : ?>
                <?= $block->getChildHtml('grid.bottom.links') ?>
            <?php endif; ?>

        <?php endif ?>
        </div>
    <?php if ($block->canDisplayContainer()) : ?>
</div>
<script>
    var deps = [];

        <?php if ($block->getDependencyJsObject()) : ?>
    deps.push('uiRegistry');
        <?php endif; ?>

        <?php if (strpos($block->getRowClickCallback(), 'order.') !== false) : ?>
    deps.push('Magento_Sales/order/create/form');
    deps.push('jquery');
        <?php endif; ?>

    deps.push('mage/adminhtml/grid');

    require(deps, function(<?= ($block->getDependencyJsObject() ? 'registry' : '') ?>){
        <?php //TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed ?>

        <?php if ($block->getDependencyJsObject()) : ?>
            registry.get('<?= $escaper->escapeJs($block->getDependencyJsObject()) ?>', function (<?= $escaper->escapeJs($block->getDependencyJsObject()) ?>) {
        <?php endif; ?>

        <?= $escaper->escapeJs($block->getJsObjectName()) ?> = new varienGrid('<?= $escaper->escapeHtml($block->getId()) ?>', '<?= $escaper->escapeJs($block->getGridUrl()) ?>', '<?= $escaper->escapeJs($block->getVarNamePage()) ?>', '<?= $escaper->escapeJs($block->getVarNameSort()) ?>', '<?= $escaper->escapeJs($block->getVarNameDir()) ?>', '<?= $escaper->escapeJs($block->getVarNameFilter()) ?>');
        <?= $escaper->escapeJs($block->getJsObjectName()) ?>.useAjax = <?= /* @noEscape */ $block->getUseAjax() ? 'true' : 'false' ?>;
        <?php if ($block->getRowClickCallback()) : ?>
                <?= $escaper->escapeJs($block->getJsObjectName()) ?>.rowClickCallback = <?= /* @noEscape */ $block->getRowClickCallback() ?>;
        <?php endif; ?>
        <?php if ($block->getCheckboxCheckCallback()) : ?>
                <?= $escaper->escapeJs($block->getJsObjectName()) ?>.checkboxCheckCallback = <?= /* @noEscape */ $block->getCheckboxCheckCallback() ?>;
        <?php endif; ?>
        <?php if ($block->getSortableUpdateCallback()) : ?>
                <?= $escaper->escapeJs($block->getJsObjectName()) ?>.sortableUpdateCallback = <?= /* @noEscape */ $block->getSortableUpdateCallback() ?>;
        <?php endif; ?>
        <?php if ($block->getFilterKeyPressCallback()) : ?>
            <?= $escaper->escapeJs($block->getJsObjectName()) ?>.filterKeyPressCallback = <?= /* @noEscape */ $block->getFilterKeyPressCallback() ?>;
        <?php endif; ?>
        <?= $escaper->escapeJs($block->getJsObjectName()) ?>.bindSortable();
        <?php if ($block->getRowInitCallback()) : ?>
                <?= $escaper->escapeJs($block->getJsObjectName()) ?>.initRowCallback = <?= /* @noEscape */ $block->getRowInitCallback() ?>;
                <?= $escaper->escapeJs($block->getJsObjectName()) ?>.initGridRows();
        <?php endif; ?>
        <?php if ($block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable()) : ?>
                <?= /* @noEscape */ $block->getChildBlock('grid.massaction')->getJavaScript() ?>
        <?php endif ?>
        <?= /* @noEscape */ $block->getAdditionalJavaScript() ?>

        <?php if ($block->getDependencyJsObject()) : ?>
            });
        <?php endif; ?>
    });
</script>
<?php endif; ?>

    <?php if ($block->getChildBlock('grid.js')) : ?>
        <?= $block->getChildHtml('grid.js') ?>
    <?php endif; ?>

<?php endif ?>
