<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $this \Magento\Backend\Block\Widget\Tabs */
?>
<?php if (!empty($tabs)): ?>
<div id="<?php echo $this->getId() ?>">
    <?php if ($this->getTitle()): ?>
    <h3 <?php echo $this->getUiId('title') ?>><?php echo $this->getTitle() ?></h3>
    <?php endif ?>
    <ul <?php echo $this->getUiId('tab', $this->getId()) ?> class="<?php echo $this->getIsHoriz() ? 'tabs-horiz' : 'tabs' ?>">
        <?php foreach ($tabs as $_tab): ?>
        <?php if (!$this->canShowTab($_tab)): continue;  endif; ?>
        <?php $_tabClass = 'tab-item-link ' . $this->getTabClass($_tab) . ' ' . (preg_match('/\s?ajax\s?/', $_tab->getClass()) ? 'notloaded' : '') ?>
        <?php $_tabType = (!preg_match('/\s?ajax\s?/', $_tabClass) && $this->getTabUrl($_tab) != '#') ? 'link' : '' ?>
        <?php $_tabHref = $this->getTabUrl($_tab) == '#' ? '#' . $this->getTabId($_tab) . '_content' : $this->getTabUrl($_tab) ?>
        <li <?php if ($this->getTabIsHidden($_tab)): ?> style="display:none"<?php endif; ?><?php echo $this->getUiId('tab', 'item', $_tab->getId()) ?>>
            <a href="<?php echo $_tabHref ?>" id="<?php echo $this->getTabId($_tab) ?>" name="<?php echo $this->getTabId($_tab, false) ?>" title="<?php echo $this->getTabTitle($_tab) ?>" class="<?php echo $_tabClass;?>" data-tab-type="<?php echo $_tabType;?>" <?php echo $this->getUiId('tab', 'link', $_tab->getId()) ?>>
            <span>
                <span class="changed" title="<?php echo __('The information in this tab has been changed.') ?>"></span>
                <span class="error" title="<?php echo __('This tab contains invalid data. Please solve the problem before saving.') ?>"></span>
                <span class="loader" title="<?php echo __('Loading...') ?>"></span>
                <?php echo $this->getTabLabel($_tab); ?>
            </span>
            </a>
            <div id="<?php echo $this->getTabId($_tab) ?>_content" style="display:none;"<?php echo $this->getUiId('tab', 'content', $_tab->getId()) ?>><?php echo $this->getTabContent($_tab) ?></div>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<script type="text/javascript">
require(['jquery',"mage/backend/tabs"], function($){
    $(function() {
        $('#<?php echo $this->getId() ?>').tabs({
            active: '<?php echo $this->getActiveTabId() ?>',
            destination: '#<?php echo $this->getDestElementId() ?>',
            shadowTabs: <?php echo $this->getAllShadowTabs()?>,
            tabsBlockPrefix: '<?php echo $this->getId() ?>_',
            tabIdArgument: 'active_tab'
        });
    });
});
</script>
<?php endif; ?>
