<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 ?>
<div class="fieldset-wrapper-title <?php echo $this->getHeaderCssClass() ?>">
	<span class="title"><?php echo $this->getHeaderText() ?></span>
	<div class="actions"></div>
</div>
<div class="form-inline" id="customer_account_fieds">
    <?php echo $this->getForm()->getHtml() ?>
</div>
<script type="text/javascript">
	require(["prototype", "Magento_Sales/order/create/form"], function(){
		order.accountFieldsBind($('customer_account_fieds'));
	});
</script>
