<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Review\Block\Product\View\Other;

/** @var Escaper $escaper */
/** @var Other $block */
?>
<?php $_product = $block->getProduct(); ?>
<div class="actions">
    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="action back"><span><?= $escaper->escapeHtml(__('Back to Main Product Info')) ?></span></a>
</div>
