<?php
/**
 * Copyright 2026 Adobe
 * All Rights Reserved.
 *
 * @var Escaper $escaper
 * @var \Magento\CatalogImportExport\Block\Adminhtml\Export\MandatoryAttributesNotice $block
 */

use Magento\Framework\Escaper;

?>
<?php $mandatoryAttributes = $block->getSystemMandatoryAttributes(); ?>
<?php if ($mandatoryAttributes): ?>
    <div id="mandatory-attributes-notice"
         class="message message-notice notice mandatory-attributes-notice"
         style="display: none;"
         data-mage-init='{"Magento_CatalogImportExport/js/mandatory-notice-toggle": {"entitySelector": "#entity"}}'>
        <div data-ui-id="messages-message-notice">
            <strong><?= $escaper->escapeHtml(__('Note:')) ?></strong>
            <?= $escaper->escapeHtml(
                __(
                    'The following system columns are automatically appended ' .
                    'during the export process and cannot be excluded:'
                )
            ) ?>
            <br/>
            <span class="mandatory-system-fields"><?= $escaper->escapeHtml($mandatoryAttributes) ?></span>
        </div>
    </div>
<?php endif; ?>