<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/**
 * @var $block Template
 * @var $escaper Escaper
 */
?>
<div class="spectrum-InLineAlert spectrum-InLineAlert--error admin-adobe-ims-message-container">
    <svg class="spectrum-Icon spectrum-Icon--sizeM spectrum-InLineAlert-icon" focusable="false" aria-hidden="true">
        <use xlink:href="#spectrum-icon-18-Alert" />
    </svg>
    <div class="spectrum-InLineAlert-header admin-adobe-ims-message-header">
        <?= $escaper->escapeHtml($block->getData('headline')) ?>
    </div>
    <div class="spectrum-InLineAlert-content admin-adobe-ims-message-message">
        <?= $escaper->escapeHtml($block->getData('message')) ?>
    </div>
</div>
