<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */
?>
<button type="submit" data-role="review-save" title="<?= $escaper->escapeHtml(__('Continue')) ?>"
        class="button action checkout primary">
    <span><?= $escaper->escapeHtml(__('Continue')) ?></span>
</button>
