<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Theme\Block\Adminhtml\Design\Config\Edit\Scope */
?>

<div class="desing-config-edit">
    <span class="desing-config-edit-label"><?php /* @escapeNotVerified */ echo __('Scope:'); ?></span>
    <span class="desing-config-edit-label"><?php /* @escapeNotVerified */ echo $block->getScopeTitle(); ?></span>
</div>
