<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Theme\Block\Adminhtml\Design\Config\Edit\Scope */
?>

<div class="store-view">
    <span class="store-switcher-label"><?php echo /* @escapeNotVerified */ __('Scope:') ?></span>
    <span class="store-switcher-value"><?php echo /* @escapeNotVerified */ $block->getScopeTitle() ?></span>
</div>
