<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Theme\Block\Html\Topmenu */
/** @var $viewModel \Magento\Catalog\ViewModel\SeoConfigTopMenu */
$viewModel = $block->getData('viewModel');
$columnsLimit = $block->getColumnsLimit() ?: 0;
$menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit);
$jsonSerializer = $viewModel->getJsonSerializer();

$widgetOptions = [
    'menu' => array_merge(
        $viewModel->getSeoConfigOptions()['menu'] ?? [],
        [
            'responsive' => true,
            'expanded' => true,
            'position' => [
                'my' => 'left top',
                'at' => 'left bottom'
            ]
        ]
    )
];
$widgetOptionsJson = $jsonSerializer->serialize($widgetOptions);
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='<?= /* @noEscape */ $widgetOptionsJson ?>'>
        <?= /* @noEscape */ $menuHtml ?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
