<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Customer\ListCustomer $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Review\Helper\Data $reviewHelper */
$reviewHelper = $block->getData('reviewHelper');
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>
    <div class="table-wrapper reviews">
        <table class="data table table-reviews" id="my-reviews-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Product Reviews')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Created')) ?></th>
                    <th scope="col" class="col item"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col summary"><?= $escaper->escapeHtml(__('Rating')) ?></th>
                    <th scope="col" class="col description"><?= $escaper->escapeHtml(__('Review')) ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getReviews() as $review): ?>
                <tr>
                    <td data-th="<?= $escaper->escapeHtml(__('Created')) ?>"
                        class="col date"><?= $escaper->escapeHtml($block->dateFormat($review->getReviewCreatedAt())) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>" class="col item">
                        <strong class="product-name">
                            <a href="<?= $escaper->escapeUrl($block->getProductUrl($review)) ?>">
                                <?= $escaper->escapeHtml($review->getName()) ?>
                            </a>
                        </strong>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Rating')) ?>" class="col summary">
                    <?php if ($review->getSum()): ?>
                        <div class="rating-summary">
                            <span class="label"><span><?= $escaper->escapeHtml(__('Rating')) ?>:</span></span>
                            <div class="rating-result"
                                 id="rating-result_<?= /* @noEscape */ $block->escapeHtml($review->getId()) ?>"
                                 title="<?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%">
                                <span class="rating_<?= $escaper->escapeUrl($review->getReviewId())?>">
                                    <span>
                                        <?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%
                                    </span>
                                </span>
                            </div>
                        </div>
                        <?= /* @noEscape */
                        $secureRenderer->renderStyleAsTag(
                            "width:" . /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) . "%;",
                            'div.rating-summary div.rating-result>span.rating_' .
                                            $escaper->escapeUrl($review->getReviewId())
                        ) ?>
                    <?php endif; ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Review')) ?>" class="col description">
                        <?= $reviewHelper->getDetailHtml($review->getDetail()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                        <a href="<?= $escaper->escapeUrl($block->getReviewUrl($review)) ?>" class="action more">
                            <span><?= $escaper->escapeHtml(__('See Details')) ?></span>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?= $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have submitted no reviews.')) ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
