<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Customer\Recent $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>
<div class="block block-reviews-dashboard">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('My Recent Reviews')) ?></strong>
        <a class="action view" href="<?= $escaper->escapeUrl($block->getAllReviewsUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('View All')) ?></span>
        </a>
    </div>
    <div class="block-content">
        <ol class="items">
        <?php foreach ($block->getReviews() as $_review): ?>
            <li class="item">
                <strong class="product-name">
                    <a href="<?= $escaper->escapeUrl($block->getReviewUrl($_review->getReviewId())) ?>">
                        <?= $escaper->escapeHtml($_review->getName()) ?>
                    </a>
                </strong>
                <?php if ($_review->getSum()): ?>
                    <?php $rating = $_review->getSum() / $_review->getCount() ?>
                    <div class="rating-summary">
                         <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                         <div class="rating-result"
                              id="rating-result_<?= /* @noEscape */ $block->escapeHtml($_review->getId()) ?>"
                              title="<?= $block->escapeHtmlAttr($rating) ?>%">
                             <span>
                                 <span><?= $block->escapeHtml($rating) ?>%</span>
                             </span>
                         </div>
                        <?= /* @noEscape */
                        $secureRenderer->renderStyleAsTag(
                            "width:" . $block->escapeHtmlAttr($rating) . "%",
                            '#rating-result_' . $block->escapeHtml($_review->getId()) . ' span'
                        ) ?>
                     </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
