<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php /** @var $this \Magento\Backend\Block\Template */?>

<div class="themes-assigned"><?php echo $this->getChildHtml('assigned.theme.list') ?></div>
<div class="themes-unassigned"><?php echo $this->getChildHtml('unassigned.theme.list') ?></div>

<script type="text/javascript">
require([
	'jquery',
	'Magento_DesignEditor/js/theme-delete'
], function($){

    $(document).ready(function() {
        $('body').themeDelete();
    });

});
</script>
