<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\Backend\Block\Template */?>

<div class="themes-assigned"><?php echo $this->getChildHtml('assigned.theme.list') ?></div>
<div class="themes-unassigned"><?php echo $this->getChildHtml('unassigned.theme.list') ?></div>

<script type="text/javascript">
require([
	'jquery',
	'Magento_DesignEditor/js/theme-delete'
], function($){

    $(document).ready(function() {
        $('body').themeDelete();
    });

});
</script>
