<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Theme\Selector\StoreView */?>

<div id="dialog-message-assign" title="<?php echo __('Choose the store views you want to update.') ?>" style="display:none">
    <div class="messages"></div>
    <p class="confirm_message"></p>
    <form method="post" action="">
        <ul class="websites">
            <?php foreach ($this->getWebsiteStructure() as $website => $stores): ?>
            <li class="website">
                <h3 class="website-title"><?php echo $website; ?></h3>
                <ul class="stores">
                    <?php foreach ($stores as $store => $storeViews): ?>
                    <li class="store">
                        <h4 class="store-title"><?php echo $store; ?></h4>
                        <ul class="storeviews">
                            <?php foreach ($storeViews as $storeView => $id): ?>
                            <li class="storeview">
                                <input type="hidden" name="storeviews[<?php echo $id; ?>]" value="0" />
                                <label for="storeview_<?php echo $id ?>">
                                    <input type="checkbox" id="storeview_<?php echo $id ?>" class="storeview-selector-control" name="storeviews[<?php echo $id; ?>]" value="1" />
                                    <span class="storeview-name"><?php echo $storeView; ?></span>
                                </label>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php endforeach; ?>
        </ul>
    </form>
</div>

<div id="dialog-message-assign-single">
    <div class="dialog-message-confirm messages"></div>
    <p class="confirm_message"></p>
</div>

<script type="text/javascript">
require([
    'jquery',
    'Magento_DesignEditor/js/theme-assign'
], function($){


    $(document).ready(function() {
        $('body').themeAssign(<?php echo $this->getOptionsJson(); ?>);
    });

});
</script>
