<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Template for block \Magento\Customer\Block\Adminhtml\Edit\Tab\View\Status\PersonalInfo
 */

$createDateAdmin    = $this->getCreateDate();
$createDateStore    = $this->getStoreCreateDate();
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Personal Information') ?></span>
    </div>
    <table class="data-table">
        <tbody>
        <?php echo $this->getChildHtml(); ?>
        <tr>
            <th><?php echo __('Confirmed email:') ?></th>
            <td><?php echo $this->getIsConfirmedStatus() ?></td>
        </tr>
        <tr>
            <th><?php echo __('Account Created on:') ?></th>
            <td><?php echo $createDateAdmin ?></td>
        </tr>
        <?php if ($createDateAdmin != $createDateStore): ?>
            <tr>
                <th><?php echo __('Account Created on (%1):', $this->getStoreCreateDateTimezone()) ?></th>
                <td><?php echo $createDateStore ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <th><?php echo __('Account Created in:') ?></th>
            <td><?php echo $this->getCreatedInStore() ?></td>
        </tr>
        <tr>
            <th><?php echo __('Customer Group:') ?></th>
            <td><?php echo $this->getGroupName() ?></td>
        </tr>
        </tbody>
    </table>
    <address>
        <strong><?php echo __('Default Billing Address') ?></strong><br/>
        <?php echo $this->getBillingAddressHtml() ?>
    </address>

</div>
