<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// no notice of license for now
?>

<?php
/**
 * Calendar localization script. Should be put into page header.
 *
 * @see \Magento\Framework\View\Element\Html\Calendar
 */
?>

<script>
require([
    "jquery",
    "jquery/ui"
], function($){

    $.extend(true, $, {
        calendarConfig: {
            dayNames: <?php echo /* @escapeNotVerified */ $days['wide'] ?>,
            dayNamesMin: <?php echo /* @escapeNotVerified */ $days['abbreviated'] ?>,
            monthNames: <?php echo /* @escapeNotVerified */ $months['wide'] ?>,
            monthNamesShort: <?php echo /* @escapeNotVerified */ $months['abbreviated'] ?>,
            infoTitle: "<?php echo /* @escapeNotVerified */ __('About the calendar') ?>",
            firstDay: <?php echo /* @escapeNotVerified */ $firstDay ?>,
            closeText: "<?php echo /* @escapeNotVerified */ __('Close') ?>",
            currentText: "<?php echo /* @escapeNotVerified */ __('Go Today') ?>",
            prevText: "<?php echo /* @escapeNotVerified */ __('Previous') ?>",
            nextText: "<?php echo /* @escapeNotVerified */ __('Next') ?>",
            weekHeader: "<?php echo /* @escapeNotVerified */ __('WK') ?>",
            timeText: "<?php echo /* @escapeNotVerified */ __('Time') ?>",
            hourText: "<?php echo /* @escapeNotVerified */ __('Hour') ?>",
            minuteText: "<?php echo /* @escapeNotVerified */ __('Minute') ?>",
            dateFormat: $.datepicker.RFC_2822,
            showOn: "button",
            showAnim: "",
            changeMonth: true,
            changeYear: true,
            buttonImageOnly: null,
            buttonImage: null,
            showButtonPanel: true,
            showOtherMonths: true,
            showWeek: false,
            timeFormat: '',
            showTime: false,
            showHour: false,
            showMinute: false,
            serverTimezoneSeconds: <?php echo (int) $block->getStoreTimestamp() ?>,
            serverTimezoneOffset: <?php echo (int) $block->getTimezoneOffsetSeconds() ?>,
            yearRange: '<?php echo /* @escapeNotVerified */ $block->getYearRange() ?>'
        }
    });

enUS = <?php echo /* @escapeNotVerified */ $enUS ?>; // en_US locale reference

});
</script>
