<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// no notice of license for now
?>

<?php
/**
 * Calendar localization script. Should be put into page header.
 *
 * @see \Magento\Framework\View\Element\Html\Calendar
 */
?>

<script>
require([
    "jquery",
    "jquery/ui"
], function($){

    $.extend(true, $, {
        calendarConfig: {
            dayNames: <?= /* @escapeNotVerified */ $days['wide'] ?>,
            dayNamesMin: <?= /* @escapeNotVerified */ $days['abbreviated'] ?>,
            monthNames: <?= /* @escapeNotVerified */ $months['wide'] ?>,
            monthNamesShort: <?= /* @escapeNotVerified */ $months['abbreviated'] ?>,
            infoTitle: "<?= $block->escapeHtml(__('About the calendar')) ?>",
            firstDay: <?= /* @escapeNotVerified */ $firstDay ?>,
            closeText: "<?= $block->escapeHtml(__('Close')) ?>",
            currentText: "<?= $block->escapeHtml(__('Go Today')) ?>",
            prevText: "<?= $block->escapeHtml(__('Previous')) ?>",
            nextText: "<?= $block->escapeHtml(__('Next')) ?>",
            weekHeader: "<?= $block->escapeHtml(__('WK')) ?>",
            timeText: "<?= $block->escapeHtml(__('Time')) ?>",
            hourText: "<?= $block->escapeHtml(__('Hour')) ?>",
            minuteText: "<?= $block->escapeHtml(__('Minute')) ?>",
            dateFormat: $.datepicker.RFC_2822,
            showOn: "button",
            showAnim: "",
            changeMonth: true,
            changeYear: true,
            buttonImageOnly: null,
            buttonImage: null,
            showButtonPanel: true,
            showOtherMonths: true,
            showWeek: false,
            timeFormat: '',
            showTime: false,
            showHour: false,
            showMinute: false,
            serverTimezoneSeconds: <?= (int) $block->getStoreTimestamp() ?>,
            serverTimezoneOffset: <?= (int) $block->getTimezoneOffsetSeconds() ?>,
            yearRange: '<?= /* @escapeNotVerified */ $block->getYearRange() ?>'
        }
    });

enUS = <?= /* @escapeNotVerified */ $enUS ?>; // en_US locale reference

});
</script>
