<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    var BASE_URL = '<?php echo /* @escapeNotVerified */ $block->getUrl('*') ?>';
    var FORM_KEY = '<?php echo /* @escapeNotVerified */ $block->getFormKey() ?>';
    var require = {
        "baseUrl": "<?php echo /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
</script>
