<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Payment\Block\Transparent\Form $block */
$code = $block->getMethodCode();
?>

<!-- IFRAME for request to Payment Gateway -->
<iframe id="<?php echo $code ?>-transparent-iframe"
        data-container="<?php echo $code ?>-transparent-iframe"
        allowtransparency="true"
        frameborder="0"
        name="iframeTransparent"
        style="display: none; width: 100%; background-color: transparent;"
        src="<?php echo $block->getViewFileUrl('blank.html') ?>"></iframe>
<fieldset
    id="payment_form_<?php echo $code ?>"
    class="admin__fieldset"
    data-mage-init='{
     "transparent":{
        "controller":"<?php echo $block->getRequest()->getControllerName() ?>",
        "gateway":"<?php echo $block->getMethodCode() ?>",
        "dateDelim":"<?php echo $block->getDateDelim() ?>",
        "cardFieldsMap":<?php echo $block->getCardFieldsMap() ?>,
        "orderSaveUrl":"<?php echo $block->getOrderUrl() ?>",
        "cgiUrl":"<?php echo $block->getCgiUrl() ?>",
        "expireYearLength":"<?php echo $block->getMethodConfigData('cc_year_length') ?>",
        "nativeAction":"<?php echo $block->getUrl('*/*/save', ['_secure' => $block->getRequest()->isSecure()]) ?>"
      }, "validation":[]}'
    style="display: none;">
    <div class="admin__field _required">
        <label for="<?php echo $code ?>_cc_type" class="admin__field-label">
            <span><?php echo __('Credit Card Type') ?></span>
        </label>

        <div class="admin__field-control">
            <select id="<?php echo $code ?>_cc_type"
                    data-container="<?php echo $code ?>-cc-type"
                    name="payment[cc_type]"
                    data-validate='{required:true, "validate-cc-type-select":"#<?php echo $code ?>_cc_number"}'
                    class="admin__control-select">
                <option value=""><?php echo __('Please Select') ?></option>
                <?php $_ccType = $block->getInfoData('cc_type') ?>
                <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option
                        value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <div class="admin__field _required field-number">
        <label for="<?php echo $code ?>_cc_number" class="admin__field-label">
            <span><?php echo __('Credit Card Number') ?></span>
        </label>

        <div class="admin__field-control">
            <input type="text" id="<?php echo $code ?>_cc_number" data-container="<?php echo $code ?>-cc-number"
                   name="payment[cc_number]" title="<?php echo __('Credit Card Number') ?>"
                   class="admin__control-text"
                   value=""
                   data-validate='{"required-number":true, "validate-cc-number":"#<?php echo $code ?>_cc_type", "validate-cc-type":"#<?php echo $code ?>_cc_type"}'
                   autocomplete="off"/>
        </div>
    </div>

    <div class="admin__field _required field-date" id="<?php echo $code ?>_cc_type_exp_div">
        <label for="<?php echo $code ?>_expiration" class="admin__field-label">
            <span><?php echo __('Expiration Date') ?></span>
        </label>

        <div class="admin__field-control">
            <select id="<?php echo $code ?>_expiration" name="payment[cc_exp_month]"
                    data-container="<?php echo $code ?>-cc-month"
                    class="admin__control-select admin__control-select-month"
                    data-validate='{required:true, "validate-cc-exp":"#<?php echo $code ?>_expiration_yr"}'>
                <?php $_ccExpMonth = $block->getInfoData('cc_exp_month') ?>
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option
                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>

            <?php $_ccExpYear = $block->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $code ?>_expiration_yr" name="payment[cc_exp_year]"
                    class="admin__control-select admin__control-select-year"
                    data-container="<?php echo $code ?>-cc-year" data-validate='{required:true}'>
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option
                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <?php if ($block->hasVerification()): ?>
        <div class="admin__field _required field-cvv" id="<?php echo $code ?>_cc_type_cvv_div">
            <label for="<?php echo $code ?>_cc_cid" class="admin__field-label">
                <span><?php echo __('Card Verification Number') ?></span>
            </label>

            <div class="admin__field-control">
                <input type="text" title="<?php echo __('Card Verification Number') ?>"
                       data-container="<?php echo $code ?>-cc-cvv"
                       class="admin__control-text cvv"
                       id="<?php echo $code ?>_cc_cid" name="payment[cc_cid]"
                       value=""
                       data-validate='{"required-number":true, "validate-cc-cvn":"#<?php echo $code ?>_cc_type"}'
                       autocomplete="off"/>
            </div>
        </div>
    <?php endif; ?>
    <?php echo $block->getChildHtml() ?>
</fieldset>

<script>
    /**
     * Disable card server validation in admin
     */
    require(["Magento_Sales/order/create/form"], function () {
        order.addExcludedPaymentMethod('<?php echo $code ?>');
    });
</script>
