<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Transparent\Info $block
 * @see \Magento\Payment\Block\Transparent\Info
 */
?>
<fieldset id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>" style="display:none" class="fieldset items redirect">
    <div><?= $escaper->escapeHtml(__('We\'ll ask for your payment details before you place an order.')) ?></div>
</fieldset>
