<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td class="cell-content product-info">
        <p class="product-name"><?php echo $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?php echo __('SKU'); ?>: <?php echo $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl>
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
                <dd>
                    <?php echo nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="cell-content align-center"><?php echo $_item->getQtyOrdered()*1 ?></td>
    <td class="cell-content align-right">
        <?php echo $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3">
        <table class="message-gift">
            <tr>
                <td>
                    <strong><?php echo __('Gift Message') ?></strong>
                    <?php echo __('From:'); ?> <?php echo $block->escapeHtml($_giftMessage->getSender()) ?><br />
                    <?php echo __('To:'); ?> <?php echo $block->escapeHtml($_giftMessage->getRecipient()) ?><br />
                    <strong><?php echo __('Message:'); ?></strong><br /><?php echo $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
