<?php
/**
 * Copyright 2017 Adobe
 * All Rights Reserved.
 */
/** @var \Magento\Framework\Escaper $escaper */
?>

<section class="dashboard-advanced-reports" data-index="dashboard-advanced-reports">
    <div class="dashboard-advanced-reports-description">
        <header class="dashboard-advanced-reports-title">
            <?= $escaper->escapeHtml(__('Advanced Reporting')) ?>
        </header>
        <div class="dashboard-advanced-reports-content">
            <?= $escaper->escapeHtml(__('Gain new insights and take command of your business\' performance,' .
                ' using our dynamic product, order, and customer reports tailored to your customer data.')) ?>
        </div>
    </div>
    <div class="dashboard-advanced-reports-actions">
        <a href="<?= $escaper->escapeUrl($block->getUrl('analytics/reports/show')) ?>"
           target="_blank"
           class="action action-advanced-reports"
           data-index="analytics-service-link"
           title="<?= $escaper->escapeHtmlAttr(__('Go to Advanced Reporting')) ?>">
            <span><?= $escaper->escapeHtml(__('Go to Advanced Reporting')) ?></span>
        </a>
    </div>
</section>
