<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/* @var $block \Magento\Customer\Block\CustomerScopeData */
?>
<script type="text/x-magento-init">
<?php
    /* @noEscape */
    echo \Zend_Json::encode([
        '*' => ['Magento_Customer/js/invalidation-processor' => [
            'invalidationRules' => [
                'website-rule' => [
                    'Magento_Customer/js/invalidation-rules/website-rule' => [
                        'scopeConfig' => [
                            'websiteId' => $block->getWebsiteId(),
                        ]
                    ]
                ]
            ]
        ]],
    ]);
    ?>
</script>
