<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Customer\Block\CustomerScopeData
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/invalidation-processor": {
                "invalidationRules": {
                    "website-rule": {
                        "Magento_Customer/js/invalidation-rules/website-rule": {
                            "scopeConfig": {
                                "websiteId": "<?= $escaper->escapeJs($block->getWebsiteId()) ?>"
                            }
                        }
                    }
                }
            }
        }
    }
</script>
