<?php
/**
 * Captcha interface
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magento\Captcha\Model;

/**
 * Captcha Model Interface
 *
 * @api
 * @since 2.0.0
 */
interface CaptchaInterface
{
    /**
     * Generates captcha
     *
     * @abstract
     * @return void
     * @since 2.0.0
     */
    public function generate();

    /**
     * Checks whether word entered by user corresponds to the one generated by generate()
     *
     * @param string $word
     * @return bool
     * @abstract
     * @since 2.0.0
     */
    public function isCorrect($word);

    /**
     * Get Block Name
     * @return string
     * @since 2.0.0
     */
    public function getBlockName();
}
