<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Checkout\Block\Total\DefaultTotal;
use Magento\Checkout\Helper\Data;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var DefaultTotal $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Data $checkoutHelper */
$checkoutHelper = $block->getData('checkoutHelper');
?>
<tr class="totals">
    <th colspan="<?= $escaper->escapeHtmlAttr($block->getColspan()) ?>"
        class="mark" scope="row">
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()):?>
            <strong>
        <?php endif; ?>
        <?= $escaper->escapeHtml($block->getTotal()->getTitle()) ?>
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()):?>
            </strong>
        <?php endif; ?>
    </th>
    <td class="amount"
        data-th="<?= $escaper->escapeHtmlAttr($block->getTotal()->getTitle()) ?>">
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()):?>
            <strong>
        <?php endif; ?>
            <span>
                <?= $escaper->escapeHtml(
                    $checkoutHelper->formatPrice($block->getTotal()->getValue()),
                    ['span']
                ) ?>
            </span>
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()):?>
            </strong>
        <?php endif; ?>
    </td>
</tr>
<?php if ($block->getTotal()->getStyle()): ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($block->getTotal()->getStyle(), 'tr.totals th.mark') ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($block->getTotal()->getStyle(), 'tr.totals td.amount') ?>
<?php endif; ?>
