<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_item = $block->getItem() ?>
<tr>
    <td>
        <strong><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($block->getItemOptions()): ?>
        <dl>
            <?php foreach ($block->getItemOptions() as $option): ?>
            <dt><strong><em><?= $option['label'] ?></em></strong></dt>
            <dd><?= nl2br($option['value']) ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td><?= $block->escapeHtml($block->getSku($_item)) ?></td>
    <td><?= $_item->getQty() * 1 ?></td>
</tr>
