<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Product\ReviewRenderer $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary short<?= !$rating ? ' no-rating' : '' ?>">
        <?php if ($rating):?>
        <div class="rating-summary">
            <span class="label"><span><?= $escaper->escapeHtml(__('Rating')) ?>:</span></span>
            <div class="rating-result"
                 id="rating-result_<?= /* @noEscape */ $block->getProduct()->getId() ?>"
                 title="<?= $escaper->escapeHtmlAttr($rating) ?>%">
                <span><span><?= $escaper->escapeHtml($rating) ?>%</span></span>
            </div>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                'width:' . $escaper->escapeHtmlAttr($rating) . '%',
                '#rating-result_' . $block->getProduct()->getId() . ' span'
            ) ?>
        </div>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view"
               href="<?= $escaper->escapeUrl($url) ?>"><?= $escaper->escapeHtml($block->getReviewsCount()) ?>
                &nbsp;<span><?= ($block->getReviewsCount() == 1) ?
                        $escaper->escapeHtml(__('Review')) : $escaper->escapeHtml(__('Reviews')) ?>
                </span>
            </a>
        </div>
    </div>
<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary short empty">
        <div class="reviews-actions">
            <a class="action add" href="<?= $escaper->escapeUrl($urlForm) ?>">
                <?= $escaper->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
