<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $url = $this->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $this->getReviewsUrl() . '#review-form'; ?>
<?php if ($this->getReviewsCount()): ?>
<?php $rating = $this->getRatingSummary(); ?>
<div class="product-reviews-summary short<?php echo !$rating ? ' no-rating' : ''?>">
    <?php if ($rating):?>
    <div class="rating-summary">
        <span class="label"><span><?php echo __('Rating') ?>:</span></span>
        <div class="rating-result" title="<?php echo $rating; ?>%">
            <span style="width:<?php echo $rating; ?>%"><span><?php echo $rating; ?>%</span></span>
        </div>
    </div>
    <?php endif;?>
    <div class="reviews-actions">
        <a class="action view" href="<?php echo $url ?>"><?php echo $this->getReviewsCount() ?>&nbsp;<span><?php echo($this->getReviewsCount() == 1) ? __('Review') : __('Reviews') ?></span></a>
    </div>
</div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
<div class="product-reviews-summary short empty">
    <div class="reviews-actions">
        <a class="action add" href="<?php echo $urlForm; ?>">
            <?php echo __('Be the first to review this product') ?>
        </a>
    </div>
</div>
<?php endif; ?>
