<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Comments;

/** @var Escaper $escaper */
/** @var Comments $block */
?>
<?php if ($block->hasComments()) : ?>
    <div class="order additional details comments">
        <h3 class="subtitle"><?= $escaper->escapeHtml($block->getTitle()) ?></h3>
        <dl class="order comments">
            <?php foreach ($block->getComments() as $_commentItem) : ?>
                <dt class="comment date">
                    <?= /* @noEscape */
                    $block->formatDate($_commentItem->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?>
                </dt>
                <dd class="comment text"><?= $escaper->escapeHtml($_commentItem->getComment()) ?></dd>
            <?php endforeach; ?>
        </dl>
    </div>
<?php endif;?>
