<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="table-wrapper">
        <table class="data">
            <thead>
            <tr>
                <?php if (!$_order->getIsVirtual()) : ?>
                    <th>
                        <strong class="box-title">
                            <span><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                        </strong>
                    </th>
                    <th>
                        <strong class="box-title">
                            <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                        </strong>
                    </th>
                <?php endif; ?>
                <th>
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
                    </strong>
                </th>
                <th>
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Payment Method')) ?></span>
                    </strong>
                </th>
            </tr>
            </thead>
            <tbody class="block-content">
            <tr>
                <?php if (!$_order->getIsVirtual()) : ?>
                    <td data-th="<?= $block->escapeHtml(__('Shipping Address')) ?>" class="box-content order-shipping-address">
                        <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Shipping Method')) ?>" class="box-content order-shipping-method">
                        <?php if ($_order->getShippingDescription()) : ?>
                            <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                        <?php else : ?>
                            <?= $block->escapeHtml(__('No shipping information available')) ?>
                        <?php endif ?>
                    </td>
                <?php endif ?>
                <td data-th="<?= $block->escapeHtml(__('Billing Address')) ?>" class="box-content order-billing-address">
                    <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Payment Method')) ?>" class="box-content order-payment-method">
                    <?= $block->getPaymentInfoHtml() ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
