<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Invoice;

/** @var Escaper $escaper */
/** @var Invoice $block */
?>
<div class="order-details-items invoice">
    <?= $block->getChildHtml('invoice_items') ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <a href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>" class="action back">
                <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
            </a>
        </div>
    </div>
</div>
