<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var  $this \Magento\Sales\Block\Order\View*/?>

<?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
<?php if (count($_history)): ?>
    <div class="block block-order-details-comments">
        <div class="block-title"><strong><?php echo __('About Your Order') ?></strong></div>
        <div class="block-content">
            <dl class="order-comments">
                <?php foreach ($_history as $_historyItem): ?>
                    <dt class="comment-date"><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                    <dd class="comment-content"><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
                <?php endforeach; ?>
            </dl>

        </div>
    </div>
<?php endif; ?>
