<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>
    <tr class="<?php echo /* @escapeNotVerified */ $_code ?>">
        <th <?php echo /* @escapeNotVerified */ $block->getLabelProperties() ?> scope="row">
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else:?>
            <?php echo $block->escapeHtml($_total->getLabel()) ?>
            <?php endif?>
        </th>
        <td <?php echo /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?php echo $block->escapeHtml($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()):?>
            <strong><?php echo /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?php echo /* @escapeNotVerified */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
