<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var  $this \Magento\Sales\Block\Order\View*/?>
<div class="order-details-items ordered">
    <?php $_order = $this->getOrder() ?>

    <div class="order-title">
        <strong><?php echo __('Items Ordered') ?></strong>
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <?php echo $this->getChildHtml('tracking-info-link') ?>
        <?php endif; ?>
    </div>

    <?php echo $this->getChildHtml('order_items') ?>

    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
    <div class="block block-order-details-gift-message">
        <div class="block-title"><strong><?php echo __('Gift Message for This Order') ?></strong></div>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_order); ?>
        <div class="block-content">
            <dl class="item-options">
                <dt class="item-sender"><strong class="label"><?php echo __('From') ?></strong><?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dt>
                <dt class="item-recipient"><strong class="label"><?php echo __('To') ?></strong><?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                <dd class="item-message"><?php echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($_order) ?></dd>
            </dl>
        </div>
    </div>
    <?php endif; ?>

    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?php echo $this->getBackUrl() ?>">
                <span><?php echo $this->getBackTitle() ?></span>
            </a>
        </div>
    </div>
</div>
