<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Payflow\Advanced\Iframe $block
 */
?>
<html>
<head>
</head>
<body>
<form id="token_form" method="GET" action="<?= $block->escapeUrl($block->getTransactionUrl()) ?>">
    <input type="hidden" name="SECURETOKEN" value="<?= $block->escapeHtml($block->getSecureToken()) ?>"/>
    <input type="hidden" name="SECURETOKENID" value="<?= $block->escapeHtml($block->getSecureTokenId()) ?>"/>
    <input type="hidden" name="MODE" value="<?php /* @noEscape */ echo $block->isTestMode() ? 'TEST' : 'LIVE'; ?>"/>
</form>
<script>
    document.getElementById('token_form').submit();
</script>
</body>
</html>
