<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */

/**
 * @var $this \Magento\Paypal\Block\Payflow\Advanced\Iframe
 */
?>
<html>
<head>
</head>
<body>
<form id="token_form" method="POST" action="<?php echo $this->getTransactionUrl() ?>">
    <input type="hidden" name="SECURETOKEN" value="<?php echo $this->getSecureToken(); ?>"/>
    <input type="hidden" name="SECURETOKENID" value="<?php echo $this->getSecureTokenId(); ?>"/>
    <input type="hidden" name="MODE" value="<?php echo $this->isTestMode() ? 'TEST' : 'LIVE'; ?>"/>
</form>
<script type="text/javascript">
    document.getElementById('token_form').submit();
</script>
</body>
</html>
