<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Paypal\Block\Payflow\Advanced\Form;

/** @var Escaper $escaper */
/** @var Form $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>
<fieldset id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>"
          class="fieldset payflowadvanced items redirect">
    <div>
        <?= $escaper->escapeHtml(__('You will be required to enter your payment details after you place an order.')) ?>
    </div>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    'fieldset#payment_form_' . $escaper->escapeHtml($block->getMethodCode())
) ?>
