<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */

/**
 * @var $this \Magento\Paypal\Block\Payflow\Advanced\Form
 */
?>
<fieldset id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="fieldset payflowadvanced items redirect">
    <div><?php echo __('You will be required to enter your payment details after you place an order.') ?></div>
</fieldset>
