<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div id="product_composite_configure" class="product-configure-popup">
    <iframe name="product_composite_configure_iframe" id="product_composite_configure_iframe"></iframe>
    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onload',
        "window.productConfigure && productConfigure.onLoadIFrame()",
        '#product_composite_configure_form'
    ) ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "width:0; height:0; border:0px solid #fff; position:absolute; top:-1000px; left:-1000px",
        '#product_composite_configure_confirmed'
    ) ?>

    <form action="" method="post" id="product_composite_configure_form" enctype="multipart/form-data"
          target="product_composite_configure_iframe">
        <div class="entry-edit">
            <div id="product_composite_configure_messages">
                <div class="messages"><div class="message message-error error"><div></div></div></div>
            </div>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                'display:none;',
                '#product_composite_configure_messages'
            ) ?>
            <div id="product_composite_configure_form_fields" class="content product-composite-configure-inner"></div>
            <div id="product_composite_configure_form_additional"></div>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                'display:none;',
                '#product_composite_configure_form_additional'
            ) ?>
            <div id="product_composite_configure_form_confirmed"></div>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                'display:none;',
                '#product_composite_configure_form_confirmed'
            ) ?>
        </div>
        <input type="hidden" name="as_js_varname" value="iFrameResponse" />
        <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>" />
    </form>
    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onsubmit',
        "productConfigure.onConfirmBtn(); return false;",
        '#product_composite_configure_form'
    ) ?>

    <div id="product_composite_configure_confirmed"></div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        'display:none;',
        '#product_composite_configure_confirmed'
    ) ?>

    <?php $scriptString = <<<script
        require([
            "jquery",
            "mage/mage"
        ], function(jQuery){

            jQuery('#product_composite_configure_form').mage('form').mage('validation');

        });
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    '#product_composite_configure'
) ?>

