<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>

<div class="cards-list">

<?php if (!$this->getHideTitle()): ?>
    <div class="bold"><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></div>
<?php endif;?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

    <?php foreach ($cards as $key => $card): ?>
        <?php if ($showCount): ?>
            <span><?php echo __('Credit Card %1', $key + 1); ?></span>
        <?php endif;?>

        <table class="data-table<?php if ($showCount):?> offset<?php endif;?>">
            <tbody>
            <?php foreach ($card as $_label => $_value):?>
            <tr>
                <th><?php echo $this->escapeHtml($_label)?>:</th>
                <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endforeach; ?>

</div>
