<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php /* @escapeNotVerified */ echo $block->getSomeData();?>
<?php /* @noEscape */ echo $block->getSomeData();?>
<input name="form_key" type="hidden" value="<?php echo $block->escapeUrl($var) ?>" />
<input name="form_key" type="hidden" value="<?php echo $block->escapeHtmlAttr('value') ?>" />
<input name="form_key" type="hidden" value="<?php echo $block->escapeJs('value') ?>" />
<?php echo $block->escapeCss('value') ?>
echo $var;
<?php echo $block->getHtmlId("some value") ?>
<?php echo $block->getIdHtml("some value") ?>
<?= $block->getIdHtml("some value"); ?>
<?php echo "\$var1"; ?>
<?php echo '$var'; ?>
<?php echo "value"; ?>
<?php echo 'value'; ?>
<?php echo (int)$var; ?>
<?php echo (bool)$var; ?>
<?php echo count($var); ?>
<?php echo $object->methodHtml(); ?>
<?php pecho($var);?>
<?php echo $object->methodHtml() .
    (bool)$var .
    $block->escapeUrl("some value");
?>
<?php /* @noEscape */ echo '\'' . $code . '\',\'' . $block->escapeHtml($data['parentSymbol']) . '\''; ?>
<?= $block->getExtendedElement($switchAttributeCode)->toHtml(); ?>
<?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>
<?php
/**
 * echo $someVar;
 */
?>

<?php
/* This part is commented to remove all <col> tags from the code. */
/* foreach ($block->getColumns() as $_column): ?>
    <col <?php echo $_column->getProperty() ?> />
<?php endforeach; */ ?>

<?php echo $block->escapeHtmlAttr($block->getParamValue('title_' . $store['value'])); ?>
