<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php echo $block->getSomeData();?>
<?=  $block->getTitle();?>
<?php echo $object->getSomeMethod($block->getHtmlId());?>
<?php echo "Title: $title";?>
<?php echo $block->escapeUrl($var) . $var . 'bla';?>
<?php echo $var;?>
<?= $someVar?>
<?php echo __("bla");?>

<?php echo $object->methodHtml() .
    $var .
    $block->getSomeData();
?>
<?php echo '\'' . $code . '\',\'' . $block->escapeQuote($data['parentSymbol']) . '\''; ?>
<?php echo "\"" . $code . "\",\"" . $block->escapeQuote($data['parentSymbol']) . "\""; ?>

<?php
/* This part is commented to remove all <col> tags from the code. */
/* foreach ($block->getColumns() as $_column): ?>
    <col <?php echo $_column->getProperty() ?> />
<?php endforeach; */ ?>
