<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\Checkbox */ ?>
<?php
/** @var $element \Magento\Framework\Data\Form\Element\Checkbox */
$element = $this->getElement();
?>

<?php echo $this->getHtml() ?>

<script type="text/javascript">
require(['jquery'], function($){

    var checkbox = document.getElementById('<?php echo $element->getHtmlId() ?>');
    $(checkbox).on('quickStyleElementBeforeChange', function(e) {
        var checkbox = $(e.target);
        if (checkbox && checkbox.attr('checked')) {
            checkbox.val('<?php echo $element->getValue() ?>');
        } else {
            checkbox.val('<?php echo $element->getUncheckedValue() ?>');
        }
    });

});
</script>
