<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var $block \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\ColorPicker */ ?>
<?php /** @var $element \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Element\ColorPicker */ ?>
<?php $element = $block->getElement(); ?>

<div class="color-box" style="background-color:<?php echo $element->getValue() ?>;"></div>
<?php echo $block->getHtml() ?>
