<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\Composite */ ?>
<?php
/** @var $element \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Element\Composite\AbstractComposite */
$element = $this->getElement();
$containerId = $element->getFieldsetContainerId();
$id = $element->getHtmlId();
$isCollapsable = $element->getCollapsable();
$isWrapped = $containerId || $element->getHeaderBar() || $isCollapsable;
$isField = $element->getFieldsetType() == 'field';
$advancedAfter = $element->getAdvancedPosition() == 'after'; // To place advanced options inside or after fieldset
?>

    <?php if (!$element->getNoContainer()): ?>
        <fieldset class="<?php echo join(' ', $this->getCssClasses()) ?>" id="<?php echo $id ?>">
        <?php if ($element->getLegend() && !$isWrapped): ?>
            <legend class="<?php echo $isField ? 'label' : 'legend'?>">
                <span><?php echo $element->getLegend() ?></span>
            </legend>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($element->getComment() && !$isField): ?>
        <div class="comment"><?php echo $this->escapeHtml($element->getComment()) ?></div>
    <?php endif; ?>

    <?php echo($isField) ? '<div class="control">' : ''; ?>

    <?php if ($element->hasHtmlContent() && !$isField): ?>
        <?php echo $element->getHtmlContent(); ?>
    <?php else: ?>

        <?php $count = $element->getCountBasicChildren(); ?>

        <?php if ($isField && $count > 1):?>
            <div class="fields-group-<?php echo $count?>">
        <?php endif; ?>

        <?php echo $this->getHtml(); ?>

        <?php echo($isField && $count > 1) ? '</div>' : '' ?>

        <?php if ($element->getComment() && $isField): ?>
            <div class="note"><?php echo $this->escapeHtml($element->getComment()) ?></div>
        <?php endif; ?>

        <?php if ($element->hasAdvanced() && !$isField): ?>
            <?php echo(!$element->getNoContainer() && $advancedAfter)  ? '</fieldset>' : ''?>
            <details class="details" id="details<?php echo $id ?>">
                <summary class="details-summary" id="details-summary<?php echo $id ?>">
                    <span><?php echo $element->getAdvancedLabel() ?></span>
                </summary>
                <div class="details-content" id="details-content<?php echo $id ?>">
                    <?php echo $element->getAdvancedChildrenHtml(); ?>
                </div>
            </details>
        <?php elseif ($element->hasAdvanced() && $isField): ?>
            <div class="nested" id="nested<?php echo $id ?>">
                <?php echo $element->getAdvancedChildrenHtml(); ?>
            </div>
        <?php endif; ?>

        <?php echo($isField) ? '</div>' : ''; ?>

    <?php endif; ?>


    <?php if (!$element->getNoContainer() && !$advancedAfter): ?>
        </fieldset>
    <?php endif; ?>
