<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\Font */ ?>
<?php
/** @var $element \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Element\Font */
$element = $this->getElement();
?>

<fieldset class="<?php echo join(' ', $this->getClasses()) ?>" id="<?php echo $element->getHtmlId() ?>">
    <legend class="legend">
        <span><?php echo $element->getLegend(); ?></span>
    </legend>
    <?php echo $element->getChildrenHtml(); ?>
</fieldset>
