<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Downloadable\Block\Sales\Order\Email\Items\Order\Downloadable */ ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder() ?>
<tr>
    <td class="item-info has-extra">
        <p class="product-name"><?php echo $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?php echo /* @escapeNotVerified */  __('SKU') ?>: <?php echo $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
        <dl>
            <?php foreach ($block->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
            <dd><?php echo /* @escapeNotVerified */  $option['value'] ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php if ($links = $block->getLinks()->getPurchasedItems()): ?>
        <dl>
            <dt><strong><em><?php echo /* @escapeNotVerified */  $block->getLinksTitle() ?></em></strong></dt>
            <?php foreach ($links as $link): ?>
                <dd>
                    <?php echo $block->escapeHtml($link->getLinkTitle()) ?>&nbsp;
                    (<a href="<?php echo /* @escapeNotVerified */  $block->getPurchasedLinkUrl($link) ?>"><?php echo /* @escapeNotVerified */  __('download') ?></a>)
                </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
        <?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?php echo /* @escapeNotVerified */  __('Gift Message') ?></h3>
                        <strong><?php echo /* @escapeNotVerified */  __('From:') ?></strong> <?php echo $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?php echo /* @escapeNotVerified */  __('To:') ?></strong> <?php echo $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?php echo /* @escapeNotVerified */  __('Message:') ?></strong>
                        <br /><?php echo $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    </td>
    <td class="item-qty"><?php echo /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?php echo /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
    </td>
</tr>
