<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $this \Magento\Tax\Block\Checkout\Grandtotal
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax() >= 0):?>
<tr class="grand totals excl">
    <th style="<?php echo $this->getStyle() ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <strong><?php echo __('Grand Total Excl. Tax')?></strong>
    </th>
    <td style="<?php echo $this->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml(__('Grand Total Excl. Tax')); ?>">
        <strong><?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
</tr>
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<tr class="grand totals incl">
    <th style="<?php echo $this->getStyle() ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <strong><?php echo __('Grand Total Incl. Tax')?></strong>
    </th>
    <td style="<?php echo $this->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml(__('Grand Total Incl. Tax')); ?>">
        <strong><?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php else:?>
<tr class="grand totals">
    <th style="<?php echo $this->getStyle() ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <strong><?php echo $this->getTotal()->getTitle() ?></strong>
    </th>
    <td style="<?php echo $this->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>">
        <strong><?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php endif;?>
