<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $this \Magento\Tax\Block\Checkout\Shipping
 * @see \Magento\Tax\Block\Checkout\Shipping
 */
?>
<?php if ($this->displayBoth()):?>
<tr class="totals shipping excl">
    <th style="<?php echo $this->getStyle() ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <?php echo $this->getExcludeTaxLabel() ?>
    </th>
    <td style="<?php echo $this->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml($this->getExcludeTaxLabel()); ?>">
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
</tr>
<tr class="totals shipping incl">
    <th style="<?php echo $this->getStyle() ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <?php echo $this->getIncludeTaxLabel() ?>
    </th>
    <td style="<?php echo $this->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml($this->getIncludeTaxLabel()); ?>">
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
</tr>
<?php elseif ($this->displayIncludeTax()) : ?>
<tr class="totals shipping incl">
    <th style="<?php echo $this->getStyle() ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <?php echo $this->getTotal()->getTitle() ?>
    </th>
    <td style="<?php echo $this->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>">
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
</tr>
<?php else:?>
<tr class="totals shipping excl">
    <th style="<?php echo $this->getStyle() ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <?php echo $this->escapeHtml($this->getTotal()->getTitle()) ?>
    </th>
    <td style="<?php echo $this->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>">
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
</tr>
<?php endif;?>
