<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Tax\Block\Checkout\Subtotal
 * @see \Magento\Tax\Block\Checkout\Subtotal
 */
?>
<?php if ($block->displayBoth()):?>
<tr class="totals sub excl">
    <th style="<?php echo /* @escapeNotVerified */ $block->getStyle() ?>" class="mark" colspan="<?php echo /* @escapeNotVerified */ $block->getColspan() ?>" scope="row">
        <?php echo /* @escapeNotVerified */ __('Subtotal (Excl. Tax)') ?>
    </th>
    <td style="<?php echo /* @escapeNotVerified */ $block->getStyle() ?>" class="amount" data-th="<?php echo $block->escapeHtml(__('Subtotal (Excl. Tax)')) ?>">
        <?php echo /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr class="totals sub incl">
    <th style="<?php echo /* @escapeNotVerified */ $block->getStyle() ?>" class="mark" colspan="<?php echo /* @escapeNotVerified */ $block->getColspan() ?>" scope="row">
        <?php echo /* @escapeNotVerified */ __('Subtotal (Incl. Tax)') ?>
    </th>
    <td style="<?php echo /* @escapeNotVerified */ $block->getStyle() ?>" class="amount" data-th="<?php echo $block->escapeHtml(__('Subtotal (Incl. Tax)')) ?>">
        <?php echo /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else : ?>
<tr class="totals sub">
    <th style="<?php echo /* @escapeNotVerified */ $block->getStyle() ?>" class="mark" colspan="<?php echo /* @escapeNotVerified */ $block->getColspan() ?>" scope="row">
        <?php echo /* @escapeNotVerified */ $block->getTotal()->getTitle() ?>
    </th>
    <td style="<?php echo /* @escapeNotVerified */ $block->getStyle() ?>" class="amount" data-th="<?php echo $block->escapeHtml($block->getTotal()->getTitle()) ?>">
        <?php echo /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif;?>
