<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Tax\Block\Checkout\Subtotal
 * @see \Magento\Tax\Block\Checkout\Subtotal
 */
?>
<?php if ($block->displayBoth()):?>
<tr class="totals sub excl">
    <th style="<?= /* @noEscape */ $block->getStyle() ?>" class="mark" colspan="<?= /* @noEscape */ $block->getColspan() ?>" scope="row">
        <?= $block->escapeHtml(__('Subtotal (Excl. Tax)')) ?>
    </th>
    <td style="<?= /* @noEscape */ $block->getStyle() ?>" class="amount" data-th="<?= $block->escapeHtml(__('Subtotal (Excl. Tax)')) ?>">
        <?= /* @noEscape */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr class="totals sub incl">
    <th style="<?= /* @noEscape */ $block->getStyle() ?>" class="mark" colspan="<?= /* @noEscape */ $block->getColspan() ?>" scope="row">
        <?= $block->escapeHtml(__('Subtotal (Incl. Tax)')) ?>
    </th>
    <td style="<?= /* @noEscape */ $block->getStyle() ?>" class="amount" data-th="<?= $block->escapeHtml(__('Subtotal (Incl. Tax)')) ?>">
        <?= /* @noEscape */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else : ?>
<tr class="totals sub">
    <th style="<?= /* @noEscape */ $block->getStyle() ?>" class="mark" colspan="<?= /* @noEscape */ $block->getColspan() ?>" scope="row">
        <?= $block->escapeHtml($block->getTotal()->getTitle()) ?>
    </th>
    <td style="<?= /* @noEscape */ $block->getStyle() ?>" class="amount" data-th="<?= $block->escapeHtml($block->getTotal()->getTitle()) ?>">
        <?= /* @noEscape */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif;?>
