<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Tax\Block\Checkout\Tax
 * @see \Magento\Tax\Block\Checkout\Tax
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
    $_value = $block->getTotal()->getValue();
    $_style = $block->escapeHtmlAttr($block->getTotal()->getStyle());
    $jsonHelper = $block->getData('jsonHelper');
    $attributes = 'class="totals-tax"';

if ($jsonHelper->displayFullSummary() && $_value != 0) {
    $attributes = 'class="totals-tax-summary" data-mage-init=\'{"toggleAdvanced": {"selectorsToggleClass": "shown",
     "baseToggleClass": "expanded", "toggleContainers": ".totals-tax-details"}}\'';
}
?>

<tr <?= /* @noEscape */ $attributes ?>>
    <th class="mark" colspan="<?= (int) $block->getColspan() ?>" scope="row">
        <?php if ($jsonHelper->displayFullSummary()): ?>
            <span class="detailed"><?= $block->escapeHtml($block->getTotal()->getTitle()) ?></span>
        <?php else: ?>
            <?= $block->escapeHtml($block->getTotal()->getTitle()) ?>
        <?php endif; ?>
    </th>
    <td class="amount" data-th="<?= $block->escapeHtmlAttr($block->getTotal()->getTitle()) ?>">
        <?= /* @noEscape */ $jsonHelper->formatPrice($_value) ?>
    </td>
</tr>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax th.mark') ?>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax td.amount') ?>

<?php if ($jsonHelper->displayFullSummary() && $_value != 0): ?>
    <?php foreach ($block->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) { continue; } ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
            <tr class="totals-tax-details">
                <th class="mark" colspan="<?= (int) $block->getColspan() ?>" scope="row">
                    <?= $block->escapeHtml($rate['title']) ?>
                    <?php if ($rate['percent'] !== null): ?>
                        (<?= (float) $rate['percent'] ?>%)
                    <?php endif; ?>
                </th>
                <?php if ($isFirst): ?>
                    <td class="amount" rowspan="<?= count($rates) ?>"
                       data-th="<?= $block->escapeHtmlAttr($rate['title']) ?>
                        <?php if ($rate['percent'] !== null): ?>(<?= (float) $rate['percent'] ?>%)<?php endif; ?>">
                        <?= /* @noEscape */ $jsonHelper->formatPrice($amount) ?>
                    </td>
                <?php endif; ?>
            </tr>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax-details th.mark') ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax-details td.amount') ?>
            <?php $isFirst = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>
