<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Magento\Paypal\Block\Adminhtml\System\Config\ApiWizard
 * @var \Magento\Paypal\Block\Adminhtml\System\Config\ApiWizard $block
 */
?>
<div class="pp-buttons-container">
    <button onclick="javascript:window.open(
            '<?php echo $block->escapeUrl($block->getButtonUrl()); ?>',
            'apiwizard',
            'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,' +
            'left=100, top=100, width=380, height=470'
        ); return false;"
            class="scalable" type="button" id="<?php echo $block->escapeHtml($block->getHtmlId()); ?>">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
    <button onclick="javascript:window.open(
            '<?php echo $block->escapeUrl($block->getSandboxButtonUrl()); ?>',
            'apiwizard',
            'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,' +
            'left=100, top=100, width=380, height=470'
        ); return false;"
            class="scalable" type="button" id="<?php echo $block->escapeHtml($block->getSandboxHtmlId()); ?>">
        <span><span><span><?php echo $block->escapeHtml($block->getSandboxButtonLabel()); ?></span></span></span>
    </button>
</div>
