<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Adminhtml\System\Config\ResolutionRules $block
 */

?>
<script>
    require([
        "Magento_Paypal/js/solutions",
        "domReady!"
    ], function (Solutions) {
        var solutions = new Solutions({config: {solutions: <?php /* @noEscape */ echo $block->getJson(); ?>}});
    });
</script>
