<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="gift-options-cart" data-bind="scope:'giftOptionsCart'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#gift-options-cart": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.giftOptionsConfig = <?php /* @escapeNotVerified */ echo $block->getGiftOptionsConfigJson(); ?>;
    </script>
</div>
