<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div id="checkout-cart-options" data-bind="scope:'checkoutCartOptions'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout-cart-options": {
                "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.cartOptionsConfig = <?php echo $block->getOptionsConfigJson(); ?>;
    </script>
</div>
