<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<h4>
    <?php echo $block->escapeHtml(__('A conflict has occurred between the product\'s URL and other URL.')); ?>
</h4>
<p>
    <?php echo $block->escapeHtml(
        __('As a result, you cannot access this product through the specified URL:')
    ); ?>
    <i>
        <?php echo $block->getData('urls');?>
    </i>
    <br>
    <?php echo $block->escapeHtml(
        __('To fix the conflict, navigate to Search Engine Optimization section, then edit the URL key to make it unique.')
    );
    ?>
</p>