<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\File */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_fileInfo = $block->getFileInfo(); ?>
<?php $_fileExists = $_fileInfo->hasData(); ?>
<?php $_fileName = 'options_' . $_option->getId() . '_file'; ?>
<?php $_fieldNameAction = $_fileName . '_action'; ?>
<?php $_fieldValueAction = $_fileExists ? 'save_old' : 'save_new'; ?>
<?php $_fileNamed = $_fileName . '_name'; ?>
<?php $class = ($_option->getIsRequire()) ? ' required' : ''; ?>

<div class="field file<?php echo /* @escapeNotVerified */ $class ?>">
    <label class="label" for="<?php echo /* @noEscape */ $_fileName ?>" id="<?php echo /* @noEscape */ $_fileName ?>-label">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
        <?php echo /* @escapeNotVerified */ $block->getFormattedPrice() ?>
    </label>
    <?php if ($_fileExists): ?>
    <div class="control">
        <span class="<?php echo /* @noEscape */ $_fileNamed ?>"><?php echo $block->escapeHtml($_fileInfo->getTitle()) ?></span>
        <a href="javascript:void(0)" class="label" id="change-<?php echo /* @noEscape */ $_fileName ?>" >
            <?php echo /* @escapeNotVerified */ __('Change') ?>
        </a>
        <?php if (!$_option->getIsRequire()): ?>
            <input type="checkbox" id="delete-<?php echo /* @escapeNotVerified */ $_fileName ?>" />
            <span class="label"><?php echo /* @escapeNotVerified */ __('Delete') ?></span>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="control" id="input-box-<?php echo /* @escapeNotVerified */ $_fileName ?>"
             data-mage-init='{"priceOptionFile":{
                "fileName":"<?php echo /* @noEscape */ $_fileName ?>",
                "fileNamed":"<?php echo /* @noEscape */ $_fileNamed ?>",
                "fieldNameAction":"<?php echo /* @escapeNotVerified */ $_fieldNameAction ?>",
                "changeFileSelector":"#change-<?php echo /* @escapeNotVerified */ $_fileName ?>",
                "deleteFileSelector":"#delete-<?php echo /* @escapeNotVerified */ $_fileName ?>"}
             }'
            <?php echo $_fileExists ? 'style="display:none"' : '' ?>>
        <input type="file"
               name="<?php echo /* @escapeNotVerified */ $_fileName ?>"
               id="<?php echo /* @escapeNotVerified */ $_fileName ?>"
               class="product-custom-option<?php echo $_option->getIsRequire() ? ' required' : '' ?>"
               <?php echo $_fileExists ? 'disabled="disabled"' : '' ?> />
        <input type="hidden" name="<?php echo /* @escapeNotVerified */ $_fieldNameAction ?>" value="<?php echo /* @escapeNotVerified */ $_fieldValueAction ?>" />
        <?php if ($_option->getFileExtension()): ?>
            <p class="note">
                <?php echo /* @escapeNotVerified */ __('Compatible file extensions to upload') ?>: <strong><?php echo /* @escapeNotVerified */ $_option->getFileExtension() ?></strong>
            </p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeX() > 0): ?>
            <p class="note">
                <?php echo /* @escapeNotVerified */ __('Maximum image width') ?>: <strong><?php echo /* @escapeNotVerified */ $_option->getImageSizeX() ?> <?php echo /* @escapeNotVerified */ __('px.') ?></strong>
            </p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeY() > 0): ?>
            <p class="note">
                <?php echo /* @escapeNotVerified */ __('Maximum image height') ?>: <strong><?php echo /* @escapeNotVerified */ $_option->getImageSizeY() ?> <?php echo /* @escapeNotVerified */ __('px.') ?></strong>
            </p>
        <?php endif; ?>
    </div>
</div>
