<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Translation\Block\Html\Head\Dictionary $block  */
?>
<link rel="preload" as="script" src="<?= $block->getTranslationDictionaryFile() ?>">
<script>
    require.config({
        map: {
            '*': {
                'dictionary': '<?= $block->getTranslationDictionaryFile() ?>'
            }
        }
    });
</script>
