<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Translation\Block\Js */ ?>
<?php if ($block->dictionaryEnabled()): ?>
    <script>
        require.config({
            config: {
                'mage/advancedtranslate': {
                    currentVersion: '<?php echo sha1($block->getTranslationFileTimestamp() . $block->getTranslationFilePath()) ?>',
                    dictFile: '<?php echo Magento\Translation\Model\Js\Config::DICTIONARY_FILE_NAME; ?>'
                }
            }
        });
        define("mage/advancedtranslate",
            [
                'jquery',
                'mage/translate',
                'jquery/jquery-storageapi',
                'module'
            ],
            function ($, translate, storageApi, module) {
                console.log("Started Advancedtranslate...");
                var versionObj;

                $.initNamespaceStorage('mage-translation-storage');
                $.initNamespaceStorage('mage-translation-file-version');
                versionObj = $.localStorage.get('mage-translation-file-version');

                var text = null;
                // Comment out for fetching all translations only over AJAX and not over LocalStorage
                //versionObj.version = null;
                if (versionObj.version !== module.config().currentVersion) {
                    var url = require.toUrl(module.config().dictFile);
                    console.log("Mismatch of Versions...");
                    console.log("Getting the Data from " + url);
                    text = $.ajax({
                        type: "GET",
                        url: url,
                        cache: false,
                        async: false
                    }).responseText;
                    //console.log(text);
                }


                if (typeof text === 'string') {

                    $.mage.translate.add(JSON.parse(text));
                    $.localStorage.set('mage-translation-storage', text);
                    $.localStorage.set(
                        'mage-translation-file-version',
                        {
                            version: module.config().currentVersion
                        }
                    );
                } else {
                    $.mage.translate.add($.localStorage.get('mage-translation-storage'));
                }
            }
        );

        require(['mage/advancedtranslate'], function () {

        });

    </script>
<?php endif; ?>
