<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\CustomerData $block */
/** @var \Magento\Customer\ViewModel\Customer\Data $viewModel */
$viewModel = $block->getViewModel();
$customerDataUrl = $block->getCustomerDataUrl('customer/account/updateSession');
$expirableSectionNames = $block->getExpirableSectionNames();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/customer-data": {
                "sectionLoadUrl": "<?= $block->escapeJs($block->getCustomerDataUrl('customer/section/load')) ?>",
                "expirableSectionLifetime": <?= (int)$block->getExpirableSectionLifetime() ?>,
                "expirableSectionNames": <?= /* @noEscape */ $viewModel->jsonEncode($expirableSectionNames) ?>,
                "cookieLifeTime": "<?= $block->escapeJs($block->getCookieLifeTime()) ?>",
                "updateSessionUrl": "<?= $block->escapeJs($customerDataUrl) ?>",
                "isLoggedIn": "<?= /* @noEscape */ $viewModel->isLoggedIn() ?>"
            }
        }
    }
</script>
