<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\CustomerData $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/customer-data": {
                "sectionLoadUrl": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getCustomerDataUrl('customer/section/load'))) ?>",
                "expirableSectionLifetime": <?= (int)$block->getExpirableSectionLifetime() ?>,
                "expirableSectionNames": <?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getExpirableSectionNames()) ?>,
                "cookieLifeTime": "<?= $escaper->escapeJs($block->getCookieLifeTime()) ?>",
                "updateSessionUrl": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getCustomerDataUrl('customer/account/updateSession'))) ?>"
            }
        }
    }
</script>
