<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Customer\Block\SectionConfig;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var SectionConfig $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/section-config": {
                "sections": <?= /* @noEscape */ $escaper->escape->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getSections()) ?>,
                "clientSideSections": <?= /* @noEscape */ $escaper->escape->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getClientSideSections()) ?>,
                "baseUrls": <?= /* @noEscape */ $escaper->escape->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode(array_unique([
                    $block->getUrl(null, ['_secure' => true]),
                    $block->getUrl(null, ['_secure' => false]),
                ])) ?>,
                "sectionNames": <?= /* @noEscape */ $escaper->escape->helper(\Magento\Framework\Json\Helper\Data::class)
                    ->jsonEncode($block->getData('sectionNamesProvider')->getSectionNames()) ?>
            }
        }
    }
</script>
