<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Customer\Block\SectionConfig $block
 */
?>
<script type="text/x-magento-init">
<?php
    /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode([
        '*' => ['Magento_Customer/js/section-config' => [
            'sections' => $block->getSections(),
            'clientSideSections' => $block->getClientSideSections(),
            'baseUrls' => array_unique([
                $block->getUrl(null, ['_secure' => true]),
                $block->getUrl(null, ['_secure' => false]),
            ]),
        ]],
    ]);
?>
</script>
