<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://example.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="ExampleService" targetNamespace="http://example.com">
    <types>
        <xsd:schema targetNamespace="http://example.com">
            <xsd:element name="triggerError">
                <xsd:complexType/>
            </xsd:element>
        </xsd:schema>
    </types>
    <portType name="ExampleServicePort">
        <operation name="triggerError">
            <documentation>triggerError</documentation>
            <input message="tns:triggerErrorIn"/>
        </operation>
    </portType>
    <binding name="ExampleServiceBinding" type="tns:ExampleServicePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="triggerError">
            <soap:operation soapAction="http://example.com#triggerError"/>
            <input>
                <soap:body use="literal"/>
            </input>
        </operation>
    </binding>
    <service name="ExampleServiceService">
        <port name="ExampleServicePort" binding="tns:ExampleServiceBinding">
            <soap:address location="http://example.com"/>
        </port>
    </service>
    <message name="triggerErrorIn">
        <part name="parameters" element="tns:triggerError"/>
    </message>
</definitions>
