<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
return [
    '/app\/code\/Magento\/Webapi\/Api\/Data\/ClientInterface\.php/',
    '/app\/code\/Magento\/Webapi\/Api\/Data\/ComplexTypeStrategyInterface\.php/',
    '/app\/code\/Magento\/Webapi\/Api\/Data\/DiscoveryStrategyInterface\.php/',
    '/app\/code\/Magento\/Webapi\/Api\/Data\/DocumentationStrategyInterface\.php/',
    '/app\/code\/Magento\/Webapi\/Api\/Data\/ServerInterface\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Client\/Common\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Client\/Local\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/AbstractComplexTypeStrategy\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/AnyType\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/ArrayOfTypeComplex\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/ArrayOfTypeSequence\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/Composite\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/DefaultComplexType\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/DiscoveryStrategy\/ReflectionDiscovery\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/DocumentationStrategy\/ReflectionDocumentation\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Exception\/ExtensionNotLoadedException\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Exception\/InvalidArgumentException\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Exception\/RuntimeException\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Exception\/UnexpectedValueException\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/AutoDiscover\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Client\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Server\.php/',
    '/app\/code\/Magento\/Webapi\/Model\/Laminas\/Soap\/Wsdl\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/AutoDiscoverTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/ClientTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/ServerTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/WsdlTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/WsdlTestHelper\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/ArrayOfTypeComplexStrategyTest\.php/', // phpcs:ignore
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/ArrayOfTypeSequenceStrategyTest\.php/', // phpcs:ignore
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/CompositeStrategyTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/ComplexTypeStrategy\/DefaultComplexTypeTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/DocumentationStrategy\/ReflectionDocumentationTest\.php/', // phpcs:ignore
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscover\/MyResponse\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscover\/MyService\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscover\/MyServiceSequence\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscover\/NoReturnType\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscover\/Recursion\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscover\/TestFixingMultiplePrototypes\.php/', // phpcs:ignore
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/CompositeStrategyTest\/Anything\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/CompositeStrategyTest\/Book\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/CompositeStrategyTest\/Cookie\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscoverTestClass1\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/AutoDiscoverTestClass2\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/ComplexObjectStructure\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/ComplexObjectWithObjectStructure\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/ComplexTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/ComplexTypeA\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/ComplexTypeB\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/errorClass\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/MockServer\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/MockSoapServer\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/PropertyDocumentationTestClass\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/PublicPrivateProtected\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/SequenceTest\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/ServerTestClass\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/test-functions\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/TestClass\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/TestData1\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/TestData2\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/TestLocalSoapClient\.php/',
    '/app\/code\/Magento\/Webapi\/Test\/Unit\/Model\/Laminas\/Soap\/TestAsset\/WsdlTestClass\.php/',
];
