<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php /** @var $this \Magento\Authorizenet\Block\Authorizenet\Form\Cc */ ?>

<?php $_formMessage = $this->getPartialAuthorizationFormMessage(); ?>
<?php $_isPartialAuthorization = $this->isPartialAuthorization(); ?>
<?php if ($_isPartialAuthorization || $_formMessage): ?>
<div class="form-list items" id="payment_form_<?php echo $this->getMethodCode() ?>_before" style="display:none;">
    <?php if ($_formMessage): ?>
    <?php echo $this->showNoticeMessage($_formMessage) ?>
    <?php endif;?>

    <?php if ($this->isPartialAuthorization()): ?>
        <?php echo $this->getChildHtml('cards') ?>
        <div class="release-amounts"
             data-container="release-amounts"
             data-mage-init='<?php echo $this->escapeMessage($this->getWidgetInitData()); ?>'>
            <button class="button" type="button" id="payment-button-cancel" name="cancel"><span><span>Cancel</span></span></button>
            <span><?php echo __('To cancel pending authorizations and release amounts that have already been processed during this payment, click Cancel.') ?></span>
        </div>
        <?php echo $this->showNoticeMessage(__('Please enter a different credit card number to complete your purchase.')) ?>

        <span id="cancel-please-wait" class="please-wait load indicator" style="display: none" data-text="<?php echo __('Processing...') ?>">
            <span><?php echo __('Processing...') ?></span>
        </span>
    <?php endif;?>
</div>
<?php endif;?>
<?php echo $this->getChildHtml('method_form_block') ?>
