<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\AdminNotification\Block\System\Messages\UnreadMessagePopup $block */
?>

<div style="display:none" id="system_messages_list" data-role="system_messages_list"
     title="<?= $escaper->escapeHtmlAttr($block->getPopupTitle()) ?>">
    <ul class="message-system-list messages">
        <?php foreach ($block->getUnreadMessages() as $message) : ?>
            <li class="message message-warning <?= $escaper->escapeHtmlAttr($block->getItemClass($message)) ?>">
                <?= $escaper->escapeHtml($message->getText()) ?>
            </li>
        <?php endforeach;?>
    </ul>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=system_messages_list]": {
            "Magento_AdminNotification/js/system/messages/popup": {
                "class":"modal-system-messages ui-popup-message"
            }
        }
    }
</script>
