<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\AdminNotification\Block\System\Messages\UnreadMessagePopup */ ?>
<div id="system_messages_list" title="<?php echo $this->escapeHtml($this->getPopupTitle()); ?>">
    <ul class="message-system-list">
        <?php foreach ($this->getUnreadMessages() as $message): ?>
            <li class="<?php echo $this->getItemClass($message);?>">
                <?php echo $message->getText();?>
            </li>
        <?php endforeach;?>
    </ul>
</div>
<script type="text/javascript">
require([
    "jquery",
    "jquery/ui"
], function($){

    $(function() {
        $("#system_messages_list").dialog({
            autoOpen: true,
            resizable: false,
            width: 650,
            position: {
                using: function(pos) {
                    $(this).css({
                        "position": "absolute",
                        "top": Math.ceil($(window).height()/2 - $(this).height()/2),
                        "left": pos.left
                    });
                }
            }
        });
    });

});
</script>
