<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Reports\Block\Adminhtml\Grid */
$numColumns = sizeof($block->getColumns());
?>
<?php if ($block->getCollection()): ?>
<?php if ($block->canDisplayContainer()): ?>
    <div id="<?php echo $block->getId() ?>">
<?php else: ?>
    <?php echo $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<?php endif; ?>
<?php if ($block->getStoreSwitcherVisibility() || $block->getDateFilterVisibility()): ?>
    <div class="grid-actions">
        <?php if ($block->getChildBlock('grid.export')): ?>
        <div class="export">
            <?php echo $block->getChildHtml('grid.export');?>
        </div>
        <?php endif; ?>
        <?php if ($block->getDateFilterVisibility()): ?>
        <div class="filter required" id="<?php echo $block->getSuffixId('period_date_range')?>">
            <div class="field date">
                <label class="label">
                    <span><?php echo __('From') ?>:</span>
                    <input class="input-text no-changes required-entry"
                           type="text"
                           id="<?php echo $block->getSuffixId('period_date_from') ?>"
                           name="report_from"
                           value="<?php echo $block->getFilter('report_from') ?>">
                    <div id="<?php echo $block->getSuffixId('period_date_from_advice')?>"></div>
                </label>
            </div>

            <div class="field date">
                <label class="label">
                    <span><?php echo __('To') ?>:</span>
                    <input class="input-text no-changes required-entry"
                           type="text"
                           id="<?php echo $block->getSuffixId('period_date_to') ?>"
                           name="report_to"
                           value="<?php echo $block->getFilter('report_to') ?>"/>
                    <div id="<?php echo $block->getSuffixId('period_date_to_advice')?>"></div>
                </label>
            </div>

            <div class="show-by">
                <label class="label">
                    <span><?php echo __('Show By') ?>:</span>
                    <select name="report_period" id="<?php echo $block->getSuffixId('report_period')?>" class="select">
                        <?php foreach ($block->getPeriods() as $_value => $_label): ?>
                        <option value="<?php echo $_value ?>" <?php if ($block->getFilter('report_period') == $_value): ?> selected<?php endif; ?>><?php echo $_label ?></option>
                        <?php endforeach; ?>
                    </select>
                </label>
                <?php echo $block->getRefreshButtonHtml() ?>
            </div>
            <script>
require([
    "jquery",
    "mage/calendar"
], function($){

    $("#<?php echo $block->getSuffixId('period_date_range') ?>").dateRange({
        dateFormat:"<?php echo $block->getDateFormat() ?>",
        buttonImage:"<?php echo $block->getViewFileUrl('images/grid-cal.png') ?>",
        buttonText:"<?php echo __('Select Date') ?>",
        from:{
            id:"<?php echo $block->getSuffixId('period_date_from')?>"
        },
        to:{
            id:"<?php echo $block->getSuffixId('period_date_to')?>"
        }
    });
});
</script>
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
    <div class="grid">
        <div class="hor-scroll">
            <table cellspacing="0" class="data" id="<?php echo $block->getId() ?>_table">
                <!-- Rendering column set -->
                <?php echo $block->getChildHtml('grid.columnSet'); ?>
            </table>
        </div>
    </div>
</div>
<?php if ($block->canDisplayContainer()): ?>
    <script>
require([
    "jquery",
    "validation",
    "mage/mage",
    "mage/adminhtml/grid"
], function(jQuery){

        //<![CDATA[
            <?php echo $block->getJsObjectName() ?> = new varienGrid('<?php echo $block->getId() ?>', '<?php echo $block->getGridUrl() ?>', '<?php echo $block->getVarNamePage() ?>', '<?php echo $block->getVarNameSort() ?>', '<?php echo $block->getVarNameDir() ?>', '<?php echo $block->getVarNameFilter() ?>');
            <?php echo $block->getJsObjectName() ?>.useAjax = '<?php if ($block->getUseAjax()): echo $block->getUseAjax(); endif; ?>';
            <?php if ($block->getDateFilterVisibility()): ?>
            <?php echo $block->getJsObjectName() ?>.doFilterCallback = validateFilterDate;
        var period_date_from = $('<?php echo $block->getSuffixId('period_date_from')?>');
        var period_date_to = $('<?php echo $block->getSuffixId('period_date_to')?>');
        period_date_from.adviceContainer = $('<?php echo $block->getSuffixId('period_date_from_advice')?>');
        period_date_to.adviceContainer = $('<?php echo $block->getSuffixId('period_date_to_advice')?>');

        var validateFilterDate = function() {
            if (period_date_from && period_date_to) {
                var valid = true;
                jQuery(period_date_from).add(period_date_to).each(function() {
                    valid = Validation.validate(this) && valid;
                });
                return valid;
            }
            else {
                return true;
            }
        }
            <?php endif;?>
            <?php if ($block->getStoreSwitcherVisibility()): ?>
        /* Overwrite function from switcher.phtml widget*/
        switchStore = function(obj) {
            if (obj.options[obj.selectedIndex].getAttribute('website') == 'true') {
                var selectionType = 'website';
            } else if (obj.options[obj.selectedIndex].getAttribute('group') == 'true') {
                var selectionType = 'group';
            } else {
                var selectionType = 'store';
            }
            var storeParam = obj.value ? selectionType + '/' + obj.value + '/' : '';
            if (obj.switchParams) {
                storeParam += obj.switchParams;
            }
            var formParam = new Array('<?php echo $block->getSuffixId('period_date_from')?>', '<?php echo $block->getSuffixId('period_date_to')?>', '<?php echo $block->getSuffixId('report_period')?>');
            var paramURL = '';
            var switchURL = '<?php echo $block->getAbsoluteGridUrl(['_current' => false]); ?>'.replace(/(store|group|website)\/\d+\//, '');

            for (var i = 0; i < formParam.length; i++) {
                if ($(formParam[i]).value && $(formParam[i]).name) {
                    paramURL += $(formParam[i]).name + '=' + escape($(formParam[i]).value) + '&';
                }
            }
            setLocation(switchURL + storeParam + '?' + paramURL);
        }
            <?php endif; ?>
        //]]>

});
</script>
    <?php endif; ?>
<?php endif; ?>
