<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 /** @var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content */
?>

<div data-mage-init='{"mediabrowser": <?php echo $block->escapeHtml($block->getFilebrowserSetupObject()); ?>}'>
    <div class="side-col"><?php echo $block->getChildHtml('wysiwyg_images.tree') ?></div>
    <div class="main-col">
        <div class="insert-title" id="content_header">
            <div class="insert-title-inner">
                <div class="insert-actions">
                    <?php echo $block->getButtonsHtml() ?>
                </div>
                <div class="title"><?php echo $block->getHeaderText() ?></div>
            </div>
        </div>
        <div id="contents-uploader"><?php echo $block->getChildHtml('wysiwyg_images.uploader') ?></div>
        <div id="contents"></div>
    </div>
</div>
