<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 /** @var \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Tree $this */
?>
<div class="tree-panel" >
    <div class="categories-side-col">
        <div class="tree-actions">
            <a onclick="jQuery('[data-role=tree]').jstree('close_all');"><?php echo __('Collapse All'); ?></a>
            <span class="separator">|</span>
            <a onclick="jQuery('[data-role=tree]').jstree('open_all');"><?php echo __('Expand All'); ?></a>
        </div>
    </div>
    <div data-role="tree" data-mage-init='<?php echo $this->escapeHtml($this->helper('Magento\Core\Helper\Data')->jsonEncode($this->getTreeWidgetOptions())); ?>'>
    </div>
</div>
