<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if ($this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if ($this->getPayableTo()): ?>
        <?php echo __('Make Check payable to: %1', $this->escapeHtml($this->getPayableTo())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
    <?php if ($this->getMailingAddress()): ?>
        <?php echo __('Send Check to:') ?>
        {{pdf_row_separator}}
        <?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
<?php endif; ?>
