<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<section class="page-landing">
    <img class="logo" src="<?php echo $this->basePath() ?>/pub/images/magento-logo.svg" alt="Magento"/>
    <p class="text-welcome">
        Welcome to Magento Admin, your online store headquarters.
        <br>
        Sign into your Admin account to use the Magento setup wizard.
    </p>
</section>
