<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

return [
    'id' => '18',
    'item_id' => '18',
    'quote_id' => '1',
    'created_at' => '2012-07-04 14:54:33',
    'updated_at' => '2012-07-04 15:02:22',
    'product_id' => '5',
    'store_id' => '1',
    'parent_item_id' => null,
    'is_virtual' => '0',
    'sku' => 'sp01',
    'name' => 'Simple Product',
    'description' => null,
    'applied_rule_ids' => '1',
    'additional_data' => null,
    'free_shipping' => '0',
    'is_qty_decimal' => '0',
    'no_discount' => '0',
    'weight' => '1.0000',
    'qty' => 1,
    'price' => 10,
    'base_price' => '10.0000',
    'custom_price' => null,
    'discount_percent' => '10.0000',
    'discount_amount' => '1.0000',
    'base_discount_amount' => '1.0000',
    'tax_percent' => '8.2500',
    'tax_amount' => '0.8300',
    'base_tax_amount' => '0.8300',
    'row_total' => 10,
    'base_row_total' => 10,
    'row_total_with_discount' => '0.0000',
    'row_weight' => '1.0000',
    'product_type' => 'simple',
    'base_tax_before_discount' => null,
    'tax_before_discount' => null,
    'original_custom_price' => null,
    'redirect_url' => null,
    'base_cost' => null,
    'price_incl_tax' => '10.8300',
    'base_price_incl_tax' => '10.8300',
    'row_total_incl_tax' => '10.8300',
    'base_row_total_incl_tax' => '10.8300',
    'discount_tax_compensation_amount' => null,
    'base_discount_tax_compensation_amount' => null,
    'gift_message_id' => null,
    'weee_tax_disposition' => '0.0000',
    'weee_tax_row_disposition' => '0.0000',
    'base_weee_tax_disposition' => '0.0000',
    'base_weee_tax_row_disposition' => '0.0000',
    'weee_tax_applied' => 'a:0:{}',
    'weee_tax_applied_amount' => '0.0000',
    'weee_tax_applied_row_amount' => '0.0000',
    'base_weee_tax_applied_amount' => '0.0000',
    'base_weee_tax_applied_row_amnt' => '0.0000',
    'event_id' => null,
    'gw_id' => null,
    'gw_base_price' => null,
    'gw_price' => null,
    'gw_base_tax_amount' => null,
    'gw_tax_amount' => null,
    'qty_options' => [],
    'product' => null,
    'tax_class_id' => '2',
    'has_error' => false,
    'base_calculation_price' => 10,
    'calculation_price' => 10,
    'converted_price' => 10,
    'base_original_price' => 10
];
