<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<form class="form form-orders-search"
      id="oar-widget-orders-and-returns-form"
      data-mage-init='{"ordersReturns":{}, "validation":{}}'
      action="<?= $escaper->escapeUrl($block->getActionUrl()) ?>"
      method="post" name="guest_post">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Order Information')) ?></span></legend>
        <br>

        <div class="field id required">
            <label class="label" for="oar-order-id"><span><?= $escaper->escapeHtml(__('Order ID')) ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar-order-id" name="oar_order_id"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field lastname required">
            <label class="label" for="oar-billing-lastname"><span><?= $escaper->escapeHtml(__('Billing Last Name')) ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar-billing-lastname" name="oar_billing_lastname"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field find required">
            <label class="label" for="quick-search-type-id"><span><?= $escaper->escapeHtml(__('Find Order By')) ?></span></label>

            <div class="control">
                <select name="oar_type" id="quick-search-type-id" class="select">
                    <option value="email"><?= $escaper->escapeHtml(__('Email')) ?></option>
                    <option value="zip"><?= $escaper->escapeHtml(__('ZIP Code')) ?></option>
                </select>
            </div>
        </div>
        <div id="oar-email" class="field email required">
            <label class="label" for="oar_email"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>

            <div class="control">
                <input type="email" class="input-text" id="oar_email" name="oar_email"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div id="oar-zip" style="display: none;" class="field zip required">
            <label class="label" for="oar_zip"><span><?= $escaper->escapeHtml(__('Billing ZIP Code')) ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar_zip" name="oar_zip" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $escaper->escapeHtml(__('Continue')) ?>" class="action submit primary">
                <span><?= $escaper->escapeHtml(__('Continue')) ?></span>
            </button>
        </div>
    </div>
</form>
