<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/**
 * Wysiwyg Images content template
 *
 * @var $block \Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Content
 */
?>
<?= $block->getChildHtml('wysiwyg_files.js') ?>

<div id="contents-uploader" class="contents-uploader"><?= $block->getChildHtml('wysiwyg_files.uploader') ?></div>
<div id="contents"></div>
<div id="contents-newfolder" class="no-display"><?= $block->getChildHtml('wysiwyg_files.newfolder') ?></div>
