<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Wysiwyg Images content template
 *
 * @var $block \Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Content
 */
?>
<?php echo $block->getChildHtml('wysiwyg_files.js') ?>

<div id="contents-uploader" class="contents-uploader"><?php echo $block->getChildHtml('wysiwyg_files.uploader') ?></div>
<div id="contents"></div>
<div id="contents-newfolder" class="no-display"><?php echo $block->getChildHtml('wysiwyg_files.newfolder') ?></div>
