<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Wysiwyg Images content template
 *
 * @var $this \Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Content
 */
?>
<?php echo $this->getChildHtml('wysiwyg_files.js') ?>

<div class="content-header skip-header" id="content_header">
    <table cellspacing="0">
        <tr>
            <td><h3 id="content_header_text"><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>

<div id="contents-uploader"><?php echo $this->getChildHtml('wysiwyg_files.uploader') ?></div>
<div id="contents"></div>
<div id="contents-newfolder" class="no-display"><?php echo $this->getChildHtml('wysiwyg_files.newfolder') ?></div>
