<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<?php $_cartQty = (float) $block->getSummaryCount() ?>
<div class="block-title">
    <strong>
        <span class="text"><?php echo __('My Cart'); ?></span>
                    <span title="<?php echo $block->escapeHtml(__('Items in Cart')); ?>"
                          class="qty<?php echo($_cartQty > 0) ? '' : ' empty'; ?>"
                        ><?php echo $_cartQty ?></span>
    </strong>
</div>
<div class="block-content">
    <button type="button"
            id="btn-minicart-close"
            title="<?php echo $block->escapeHtml(__('Close')); ?>"
            class="action close">
        <span><?php echo __('Close') ?></span>
    </button>

    <?php if ($_cartQty || $block->getAllowCartLink()): ?>
        <div class="items-total">
            <span class="count"><?php echo $_cartQty; ?></span>
            <?php echo $block->getSummaryText($_cartQty); ?>
        </div>
        <?php $isPossibleOnepageCheckout = $_cartQty && $block->isPossibleOnepageCheckout() ?>
        <?php if ($isPossibleOnepageCheckout): ?>
            <?php echo $block->getChildHtml('subtotal'); ?>
        <?php endif; ?>
        <?php echo $block->getChildHtml('minicart_info') ?>
        <div class="actions">
            <div class="primary">
                <?php if ($isPossibleOnepageCheckout): ?>
                    <button
                        id="top-cart-btn-checkout"
                        type="button"
                        class="action primary checkout"
                        title="<?php echo $block->escapeHtml(__('Go to Checkout')); ?>">
                        <span><?php echo __('Go to Checkout') ?></span>
                    </button>
                    <?php echo $block->getChildHtml('extra_actions') ?>
                <?php endif; ?>
            </div>
        </div>
    <?php endif ?>

    <?php $_items = $block->getRecentItems() ?>
    <?php if (count($_items)): ?>
        <strong class="subtitle"><?php echo __('Recently added item(s)') ?></strong>
        <div data-action="scroll" class="minicart-items-wrapper">
            <ol id="mini-cart" class="minicart-items">
                <?php foreach ($_items as $_item): ?>
                    <?php echo $block->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php else: ?>
        <strong class="subtitle empty">
            <?php echo __('You have no items in your shopping cart.') ?>
        </strong>
        <?php if ($block->getCartEmptyMessage()): ?>
            <p class="minicart empty text"><?php echo $block->getCartEmptyMessage(); ?></p>
        <?php endif; ?>
    <?php endif ?>

    <?php if ($_cartQty || $block->getAllowCartLink()): ?>
        <div class="actions">
            <div class="secondary">
                <a class="action viewcart" href="<?php echo $block->getUrl('checkout/cart'); ?>">
                    <span><?php echo __('View and edit cart') ?></span>
                </a>
            </div>
        </div>
    <?php endif ?>

    <div id="minicart-widgets" class="minicart-widgets">
        <?php echo $block->getChildHtml('cart_promotion') ?>
    </div>
</div>
