<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Framework\View\Element\Template */

$id = $block->escapeHtml($attribute['attribute_id']);
?>
<div data-role="configurable-attribute">
    <input name="attributes[]" id="configurable_attribute_<?php echo $id ?>" value="<?php echo $id; ?>" type="hidden"/>
    <input value="<?php echo $block->escapeHtml($attribute['id']); ?>" type="hidden"
           name="product[configurable_attributes_data][<?php echo $id ?>][id]"/>
    <input value="<?php echo $block->escapeHtml($attribute['attribute_code']); ?>" type="hidden"
           name="product[configurable_attributes_data][<?php echo $id ?>][code]"/>
    <input value="<?php echo $id; ?>" type="hidden"
           name="product[configurable_attributes_data][<?php echo $id ?>][attribute_id]"/>
    <input value="<?php echo $block->escapeHtml($attribute['position']); ?>" type="hidden"
           name="product[configurable_attributes_data][<?php echo $id ?>][position]"/>
    <input type="hidden" value="<?php echo $block->escapeHtml($attribute['label']); ?>"
           name="product[configurable_attributes_data][<?php echo $id ?>][label]"/>
    <input value="1" type="hidden" name="product[configurable_attributes_data][<?php echo $id ?>][use_default]"/>
    <?php
    $namePrefix = 'product[configurable_attributes_data][' . $id . '][values]';
    foreach ($attribute['options'] as $option) {
        $valueIndex = $option['value'];
        ?>
        <input type="hidden" name="<?php echo $namePrefix ?>[<?php echo $valueIndex ?>][value_index]"
               value="<?php echo $block->escapeHtml($valueIndex); ?>">
        <input type="hidden" name="<?php echo $namePrefix ?>[<?php echo $valueIndex ?>][include]" value="1"/>
    <?php
    } ?>
</div>
