<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Super\Config\Matrix */
?>
<?php
$variations = $block->getVariations();
$productMatrix = [];
$attributes = [];
if ($variations) {
    $usedProductAttributes = $block->getUsedAttributes();
    $productByUsedAttributes = $block->getAssociatedProducts();
    $productPrice = (float)$block->getProduct()->getPrice();
    foreach ($variations as $variation) {
        $attributeValues = [];
        $price = $productPrice;
        foreach ($usedProductAttributes as $attribute) {
            $attributeValues[$attribute->getAttributeCode()] = $variation[$attribute->getId()]['value'];
        }
        $key = implode('-', $attributeValues);
        if (isset($productByUsedAttributes[$key])) {
            $product = $productByUsedAttributes[$key];
            $price = $originPrice = $product->getPrice();
            $variationOptions = [];
            foreach ($usedProductAttributes as $attribute) {
                if (!isset($attributes[$attribute->getAttributeId()])) {
                    $attributes[$attribute->getAttributeId()] = [
                        'code' => $attribute->getAttributeCode(),
                        'label' => $attribute->getStoreLabel(),
                        'id' => $attribute->getAttributeId(),
                        'position' => $attribute->getPosition(),
                        'chosen' => [],
                    ];
                }
                $optionId = $variation[$attribute->getId()]['value'];
                $variationOption = [
                    'attribute_code' => $attribute->getAttributeCode(),
                    'attribute_label' => $attribute->getStoreLabel(0),
                    'id' => $optionId,
                    'label' => $variation[$attribute->getId()]['label'],
                    'value' => $optionId,
                ];
                $variationOptions[] = $variationOption;
                $attributes[$attribute->getAttributeId()]['chosen'][] = $variationOption;
            }

            $productMatrix[] = [
                'product_id' => $product->getId(),
                'images' => [
                    'preview' => (string)$this->helper('Magento\Catalog\Helper\Image')->init($product, 'image')
                ],
                'sku' => $product->getSku(),
                'name' => $product->getName(),
                'inventory' => $block->getProductStockQty($product),
                'price' => $price,
                'options' => $variationOptions,
                'weight' => $product->getWeight(),
            ];
        }
    }
}
?>

<div data-bind="scope: 'configurableVariations'">
    <h3 class="hidden" data-bind="css: {hidden: !showVariations() }" class="title"><?php echo __('Current Variations'); ?></h3>

    <script data-template-for="variation-image" type="text/x-magento-template">
        <img src="<% -data . url %>" class="variation" data-role="image"/>
    </script>
    <!-- ko if: showVariations() -->
    <div class="hidden" data-bind="css: {hidden: !showVariations() }" data-role="product-variations-matrix-tmp">
        <div class="field">
            <div data-role="configurable-attribute">
                <!-- ko foreach: {data: attributes, as: 'attribute'} -->
                <div data-role="attribute-info">
                    <input name="attributes[]"
                           data-bind="value: attribute.id, attr:{id: 'configurable_attribute_' + attribute.id}"
                           type="hidden"/>
                    <input
                        data-bind="value: attribute.id, attr: {name: $parent.getAttributeRowName(attribute, 'attribute_id')}"
                        type="hidden"/>
                    <input
                        data-bind="value: attribute.code, attr: {name: $parent.getAttributeRowName(attribute, 'code')}"
                        type="hidden"/>
                    <input
                        data-bind="value: attribute.label, attr: {name: $parent.getAttributeRowName(attribute, 'label')}"
                        type="hidden"/>
                    <input data-bind="value: $index(), attr: {name: $parent.getAttributeRowName(attribute, 'position')}"
                           type="hidden"/>
                    <!-- ko foreach: {data: attribute.chosen, as: 'option'} -->
                    <div data-role="option-info">
                        <input value="1"
                               data-bind="attr: {name: $parents[1].getOptionRowName(attribute, option, 'include')}"
                               type="hidden"/>
                        <input
                            data-bind="value: option.value, attr: {name: $parents[1].getOptionRowName(attribute, option, 'value_index')}"
                            type="hidden"/>
                    </div>
                    <!-- /ko -->
                </div>
                <!-- /ko -->
            </div>
            <div class="admin__data-grid-wrap">
                <table class="data-grid"
                ">
                <thead>
                <tr>
                    <th class="data-grid-th col-display" data-column="display">
                        <?= __('Display'); ?>
                    </th>
                    <th class="data-grid-th col-image" data-column="image">
                        <?= __('Image'); ?>
                    </th>
                    <th class="data-grid-th col-name" data-column="name">
                        <?= __('Name'); ?>
                    </th>
                    <th class="data-grid-th col-sku" data-column="sku">
                        <?= __('SKU'); ?>
                    </th>
                    <th class="data-grid-th col-price" data-column="price">
                        <?= __('Price'); ?>
                    </th>
                    <th class="data-grid-th col-qty" data-column="qty">
                        <?= __('Quantity'); ?>
                    </th>
                    <th class="data-grid-th col-weight" data-column="weight">
                        <?= __('Weight'); ?>
                    </th>
                    <!-- ko foreach: getAttributesOptions() -->
                    <th data-bind="attr: {class:'data-grid-th col-' + $data.attribute_code}, text: $data.attribute_label"></th>
                    <!-- /ko -->
                    <th class="data-grid-th">
                        <?= __('Actions'); ?>
                    </th>
                </tr>
                </thead>
                <tbody data-bind="foreach: {data: productMatrix, as: 'variation'}">
                <tr data-role="row" data-bind="attr: {class:  $index() % 2 ? 'even' : ''}">
                    <td class="col-display" data-column="display">
                        <input type="checkbox"
                               name="associated_product_ids[]"
                               data-bind="value: variation.product_id"
                               class="checkbox"
                               data-column="entity_id" checked="checked"/>
                    </td>
                    <td class="col-image" data-column="image">
                        <div class="actions split actions-image-uploader">
                            <img data-bind='attr: {src: variation.images.preview}' class="variation" data-role="image"/>
                            <!-- ko ifnot: variation.readonly -->
                                <!-- ko ifnot: variation.images.file-->
                                <div class="action-upload action split" data-action="upload-image">
                                    <input type="hidden" data-bind="attr: {id: $parent.getRowId(variation, 'image'), name: $parent.getVariationRowName(variation, 'image')}"/>
                                    <span><?= __('Upload Image'); ?></span>
                                    <input name="image" type="file"
                                           data-url="<?= $block->escapeHtml($block->getImageUploadUrl()) ?>"
                                           title="<?= $block->escapeHtml(__('Upload image')); ?>"/>
                                </div>
                                <button type="button" class="action toggle no-display" data-toggle="dropdown"
                                        data-mage-init='{"dropdown":{}}'>
                                    <span><?= __('Select'); ?></span>
                                </button>
                                <ul class="dropdown">
                                    <li>
                                        <a class="item" data-action="no-image"><?= __('No Image'); ?></a>
                                    </li>
                                </ul>
                                <!-- /ko -->
                            <!-- ko if: variation.images.file -->
                                <span data-bind="html: $parent.generateImageGallery(variation)"></span>
                            <!-- /ko -->
                            <!-- /ko -->
                        </div>
                    </td>
                    <td class="col-name" data-column="name">
                        <!-- ko if: variation.readonly -->
                            <!-- ko text: variation.name --><!--/ko-->
                        <!-- /ko -->
                        <!-- ko ifnot: variation.readonly -->
                        <input type="text" data-bind="attr: {id: $parent.getRowId(variation, 'name'), name: $parent.getVariationRowName(variation, 'name'), value: variation.sku}"/>
                        <input type="hidden" data-bind="attr: {id: $parent.getRowId(variation, 'configurable_attribute'), name: $parent.getVariationRowName(variation, 'configurable_attribute'), value: variation.attribute}"/>
                        <button type="button"
                                data-action="choose"
                                class="action-choose"
                                title="<?= $block->escapeHtml(__('Choose')); ?>"
                                data-bind="attr: {'data-attributes': variation.attribute}">
                            <span><?= __('Choose'); ?></span>
                        </button>
                        <!-- /ko -->
                    </td>
                    <td class="col-sku" data-column="sku">
                        <!-- ko if: variation.readonly -->
                            <!-- ko text: variation.sku --><!--/ko-->
                        <!-- /ko -->
                        <!-- ko ifnot: variation.readonly -->
                        <input type="text"
                               data-bind="attr: {id: $parent.getRowId(variation, 'sku'), name: $parent.getVariationRowName(variation, 'sku'), value: variation.sku}"/>
                        <!-- /ko -->
                    </td>
                    <td class="col-price" data-column="price">
                        <!-- ko if: variation.readonly -->
                            <!-- ko text: variation.price --><!--/ko-->
                        <!-- /ko -->
                        <!-- ko ifnot: variation.readonly -->
                        <div class="addon">
                            <input type="text"
                                   id=""
                                   class="validate-zero-or-greater"
                                   data-bind="attr: {id: $parent.getRowId(variation, 'price'), name: $parent.getVariationRowName(variation, 'price'), value: variation.price}"/>
                            <label class="addafter"
                                   data-bind="attr: {for: $parent.getRowId(variation, 'price')"><strong>$</strong></label>
                        </div>
                        <!-- /ko -->

                    </td>
                    <td class="col-qty" data-column="qty">
                        <!-- ko if: variation.readonly -->
                            <!-- ko text: variation.inventory --><!--/ko-->
                        <!-- /ko -->
                        <!-- ko ifnot: variation.readonly -->
                        <input type="text"
                               class="validate-number"
                               data-bind="attr: {id: $parent.getRowId(variation, 'qty'), name: $parent.getVariationRowName(variation, 'quantity_and_stock_status/qty'), value: variation.inventory}"/>
                        <!-- /ko -->

                    </td>
                    <td class="col-weight" data-column="weight">
                        <!-- ko if: variation.readonly -->
                            <!-- ko text: variation.weight --><!--/ko-->
                        <!-- /ko -->
                        <!-- ko ifnot: variation.readonly -->
                        <input type="text"
                               data-bind="attr: {id: $parent.getRowId(variation, 'weight'), name: $parent.getVariationRowName(variation, 'weight'), value: variation.weight}"/>
                        <!-- /ko -->

                    </td>
                    <!-- ko foreach: variation.options -->
                    <td data-bind="text: label"></td>
                    <!-- /ko -->
                    <td class="data-grid-actions-cell">
                        <div class="action-select-wrap">
                            <button class="action-select">
                                <span>Select</span>
                            </button>
                            <ul class="action-menu">
                                <li>
                                    <a class="action-menu-item" href="#">Edit</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "configurableVariations": {
                        "component": "Magento_ConfigurableProduct/js/variations/variations",
                        "variations": <?= $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($productMatrix) ?>,
                        "productAttributes": <?= $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(array_values($attributes)) ?>
                    }
                }
            }
        }
    }

</script>
