<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix */
?>
<?php
$productMatrix = $block->getProductMatrix();
$attributes = $block->getProductAttributes();
$currencySymbol = $block->getCurrencySymbol();
?>
<div data-role="step-wizard-dialog" data-bind="scope: 'product_form.product_form.configurableModal'">
    <!-- ko template: getTemplate() -->
    <?php
    /* @escapeNotVerified */ echo $block->getVariationWizard([
        'attributes' => $attributes,
        'configurations' => $productMatrix
    ]);
    ?>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "product_form.product_form.configurableModal": {
                        "component": "Magento_Ui/js/modal/modal-component",
                        "options": {"type": "slide", "title": "<?= /* @escapeNotVerified */  __('Create Product Configurations') ?>"},
                        "children": {
                            "wizard": {
                                "url": "<?= /* @noEscape */ $block->getUrl('catalog/product/wizard', ['id' => $block->getProduct()->getId()]) ?>",
                                "component": "Magento_Ui/js/form/components/html"
                            }
                        }
                    },
                    "configurableVariations": {
                        "component": "Magento_ConfigurableProduct/js/variations/variations",
                        "variations": <?= /* @noEscape */ $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($productMatrix) ?>,
                        "productAttributes": <?= /* @noEscape */ $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($attributes) ?>,
                        "productUrl": "<?= /* @noEscape */ $block->getUrl('catalog/product/edit', ['id' => '%id%']) ?>",
                        "currencySymbol": "<?= /* @noEscape */ $currencySymbol ?>",
                        "configurableProductGrid": "configurableProductGrid"
                    }
                }
            }
        }
    }
</script>
<script>
    require(['jquery'], function ($) {
        $('[data-role=step-wizard-dialog]').applyBindings();
    })
</script>