<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix */
?>
<?php
$productMatrix = $block->getProductMatrix();
$attributes = $block->getProductAttributes();

/* @escapeNotVerified */ echo $block->getVariationWizard([
    'attributes' => $attributes,
    'configurations' => $productMatrix
]);
?>
<script>
    require(['jquery'], function ($) {
        $('[data-role=steps-wizard-main]').applyBindings();
    })
</script>
