<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$titleId = ($block->getTitleId()) ? ' id="' . $block->getTitleId() . '"' : '';
$titleClass = ($block->getTitleClass()) ? ' ' . $block->getTitleClass() : '';
$title = $block->escapeHtml($block->getPageTitle());
?>

<div class="page-title-wrapper<?php echo $titleClass; ?>">
    <h1 class="page-title"<?php echo $titleId?>><?php echo $title ?></h1>
    <?php echo $block->getChildHtml(); ?>
</div>
