<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\OfflinePayments\Block\Info\Purchaseorder;

/** @var Escaper $escaper */
/** @var Purchaseorder $block */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <strong><?= $escaper->escapeHtml(__('Purchase Order Number')) ?></strong>
        <span class="number"><?= $escaper->escapeHtml($block->getInfo()->getPoNumber()) ?></span>
    </dd>
</dl>
