<?php
/**
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\Version\Controller\Index;

use Magento\Framework\App\Action\HttpGetActionInterface as HttpGetActionInterface;
use Magento\Framework\App\ProductMetadataInterface;
use Magento\Framework\App\ResponseInterface;

/**
 * Magento Version controller
 */
class Index implements HttpGetActionInterface
{
    const DEV_PREFIX = 'dev-';

    /**
     * @var ProductMetadataInterface
     */
    protected $productMetadata;
    /**
     * @var ResponseInterface
     */
    private $response;

    /**
     * @param ResponseInterface $response
     * @param ProductMetadataInterface $productMetadata
     */
    public function __construct(ResponseInterface $response, ProductMetadataInterface $productMetadata)
    {
        $this->productMetadata = $productMetadata;
        $this->response = $response;
    }

    /**
     * Sets the response body to ProductName/Major.MinorVersion (Edition).
     *
     * @return void
     */
    public function execute(): void
    {
        $version = $this->productMetadata->getVersion();
        $versionParts = explode('.', $version);
        if ($this->isGitBasedInstallation($version) || !$this->isCorrectVersion($versionParts)) {
            return;
        }

        $this->response->setBody(
            $this->productMetadata->getName() . '/' .
            $this->getMajorMinorVersion($versionParts) .
            ' (' . $this->productMetadata->getEdition() . ')'
        );
    }

    /**
     * Check if provided version is generated by Git-based Magento instance.
     *
     * @param string $fullVersion
     * @return bool
     */
    private function isGitBasedInstallation($fullVersion): bool
    {
        return 0 === strpos($fullVersion, self::DEV_PREFIX);
    }

    /**
     * Verifies if the Magento version is correct
     *
     * @param array $versionParts
     * @return bool
     */
    private function isCorrectVersion(array $versionParts): bool
    {
        return isset($versionParts[0]) && isset($versionParts[1]);
    }

    /**
     * Returns string only with Major and Minor version number
     *
     * @param array $versionParts
     * @return string
     */
    private function getMajorMinorVersion(array $versionParts): string
    {
        return $versionParts[0] . '.' . $versionParts[1];
    }
}
