<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Tax\Block\Checkout\Shipping\Price */ ?>

<?php $_excl = $block->getShippingPriceExclTax(); ?>
<?php $_incl = $block->getShippingPriceInclTax(); ?>
<?php if ($block->displayShippingPriceExclTax()): ?>
    <span class="price"><?php echo /* @escapeNotVerified */ $_excl ?></span>
<?php else: ?>
<?php if ($block->displayShippingBothPrices() && $_incl != $_excl): ?>
    <span class="price-including-tax" data-label="<?php echo /* @escapeNotVerified */ __('Incl. Tax') ?>">
<?php endif; ?>
    <span class="price"><?php echo /* @escapeNotVerified */ $_incl ?></span>
<?php if ($block->displayShippingBothPrices() && $_incl != $_excl): ?>
    </span>
<?php endif; ?>
<?php endif; ?>
<?php if ($block->displayShippingBothPrices() && $_incl != $_excl): ?>
    <span class="price-excluding-tax" data-label="<?php echo /* @escapeNotVerified */ __('Excl. Tax') ?>"><span class="price"><?php echo /* @escapeNotVerified */ $_excl ?></span></span>
<?php endif; ?>
