<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\Tax\Block\Checkout\Shipping\Price */ ?>

<?php $_excl = $this->getShippingPriceExclTax(); ?>
<?php $_incl = $this->getShippingPriceInclTax(); ?>
<?php if ($this->displayShippingPriceExclTax()): ?>
    <span class="price"><?php echo $_excl; ?></span>
<?php else: ?>
<?php if ($this->displayShippingBothPrices() && $_incl != $_excl): ?>
    <span class="price-including-tax" data-label="<?php echo __('Incl. Tax'); ?>">
<?php endif; ?>
    <span class="price"><?php echo $_incl; ?></span>
<?php if ($this->displayShippingBothPrices() && $_incl != $_excl): ?>
    </span>
<?php endif; ?>
<?php endif; ?>
<?php if ($this->displayShippingBothPrices() && $_incl != $_excl): ?>
    <span class="price-excluding-tax" data-label="<?php echo __('Excl. Tax'); ?>"><span class="price"><?php echo $_excl; ?></span></span>
<?php endif; ?>
