<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /* @var $this \Magento\Catalog\Block\Adminhtml\Product\Composite\Fieldset\Options */ ?>
<?php $options = $this->decorateArray($this->getOptions()); ?>
<?php if (count($options)): ?>

<?php echo $this->getChildHtml('options_js') ?>

<fieldset id="product_composite_configure_fields_options" class="fieldset <?php echo $this->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
    <legend class="legend"><span><?php echo __('Custom Options') ?></span></legend>
    <?php foreach ($options as $option): ?>
        <?php echo $this->getOptionHtml($option); ?>
    <?php endforeach;?>
</fieldset>

<?php endif; ?>
