<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/** @var \Magento\Tax\Block\Adminhtml\Items\Price\Renderer $block */

$_item = $block->getItem();
?>
<?php if ($block->displayBothPrices() || $block->displayPriceExclTax()) : ?>
    <div class="price-excl-tax">
        <?php if ($block->displayBothPrices()) : ?>
            <span class="label"><?= $block->escapeHtml(__('Excl. Tax')) ?>:</span>
        <?php endif; ?>
        <?= /* @noEscape */ $block->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
    </div>
<?php endif; ?>
<?php if ($block->displayBothPrices() || $block->displayPriceInclTax()) : ?>
    <div class="price-incl-tax">
        <?php if ($block->displayBothPrices()) : ?>
            <span class="label"><?= $block->escapeHtml(__('Incl. Tax')) ?>:</span>
        <?php endif; ?>
        <?php $_incl = $this->helper(\Magento\Checkout\Helper\Data::class)->getSubtotalInclTax($_item); ?>
        <?php $_baseIncl = $this->helper(\Magento\Checkout\Helper\Data::class)->getBaseSubtotalInclTax($_item); ?>
        <?= /* @noEscape */ $block->displayPrices($_baseIncl, $_incl) ?>
    </div>
<?php endif; ?>
