<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
return [
    [
        'dest_country_id' => 'US',
        'dest_region_id' => '12',
        'dest_region_code' => 'CA',
        'dest_street' => 'main st1',
        'dest_city' => 'Los Angeles',
        'dest_postcode' => '90032',
        'package_value' => '5',
        'package_value_with_discount' => '5',
        'package_weight' => '4.2657',
        'package_qty' => '1',
        'package_physical_value' => '5',
        'free_method_weight' => '5',
        'store_id' => '1',
        'website_id' => '1',
        'free_shipping' => '0',
        'limit_carrier' => 'null',
        'base_subtotal_incl_tax' => '5',
        'orig_country_id' => 'US',
        'country_id' => 'US',
        'region_id' => '12',
        'city' => 'Culver City',
        'postcode' => '90034',
        'usps_userid' => '213MAGEN6752',
        'usps_container' => 'VARIABLE',
        'usps_size' => 'REGULAR',
        'girth' => null,
        'height' => null,
        'length' => null,
        'width' => null,
    ], [
        'dest_country_id' => 'CA',
        'dest_postcode' => 'M5V 3G5',
        'dest_country_name' => 'Canada',
        'package_value' => '3.2568',
        'package_value_with_discount' => '5',
        'package_weight' => '5',
        'package_qty' => '1',
        'package_physical_value' => '5',
        'free_method_weight' => '5',
        'store_id' => '1',
        'website_id' => '1',
        'free_shipping' => '0',
        'limit_carrier' => 'null',
        'base_subtotal_incl_tax' => '5',
        'orig_country_id' => 'US',
        'country_id' => 'US',
        'region_id' => '12',
        'city' => 'Culver City',
        'postcode' => '90034',
        'usps_userid' => '213MAGEN6752',
        'usps_container' => 'VARIABLE',
        'usps_size' => 'REGULAR',
        'girth' => null,
        'height' => null,
        'length' => null,
        'width' => null,
    ]
];
