<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Tracking\Link */ ?>
<?php $order = $block->getOrder() ?>
<a href="#" class="action track" title="<?php /* @escapeNotVerified */ echo $block->getLabel() ?>"
   data-mage-init='{"popupWindow": {"windowURL":"<?php /* @escapeNotVerified */ echo $block->getWindowUrl($order) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'>
    <span><?php /* @escapeNotVerified */ echo $block->getLabel()?></span>
</a>
