<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
$parentBlock = $block->getParentBlock();
$track = $block->getData('track');
?>
<div class="table-wrapper">
    <table class="data table order tracking" id="track-history-table-<?= $escaper->escapeHtml($track->getTracking()) ?>">
        <caption class="table-caption"><?= $escaper->escapeHtml(__('Track history')) ?></caption>
        <thead>
        <tr>
            <th class="col location" scope="col"><?= $escaper->escapeHtml(__('Location')) ?></th>
            <th class="col date" scope="col"><?= $escaper->escapeHtml(__('Date')) ?></th>
            <th class="col time" scope="col"><?= $escaper->escapeHtml(__('Local Time')) ?></th>
            <th class="col description" scope="col"><?= $escaper->escapeHtml(__('Description')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($track->getProgressdetail() as $detail) : ?>
            <?php $detailDate = (!empty($detail['deliverydate']) ?
                $parentBlock->formatDeliveryDate($detail['deliverydate'] . ' ' . $detail['deliverytime']) :
                ''); ?>
            <?php $detailTime = (!empty($detail['deliverytime']) ?
                $parentBlock->formatDeliveryTime($detail['deliverytime'], $detail['deliverydate']) :
                ''); ?>
            <tr>
                <td data-th="<?= $escaper->escapeHtml(__('Location')) ?>" class="col location">
                    <?= (!empty($detail['deliverylocation']) ? $escaper->escapeHtml($detail['deliverylocation']) : '') ?>
                </td>
                <td data-th="<?= $escaper->escapeHtml(__('Date')) ?>" class="col date">
                    <?= /* @noEscape */ $detailDate ?>
                </td>
                <td data-th="<?= $escaper->escapeHtml(__('Local Time')) ?>" class="col time">
                    <?= /* @noEscape */ $detailTime ?></td>
                <td data-th="<?= $escaper->escapeHtml(__('Description')) ?>" class="col description">
                    <?= (!empty($detail['activity']) ? $escaper->escapeHtml($detail['activity']) : '') ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
