<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/**
 * @deprecated
 */

/* @var $block \Magento\Reports\Block\Product\Widget\Viewed */
?>

<?php
$mode = $block->getViewMode();
$type = $block->getType() . '-' . $mode;
$class = 'widget viewed' . ' ' . $mode;
$title = __('Recently Viewed');
?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>" id="recently_viewed_container" data-mage-init='{"recentlyViewedProducts":{}}' data-count="<?= $block->escapeHtmlAttr($block->getCount()) ?>" style="display: none;">
    <div class="title">
        <strong><?= $block->escapeHtml($title) ?></strong>
    </div>
    <div class="content">
        <ol class="products list items <?= $block->escapeHtmlAttr($type) ?>">
        </ol>
    </div>
</div>
