<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Reports\Block\Product\Widget\Viewed */
?>

<?php
$mode = $block->getViewMode();
$type = $block->getType() . '-' . $mode;
$class = 'widget viewed' . ' ' . $mode;
$title = __('Recently Viewed');
?>
<div class="block <?= $block->escapeHtml($class) ?>" id="recently_viewed_container" data-mage-init='{"recentlyViewedProducts":{}}' data-count="<?= $block->escapeHtml($block->getCount()) ?>" style="display: none;">
    <div class="title">
        <strong><?= $block->escapeHtml($title) ?></strong>
    </div>
    <div class="content">
        <ol class="products list items <?= $block->escapeHtml($type) ?>">
        </ol>
    </div>
</div>
