<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Weee\Block\Adminhtml\Items\Price\Renderer $block */

/** @var $_weeeHelper \Magento\Weee\Helper\Data */
$_weeeHelper = $this->helper('Magento\Weee\Helper\Data');

$_item = $block->getItem();
?>

<?php if ($block->displayBothPrices() || $block->displayPriceExclTax()): ?>
    <div class="price-excl-tax">
        <?php if ($block->displayBothPrices()): ?>
            <span class="label"><?php /* @escapeNotVerified */ echo __('Excl. Tax'); ?>:</span>
        <?php endif; ?>

        <?= $block->getRowPriceExclTaxHtml() ?>

        <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
            <?php if ($block->displayPriceWithWeeeDetails()): ?>
                <small>
                    <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php /* @escapeNotVerified */ echo $tax['title']; ?>: <?php /* @escapeNotVerified */ echo $block->displayPrices($tax['base_row_amount'], $tax['row_amount']); ?></span>
                    <?php endforeach; ?>
                </small>
            <?php endif; ?>

            <?php if ($block->displayFinalPrice()): ?>
                <br />
                <span class="nobr"><?php /* @escapeNotVerified */ echo __('Total'); ?>:<br />
                    <?= $block->getFinalRowPriceExclTaxHtml() ?>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($block->displayBothPrices() || $block->displayPriceInclTax()): ?>
    <div class="price-incl-tax">
        <?php if ($block->displayBothPrices()): ?>
            <span class="label"><?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?>:</span>
        <?php endif; ?>
        <?= $block->getRowPriceInclTaxHtml() ?>

        <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
            <br />
            <?php if ($block->displayPriceWithWeeeDetails()): ?>
                <small>
                    <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php /* @escapeNotVerified */ echo $tax['title']; ?>: <?php /* @escapeNotVerified */ echo $block->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></span>
                    <?php endforeach; ?>
                </small>
            <?php endif; ?>

            <?php if ($block->displayFinalPrice()): ?>
                <br />
                <span class="nobr"><?php /* @escapeNotVerified */ echo __('Total'); ?>:<br />
                    <?= $block->getFinalRowPriceInclTaxHtml() ?>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
