<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Braintree\Block\Customer\PayPal\VaultTokenRenderer;
use Magento\Vault\Api\Data\PaymentTokenInterface;

/** @var VaultTokenRenderer $block */

$payerEmail = $block->getPayerEmail();
$confirmDeleteMessage = sprintf('%s: %s?', __('Are you sure you want to delete this PayPal account'), $payerEmail);
?>
<tr>
    <td data-th="<?php echo $block->escapeHtml(__('PayPal Account')) ?>" class="col paypal-account">
        <img src="<?php echo /* @noEscape */ $block->getIconUrl() ?>"
             width="<?php echo /* @noEscape */ $block->getIconWidth() ?>"
             height="<?php echo /* @noEscape */ $block->getIconHeight() ?>"
             alt="<?php echo $block->escapeHtml(__('PayPal Logo')) ?>">
        <span><?php echo $block->escapeHtml($payerEmail) ?></span>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
        <form
            class="form"
            action="<?php echo $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            method="post">
            <?php echo $block->getBlockHtml('formkey') ?>
            <input
                name="<?php echo /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                value="<?php echo /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget":{
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?php echo $block->escapeHtml(__('Delete')) ?>",
                            "content":"<?php echo $block->escapeHtml($confirmDeleteMessage) ?>"
                        }
                    }'>
                <span><?php echo $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
