<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<ul class="dropdown-menu">
    <?php foreach ($items as $item): ?>
    <li id="<?php echo $item['id'] ?>" class="item">
        <a href="<?php echo $item['url'] ?>" class="title"><?php echo $block->escapeHtml($item['name']) ?></a>
        <div class="type"><?php echo $item['type'] ?></div>
        <?php echo $block->escapeHtml($item['description']) ?>
    </li>
    <?php endforeach ?>
</ul>
