<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Backend\Block\GlobalSearch */
?>
<div class="search-global" data-mage-init='{"globalSearch": {}}'>
    <form action="#" id="form-search">
        <div class="search-global-field">
            <label class="search-global-label" for="search-global"></label>
            <input
                    type="text"
                    class="search-global-input"
                    id="search-global"
                    name="query"
                    data-mage-init='<?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getWidgetInitOptions()) ?>'>
            <button
                type="submit"
                class="search-global-action"
                title="<?= $block->escapeHtmlAttr(__('Search')) ?>"
                ></button>
        </div>
    </form>
    <script data-template="search-suggest" type="text/x-magento-template">
        <ul class="search-global-menu">
            <?php foreach ($block->getEntitiesToShow() as $entity) : ?>
                <li class="item">
                    <a id="<?= $block->escapeHtmlAttr($entity->getId()); ?>"
                       href="<?= $block->escapeUrl($entity->getUrl()) ?>?search=<%- data.term%>"
                       class="title">
                        "<%- data.term%>" <?= $block->escapeHtml(__($entity->getTitle())); ?>
                    </a>
                </li>
            <?php endforeach; ?>
            <% if (data.items.length) { %>
            <% _.each(data.items, function(value){ %>
            <li class="item"
                <%= data.optionData(value) %>
                >
                <a href="<%- value.url %>" class="title"><%- value.name %></a>
                <span class="type"><%- value.type %></span>
                <%- value.description || "" %>
            </li>
            <% }); %>
        <% } else { %>
            <li>
                <span class="mage-suggest-no-records">
                    <?= $block->escapeHtml(__('No records found.')) ?>
                </span>
            </li>
        <% } %>
        </ul>
    </script>
</div>
