<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
?>
<dl class="payment-method">
    <dt class="title"><?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?></dt>
<?php if ($block->getInstructions()) : ?>
    <dd class="content"><?= /* @noEscape */ nl2br($escaper->escapeHtml($block->getInstructions())) ?></dd>
<?php endif; ?>
</dl>
