<?php
/**
 * Copyright 2015 Adobe
 * All Rights Reserved.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<script type="text/x-magento-init">
    {
        "*": {
            "swatchesProductAttributes": {
                "hiddenFields": <?= /* @noEscape */ json_encode($this->helper(Magento\Catalog\Helper\Data::class)->getAttributeHiddenFields()) ?>
            }
        }
    }
</script>
