<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\Adminhtml\Attribute\Edit\Options\Visual */

$stores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="fieldset">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Manage Swatch (Values of Your Attribute)') ?></span></legend>
    <div id="swatch-visual-options-panel">
        <table class="data-table clearfix" cellspacing="0">
            <thead>
            <tr id="swatch-visual-options-table">
                <th class="col-draggable"></th>
                <th class="col-default"><span><?php /* @escapeNotVerified */ echo __('Is Default') ?></span></th>
                <th><span><?php /* @escapeNotVerified */ echo __('Swatch') ?></span></th>
                <?php foreach ($stores as $_store): ?>
                    <th<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> class="_required"<?php endif; ?>>
                        <span><?php /* @escapeNotVerified */ echo $_store->getName() ?></span>
                    </th>
                <?php endforeach;
                $colTotal = count($stores) * 2 + 3;
                ?>
                <th class="col-delete">&nbsp;</th>
            </tr>
            </thead>
            <tbody data-role="swatch-visual-options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?php echo (int)$colTotal; ?>">
                    <input type="hidden" class="required-visual-swatch-entry" name="visual_swatch_validation"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?php /* @escapeNotVerified */ echo $colTotal; ?>" class="col-actions-add">
                    <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                        <button id="add_new_swatch_visual_option_button" title="<?php /* @escapeNotVerified */ echo __('Add Swatch'); ?>"
                                type="button" class="action- scalable add">
                            <span><?php /* @escapeNotVerified */ echo __('Add Swatch'); ?></span>
                        </button>
                    <?php endif; ?>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="swatch-visual-option-count-check" value="" />
    </div>
    <script id="swatch-visual-row-template" type="text/x-magento-template">
        <tr>
            <td class="col-draggable">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                    <div data-role="draggable-handle" class="draggable-handle" title="<?php /* @escapeNotVerified */ echo __('Sort Option'); ?>"></div>
                <?php endif; ?>
                <input data-role="order" type="hidden" name="optionvisual[order][<%- data.id %>]"  value="<%- data.sort_order %>" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?> disabled="disabled"<?php endif; ?>/>
            </td>
            <td class="col-default">
                <input class="input-radio" type="<%- data.intype %>" name="defaultvisual[]" value="<%- data.id %>" <%- data.checked %><?php if ($block->getReadOnly()):?>disabled="disabled"<?php endif;?>/>
            </td>
            <td class="swatches-visual-col col-default <%- data.empty_class %>">
                <?php //@todo add logic getting swatch value from db */ ?>
                <input id="swatch_visual_value_<%- data.id %>" type="hidden" name="swatchvisual[value][<%- data.id %>]" value="<%- data.defaultswatch0 %>" />
                <div class="swatch_window" id="swatch_window_option_<%- data.id %>" style="<%- data.swatch0 %>"></div>
                <div class="swatch_sub-menu_container" id="swatch_container_option_<%- data.id %>">
                    <div class="swatch_row position-relative">
                        <div class="swatch_row_name colorpicker_handler">
                            <p><?php /* @escapeNotVerified */ echo __('Choose a color'); ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_choose_file_upload" id="swatch_choose_file_option_<%- data.id %>">
                            <p><?php /* @escapeNotVerified */ echo __('Upload a file'); ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_remove_swatch">
                            <p><?php /* @escapeNotVerified */ echo __('Clear'); ?></p>
                        </div>
                    </div>
                </div>
            </td>
            <?php foreach ($stores as $_store): ?>
                <td class="swatch-col-<%- data.id %>">
                    <input name="optionvisual[value][<%- data.id %>][<?php /* @escapeNotVerified */ echo $_store->getId() ?>]" value="<%- data.store<?php /* @escapeNotVerified */ echo $_store->getId() ?> %>" class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>" type="text" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()):?> disabled="disabled"<?php endif;?>/>
                </td>
            <?php endforeach; ?>
            <td id="delete_button_swatch_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="optionvisual[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                    <button title="<?php /* @escapeNotVerified */ echo __('Delete') ?>" type="button"
                            class="action- scalable delete delete-option"
                        >
                        <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Swatches/js/visual": <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>
            }
        }
    </script>
</fieldset>
