<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_element = $block->getElement() ?>
<?php if ($_element->getFieldsetContainerId()): ?>
    <div id="<?php /* @escapeNotVerified */ echo $_element->getFieldsetContainerId(); ?>">789
<?php endif; ?>

<?php if (!$_element->getNoContainer()): ?>
    <fieldset class="admin__fieldset fieldset <?php /* @escapeNotVerified */ echo $_element->getClass() ?>" id="<?= $_element->getHtmlId() ?>">
<?php endif; ?>

    <?php if ($_element->getLegend()): ?>
        <legend class="admin__legend legend">
            <span><?php /* @escapeNotVerified */ echo $_element->getLegend() ?></span>
            <?= $block->getHintHtml() ?>
        </legend><br/>
        <?php /* @escapeNotVerified */ echo $_element->getHeaderBar() ?>
    <?php else: ?>
        <?= $block->getHintHtml() ?>
    <?php endif; ?>
        <div class="admin__fieldset tree-store-scope">
            <?php if ($_element->getComment()): ?>
            <p class="comment"><?= $block->escapeHtml($_element->getComment()) ?></p>
            <?php endif; ?>
            <?php if ($_element->hasHtmlContent()): ?>
               <?= $_element->getHtmlContent() ?>
            <?php else: ?>
                <?= $_element->getChildrenHtml() ?>
            <?php endif; ?>
        </div>
<?= $_element->getSubFieldsetHtml() ?>

<?php if (!$_element->getNoContainer()): ?>
    </fieldset>
<?php endif; ?>
<?php if ($_element->getFieldsetContainerId()): ?>
    </div>
<?php endif; ?>
