<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $this \Magento\Downloadable\Block\Customer\Products\ListProducts
 */
?>
<?php $_items = $this->getItems(); ?>
<?php if (count($_items)): ?>
    <div class="table-wrapper downloadable-products">
        <table id="my-downloadable-products-table" class="data table table-downloadable-products">
            <caption class="table-caption"><?php echo __('Downloadable Products') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php echo __('Order #') ?></th>
                    <th scope="col" class="col date"><?php echo __('Date') ?></th>
                    <th scope="col" class="col title"><?php echo __('Title') ?></th>
                    <th scope="col" class="col status"><?php echo __('Status') ?></th>
                    <th scope="col" class="col remaining"><?php echo __('Remaining Downloads') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($_items as $_item): ?>
                <tr>
                    <td data-th="<?php echo $this->escapeHtml(__('Order #')) ?>" class="col id">
                        <a href="<?php echo $this->getOrderViewUrl($_item->getPurchased()->getOrderId()) ?>"
                            title="<?php echo $this->escapeHtml(__('View Order')) ?>">
                            <?php echo $_item->getPurchased()->getOrderIncrementId() ?>
                        </a>
                    </td>
                    <td data-th="<?php echo $this->escapeHtml(__('Date')) ?>" class="col date"><?php echo $this->formatDate($_item->getPurchased()->getCreatedAt()) ?></td>
                    <td data-th="<?php echo $this->escapeHtml(__('Title')) ?>" class="col title">
                        <strong class="product-name"><?php echo $this->escapeHtml($_item->getPurchased()->getProductName()) ?></strong>
                        <a href="<?php echo $this->getDownloadUrl($_item) ?>" title="<?php echo $this->escapeHtml(__('Start Download')) ?>" class="action download" <?php echo $this->getIsOpenInNewWindow() ? 'onclick="this.target=\'_blank\'"' : ''; ?>><?php echo $this->escapeHtml($_item->getLinkTitle()) ?></a>
                    </td>
                    <td data-th="<?php echo $this->escapeHtml(__('Status')) ?>" class="col status"><?php echo __(ucfirst($_item->getStatus())) ?></td>
                    <td data-th="<?php echo $this->escapeHtml(__('Remaining Downloads')) ?>" class="col remaining"><?php echo $this->getRemainingDownloads($_item) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($this->getChildHtml('pager')): ?>
        <div class="toolbar downloadable-products-toolbar bottom">
            <?php echo $this->getChildHtml('pager'); ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have not purchased any downloadable products yet.'); ?></span></div>
<?php endif; ?>

<div class="actions-toolbar">
    <div class="secondary">
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="action back">
            <span><?php echo __('Back') ?></span>
        </a>
    </div>
</div>
