<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<form action="<?php echo $this->getUrl('*/*/saverole') ?>" method="post" id="role-edit-form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
require([
	"jquery",
	"mage/mage"
], function(jQuery){

    jQuery(document).ready(function() {
        jQuery('#role-edit-form').mage('form').mage('validation');
    });

});
</script>
