<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * @see \Magento\Paypal\Block\System\Config\Fieldset\Hint
 */
?>
<?php
    if ($this->getHelpLink()):
?>
<div class="paypal-payment-notice">
    <?php echo __('Not sure what PayPal payment method to use? Click <a href="%1" target="_blank">here</a> to learn more.', $this->getHelpLink()); ?>
</div>
<?php
    endif;
?>
