<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if (sizeof($this->getTerms()) > 0): ?>
    <ul class="search-terms">
        <?php foreach ($this->getTerms() as $_term): ?>
            <li class="item">
                <a href="<?php echo $this->getSearchUrl($_term) ?>"
                   style="font-size:<?php echo $_term->getRatio()*70+75 ?>%;">
                    <?php echo $this->escapeHtml($_term->getName()) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <div class="message notice">
        <div><?php echo __('There are no search terms available.'); ?></div>
    </div>
<?php endif; ?>
