<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if (sizeof($block->getTerms()) > 0): ?>
    <ul class="search-terms">
        <?php foreach ($block->getTerms() as $_term): ?>
            <li class="item">
                <a href="<?= /* @escapeNotVerified */ $block->getSearchUrl($_term) ?>"
                   style="font-size:<?= /* @escapeNotVerified */ $_term->getRatio()*70+75 ?>%;">
                    <?= $block->escapeHtml($_term->getName()) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <div class="message notice">
        <div><?= /* @escapeNotVerified */ __('There are no search terms available.') ?></div>
    </div>
<?php endif; ?>
