<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Customer\Block\Adminhtml\Edit\Renderer\Attribute\Sendemail $block */
$element = $block->getElement();
?>

<div class="field field-<?php echo $element->getId() ?>">
    <?php echo $element->getLabelHtml(); ?>
    <div class="control">
        <?php echo $element->getElementHtml(); ?>
    </div>
</div>

<script>
require(['prototype'], function(){

    document.observe('dom:loaded', function() {
        $('<?php echo $block->getFormHtmlId() ?>website_id').disableSendemail = function() {
            $('<?php echo $block->getFormHtmlId() ?>sendemail').disabled = ('' == this.value || '0' == this.value);
        <?php if (!$block->isSingleStoreMode()): ?>
            $('<?php echo $block->getFormHtmlId() ?>sendemail_store_id').disabled=(''==this.value || '0'==this.value);
        <?php endif; ?>
        }.bind($('<?php echo $block->getFormHtmlId() ?>website_id'));
        Event.observe(
            '<?php echo $block->getFormHtmlId() ?>website_id',
            'change',
            $('<?php echo $block->getFormHtmlId() ?>website_id').disableSendemail
        );
        $('<?php echo $block->getFormHtmlId() ?>website_id').disableSendemail();
    });

});
</script>
