<?php
/**
 * Copyright 2021 Adobe
 * All Rights Reserved.
 */
/** @var $block \Magento\Paypal\Block\PayLater\Banner */
/** @var $cartBlock Magento\Checkout\Block\Cart */
?>
<?php $cartBlock = $block->getLayout()->getBlock('checkout.cart'); ?>
<?php if ($block->getData('placement') !== 'cart' || is_object($cartBlock) && $cartBlock->getItemsCount()): ?>
    <div id="pay-later" data-bind="scope: 'payLater'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#pay-later": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
        </script>
    </div>
<?php endif; ?>




