<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="fieldset">
    <div class="legend">
        <span><?= $escaper->escapeHtml(__('Status')) ?></span>
    </div><br>
    <div class="messages">
        <div class="message message-success success">
            <div><?= $escaper->escapeHtml($block->getStatusMessage()) ?></div>
        </div>
    </div>
</div>
