<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
	<a href="<?php /* @escapeNotVerified */ echo $block->getPrintUrl() ?>" target="_blank" class="print">
		<?php /* @escapeNotVerified */ echo __('Print receipt') ?>
	</a>
    <?php echo $block->getChildHtml() ?>
<?php endif;?>
