<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */

if ($block->getItemsCount()) {
    // phpcs:ignore Magento2.Security.LanguageConstruct.DirectOutput
    echo $block->getChildHtml('with-items');
} else {
    // phpcs:ignore Magento2.Security.LanguageConstruct.DirectOutput
    echo $block->getChildHtml('no-items');
}
