<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- /Temp MAGETWO-36239 markup -->
<div class="block-authentication"
    style="display: none"
    data-mage-init='{
        "Magento_Ui/js/modal/modal":{
            "type": "popup",
            "modalClass": "popup-authentication",
            "responsive": true,
            "innerScroll": true,
            "trigger": ".proceed-to-checkout",
            "buttons": []
        }}'>
    <div class="block block-new-customer"
         data-label="<?php echo __('or')?>">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php echo __('Checkout out as a new customer') ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?php echo __('Creating an account has many benefits:') ?></p>
            <ul>
                <li><?php echo __('See order and shipping status') ?></li>
                <li><?php echo __('Track order history') ?></li>
                <li><?php echo __('Check out faster') ?></li>
            </ul>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="#" class="action action-register primary"><span><?php echo __('Create Account') ?></span></a>
                </div>
            </div>
        </div>
    </div>
    <div class="block block-customer-login"
         data-label="<?php echo __('or')?>">
        <div class="block-title">
            <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php echo __('Checkout out using your account')?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <div class="fieldset login" data-hasrequired="<?php echo __('* Required Fields') ?>">
                    <div class="field email required">
                        <label class="label" for="email"><span><?php echo __('Email Address') ?></span></label>
                        <div class="control">
                            <input name="login[username]"
                                   id="email"
                                   type="email"
                                   class="input-text"
                                   data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?php echo __('Password') ?></span></label>
                        <div class="control">
                            <input name="login[password]"
                                   type="password"
                                   class="input-text"
                                   id="pass"
                                   data-validate="{required:true, 'validate-password':true}">
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary"><button type="submit" class="action action-login secondary" name="send" id="send2"><span><?php echo __('Sign In') ?></span></button></div>
                        <div class="secondary"><a class="action" href="<?php echo $block->getForgotPasswordUrl() ?>"><span><?php echo __('Forgot Password?') ?></span></a></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
