<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var $block \Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Content\Files */
?>

<?php if ($block->getFilesCount() > 0): ?>
    <?php foreach ($block->getFiles() as $file): ?>
        <div class="filecnt file-font" id="<?= /* @escapeNotVerified */ $file['id'] ?>">
            <p class="nm">
                <?= /* @escapeNotVerified */ $file['text'] ?>
                <?php if (isset($file['thumbnailParams'])): ?>
                    <img src="<?= /* @escapeNotVerified */ $block->getUrl('*/*/previewImage', $file['thumbnailParams']) ?>">
                <?php endif; ?>
            </p>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <?= /* @escapeNotVerified */ __('We found no files.') ?>
<?php endif; ?>
