<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $this \Magento\Tax\Block\Item\Price\Renderer */

$_item = $this->getItem();
?>

<?php if ($this->displayPriceInclTax() || $this->displayBothPrices()): ?>
    <span class="price-including-tax" data-label="<?php echo $this->escapeHtml(__('Incl. Tax')); ?>">
        <?php $_incl = $_item->getPriceInclTax(); ?>
        <span class="cart-price">
            <?php echo $this->formatPrice($_incl) ?>
        </span>
    </span>
<?php endif; ?>

<?php if ($this->displayPriceExclTax() || $this->displayBothPrices()): ?>
    <span class="price-excluding-tax" data-label="<?php echo $this->escapeHtml(__('Excl. Tax')); ?>">
        <span class="cart-price">
            <?php echo $this->formatPrice($this->getItemDisplayPriceExclTax()) ?>
        </span>
    </span>
<?php endif; ?>
