<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $this \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($this->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?php echo __('Qty') ?></span></label>
                <div class="control">
                    <input type="number" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo __('Qty') ?>" class="input-text qty" data-validate="{'required-number':true,digits:true}"/>
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
                <button type="button"
                        title="<?php echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?php echo $buttonTitle ?></span>
                </button>
                <?php echo $this->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>

    <script type="text/javascript">
require([
    "jquery",
    "mage/mage"
], function($){

    var addtocartForm = $('#product_addtocart_form');
    addtocartForm.mage('validation');
    addtocartForm.mage('addToCart', {
        cartButtonId: "#product-updatecart-button",
        cartForm: "#product_addtocart_form"
    });

});
</script>
<?php endif; ?>
