apiVersion: batch/v1
kind: Job
metadata:
  name: pre-release-actions
spec:
  template:
    spec:
      securityContext:
        supplementalGroups:
          - 82
        fsGroup: 82
      containers:
      - name: php
        image: eu.gcr.io/magento2-269418/magento2-php72:$TAG_NAME
        volumeMounts:
          - mountPath: /var/www/html/var
            name: magento-var-volume
            subPath: var
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
        securityContext:
          runAsUser: 0
        command: ["/bin/sh", "-c", "chmod -R 0775 /var/www/html/var /var/www/html/pub; chgrp -R 82 /var/www/html/var /var/www/html/pub; /var/www/html/start.sh; chgrp -R 82 /var/www/html/var /var/www/html/pub"]
      volumes:
      - name: magento-var-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-2
      - name: magento-pub-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-1
      restartPolicy: Never
  backoffLimit: 4
