<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<input type="checkbox" name="newsletter:subscribe">
<label for="newsletter:subscribe">
    <?= $block->escapeHtml(__('Subscribe to Newsletter')) ?>
</label>
<?=/* @noEscape */ $secureRenderer->renderStyleAsTag("width: 90%; float: none;", "label[for='newsletter:subscribe']") ?>
<br/>
