<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<input type="checkbox" name="newsletter:subscribe">
<label for="newsletter:subscribe">
    <?= $escaper->escapeHtml(__('Subscribe to Newsletter')) ?>
</label>
<?=/* @noEscape */ $secureRenderer->renderStyleAsTag("width: 90%; float: none;", "label[for='newsletter:subscribe']") ?>
<br/>
