<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php echo $block->getChildHtml('form_before')?>
    <form class="form form-newsletter-manage" action="<?php echo $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <?php echo $block->getBlockHtml('formkey')?>
            <legend class="legend"><span><?php echo $block->escapeHtml(__('Subscription option')) ?></span></legend><br>
            <div class="field choice">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('General Subscription')) ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="subscription" class="label"><span><?php echo $block->escapeHtml(__('General Subscription')) ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.newsletter.extra')?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary"><button type="submit" title="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Save')) ?>" class="action save primary"><span><?php echo $block->escapeHtml(__('Save')) ?></span></button></div>
            <div class="secondary"><a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo $block->escapeHtml(__('Back')) ?></span></a></div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.newsletter.extra2')?>
