<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/resetpasswordpost', ['_query' => ['id' => $block->getCustomerId(), 'token' => $block->getResetPasswordLinkToken()]]); ?>"
      method="post"
      <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="form password reset"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields'); ?>">
        <div class="field password required">
            <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password'); ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password" data-validate="{required:true, 'validate-password':true}" autocomplete="off">
            </div>
        </div>
        <div class="field confirmation required">
            <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password'); ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Set a New Password'); ?></span></button>
        </div>
    </div>
</form>
