<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?= $this->doctype() ?>
<!--[if !IE]><!-->
<html lang="en" ng-app="magento">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{$state.current.title}}</title>
    <?= $this->headLink()
        ->appendStylesheet($this->basePath() . '/pub/styles/setup.css');
    ?>
    <?= $this->headScript()
        ->appendFile($this->basePath() . '/pub/angular/angular.min.js')
        ->appendFile($this->basePath() . '/pub/angular-ng-storage/angular-ng-storage.min.js')
        ->appendFile($this->basePath() . '/pub/angular-ng-dialog/angular-ng-dialog.min.js')
        ->appendFile($this->basePath() . '/pub/angular-clickout/angular-clickout.min.js')
        ->appendFile($this->basePath() . '/pub/angular-ui-router/angular-ui-router.min.js')
        ->appendFile($this->basePath() . '/pub/angular-ui-bootstrap/angular-ui-bootstrap.min.js')
        ->appendFile($this->basePath() . '/pub/angular-sanitize/angular-sanitize.min.js')
        ->appendFile($this->basePath() . '/pub/magento/setup/app.js')
        ->appendFile($this->basePath() . '/pub/magento/setup/main.js')
        ->appendFile($this->basePath() . '/pub/magento/setup/landing.js');
    ?>
    <link
        rel="icon"
        type="image/x-icon"
        href="<?= $this->basePath() ?>/pub/images/favicon/favicon.ico"
        sizes="16x16">
    <link
        rel="icon"
        type="image/png"
        href="<?= $this->basePath() ?>/pub/images/favicon/favicon-96x96.png"
        sizes="96x96">
    <link
        rel="icon"
        type="image/png"
        href="<?= $this->basePath() ?>/pub/images/favicon/favicon-32x32.png"
        sizes="32x32">
    <link
        rel="icon"
        type="image/png"
        href="<?= $this->basePath() ?>/pub/images/favicon/favicon-16x16.png"
        sizes="16x16">
    <?= $this->inlineScript() ?>
    <style>
        a.white-space-pre-line {
            white-space: pre-line;
        }
    </style>
</head>
<body>
<?= $this->content ?>
</body>
</html>
