<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($block->getQuote()->hasVirtualItems()): ?>
<div class="block block-other">
    <div class="block-title">
        <strong><?php echo /* @escapeNotVerified */ __('Other items in your order') ?></strong>
        <a href="<?php echo /* @escapeNotVerified */ $block->getVirtualProductEditUrl() ?>" class="action edit"><span><?php echo /* @escapeNotVerified */ __('Edit Items') ?></span></a>
    </div>
    <div class="block-content">
        <p><?php echo /* @escapeNotVerified */ __('Shipping is not applicable.') ?></p>
        <div class="table-wrapper">
            <table class="items data table" id="unavailable-shipping-table">
                <caption class="table-caption"><?php echo /* @escapeNotVerified */ __('Other items in your order') ?></caption>
                <thead>
                    <tr>
                        <th class="col item" scope="col"><?php echo /* @escapeNotVerified */ __('Product Name') ?></th>
                        <th class="col qty" scope="col"><?php echo /* @escapeNotVerified */ __('Qty') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($block->getVirtualQuoteItems() as $_item): ?>
                    <tr>
                        <td class="col item" data-th="<?php echo $block->escapeHtml(__('Product Name')) ?>"><?php echo $block->getItemHtml($_item) ?></td>
                        <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')) ?>"><?php echo /* @escapeNotVerified */ $_item->getQty() ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php endif; ?>
