<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<fieldset class="fieldset" id="export_filter_container" style="display:none;">
    <legend class="legend">
        <span><?php echo __('Entity Attributes'); ?></span>
    </legend>
    <br />
    <form id="export_filter_form" action="<?php echo $this->getUrl('*/*/export') ?>" method="post">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <div id="export_filter_grid_container"><!-- --></div>
    </form>
    <button class="action- scalable" type="button" onclick="getFile();"><span><?php
        echo __('Continue')
    ?></span></button>
</fieldset>
<script type="text/javascript">
require(['prototype'], function(){

//<![CDATA[
   $('entity').selectedIndex = 0; // forced resetting entity selector after page refresh
//]]>

});
</script>
