<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<div id="product-review-container" data-role="product-review"></div>
<?= $block->getChildHtml() ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
