<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\View $block */
?>
<?php if ($block->getProductData()->getId()) : ?>
<div class="product-review">
    <div class="page-title-wrapper">
        <h1><?= $escaper->escapeHtml(__('Review Details')) ?></h1>
    </div>
    <div class="product-img-box">
        <a href="<?= $escaper->escapeUrl($block->getProductData()->getProductUrl()) ?>">
            <?= $block->getImage($block->getProductData(), 'product_base_image', ['class' => 'product-image'])->toHtml() ?>
        </a>
        <?php if ($block->getRating() && $block->getRating()->getSize()) : ?>
            <p><?= $escaper->escapeHtml(__('Average Customer Rating')) ?>:</p>
            <?= $block->getReviewsSummaryHtml($block->getProductData()) ?>
        <?php endif; ?>
    </div>
    <div class="details">
        <h3 class="product-name"><?= $escaper->escapeHtml($block->getProductData()->getName()) ?></h3>
        <?php if ($block->getRating() && $block->getRating()->getSize()) : ?>
            <h4><?= $escaper->escapeHtml(__('Product Rating:')) ?></h4>
            <div class="table-wrapper">
                <table class="data-table review-summary-table">
                    <caption class="table-caption"><?= $escaper->escapeHtml(__('Product Rating')) ?></caption>
                    <?php foreach ($block->getRating() as $_rating) : ?>
                        <?php if ($_rating->getPercent()) : ?>
                            <tr>
                                <td class="label"><?= $escaper->escapeHtml(__($_rating->getRatingCode())) ?></td>
                                <td class="value">
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?= /* @noEscape */ ceil($_rating->getPercent()) ?>%;"></div>
                                    </div></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endif; ?>
        <p class="date"><?= $escaper->escapeHtml(__('Product Review (submitted on %1):', $block->dateFormat($block->getReviewData()->getCreatedAt()))) ?></p>
        <p><?= /* @noEscape */ nl2br($escaper->escapeHtml($block->getReviewData()->getDetail())) ?></p>
    </div>
    <div class="actions">
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Back to Product Reviews')) ?></span>
            </a>
        </div>
    </div>
</div>
<?php endif; ?>
