<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Quote Item row html
 *
 * @see \Magento\Checkout\Block\Cart\Item\Renderer
 */
?>
<?php /** @var $this Magento\Checkout\Block\Cart\Item\Renderer */ ?>
<?php $_item = $this->getItem() ?>
<tr>
    <td class="col item" data-th="<?php echo $this->escapeHtml(__('Product Name'));?>">
        <?php echo $this->getRenderedBlock()->getItemHtml($_item) ?>
    </td>
    <td class="col price" data-th="<?php echo $this->escapeHtml(__('Price'));?>">
        <?php /* Including Tax */ ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceInclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
                <span class="price-including-tax" data-label="<?php echo $this->escapeHtml(__('Incl. Tax'));?>">
                    <?php echo $this->getUnitPriceInclTaxHtml($_item); ?>
                </span>
            <?php endif; ?>
        <?php /* // Including Tax */ ?>
        <?php /* Excluding Tax */ ?>
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceExclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $this->escapeHtml(__('Excl. Tax'));?>">
                <?php echo $this->getUnitPriceExclTaxHtml($_item); ?>
            </span>
        <?php endif; ?>
        <?php /* // Excluding Tax */ ?>
    </td>

    <td class="col qty" data-th="<?php echo $this->escapeHtml(__('Qty'));?>"><?php echo $_item->getQty()*1 ?></td>
    <td class="col subtotal" data-th="<?php echo $this->escapeHtml(__('Subtotal'));?>">
    <?php /* Including Tax Subtotal */ ?>
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceInclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
        <span class="price-including-tax" data-label="<?php echo $this->escapeHtml(__('Incl. Tax'));?>">
            <?php echo $this->getRowTotalInclTaxHtml($_item); ?>
        </span>
        <?php endif; ?>
    <?php /* //Including Tax Subtotal */ ?>
    <?php /* Excluding Tax Subtotal */ ?>
    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceExclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
        <span class="price-excluding-tax" data-label="<?php echo $this->escapeHtml(__('Excl. Tax'));?>">
            <?php echo $this->getRowTotalExclTaxHtml($_item); ?>
        </span>
    <?php endif; ?>
    <?php /* //Excluding Tax Subtotal */ ?>
    </td>
</tr>
