<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<tr class="<?php echo /* @escapeNotVerified */ $block->getTotal()->getCode() ?> row-totals">
    <td style="<?php echo /* @escapeNotVerified */ $block->getTotal()->getStyle() ?>" class="admin__total-mark" colspan="<?php echo /* @escapeNotVerified */ $block->getColspan() ?>">
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo $block->escapeHtml($block->getTotal()->getTitle()) ?>
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
    <td style="<?php echo /* @escapeNotVerified */ $block->getTotal()->getStyle() ?>" class="admin__total-amount">
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php echo /* @escapeNotVerified */ $block->formatPrice($block->getTotal()->getValue()) ?>
        <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
