<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Tax\Block\Checkout\Shipping
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @see \Magento\Tax\Block\Checkout\Shipping
 */
?>
<?php if ($block->displayBoth()):?>
<tr id="shipping-exclude-tax" class="row-totals">
    <td class="admin__total-mark" colspan="<?= (int) $block->getColspan() ?>">
        <?= $block->escapeHtml($block->getExcludeTaxLabel()) ?>
    </td>
    <td class="admin__total-amount">
        <?= /* @noEscape */ $block->formatPrice($block->getShippingExcludeTax()) ?>
    </td>
</tr>
    <?php if ($block->escapeHtmlAttr($block->getStyle())): ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-exclude-tax td.admin__total-mark'
        ) ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-exclude-tax td.admin__total-amount'
        ) ?>
    <?php endif; ?>
<tr id="shipping-include-tax" class="row-totals">
    <td class="admin__total-mark" colspan="<?= (int) $block->getColspan() ?>">
        <?= $block->escapeHtml($block->getIncludeTaxLabel()) ?>
    </td>
    <td class="admin__total-amount">
        <?= /* @noEscape */ $block->formatPrice($block->getShippingIncludeTax()) ?>
    </td>
</tr>
    <?php if ($block->escapeHtmlAttr($block->getStyle())): ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-include-tax td.admin__total-mark'
        ) ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-include-tax td.admin__total-amount'
        ) ?>
    <?php endif; ?>
<?php elseif ($block->displayIncludeTax()): ?>
<tr id="shipping-include-tax">
    <td class="admin__total-mark" colspan="<?= (int) $block->getColspan() ?>">
        <?= $block->escapeHtml($block->getTotal()->getTitle()) ?>
    </td>
    <td class="admin__total-amount">
        <?= /* @noEscape */ $block->formatPrice($block->getShippingIncludeTax()) ?>
    </td>
</tr>
    <?php if ($block->escapeHtmlAttr($block->getStyle())): ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-include-tax td.admin__total-mark'
        ) ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-include-tax td.admin__total-amount'
        ) ?>
    <?php endif; ?>
<?php else: ?>
<tr id="shipping-exclude-tax" class="row-totals">
    <td class="admin__total-mark" colspan="<?= (int) $block->getColspan() ?>">
        <?= $block->escapeHtml($block->getTotal()->getTitle()) ?>
    </td>
    <td class="admin__total-amount">
        <?= /* @noEscape */ $block->formatPrice($block->getShippingExcludeTax()) ?>
    </td>
</tr>
    <?php if ($block->escapeHtmlAttr($block->getStyle())): ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-exclude-tax td.admin__total-mark'
        ) ?>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $block->escapeHtmlAttr($block->getStyle()),
            'tr#shipping-exclude-tax td.admin__total-amount'
        ) ?>
    <?php endif; ?>
<?php endif;?>
