<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Totals\Subtotal
 * @see \Magento\Sales\Block\Adminhtml\Order\Create\Totals\Subtotal
 */
?>
<?php if ($block->displayBoth()) : ?>
<tr class="row-totals">
    <td style="<?= $block->escapeHtmlAttr($block->getStyle()) ?>" class="admin__total-mark" colspan="<?= (int) $block->getColspan() ?>">
        <?= $block->escapeHtml(__('Subtotal (Excl. Tax)')) ?>
    </td>
    <td style="<?= $block->escapeHtmlAttr($block->getStyle()) ?>" class="admin__total-amount">
        <?= /* @noEscape */ $block->formatPrice($block->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr class="row-totals">
    <td style="<?= $block->escapeHtmlAttr($block->getStyle()) ?>" class="admin__total-mark" colspan="<?= (int) $block->getColspan() ?>">
        <?= $block->escapeHtml(__('Subtotal (Incl. Tax)')) ?>
    </td>
    <td style="<?= $block->escapeHtmlAttr($block->getStyle()) ?>" class="admin__total-amount">
        <?= /* @noEscape */ $block->formatPrice($block->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else : ?>
<tr class="row-totals">
    <td style="<?= $block->escapeHtmlAttr($block->getStyle()) ?>" class="admin__total-mark" colspan="<?= (int) $block->getColspan() ?>">
        <?= $block->escapeHtml($block->getTotal()->getTitle()) ?>
    </td>
    <td style="<?= $block->escapeHtmlAttr($block->getStyle()) ?>" class="admin__total-amount">
        <?= /* @noEscape */ $block->formatPrice($block->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif;?>
