<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var \Magento\Ui\Component\Paging $block
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/listing/paging": <?php echo $block->getConfigBuilder()->toJson($block->getConfig()); ?>
        }
    }
</script>
<div data-bind="scope: '<?php echo $block->getParentName(); ?>:<?php echo $block->getName(); ?>'" class="pager">
    <!-- ko template: 'ui/pagination' --><!-- /ko -->
</div>
