<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var \Magento\Ui\Component\Paging $block
 */
?>
<script data-mage-init='{"Magento_Ui/js/listing/paging" : ""}' type="application/json">
    <?php echo $block->getConfigBuilder()->toJson($block->getConfig()); ?>
</script>
<div data-bind="scope: '<?php echo $block->getParentName(); ?>:<?php echo $block->getName(); ?>'" class="pager">
    <!-- ko template: 'ui/pagination' --><!-- /ko -->
</div>
