<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_source  = $block->getSource() ?>
<?php $block->setPriceDataObject($_source) ?>

<tr>
    <td class="label">
        <strong><big>
        <?php if ($block->getGrandTotalTitle()): ?>
            <?= /* @escapeNotVerified */ $block->getGrandTotalTitle() ?>
        <?php else: ?>
            <?= /* @escapeNotVerified */ __('Grand Total') ?>
        <?php endif; ?>
        </big></strong>
    </td>
    <td class="emph"><big><?= /* @escapeNotVerified */ $block->displayPriceAttribute('grand_total', true) ?></big></td>
</tr>
