<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */
?>
<?php $_source = $block->getSource() ?>
<?php $block->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getDataUsingMethod($block->getSourceField())) : ?>
    <tr>
        <td class="label">
            <?php if ($block->getStrong()) : ?>
                <strong>
            <?php endif; ?>
            <?= $block->escapeHtml(__($block->getLabel())) ?>
            <?php if ($block->getStrong()) : ?>
                </strong>
            <?php endif; ?>
        </td>
        <td <?= $block->getHtmlClass() ? ('class="' . $block->escapeHtmlAttr($block->getHtmlClass()) . '"') : '' ?>>
            <?php if ($block->getStrong()) : ?><strong><?php endif; ?>
            <?= /* @noEscape */ $block->displayPriceAttribute($block->getSourceField()) ?>
            <?php if ($block->getStrong()) : ?></strong><?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
