<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($block->getCanDisplayTotalPaid()): ?>
<tr>
    <td class="label"><strong><?php echo /* @escapeNotVerified */ __('Total Paid') ?></strong></td>
    <td class="emph"><?php echo /* @escapeNotVerified */ $block->displayPriceAttribute('total_paid', true) ?>
    </td>
</tr>
<?php endif; ?>
