<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($block->getCanDisplayTotalRefunded()): ?>
<tr>
    <td class="label"><strong><?php echo /* @escapeNotVerified */ __('Total Refunded') ?></strong></td>
    <td class="emph"><?php echo /* @escapeNotVerified */ $block->displayPriceAttribute('total_refunded', true) ?></td>
</tr>
<?php endif; ?>
