<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($block->getCanDisplayTotalRefunded()): ?>
<tr>
    <td class="label"><strong><?php /* @escapeNotVerified */ echo __('Total Refunded') ?></strong></td>
    <td class="emph"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('total_refunded', true) ?></td>
</tr>
<?php endif; ?>
