<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_source  = $block->getSource() ?>
<?php $block->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getShippingAmount() || $_source->getShippingDescription()): ?>
    <tr>
        <td class="label"><?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling') ?></td>
        <td><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('shipping_amount') ?></td>
    </tr>
<?php endif; ?>
