<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<form name="validation-form" id="validation-form" action="<?php echo $block->getAcsUrl();?>" method="post">
    <fieldset>
        <input type="hidden" name="PaReq" value="<?php echo $block->getPaReq()?>" />
        <input type="hidden" name="TermUrl" value="<?php echo $block->getTermUrl()?>" />
        <input type="hidden" name="MD" value="<?php echo $block->getMd()?>" />
    </fieldset>
</form>
<script>

    window.onload = function () {
        parent.jQuery('[data-container="body"]').trigger("paymentAuthentication", {state: "start"});
        document.getElementById('validation-form').submit();
    }

</script>
