<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\CurrencySymbol\Block\Adminhtml\System\Currency\Rate\Services
 */
?>
<div class="admin__field">
    <label class="admin__field-label"><span><?= /* @escapeNotVerified */ __('Import Service') ?></span></label>
    <div class="admin__field-control">
        <?= $block->getChildHtml('import_services') ?>
    </div>
</div>
