<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Payment\Block\Info
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $block->getSpecificInformation()):?>
<table class="data-table admin__table-secondary">
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <th><?php echo $block->escapeHtml($_label)?>:</th>
        <td><?php echo nl2br(implode("\n", $block->getValueAsArray($_value, true)))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php echo $block->getChildHtml()?>
