<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
?>
<p><?= $block->escapeHtml($block->getTitle()) ?></p>
<?php if ($block->getInstructions()) : ?>
    <table>
        <tbody>
            <tr>
                <td><?= /* @noEscape */ nl2br($block->escapeHtml($block->getInstructions())) ?></td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>
