<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 */
?>
<div>
    <?= $block->getMethod()->getTitle()
        ? $escaper->escapeHtml($block->getMethod()->getTitle())
        : $escaper->escapeHtml(__('Payment method')); ?>
    <?= $escaper->escapeHtml(__(' is not available. You still can process offline actions.')) ?>
</div>
