<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Info\Buttons\Rss */
?>
<?php if ($block->isRssAllowed() && $block->getLink()): ?>
<a href="<?= /* @escapeNotVerified */ $block->getLink() ?>" class="action rss">
    <span><?= /* @escapeNotVerified */ $block->getLabel() ?></span>
</a>
<?php endif; ?>
