<?php
/**
 * Copyright 2017 Adobe
 * All Rights Reserved.
 */

/** @var Magento\Ui\Block\Wysiwyg\ActiveEditor $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$wysiwygAdapterPath = /* @noEscape */ $block->getWysiwygAdapterPath();
$scriptString = <<<script
    require.config({
        map: {
            '*': {
                wysiwygAdapter: '{$wysiwygAdapterPath}'
            }
        }
    });
script;

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
