<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Magento\Ui\Block\Wysiwyg\ActiveEditor $block */

?>

<script>
    require.config({
        map: {
            '*': {
                wysiwygAdapter: '<?php /* @noEscape */ echo $block->getWysiwygAdapterPath(); ?>'
            }
        }
    });
</script>
