<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('prototype/windows/themes/default.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('mage/translate-inline-vde.css') ?>"/>

<script id="translate-inline-dialog-form-template" type="text/x-magento-template">
    <form id="<%- data.id %>" data-form="translate-inline-dialog-form">
        <% _.each(data.items, function(item, index) { %>
            <input id="perstore_<%- index %>" name="translate[<%- index %>][perstore]" type="hidden" value="0"/>
            <input name="translate[<%- index %>][original]" type="hidden" value="<%- data.escape(item.original) %>"/>
            <textarea id="custom_<%- index %>"
                      name="translate[<%- index %>][custom]"
                      data-translate-input-index="<%- index %>"><%- data.escape(item.translated) %></textarea>
        <% }); %>
    </form>
</script>

<script data-template="translate-inline-icon" type="text/x-magento-template">
  <img src="<%- data.img %>" height="16" width="16" class="translate-edit-icon">
</script>

<div id="translate-dialog" data-role="translate-dialog"
     data-mage-init='{"loader": {"icon": "<?php echo $block->getViewFileUrl('images/ajax-loader-tr.gif', ['area' => \Magento\Backend\App\Area\FrontNameResolver::AREA_CODE]) ?>"}}'>
 </div>

<script>
require([
    "jquery",
    "mage/translate",
    "mage/loader_old",
    "mage/bootstrap",
    "mage/edit-trigger",
    "mage/translate-inline",
    "mage/translate-inline-vde"
], function($){
        $(window).load(function() {
            var $body = $('body');
            var $textTranslations = $('[data-translate-mode="text"]');
            var $imageTranslations = $('[data-translate-mode="alt"]');
            var $scriptTranslations = $('[data-translate-mode="script"]');

            <?php if ($block->getTranslateMode()): ?>
                $body.addClass('<?php echo 'trnslate-inline-' . $block->getTranslateMode() . '-area' ?>');
            <?php endif; ?>

            /** @todo temporary fix to add data- attribute to body. */
            $body.attr("data-container", "body");

            $('#translate-dialog').translateInlineDialogVde({
                ajaxUrl: '<?php echo $block->getAjaxUrl() ?>',
                area: '<?php echo $block->getArea() ?>',
                translateMode: '<?php echo $block->getTranslateMode() ?>',
                textTranslations: $textTranslations,
                imageTranslations: $imageTranslations,
                scriptTranslations: $scriptTranslations
            });
            var dialogVde = $('#translate-dialog');

            $textTranslations.translateInlineVde({
                img: '<?php echo $block->getViewFileUrl('Magento_Translation::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $block->getViewFileUrl('Magento_Translation::translate_edit_icon_hover.png') ?>',
                translateMode: '<?php echo $block->getTranslateMode() ?>',
                onClick: function(e, widget) {
                    $body.removeClass('trnslate-inline-' + widget.options.translateMode + '-area');
                    $textTranslations.translateInlineVde('hide');
                    dialogVde.translateInlineDialogVde(
                        'openWithWidget',
                        e,
                        widget,
                        $.proxy(widget.replaceText, widget)
                    );
                }
            });

            $imageTranslations.translateInlineImageVde({
                img: '<?php echo $block->getViewFileUrl('Magento_Translation::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $block->getViewFileUrl('Magento_Translation::translate_edit_icon_hover.png') ?>',
                translateMode: '<?php echo $block->getTranslateMode() ?>',
                onClick: function(e, widget) {
                    $body.removeClass('trnslate-inline-' + widget.options.translateMode + '-area');
                    $imageTranslations.translateInlineImageVde('hide');
                    dialogVde.translateInlineDialogVde(
                        'openWithWidget',
                        e,
                        widget,
                        $.proxy(widget.replaceText, widget)
                    );
                }
            });

            $scriptTranslations.translateInlineScriptVde({
                img: '<?php echo $block->getViewFileUrl('Magento_Translation::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $block->getViewFileUrl('Magento_Translation::translate_edit_icon_hover.png') ?>',
                translateMode: '<?php echo $block->getTranslateMode() ?>',
                onClick: function(e, widget) {
                    $body.removeClass('trnslate-inline-' + widget.options.translateMode + '-area');
                    $scriptTranslations.translateInlineScriptVde('hide');
                    dialogVde.translateInlineDialogVde(
                        'openWithWidget',
                        e,
                        widget,
                        $.proxy(widget.replaceText, widget)
                    );
                }
            });

            parent.jQuery('[data-translate-container]').translateInlineToggle({
                frameUrl: '<?php echo $block->getFrameUrl() ?>',
                refreshVdeCanvas: <?php if ($block->getRefreshCanvas()): ?>false<?php else: ?>true<?php endif; ?>,
                dialogWidgetElement: dialogVde
            });
        });
});
</script>
