<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $this \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $this->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?php echo $this->escapeHtml(__('Item')); ?>" class="col item">
        <?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-item-photo">
            <?php else:?>
            <span class="product-item-photo">
        <?php endif;?>
        <?php echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\Image')->init($this->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($this->hasProductUrl()):?></a><?php else: ?></span><?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($this->hasProductUrl()):?>
                    <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $this->escapeHtml($this->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $this->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $this->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?php echo $message['type'] ?>"><div><?php echo $this->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
        <?php $cols = 1; ?>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?php echo $this->escapeHtml(__('Price')); ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?php echo __('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <?php $coreHelper = $this->helper('Magento\Core\Helper\Data'); ?>
                <a href="#" class="action help map" id="<?php echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php echo $helpLinkId;?>","productName": "<?php echo $product->getName(); ?>","showAddToCart": false}}'>
                    <span><?php echo __("What's this?"); ?></span>
                </a>
            </span>
            <?php $cols++; ?>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?php echo $this->escapeHtml(__('Price')); ?>">
            <?php echo $this->getUnitPriceHtml($_item); ?>
            <?php $cols++; ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?php echo $this->escapeHtml(__('Qty')); ?>">
        <div class="field qty">
            <label class="label" for="cart-<?php echo $_item->getId() ?>-qty">
                <span><?php echo __('Qty') ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?php echo $_item->getId() ?>-qty" name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" type="number" size="4" title="<?php echo __('Qty') ?>" class="input-text qty" maxlength="12" data-validate="{required:true,'validate-greater-than-zero':true}"/>
            </div>
        </div>
        <?php $cols++; ?>
    </td>

    <td class="col subtotal" data-th="<?php echo $this->escapeHtml(__('Subtotal'));?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?php echo $this->getRowTotalHtml($_item); ?>
        <?php endif; ?>
        <?php $cols++; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="<?php echo $cols;?>">
        <div class="actions-toolbar">
            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllowInCart()) : ?>
                <?php if ($isVisibleProduct): ?>
                    <a href="#" data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getMoveFromCartParams($_item->getId()); ?>' class="use-ajax action towishlist">
                        <span><?php echo __('Move to Wishlist'); ?></span>
                    </a>
                <?php endif ?>
            <?php endif ?>

            <?php if ($isVisibleProduct): ?>
                <a class="action edit" href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo __('Edit item parameters') ?>"><span><?php echo __('Edit') ?></span></a>
            <?php endif ?>

            <a href="#" title="<?php echo __('Remove item') ?>"
                    class="action delete"
                    data-post='<?php echo $this->helper('Magento\Checkout\Helper\Cart')->getDeletePostJson($_item); ?>'>
                <span><?php echo __('Remove item')?></span>
            </a>
        </div>
    </td>
</tr>
</tbody>
