<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $this \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $this->getProduct() ?>

<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
        <div class="stock available" title="<?php echo __('Availability') ?>">
            <span><?php echo __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php echo __('Availability') ?>">
            <span><?php echo __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
