<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @see \Magento\Catalog\Block\Adminhtml\Form\Renderer\Fieldset\Element
 */
?>
<?php
/* @var $this \Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element */
$element = $this->getElement();
$note = $element->getNote() ? '<div class="note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox' || $element->getExtType() == 'radio';
$addOn = $element->getBeforeElementHtml() || $element->getAfterElementHtml();
$fieldId = ($element->getHtmlId()) ? ' id="attribute-' . $element->getHtmlId() . '-container"' : '';
$entity = $element->getEntityAttribute();
$fieldClass = "field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= ($entity && $entity->getIsUserDefined()) ? ' user-defined type-' . $entity->getFrontendInput() : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $this->getUiId('form-field', $element->getId());
?>

<?php $this->checkFieldDisable() ?>
<?php
    $elementToggleCode = $element->getToggleCode() ? $element->getToggleCode()
        : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>
<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?php echo $element->getElementHtml() ?>
    <?php else: ?>
    <div<?php echo $fieldAttributes ?> data-attribute-code="<?php echo $element->getHtmlId() ?>"
        data-apply-to="<?php echo $this->escapeHtml($this->helper('Magento\Core\Helper\Data')->jsonEncode(
            $element->hasEntityAttribute() ? $element->getEntityAttribute()->getApplyTo() : []
        ))?>"
        >
        <?php if ($elementBeforeLabel): ?>
            <?php echo $this->getElementHtml() ?>
            <?php echo $element->getLabelHtml() ?>
            <?php echo $note ?>
        <?php else: ?>
            <?php echo $element->getLabelHtml() ?>
            <div class="control">
                <?php echo($addOn) ? '<div class="addon">' . $this->getElementHtml() . '</div>' : $this->getElementHtml(); ?>
                <?php echo $note ?>
            </div>
        <?php endif; ?>
        <div class="field-service" value-scope="<?php echo $this->getScopeLabel()?>">
            <?php if ($this->canDisplayUseDefault()): ?>
                <label for="<?php echo $element->getHtmlId() ?>_default" class="choice use-default">
                    <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                            type="checkbox"
                            name="use_default[]"
                            class="use-default-control"
                            id="<?php echo $element->getHtmlId() ?>_default"
                            <?php if ($this->usedDefault()): ?> checked="checked"<?php endif; ?>
                            onclick="<?php echo $elementToggleCode; ?>"
                            value="<?php echo $this->getAttributeCode() ?>"/>
                    <span class="use-default-label"><?php echo __('Use Default Value') ?></span>
                </label>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
