<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */
/** @var \Magento\Catalog\Block\Adminhtml\Product\Edit\NewCategory $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div id="<?= $block->escapeHtmlAttr($block->getNameInLayout()) ?>">
    <?= $block->getFormHtml() ?>
    <?= $block->getAfterElementHtml() ?>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    $block->escapeJs($block->getNameInLayout())
) ?>
