<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\Composite
 */
?>
<?php if ($block->isMsgVisible()) : ?>
    <div class="availability only">
        <a href="#"
           data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "baseToggleClass": "expanded", "toggleContainers": "#<?= $block->escapeHtmlAttr($block->getDetailsPlaceholderId()) ?>"}}'
           id="<?= $block->escapeHtmlAttr($block->getPlaceholderId()) ?>"
           title="<?= $block->escapeHtmlAttr(__('Only %1 left', ($block->getStockQtyLeft()))) ?>"
           class="action show">
            <?= /* @noEscape */ __('Only %1 left', "<strong>{$block->escapeHtml($block->getStockQtyLeft())}</strong>") ?>
        </a>
    </div>
    <div class="availability only detailed" id="<?= $block->escapeHtmlAttr($block->getDetailsPlaceholderId()) ?>">
        <div class="table-wrapper">
            <table class="data table">
                <caption class="table-caption"><?= $block->escapeHtml(__('Product availability')) ?></caption>
                <thead>
                <tr>
                    <th class="col item" scope="col"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($block->getChildProducts() as $childProduct) : ?>
                    <?php $childProductStockQty = $block->getProductStockQty($childProduct); ?>
                    <?php if ($childProductStockQty > 0) : ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col item"><?= $block->escapeHtml($childProduct->getName()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="col qty"><?= $block->escapeHtml($childProductStockQty) ?></td>
                        </tr>
                    <?php endif ?>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif ?>
