<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if ($block->isMsgVisible()) : ?>
    <div class="availability only" title="<?= $escaper->escapeHtmlAttr(__('Only %1 left', ($block->getStockQtyLeft()))) ?>">
        <?= /* @noEscape */ __('Only %1 left', "<strong>{$escaper->escapeHtml($block->getStockQtyLeft())}</strong>") ?>
    </div>
<?php endif ?>
