<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\CatalogInventory\Block\Stockqty\DefaultStockqty;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var DefaultStockqty $block */
?>
<?php if ($block->isMsgVisible()) : ?>
    <div class="availability only" title="<?= $escaper->escapeHtmlAttr(__('Only %1 left', ($block->getStockQtyLeft()))) ?>">
        <?= /* @noEscape */ __('Only %1 left', "<strong>{$escaper->escapeHtml($block->getStockQtyLeft())}</strong>") ?>
    </div>
<?php endif ?>
