<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<fieldset id="tax-rate-titles-table" class="admin__fieldset">
    <?php $_labels = $block->getTitles() ?>
    <?php foreach ($block->getStores() as $_store) : ?>
        <div class="admin__field">
            <label class="admin__field-label">
                <span><?= $block->escapeHtml($_store->getName()) ?></span>
            </label>
            <div class="admin__field-control">
                <input
                    class="admin__control-text<?php if ($_store->getId() == 0) : ?> required-entry<?php endif; ?>"
                    type="text"
                    name="title[<?= (int) $_store->getId() ?>]"
                    value="<?= $block->escapeHtmlAttr($_labels[(int) $_store->getId()]) ?>" />
            </div>
        </div>
    <?php endforeach; ?>

    <div class="messages">
        <div class="message message-notice">
            <div>
                <strong><?= $block->escapeHtml(__('Note:')) ?></strong>
                <?= $block->escapeHtml(__('Leave this field empty if you wish to use the tax identifier.')) ?>
            </div>
        </div>
    </div>
</fieldset>
