<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="entry-edit rule-tree">
<?php echo $this->getFormHtml() ?>
</div>
<script type="text/javascript">
/*
    if ($('rule_conditions_fieldset')) {
        var conditionsForm = new VarienRulesForm('rule_conditions_fieldset', '<?php echo $this->getNewConditionChildUrl() ?>');
    }
    if ($('rule_actions_fieldset')) {
        var actionsForm = new VarienRulesForm('rule_actions_fieldset', '<?php echo $this->getNewActionChildUrl() ?>');
    }
*/
</script>
