<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
require(["jquery", "prototype"], function(jQuery){

function changeValidationForDiscountPercent()
{
    if ($('rule_simple_action').value == 'by_percent' || $('rule_simple_action').value == 'to_percent') {
        $('rule_discount_amount').addClassName('validate-number-range number-range-0.00-100.00');
    } else {
        $('rule_discount_amount').removeClassName('validate-number-range').removeClassName('number-range-0.00-100.00');
    }

    return true;
}

jQuery(document).ready(changeValidationForDiscountPercent);
jQuery(document).on('change', '#rule_simple_action', changeValidationForDiscountPercent);
window.changeValidationForDiscountPercent = changeValidationForDiscountPercent;
});
</script>
