<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Ajax\Serializer */
?>

// phpcs:disable Magento2.Security.InsecureFunction.DiscouragedWithAlternative
<?php
// md5() here is not for cryptographic use.
// phpcs:ignore Magento2.Security.InsecureFunction
$_id = 'id_' . md5(microtime())
?>
<input type="hidden"
       name="<?= $block->escapeHtmlAttr($block->getInputElementName()) ?>"
       value=""
       id="<?= /* @noEscape */ $_id ?>" />
