<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\DesignEditor\Block\Adminhtml\Editor\Tools\Code\ImageSizing */ ?>
<div class="vde-tools-image-settings">
    <div id="vde-tab-imagesizing-messages-placeholder"></div>
</div>
<div class="form-inline vde-image-sizing">
<?php echo $block->getFormHtml(); ?>
</div>
<script>
require([
    "jquery",
    "Magento_DesignEditor/js/image-sizing"
], function($){

    $('#product_image_sizing_form').vdeImageSizing({
        formId: '#product_image_sizing_form',
        imageRatioClass: '.image-ratio',
        imageWidthClass: '.image-width',
        imageHeightClass: '.image-height',
        formUrl: '<?php echo $block->getImageSizingUrl() ?>',
        maxSizeValue: <?php echo \Magento\DesignEditor\Model\Editor\Tools\ImageSizing\Validator::MAX_SIZE_VALUE ?>,
        messagesContainer: '#vde-tab-imagesizing-messages-placeholder'
    });

});
</script>
