<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/*
 * @var $block \Magento\Paypal\Block\Adminhtml\System\Config\Payflowlink\Advanced
 */
?>
<div class="payflow-settings-notice">
    <p>
        <strong class="important-label"><?php echo $block->escapeHtml(__('Important: ')); ?></strong>
        <?php echo $block->escapeHtml(__('To use PayPal Payments Advanced, you must configure  your PayPal Payments Advanced account on the PayPal website.')); ?>
        <?php echo $block->escapeHtml(__('Once you log into your PayPal Advanced account, navigate to the Service Settings - Hosted Checkout Pages - Set Up menu and set the options described below')); ?>
    </p>
    <ul class="options-list">
        <li><strong>AVS:</strong> No</li>
        <li><strong>CSC:</strong> No</li>
        <li><strong>Enable Secure Token:</strong> Yes</li>
    </ul>
</div>
