<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_creditmemo = $block->getCreditmemo() ?>
<?php $_order      = $block->getOrder() ?>
<?php if ($_creditmemo && $_order): ?>
<table>
    <thead>
        <tr>
            <th><?php echo __('Item') ?></th>
            <th><?php echo __('Sku') ?></th>
            <th><?php echo __('Qty') ?></th>
            <th><?php echo __('Subtotal') ?></th>
        </tr>
    </thead>

    <?php $i = 0; foreach ($_creditmemo->getAllItems() as $_item): ?>
    <?php if ($_item->getOrderItem()->getParentItem()) {
    continue;
} else {
    $i++;
} ?>
    <tbody<?php echo $i%2 ? ' ' : '' ?>>
        <?php echo $block->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>

    <tfoot>
        <?php echo $block->getChildHtml('creditmemo_totals');?>
    </tfoot>
</table>
<?php endif; ?>
