<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */

/**
 * @deprecated
 */
?>
<?php if ($_products = $block->getRecentlyComparedProducts()) : ?>
<div class="block widget block-compared-products-names">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Recently Compared')) ?></span></strong>
    </div>
    <div class="block-content">
        <ol id="widget-compared-<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>" class="product-items product-items-names">
        <?php $i = 0; foreach ($_products as $_product) : ?>
            <li class="product-item">
                <strong class="product-item-name">
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="product-item-link">
                        <?= $escaper->escapeHtml($this->helper(\Magento\Catalog\Helper\Output::class)->productAttribute($_product, $_product->getName(), 'name')) ?>
                    </a>
                </strong>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
