<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api;

use \Magento\SearchStorefrontApi\Api\Data\ProductSearchRequestInterface;
use \Magento\SearchStorefrontApi\Api\Data\ProductsSearchResultInterface;

/**
 * Autogenerated description for InMemorySearch class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class InMemorySearch implements SearchInterface
{
    /**
     * @var SearchServerInterface
     */
    private $service;

    /**
     * @param SearchServerInterface $service
     */
    public function __construct(
        SearchServerInterface $service
    ) {
        $this->service = $service;
    }

    /**
     * Autogenerated description for searchProducts in memory client service method
     *
     * @param ProductSearchRequestInterface $request
     * @return ProductsSearchResultInterface
     */
    public function searchProducts(ProductSearchRequestInterface $request): ProductsSearchResultInterface
    {
        return $this->service->searchProducts($request);
    }
}
