<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var \Magento\Ui\Component\Listing $block
 */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/lib/provider":
                                    <?php echo $block->getRenderContext()
                                                ->getConfigBuilder()
                                                ->toJson($block->getRenderContext()->getStorage(), $block->getName());
                                    ?>,
        "Magento_Ui/js/listing/grid": <?php echo $block->getConfigBuilder()->toJson($block->getConfig()); ?>
    }
}
</script>
<?php echo $block->getChildHtml('listing_head'); ?>
<div class="grid">
    <?php echo $block->getChildHtml('listing_before'); ?>
    <div data-bind="scope: '<?php echo $block->getParentName(); ?>:<?php echo $block->getName(); ?>'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <?php echo $block->getChildHtml('listing_after'); ?>
</div>
<div data-role="spinner" class="grid-loading-mask">
    <div class="grid-loader"></div>
</div>
