<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php echo $block->getCaptchaHtml() ?>

<div class="grid-title">
    <span class="title"><?php echo __('Google Content Items') ?></span>
</div>
<div data-mage-init='{"loader": {}}' data-container="googleContent">
<?php echo $block->getChildHtml('item') ?>
</div>

<div class="grid-title">
    <div data-mage-init='{"floatingHeader": {}}' class="page-actions"><?php echo $block->getAddButtonHtml() ?></div>
    <span class="title"><?php echo __('Available Products') ?></span>
</div>
<div data-mage-init='{"loader": {}}' data-container="products" class="available-products">
<?php echo $block->getChildHtml('product') ?>
</div>

<script>
require([
	'Magento_GoogleShopping/googleshopping'
], function(){

Mage.GoogleShopping.isProcessRunning = <?php echo $block->isProcessRunning() ? 'true' : 'false'; ?>;
Mage.GoogleShopping.statusUrl = '<?php echo $block->getStatusUrl(); ?>';
Mage.GoogleShopping.runningMessage = '<?php echo __('Google Shopping synchronization process is running');?>';

});
</script>
