<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\CatalogWidget\Block\Product\Widget\Conditions $block
 * @var \Magento\Framework\Escaper $escaper
 */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$element = $block->getElement();
$fieldId = $element->getHtmlContainerId() ? ' id="' . $escaper->escapeHtmlAttr($element->getHtmlContainerId()) . '"' : '';
$fieldClass = 'field admin__field field-' . $escaper->escapeHtmlAttr($element->getId()) . ' '
    . $escaper->escapeHtmlAttr($element->getCssClass());
$fieldClass .= $element->getRequired() ? ' required' : '';
$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $escaper->escapeHtmlAttr($element->getId()));
?>
<div<?= /* @noEscape */ $fieldAttributes ?>>
    <?= $element->getLabelHtml() ?>
    <div class="control admin__field-control">
        <div class="rule-tree">
            <div class="rule-tree-wrapper">
                <?= $block->getInputHtml() ?>
            </div>
        </div>
    </div>
</div>

<?php $scriptString = <<<script
    require([
        "Magento_Rule/rules",
        "prototype"
    ], function(VarienRulesForm){
        window.{$escaper->escapeJs($block->getHtmlId())} = new VarienRulesForm('{$escaper->escapeJs($block->getHtmlId())}',
         '{$escaper->escapeUrl($block->getNewChildUrl())}');
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
