<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php if ($this->getWishlist()->getItemsCount() && $this->getWishlist()->isSalable()): ?>
    <button type="button" data-role="all-tocart" title="<?php echo __('Add All to Cart') ?>" class="action tocart">
        <span><?php echo __('Add All to Cart') ?></span>
    </button>
<?php endif;?>
