<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\Recursive */ ?>
<?php
/** @var $element \Magento\Framework\Data\Form\Element\AbstractElement */
$element = $block->getElement();
?>

<input id="<?php echo $element->getHtmlId() ?>"
    name="<?php echo $element->getName() ?>"
    <?php echo $block->getUiId($element->getType(), $element->getName()) ?>
    value="<?php echo $element->getEscapedValue() ?>"
    type="<?php echo $element->getType() ? $element->getType() : 'text' ?>"
    <?php echo $element->serialize($element->getHtmlAttributes()) ?> />
