<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for ProductSearchRequest class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class ProductSearchRequestMapper
{
    /**
     * @var string
     */
    private static $dtoClassName = ProductSearchRequestInterface::class;

    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Set the data to populate the DTO
    *
    * @param mixed $data
    * @return $this
    */
    public function setData($data)
    {
        $this->data = $data;
        return $this;
    }

    /**
    * Build new DTO populated with the data
    *
    * @return ProductSearchRequest
    */
    public function build()
    {
        $dto = $this->objectManager->create(self::$dtoClassName);
        foreach ($this->data as $key => $valueData) {
            if ($valueData === null) {
                continue;
            }
            $this->setByKey($dto, $key, $valueData);
        }
        return $dto;
    }

    /**
    * Set the value of the key using setters.
    *
    * In case if the field is object, the corresponding Mapper would be create and DTO representing the field data
    * would be built
    *
    * @param ProductSearchRequest $dto
    * @param string $key
    * @param mixed $value
    */
    private function setByKey(ProductSearchRequest $dto, string $key, $value): void
    {
        switch ($key) {
            case "phrase":
                $dto->setPhrase((string) $value);
                break;
            case "store":
                $dto->setStore((string) $value);
                break;
            case "page_size":
                $dto->setPageSize((int) $value);
                break;
            case "current_page":
                $dto->setCurrentPage((int) $value);
                break;
            case "filters":
                $convertedArray = [];
                foreach ($value as $element) {
                    $convertedArray[] = $this->objectManager
                        ->create(\Magento\SearchStorefrontApi\Api\Data\FilterMapper::class)
                        ->setData($element)
                        ->build();
                }
                $dto->setFilters($convertedArray);
                break;
            case "sort":
                $convertedArray = [];
                foreach ($value as $element) {
                    $convertedArray[] = $this->objectManager
                        ->create(\Magento\SearchStorefrontApi\Api\Data\SortMapper::class)
                        ->setData($element)
                        ->build();
                }
                $dto->setSort($convertedArray);
                break;
            case "include_aggregations":
                $dto->setIncludeAggregations((bool) $value);
                break;
            case "customer_group_id":
                $dto->setCustomerGroupId((int) $value);
                break;
        }
    }
}
