<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

/**
 * Autogenerated description for ProductsSearchResult class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class ProductsSearchResult implements ProductsSearchResultInterface
{

    /**
     * @var int
     */
    private $totalCount;

    /**
     * @var array
     */
    private $items;

    /**
     * @var array
     */
    private $facets;

    /**
     * @var \Magento\SearchStorefrontApi\Api\Data\SearchResultPageInfoInterface
     */
    private $pageInfo;
    
    /**
     * @inheritdoc
     *
     * @return int
     */
    public function getTotalCount(): int
    {
        return (int) $this->totalCount;
    }
    
    /**
     * @inheritdoc
     *
     * @param int $value
     * @return void
     */
    public function setTotalCount(int $value): void
    {
        $this->totalCount = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return string[]
     */
    public function getItems(): array
    {
        return (array) $this->items;
    }
    
    /**
     * @inheritdoc
     *
     * @param string[] $value
     * @return void
     */
    public function setItems(array $value): void
    {
        $this->items = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return \Magento\SearchStorefrontApi\Api\Data\BucketInterface[]
     */
    public function getFacets(): array
    {
        return (array) $this->facets;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\SearchStorefrontApi\Api\Data\BucketInterface[] $value
     * @return void
     */
    public function setFacets(array $value): void
    {
        $this->facets = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return \Magento\SearchStorefrontApi\Api\Data\SearchResultPageInfoInterface|null
     */
    public function getPageInfo(): ?\Magento\SearchStorefrontApi\Api\Data\SearchResultPageInfoInterface
    {
        return $this->pageInfo;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\SearchStorefrontApi\Api\Data\SearchResultPageInfoInterface $value
     * @return void
     */
    public function setPageInfo(\Magento\SearchStorefrontApi\Api\Data\SearchResultPageInfoInterface $value): void
    {
        $this->pageInfo = $value;
    }
}
