<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

/**
 * Autogenerated description for ProductSearchRequest interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ProductSearchRequestInterface
{
    /**
     * Autogenerated description for getPhrase() interface method
     *
     * @return string
     */
    public function getPhrase(): string;

    /**
     * Autogenerated description for setPhrase() interface method
     *
     * @param string $value
     * @return void
     */
    public function setPhrase(string $value): void;

    /**
     * Autogenerated description for getStore() interface method
     *
     * @return string
     */
    public function getStore(): string;

    /**
     * Autogenerated description for setStore() interface method
     *
     * @param string $value
     * @return void
     */
    public function setStore(string $value): void;

    /**
     * Autogenerated description for getPageSize() interface method
     *
     * @return int
     */
    public function getPageSize(): int;

    /**
     * Autogenerated description for setPageSize() interface method
     *
     * @param int $value
     * @return void
     */
    public function setPageSize(int $value): void;

    /**
     * Autogenerated description for getCurrentPage() interface method
     *
     * @return int
     */
    public function getCurrentPage(): int;

    /**
     * Autogenerated description for setCurrentPage() interface method
     *
     * @param int $value
     * @return void
     */
    public function setCurrentPage(int $value): void;

    /**
     * Autogenerated description for getFilters() interface method
     *
     * @return \Magento\SearchStorefrontApi\Api\Data\FilterInterface[]
     */
    public function getFilters(): array;

    /**
     * Autogenerated description for setFilters() interface method
     *
     * @param \Magento\SearchStorefrontApi\Api\Data\FilterInterface[] $value
     * @return void
     */
    public function setFilters(array $value): void;

    /**
     * Autogenerated description for getSort() interface method
     *
     * @return \Magento\SearchStorefrontApi\Api\Data\SortInterface[]
     */
    public function getSort(): array;

    /**
     * Autogenerated description for setSort() interface method
     *
     * @param \Magento\SearchStorefrontApi\Api\Data\SortInterface[] $value
     * @return void
     */
    public function setSort(array $value): void;

    /**
     * Autogenerated description for getIncludeAggregations() interface method
     *
     * @return bool
     */
    public function getIncludeAggregations(): bool;

    /**
     * Autogenerated description for setIncludeAggregations() interface method
     *
     * @param bool $value
     * @return void
     */
    public function setIncludeAggregations(bool $value): void;

    /**
     * Autogenerated description for getCustomerGroupId() interface method
     *
     * @return int
     */
    public function getCustomerGroupId(): int;

    /**
     * Autogenerated description for setCustomerGroupId() interface method
     *
     * @param int $value
     * @return void
     */
    public function setCustomerGroupId(int $value): void;
}
