<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for ProductsSearchResult class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class ProductsSearchResultArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Convert the DTO to the array with the data
    *
    * @param ProductsSearchResult $dto
    * @return array
    */
    public function convertToArray(ProductsSearchResult $dto)
    {
        $result = [];
        $result["total_count"] = $dto->getTotalCount();
        $result["items"] = $dto->getItems();
        /** Convert complex Array field **/
        $fieldArray = [];
        foreach ($dto->getFacets() as $fieldArrayDto) {
            $fieldArray[] = $this->objectManager->get(\Magento\SearchStorefrontApi\Api\Data\BucketArrayMapper::class)
                ->convertToArray($fieldArrayDto);
        }
        $result["facets"] = $fieldArray;
        if ($dto->getPageInfo() !== null) {
            $result["page_info"] = $this->objectManager->get(\Magento\SearchStorefrontApi\Api\Data\SearchResultPageInfoArrayMapper::class)
                ->convertToArray($dto->getPageInfo());
        }
        return $result;
    }
}
