<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

/**
 * Autogenerated description for SearchResultPageInfo interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface SearchResultPageInfoInterface
{
    /**
     * Autogenerated description for getCurrentPage() interface method
     *
     * @return int
     */
    public function getCurrentPage(): int;

    /**
     * Autogenerated description for setCurrentPage() interface method
     *
     * @param int $value
     * @return void
     */
    public function setCurrentPage(int $value): void;

    /**
     * Autogenerated description for getPageSize() interface method
     *
     * @return int
     */
    public function getPageSize(): int;

    /**
     * Autogenerated description for setPageSize() interface method
     *
     * @param int $value
     * @return void
     */
    public function setPageSize(int $value): void;

    /**
     * Autogenerated description for getTotalPages() interface method
     *
     * @return int
     */
    public function getTotalPages(): int;

    /**
     * Autogenerated description for setTotalPages() interface method
     *
     * @param int $value
     * @return void
     */
    public function setTotalPages(int $value): void;
}
