<?php

class Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo02 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo03 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo04 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo05 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo06 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo07 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo08 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo09 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo10 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo11 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo12 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo13 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo14 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo15 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}

class Foo16 extends Magento_Test_Php_Exemplar_CodeMessTest_phpmd_input_descendant_count {}
