<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Bundle\Block\Catalog\Product\View\Type\Bundle;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Bundle $block */
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>
        <p class="stock available" title="<?= $escaper->escapeHtmlAttr(__('Availability:')) ?>">
            <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
        </p>
    <?php else : ?>
        <p class="stock unavailable" title="<?= $escaper->escapeHtmlAttr(__('Availability:')) ?>">
            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>
<?= $block->getChildHtml('bundle_prices') ?>
