<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var $this \Magento\Catalog\Block\Product\Compare\Sidebar */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
$count = $_helper->getItemCount();
?>
<div class="block block-compare">
    <div class="block-title">
        <strong id="block-compare-heading" role="heading" aria-level="2"><?php echo __('Compare Products') ?></strong>
        <?php if ($count > 0): ?>
        <span class="counter qty"><?php echo($count == 1) ? __('1 item') : __('%1 items', $count) ?></span>
        <?php endif; ?>
    </div>
    <div class="block-content" aria-labelledby="block-compare-heading">
        <?php if ($_helper->getItemCount() > 0): ?>
            <ol id="compare-items" class="product-items product-items-names"
                data-mage-init='{"compareItems":{
                    "removeConfirmMessage":"<?php echo __("Are you sure you would like to remove this item from the compare products?") ?>",
                    "removeSelector":"#compare-items a.action.delete",
                    "clearAllConfirmMessage":"<?php echo __("Are you sure you would like to remove all products from your comparison?") ?>",
                    "clearAllSelector":"#compare-clear-all"
                }}'>
            <?php foreach ($_items as $_index => $_item): ?>
            <li class="product-item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>"/>
                <strong class="product-item-name">
                    <a href="<?php echo $this->getProductUrl($_item) ?>" class="product-item-link">
                        <?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_item, $_item->getName(), 'name') ?>
                    </a>
                </strong>
                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>

                <a href="#" data-post='<?php echo $compareHelper->getPostDataRemove($_item); ?>'
                   title="<?php echo __('Remove This Item') ?>"
                   class="action delete">
                    <span><?php echo __('Remove This Item') ?></span></a>
            </li>
        <?php endforeach; ?>
    </ol>
    <div class="actions-toolbar">
        <div class="primary">
            <a href="<?php echo $_helper->getListUrl() ?>" class="action compare primary"><span><?php echo __('Compare') ?></span></a>
        </div>
        <div class="secondary">
            <a id="compare-clear-all" href="#" data-post='<?php echo $_helper->getPostDataClearList() ?>' class="action clear">
                <span><?php echo __('Clear All') ?></span>
            </a>
        </div>
    </div>
    <?php else: ?>
        <div class="empty"><?php echo __('You have no items to compare.') ?></div>
    <?php endif; ?>
    </div>
</div>
