<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\DesignEditor\Block\Adminhtml\Editor\Tools\Tabs\AbstractTabs */ ?>

<div class="vde-tab-content tab-panel<?php echo $block->getIsActive() ? ' active' : '' ?>" id="<?php echo $block->getHtmlId(); ?>">
    <div class="vde-tab-content-header">
        <h4 class="vde-tab-content-title"><?php echo $block->getTitle(); ?></h4>

        <div class="vde-tools-tabs">
            <ul class="vde-tab-controls">
            <?php echo join('', $block->getTabHandles()) ?>
            </ul>
        </div>
    </div>
    <div class="vde-tab-content-inner">
        <div class="vde-tab-data">
            <?php echo join('', $block->getTabContents()) ?>
        </div>
    </div>
</div>
