<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Editor\Tools\Tabs\AbstractTabs */ ?>

<div class="vde-tab-content tab-panel<?php echo $this->getIsActive() ? ' active' : '' ?>" id="<?php echo $this->getHtmlId(); ?>">
    <div class="vde-tab-content-header">
        <h4 class="vde-tab-content-title"><?php echo $this->getTitle(); ?></h4>

        <div class="vde-tools-tabs">
            <ul class="vde-tab-controls">
            <?php echo join('', $this->getTabHandles()) ?>
            </ul>
        </div>
    </div>
    <div class="vde-tab-content-inner">
        <div class="vde-tab-data">
            <?php echo join('', $this->getTabContents()) ?>
        </div>
    </div>
</div>
