<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-mage-init='{"floatingHeader": {}}' class="page-actions">
    <?php echo $block->getBackButtonHtml(); ?>
    <?php echo $block->getResetButtonHtml(); ?>
    <?php echo $block->getDeleteButtonHtml(); ?>
    <?php echo $block->getSaveButtonHtml(); ?>
</div>
<?php echo $block->getRenameFormHtml(); ?>
<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#<?php /* @escapeNotVerified */ echo $block->getRenameFormId() ?>').mage('form').mage('validation');

});
</script>
