<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="page-actions">
    <?php echo $block->getBackButtonHtml(); ?>
    <?php echo $block->getResetButtonHtml(); ?>
    <?php echo $block->getDeleteButtonHtml(); ?>
    <?php echo $block->getSaveButtonHtml(); ?>
</div>
<?php echo $block->getRenameFormHtml(); ?>
<script type="text/javascript">
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#<?php echo $block->getRenameFormId() ?>').mage('form').mage('validation');

});
</script>
