<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="row clearfix">
        <form name="form_message" method="POST" id="form_message">
            <input type="text" name="message">
            <input type="submit" id="Submit"  name="submit" value="Submit">
        </form>
</div>


<div id="result_form"></div>

<script>
    require(['jquery'],function(){
        jQuery(document).ready(function() {
            jQuery("#form_message").submit(function(){
                var messageValue = jQuery("input[name='message']").val();
                var url = "<?php echo $block->getBaseUrl() . 'helloworld/input/result' ?>";
                jQuery.ajax({
                    url: url,
                    type: "POST",
                    data: {message:messageValue},
                    showLoader: true,
                    cache: false,
                    success: function(response) {
                            document.getElementById('result_form').innerHTML = response.output;
                    },
                });
                return false;
            });
        });
    });
</script>
