<div data-bind="scope: 'exapmlefrontendui-component'">
    <h2 data-bind="text: title"></h2>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "exapmlefrontendui-component": {
                    "component": "Example_ExampleFrontendUi/js/component",
                    "title": "adsasdas",

                }
            }
        }
    }
}
</script>
