<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_ba_agreement_id" class="required"><em>*</em><?php echo __('Billing Agreement') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_ba_agreement_id" name="payment[<?php echo $this->getTransportBAId(); ?>]" class="required-entry">
                <option value="">--<?php echo __('Please Select') ?>--</option>
            <?php foreach ($this->getBillingAgreements() as $id => $referenceId): ?>
                <option value="<?php echo $id ?>"><?php echo $this->escapeHtml($referenceId) ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
</ul>
