<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Adminhtml\Billing\Agreement\View\Form $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php $code = $block->escapeHtml($block->getMethodCode()) ?>
<fieldset class="form-list" id="payment_form_<?= /* @noEscape */ $code ?>">
    <div class="admin__field _required">
        <label for="<?= /* @noEscape */ $code ?>_ba_agreement_id" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Billing Agreement')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_ba_agreement_id"
                    name="payment[<?= $block->escapeHtml($block->getTransportBAId()) ?>]"
                    class="required-entry admin__control-select">
                <option value=""><?= $block->escapeHtml(__('Please Select')) ?></option>
                <?php foreach ($block->getBillingAgreements() as $id => $referenceId): ?>
                    <option value="<?= $block->escapeHtml($id) ?>">
                        <?= $block->escapeHtml($referenceId) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    'fieldset#payment_form_' . /* @noEscape */ $code
) ?>
