<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div>
<?= $block->escapeHtml(
    __(
        'Last updated: %1. To refresh last day\'s <a href="%2">statistics</a>, click',
        $block->getData('updatedAt'),
        $block->escapeUrl($block->getData('refreshStatsLink'))
    ),
    ['a']
);
?>
    <a href="#2">
        <span data-post="<?= $block->escapeHtmlAttr($block->getData('dataPost')) ?>">
        <?= $block->escapeHtml(__('here')) ?>
        </span>
    </a>
</div>