<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Authorizenet\Block\Transparent\Iframe
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$params = $block->getParams();
$helper = $block->getHelper('adminhtml');
?>
<html>
    <head>
<?php $scriptString = '';
if (isset($params['redirect'])) {
    $scriptString .= 'window.location="<?=' . $block->escapeUrl($params['redirect']) . '";' . PHP_EOL;
}
if (isset($params['redirect_parent'])) {
    $scriptString .= 'window.top.location="' . $block->escapeUrl($params['redirect_parent']) . '";' . PHP_EOL;
}
if (isset($params['error_msg'])) {
    $scriptString .= 'window.top.directPostModel.showError(<?=' .
        /* @noEscape */ json_encode((array)$params['error_msg']) . ');' . PHP_EOL;
    if (isset($params['x_invoice_num'])) {
        $scriptString .= 'window.top.directPostModel.successUrl="' .
            $block->escapeUrl($helper->getSuccessOrderUrl($params)) . '";' . PHP_EOL;
    }
}
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    </head>
    <body></body>
</html>
