<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @see \Magento\Authorizenet\Block\Directpost\Form
 */
?>
<?php
$_form = $block;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();
$_controller = $block->getRequest()->getControllerName();
$_orderUrl = $this->helper('Magento\Authorizenet\Helper\Backend\Data')->getPlaceOrderAdminUrl();
?>
<!-- IFRAME for request to our server -->
<iframe id="order-directpost-iframe" allowtransparency="true" frameborder="0" name="iframeSubmitOrder" style="display:none;width:100%;background-color:transparent" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('blank.html') ?>"></iframe>
<!-- IFRAME for request to Authorize.net -->
<iframe id="directpost-iframe" allowtransparency="true" frameborder="0"  name="iframeDirectPost" style="display:none;width:100%;background-color:transparent" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('blank.html') ?>"></iframe>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @escapeNotVerified */ echo $_code ?>" style="display:none;">
    <div class="admin__field _required">
        <label for="<?php /* @escapeNotVerified */ echo $_code ?>_cc_type"
               class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Credit Card Type') ?></span></label>
        <div class="admin__field-control">
            <select id="<?php /* @escapeNotVerified */ echo $_code ?>_cc_type"
                    name="payment[cc_type]"
                    class="required-entry validate-cc-type-select admin__control-select">
                <?php $_ccType = $_form->getInfoData('cc_type') ?>
                <option value=""></option>
                <?php foreach ($_form->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_typeCode ?>"
                            <?php if ($_typeCode == $_ccType): ?>selected="selected"<?php endif ?>><?php /* @escapeNotVerified */ echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?php /* @escapeNotVerified */ echo $_code ?>_cc_number"
               class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Credit Card Number') ?></span></label>

        <div class="admin__field-control">
            <input type="text" id="<?php /* @escapeNotVerified */ echo $_code ?>_cc_number"
                   name="payment[cc_number]"
                   class="input-text required-entry validate-cc-number admin__control-text"
                   value="<?php /* @escapeNotVerified */ echo $block->getInfoData('cc_number') ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?php /* @escapeNotVerified */ echo $_code ?>_expiration"
               class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Expiration Date') ?></span></label>

        <div class="admin__field-control">
            <select id="<?php /* @escapeNotVerified */ echo $_code ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="validate-cc-exp required-entry admin__control-select admin__control-select-month">
                <?php $_ccExpMonth = $_form->getInfoData('cc_exp_month') ?>
                <?php foreach ($_form->getCcMonths() as $k => $v): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $k ?>"
                            <?php if ($k == $_ccExpMonth): ?>selected="selected"<?php endif ?>><?php /* @escapeNotVerified */ echo $v ?></option>
                <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $_form->getInfoData('cc_exp_year') ?>
            <select id="<?php /* @escapeNotVerified */ echo $_code ?>_expiration_yr"
                    name="payment[cc_exp_year]"
                    class="required-entry admin__control-select admin__control-select-year">
                <?php foreach ($_form->getCcYears() as $k => $v): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $k ? $k : '' ?>"
                            <?php if ($k == $_ccExpYear): ?>selected="selected"<?php endif ?>><?php /* @escapeNotVerified */ echo $v ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <?php if ($_form->hasVerification()): ?>
    <div class="admin__field _required">
        <label for="<?php /* @escapeNotVerified */ echo $_code ?>_cc_cid"><span><?php /* @escapeNotVerified */ echo __('Card Verification Number') ?></span></label>

        <div class="admin__field-control">
            <input type="text"
                   class="required-entry input-text validate-cc-cvn admin__control-text"
                   id="<?php /* @escapeNotVerified */ echo $_code ?>_cc_cid" name="payment[cc_cid]"
                   value="<?php /* @escapeNotVerified */ echo $block->getInfoData('cc_cid') ?>"/>
        </div>
    </div>
    <?php endif; ?>
</fieldset>
<script>
    require([
        'prototype',
        'Magento_Sales/order/create/scripts',
        "Magento_Sales/order/create/form",
        'Magento_Authorizenet/js/direct-post'
    ], function(){

        /**
         * Disable card server validation in admin
         */
        order.addExcludedPaymentMethod('<?php /* @escapeNotVerified */ echo $_code ?>');

        <?php if (!$block->isAjaxRequest()): ?>
            document.observe('dom:loaded', function(){
        <?php endif; ?>

        directPostModel = new directPost(
            '<?php /* @escapeNotVerified */ echo $_code ?>',
            'directpost-iframe',
            '<?php /* @escapeNotVerified */ echo $_controller ?>',
            '<?php /* @escapeNotVerified */ echo $_orderUrl ?>',
            '<?php /* @escapeNotVerified */ echo $_method->getCgiUrl() ?>',
            '<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/save', ['_secure' => $block->getRequest()->isSecure()]) ?>');

        <?php if (!$block->isAjaxRequest()): ?>
            });
        <?php endif; ?>
    });
</script>
