<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Magento\Vault\Block\Form $block */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset data-mage-init='{
        "Magento_Vault/js/vault": {
            "code": "<?php echo /* @noEscape */ $code ?>",
            "fieldset": "payment_form_<?php echo /* @noEscape */ $code ?>"
        }
    }' class="admin__fieldset payment-method"
          id="payment_form_<?php echo /* @noEscape */ $code ?>"
          style="display:none"
              >
    <input type="hidden" name="payment[public_hash]" id="<?php echo /* @noEscape */ $code ?>_public_hash" value="" />
    <?php echo $block->getChildHtml() ?>
</fieldset>
