<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\InventoryShipping\Block\Adminhtml\Order\View\Tab\SourceSelection $block */
?>
<?php foreach ($block->getSourceSelections() as $sourceSelection) : ?>
    <table class="data-table admin__table-primary edit-order-table">
        <div class="admin__page-section-item-title">
            <span class="title">
                <?= $block->escapeHtml($this->getSourceName($sourceSelection->getSourceCode())) ?>
            </span>
        </div>
        <thead>
            <tr class="headings">
                <th><span><?= $block->escapeHtml(__('Sku')) ?></span></th>
                <th><span><?= $block->escapeHtml(__('Available Qty')) ?></span></th>
                <th><span><?= $block->escapeHtml(__('Qty to Deduct')) ?></span></th>
            </tr>
        </thead>
        <?php foreach ($sourceSelection->getSourceItemSelections() as $itemSelection) : ?>
            <tr>
                <td><?= $block->escapeHtml($itemSelection->getSku()) ?></td>
                <td><?= $block->escapeHtml($itemSelection->getQtyAvailable()) ?></td>
                <td><?= $block->escapeHtml($itemSelection->getQty()) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endforeach; ?>
