<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="admin__data-grid-export">
    <label for="<?php echo /* @escapeNotVerified */ $block->getId() ?>_export" class="admin__control-support-text">
        <?php echo /* @escapeNotVerified */ __('Export to:') ?>
    </label>
    <select name="<?php echo /* @escapeNotVerified */ $block->getId() ?>_export" id="<?php echo /* @escapeNotVerified */ $block->getId() ?>_export" class="admin__control-select">
        <?php foreach ($block->getExportTypes() as $_type): ?>
            <option value="<?php echo /* @escapeNotVerified */ $_type->getUrl() ?>"><?php echo /* @escapeNotVerified */ $_type->getLabel() ?></option>
        <?php endforeach; ?>
    </select>
    <?php echo $block->getExportButtonHtml() ?>
</div>
