<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<label for="<?php echo $this->getId() ?>_export" class="label">
    <?php echo __('Export to:') ?>
</label>
<select name="<?php echo $this->getId() ?>_export" id="<?php echo $this->getId() ?>_export" class="select">
    <?php foreach ($this->getExportTypes() as $_type): ?>
        <option value="<?php echo $_type->getUrl() ?>"><?php echo $_type->getLabel() ?></option>
    <?php endforeach; ?>
</select>
<?php echo $this->getExportButtonHtml() ?>
