<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Grid\Serializer
 */
?>
<?php $_id = 'id_' . md5(microtime()) ?>
<?php $formId = $block->getFormId()?>
<?php if (!empty($formId)) :?>
<script>
    require([
        'prototype',
        'mage/adminhtml/grid'
    ], function(){
        Event.observe(window, "load", function(){
            var serializeInput  = document.createElement('input');
            serializeInput.type = 'hidden';
            serializeInput.name = '<?php echo $block->getInputElementName()?>';
            serializeInput.id   = '<?php echo $_id?>';
            try {
                document.getElementById('<?php echo $formId?>').appendChild(serializeInput);
                new serializerController('<?php echo $_id?>', <?php echo $block->getDataAsJSON() ?>, <?php echo $block->getColumnInputNames(true) ?>, <?php echo $block->getGridBlock()->getJsObjectName() ?>, '<?php echo $block->getReloadParamName()?>');
            } catch(e) {
                //Error add serializer
            }
        });
    });
</script>
<?php else :?>
<input type="hidden" name="<?php echo $block->getInputElementName()?>"  value="" id="<?php echo $_id?>" />
<script>
    require([
        'mage/adminhtml/grid'
    ], function(){
        new serializerController('<?php echo $_id?>', <?php echo $block->getDataAsJSON() ?>, <?php echo $block->getColumnInputNames(true) ?>, <?php echo $block->getGridBlock()->getJsObjectName() ?>, '<?php echo $block->getReloadParamName()?>');
    });
</script>
<?php endif;?>
