<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Grid\Serializer
 */
?>
<?php $_id = 'id_' . md5(microtime()) ?>
<?php $formId = $block->getFormId()?>
<?php if (!empty($formId)) :?>
<script>
    require([
        'prototype',
        'mage/adminhtml/grid'
    ], function(){
        Event.observe(window, "load", function(){
            var serializeInput  = document.createElement('input');
            serializeInput.type = 'hidden';
            serializeInput.name = '<?= /* @escapeNotVerified */ $block->getInputElementName() ?>';
            serializeInput.id   = '<?= /* @escapeNotVerified */ $_id ?>';
            try {
                document.getElementById('<?= /* @escapeNotVerified */ $formId ?>').appendChild(serializeInput);
                new serializerController('<?= /* @escapeNotVerified */ $_id ?>', <?= /* @escapeNotVerified */ $block->getDataAsJSON() ?>, <?= /* @escapeNotVerified */ $block->getColumnInputNames(true) ?>, <?= /* @escapeNotVerified */ $block->getGridBlock()->getJsObjectName() ?>, '<?= /* @escapeNotVerified */ $block->getReloadParamName() ?>');
            } catch(e) {
                //Error add serializer
            }
        });
    });
</script>
<?php else :?>
<input type="hidden" name="<?= /* @escapeNotVerified */ $block->getInputElementName() ?>"  value="" id="<?= /* @escapeNotVerified */ $_id ?>" />
<script>
    require([
        'mage/adminhtml/grid'
    ], function(){
        new serializerController('<?= /* @escapeNotVerified */ $_id ?>', <?= /* @escapeNotVerified */ $block->getDataAsJSON() ?>, <?= /* @escapeNotVerified */ $block->getColumnInputNames(true) ?>, <?= /* @escapeNotVerified */ $block->getGridBlock()->getJsObjectName() ?>, '<?= /* @escapeNotVerified */ $block->getReloadParamName() ?>');
    });
</script>
<?php endif;?>
