<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Widget\Grid\Serializer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var Serializer $block */
/** @var SecureHtmlRenderer $secureRenderer */

// phpcs:ignore
$_id = 'id_' . md5(microtime());
?>
<?php $formId = $block->getFormId()?>
<?php if (!empty($formId)): ?>
    <?php $scriptString = <<<script
    require([
        'prototype',
        'mage/adminhtml/grid'
    ], function(){
        Event.observe(window, "load", function(){
            var serializeInput  = document.createElement('input');
            serializeInput.type = 'hidden';
            serializeInput.name = '{$escaper->escapeJs($block->getInputElementName())}';
            serializeInput.id   = '{$_id}';
            try {
                document.getElementById('{$escaper->escapeJs($formId)}').appendChild(serializeInput);
                new serializerController('{$_id}', {$block->getDataAsJSON()}, {$block->getColumnInputNames(true)},
                 {$escaper->escapeJs($block->getGridBlock()->getJsObjectName())},
                 '{$escaper->escapeJs($block->getReloadParamName())}');
            } catch(e) {
                //Error add serializer
            }
        });
    });
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else:?>
<input type="hidden" name="<?= $escaper->escapeHtmlAttr($block->getInputElementName()) ?>"  value=""
       id="<?= /* @noEscape */ $_id ?>" />
    <?php $scriptString = <<<script
    require([
        'mage/adminhtml/grid'
    ], function(){
        new serializerController('{$_id}', {$block->getDataAsJSON()}, {$block->getColumnInputNames(true)},
         {$escaper->escapeJs($block->getGridBlock()->getJsObjectName())},
         '{$escaper->escapeJs($block->getReloadParamName())}');
    });
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif;?>
