<?php
/**
 * Copyright 2016 Adobe
 * All Rights Reserved.
 */

/**
 * Account activity template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<a class="link-account-activity"
    href="<?= $block->escapeUrl($block->getUrl('security/session/activity')) ?>"
    id="footer_account_activity"
    target="_blank"
    data-mage-init='{"popupWindow": {
        "windowURL": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('security/session/activity'))) ?>",
        "windowName": "session-activity",
        "width": 600, "height": 600, "top": 50, "left": 50, "resizable": 1, "scrollbars": 1}}'>
    <?= $block->escapeHtml(__('Account Activity')) ?>
</a> |
