<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Account activity template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<a class="link-account-activity"
    href="<?php /* @escapeNotVerified */ echo $block->getUrl('security/session/activity') ?>"
    id="footer_account_activity"
    target="_blank"
    data-mage-init='{"popupWindow": {
        "windowURL": "<?php /* @escapeNotVerified */ echo $block->getUrl('security/session/activity') ?>",
        "windowName": "session-activity",
        "width": 600, "height": 600, "top": 50, "left": 50, "resizable": 1, "scrollbars": 1}}'>
    <?php /* @escapeNotVerified */ echo __('Account Activity') ?>
</a> |
