<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Magento\Checkout\Block\Cart\Totals
 */
?>
<?php if ($this->getTotals()): ?>
    <?php $_colspan = 3; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr class="totals charge">
        <th class="mark" colspan="<?php echo $_colspan; ?>" scope="row">
            <?php echo __('Your credit card will be charged for') ?>
        </th>
        <td class="amount" data-th="<?php echo $this->escapeHtml(__('Your credit card will be charged for')); ?>">
            <?php echo $this->displayBaseGrandtotal() ?>
        </td>
    </tr>
    <?php endif?>
<?php endif; ?>
