
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
$isAnaliticsVisible = $block->getNotification()->isAnalyticsVisible() ? 1 : 0;
$scriptString = <<<script
    define('analyticsPopupConfig', function () {
        return {
            analyticsVisible: {$isAnaliticsVisible},
        }
    });
script;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
