<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<?= /* @noEscape */ $secureRenderer->renderTag(
    'script',
    [
        'src' => $block->getTrackingUrl(),
        'async' => true,
    ],
    '&nbsp;',
    false
) ?>

<?php
/** @var \Magento\AdminAnalytics\ViewModel\Metadata $metadata */
$metadata = $block->getMetadata();
$nonce = $escaper->escapeJs($metadata->getNonce());
$scriptString = '
    var adminAnalyticsMetadata = {
        "secure_base_url": "' . $escaper->escapeJs($metadata->getSecureBaseUrlForScope()) . '",
        "version": "' . $escaper->escapeJs($metadata->getMagentoVersion()) . '",
        "product_edition": "' . $escaper->escapeJs($metadata->getProductEdition()) . '",
        "user": "' . $escaper->escapeJs($metadata->getCurrentUser()) . '",
        "mode": "' . $escaper->escapeJs($metadata->getMode()) . '",
        "store_name_default": "' . $escaper->escapeJs($metadata->getStoreNameForScope()) . '",
        "admin_user_created": "' . $escaper->escapeJs($metadata->getCurrentUserCreatedDate()) . '",
        "admin_user_logdate": "' . $escaper->escapeJs($metadata->getCurrentUserLogDate()) . '",
        "admin_user_role_name": "' . $escaper->escapeJs($metadata->getCurrentUserRoleName()) . '"
    };

    var digitalData = {
        "nonce": "' . $nonce . '"
    };

    var cspNonce = "' . $nonce . '";
';
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
