<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<script src="<?= $block->escapeUrl($block->getTrackingUrl()) ?>" async></script>
<script>
    var adminAnalyticsMetadata = {
        "version": "<?= $block->escapeJs($block->getMagentoVersion()) ?>",
        "user": "<?= $block->escapeJs($block->getCurrentUser()) ?>",
        "mode": "<?= $block->escapeJs($block->getMode()) ?>"
    };
</script>