<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="attributes-edit-form" class="attributes-edit-form" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#attributes-edit-form').mage('form')
        .mage('validation', {validationUrl: '<?php echo $this->getValidationUrl() ?>'});

});
</script>
