<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/* These classes are skipped completely during comparison. */
return [
    'navigationMenu' => [
        Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\ExtractDataFromCategoryTree::class => null,
        Magento\Customer\Model\Session::class => null,
        Magento\Framework\GraphQl\Query\Fields::class => null,
        Magento\Framework\Session\Generic::class => null,
    ],
    'productDetailByName' => [
        Magento\Customer\Model\Session::class => null,
        Magento\Framework\GraphQl\Query\Fields::class => null,
        Magento\Framework\Session\Generic::class => null,
        Magento\Store\Model\GroupRepository::class => null,
    ],
    'category' => [
        Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\ExtractDataFromCategoryTree::class => null,
        Magento\Framework\GraphQl\Query\Fields::class => null,
    ],
    'productDetail' => [
        Magento\Framework\GraphQl\Query\Fields::class => null,
    ],
    'resolveUrl' => [
        Magento\Framework\GraphQl\Query\Fields::class => null,
    ],
    'isCompanyAdminEmailAvailable' => [
        Magento\Framework\MessageQueue\Code\Generator\Config\RemoteServiceReader\Communication::class => null,
        Magento\Framework\Webapi\ServiceInputProcessor::class => null,
        Magento\Framework\MessageQueue\Publisher\Config\RemoteService\Reader::class => null,
        Magento\Framework\Module\ModuleList::class => null,
        Magento\Framework\Module\Manager::class => null,
    ],
    'isCompanyUserEmailAvailable' => [
        Magento\Framework\MessageQueue\Code\Generator\Config\RemoteServiceReader\Communication::class => null,
        Magento\Framework\Webapi\ServiceInputProcessor::class => null,
        Magento\Framework\MessageQueue\Publisher\Config\RemoteService\Reader::class => null,
    ],
    'createCompany' => [
        Magento\Framework\Logger\LoggerProxy::class => null,
        Magento\Framework\Module\ModuleList::class => null,
        Magento\Framework\Module\Manager::class => null,
        Magento\Framework\View\Asset\PreProcessor\Helper\Sort::class => null,
        Magento\Framework\Url\QueryParamsResolver::class => null,
        Magento\Store\Model\Validation\StoreCodeValidator::class => null,
        Magento\Framework\Filter\FilterManager::class => null,
        Magento\Store\Model\Address\Renderer::class => null,
        Magento\Store\Model\Validation\StoreNameValidator::class => null,
        Magento\Store\Model\Validation\StoreValidator::class => null,
        Magento\Developer\Model\Logger\Handler\Debug::class => null,
        Magento\Framework\Logger\Monolog::class => null,
        Magento\Framework\MessageQueue\Code\Generator\Config\RemoteServiceReader\Communication::class => null,
        Magento\Framework\Webapi\ServiceInputProcessor::class => null,
        Magento\Framework\MessageQueue\Publisher\Config\RemoteService\Reader::class => null,
        Magento\Logging\Model\Handler\Controllers::class => null,
        Magento\Quote\Model\Quote\Item\CartItemProcessorsPool::class => null,
        Magento\Customer\Model\Session::class => null,
        Magento\Framework\App\Route\Config\Reader\Proxy::class => null,

        Magento\Catalog\Helper\Product\Flat\Indexer::class => null,
        Magento\Catalog\Helper\Product::class => null,
        Magento\Framework\Translate\Inline::class => null,
        Magento\Customer\Model\CustomerRegistry::class => null,
        Magento\Customer\Model\ResourceModel\Address\Relation::class => null,
        Magento\Framework\Json\Helper\Data::class => null,
        Magento\Directory\Helper\Data::class => null,
        Magento\Customer\Model\ResourceModel\AddressRepository::class => null,
        Magento\Customer\Model\ResourceModel\CustomerRepository::class => null,
        Magento\Framework\Url\Helper\Data::class => null,
        Magento\Backend\Helper\Data::class => null,
        Magento\TestFramework\Mail\Template\TransportBuilderMock::class => null,
        Magento\Customer\Helper\View::class => null,
        Magento\Customer\Model\Customer::class => null,
        Magento\Customer\Model\Authentication::class => null,
        Magento\Framework\Validator\EmailAddress::class => null,
        Magento\Developer\Helper\Data::class => null,
        Magento\Company\Model\ResourceModel\Tree::class => null,
        Magento\Company\Model\StructureRepository::class => null,
        Magento\Company\Model\Company\Delete::class => null,
        Magento\CompanyGraphQl\Model\Company\ValidateCreateCompanyData::class => null,
        MagentoCompany\Model\Customer::class => null,
        Magento\Company\Model\Email\Transporter::class => null,
        Magento\Company\Api\CompanyRepositoryInterface\Proxy::class => null,
        Magento\Company\Model\Email\CustomerData::class => null,
        Magento\Company\Model\Email\Sender::class => null,
        Magento\Backend\Model\Url::class => null,
        Magento\CompanyGraphQl\Model\Company\CreateCompanyAccount::class => null,
        Magento\Company\Model\Role\Validator::class => null,
        Magento\Company\Model\CompanyAdminPermission::class => null,
        Magento\Company\Model\CompanyManagement::class => null,
        Magento\Company\Model\Customer\AttributesSaver::class => null,
        Magento\Company\Model\Customer\CompanyAttributes::class => null,
        Laminas\Validator\EmailAddress::class => null,
        Magento\Company\Model\Customer\ValidateCustomerEmailAddress::class => null,
        Magento\Company\Plugin\Customer\Api\CustomerRepository\Save::class => null,
        Magento\Framework\Pricing\Helper\Data::class => null,
        Magento\Catalog\Helper\Category::class => null,
        Magento\Catalog\Helper\Data::class => null,
        Magento\Company\Model\ResourceModel\Structure\Tree::class => null,
        Magento\Company\Model\Customer::class => null,
        Magento\Tax\Helper\Data::class => null,
        Magento\CustomerBalance\Helper\Data::class => null,
        Magento\GiftCardAccount\Helper\Data::class => null,
        Magento\Weee\Helper\Data::class => null,
        Magento\GiftWrapping\Helper\Data::class => null,
        Magento\Reward\Helper\Data::class => null,
        Magento\NegotiableQuote\Model\Restriction\Admin::class => null,
        Magento\NegotiableQuote\Model\Restriction\Customer::class => null,
        Magento\NegotiableQuote\Helper\Quote::class => null,
        Magento\Catalog\Helper\Product\Configuration::class => null,
        Magento\Bundle\Helper\Catalog\Product\Configuration::class => null,
        Magento\NegotiableQuote\Model\Email\LinkBuilder::class => null,
        Magento\NegotiableQuote\Model\Email\Sender::class => null,
        Magento\NegotiableQuote\Model\Purged\Extractor::class => null,
        Magento\Eav\Model\AttributeDataFactory::class => null,
        Magento\PageCache\Model\Cache\Server::class => null,
        Magento\SharedCatalog\Model\CompanyManagement::class => null,
        Magento\Company\Plugin\Customer\Api\CustomerRepository\Query::class => null,
        Magento\Logging\Helper\Data::class => null,
        Magento\Catalog\Helper\Product\Edit\Action\Attribute::class => null,
        Magento\Newsletter\Model\CustomerSubscriberCache::class => null,
        Magento\Newsletter\Model\SubscriptionManager::class => null,
        Magento\Newsletter\Model\Plugin\CustomerPlugin::class => null,
        Magento\Newsletter\Helper\Data::class => null,
        Magento\CustomerSegment\Model\Customer::class => null,
        Magento\CustomerSegment\Observer\ProcessCustomerEventObserver::class => null,
        Magento\Wishlist\Plugin\SaveWishlistDataAndAddReferenceKeyToBackUrl::class => null,
        Magento\Framework\View\Page\Config\Generator\Head::class => null,
        Magento\Store\Model\Argument\Interpreter\ServiceUrl::class => null,
        Magento\Framework\View\Layout\Argument\Interpreter\Url::class => null,
        Magento\Framework\Css\PreProcessor\Adapter\CssInliner::class => null,
        Magento\Company\Model\Action\Company\ReplaceSuperUser::class => null,
        Magento\Company\Model\CompanySuperUserSave::class => null,
        Magento\Company\Model\CompanyHierarchy::class => null,
        Magento\User\Helper\Data::class => null,
        Magento\User\Model\Notificator::class => null,
        Magento\CompanyCredit\Model\CreditLimitHistory::class => null,
        Magento\CompanyCredit\Model\CreditLimitRepository::class => null,
        Magento\CompanyCredit\Plugin\Company\Model\CompanyCreditCreatePlugin::class => null,
        Magento\CompanyCredit\Plugin\Company\Model\Customer\CompanyPlugin::class => null,






    ],
    '*' => [
        Magento\TestFramework\Interception\PluginList::class => null,
        // memory leak, wrong sql, potential issues
        Magento\Framework\Event\Config\Data::class => null,
        Magento\Framework\App\AreaList::class => null,
        'customRemoteFilesystem' => null,
        Magento\Store\App\Config\Type\Scopes::class => null,
        Magento\Framework\Module\Dir\Reader::class => null,
        Magento\Framework\Module\PackageInfo::class => null,
        Magento\Framework\App\Language\Dictionary::class => null,
        Magento\Framework\ObjectManager\ConfigInterface::class => null,
        Magento\Framework\App\Cache\Type\Config::class => null,
        Magento\Framework\Interception\PluginListGenerator::class => null,
        Magento\TestFramework\App\Config::class => null,
        Magento\TestFramework\Request::class => null,
        Magento\Framework\View\FileSystem::class => null,
        Magento\Framework\App\Config\FileResolver::class => null,
        Magento\TestFramework\ErrorLog\Logger::class => null,
        'translationConfigSourceAggregated' => null,
        Magento\Framework\App\Request\Http\Proxy::class => null,
        Magento\Framework\Event\Config\Reader\Proxy::class => null,
        Magento\Theme\Model\View\Design\Proxy::class => null,
        Magento\Translation\Model\Source\InitialTranslationSource\Proxy::class => null,
        Magento\Translation\App\Config\Type\Translation::class => null,
        Magento\Backend\App\Request\PathInfoProcessor\Proxy::class => null,
        Magento\Framework\View\Asset\Source::class => null,
        Magento\Framework\Translate\ResourceInterface\Proxy::class => null,
        Magento\Framework\Locale\Resolver\Proxy::class => null,
        Magento\MediaStorage\Helper\File\Storage\Database::class => null,
        Magento\Framework\App\Cache\Proxy::class => null,
        Magento\Framework\Translate::class => null,
        Magento\Store\Model\StoreManager::class => null,
        Magento\Framework\App\Http\Context::class => null,
        Magento\TestFramework\Response::class => null,
        Magento\Store\Model\WebsiteRepository::class => null,
        Magento\Framework\Locale\Resolver::class => null,
        Magento\Store\Model\GroupRepository::class => null,
        Magento\Store\Model\StoreRepository::class => null,
        Magento\Framework\View\Design\Fallback\RulePool::class => null,
        Magento\Framework\View\Asset\Repository::class => null,
        Magento\Framework\HTTP\Header::class => null,
        Magento\Framework\App\Route\Config::class => null,
        Magento\Store\Model\System\Store::class => null,
        Magento\AwsS3\Driver\CredentialsCache::class => null,
        Magento\Eav\Model\Config::class => null,
        'AssetPreProcessorPool' => null,
        Magento\GraphQl\Model\Query\ContextFactory::class => null,
        'viewFileMinifiedFallbackResolver' => null,
        Magento\Framework\View\Asset\Minification::class => null,
        Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection::class => null,
        Magento\Framework\Url::class => null,
        Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::class => null,
    ],
    '' => [
    ],
];
