<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Customer\Block\Adminhtml\System\Config\Validatevat;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Validatevat $block */

$merchantCountryField = $escaper->escapeJs($block->getMerchantCountryField());
$merchantVatNumberField = $escaper->escapeJs($block->getMerchantVatNumberField());
$ajaxUrl = $escaper->escapeJs($block->getAjaxUrl());
$errorMessage = $escaper->escapeJs($escaper->escapeHtml(__('Error during VAT Number verification.')));

$scriptString = <<<script
require(['prototype'], function(){

//<![CDATA[
    function validateVat() {
        var validationMessage = $('validation_result');

        params = {
            country: $('{$merchantCountryField}').value,
            vat: $('{$merchantVatNumberField}').value
        };

        new Ajax.Request('{$ajaxUrl}', {
            parameters: params,
            onSuccess: function(response) {
                var result = '{$errorMessage}';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.valid == 1) {
                        validationMessage.removeClassName('hidden').removeClassName('admin__field-error').
                        addClassName('note');
                        validationMessage.setStyle({color:'green'});
                    } else {
                        validationMessage.removeClassName('hidden').addClassName('admin__field-error');
                        if (validationMessage.style.removeProperty) {
                            validationMessage.style.removeProperty('color');
                        } else {
                            validationMessage.style.removeAttribute('color');
                        }
                    }
                } catch (e) {
                    validationMessage.removeClassName('hidden').addClassName('admin__field-error');
                }
                validationMessage.update(result);
            }
        });
    }

    window.validateVat = validateVat;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-validate-vat">
    <p class="admin__field-error hidden" id="validation_result"></p>
    <button class="action-validate-vat" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>"
            style="display:none">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#validation_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'validateVat();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
