<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="page-actions">
    <?php echo $this->getBackButtonHtml() ?>
    <?php echo $this->getResetButtonHtml() ?>
    <span class="hidden" id="formButtons">
        <?php echo $this->getSaveButtonHtml() ?>
    </span>
</div>
<div class="hidden" id="formContainer">
    <?php echo $this->getFormHtml() ?>
</div>
<script type="text/javascript">
require([
    "jquery",
    "mage/mage",
    "mage/backend/form",
    "mage/backend/validation"
], function($){

   $('#edit_form').mage('form').mage('validation');

});
</script>
