<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
$urls = $block->getData('urls');
?>
<h4>
<?=$escaper->escapeHtml(__('The value specified in the URL Key field would generate a URL that already exists.')); ?>
</h4>
<p>
<?=$escaper->escapeHtml(
    __(
        'To resolve this conflict, you can either change the value of the URL Key field '
        . '(located in the Search Engine Optimization section) to a unique value, or change the Request Path fields'
        . ' in all locations listed below:'
    )
);
?>
<?php
if (!empty($urls)) {
    foreach ($urls as $url => $urlTitle) {
        ?>
        <?='<p> - <a href="' . $escaper->escapeHtml($url) . '">' . $escaper->escapeHtml($urlTitle) . '</a></p>'; ?>
        <?php
    }
}
?>
</p>
