<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 ?>
<!--<h4 class="icon-head fieldset-legend <?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderText() ?></h4>-->
<label for="order-comment"><?php echo __('Order Comments') ?></label><br />
<textarea style="width:98%; height:8em;" id="order-comment" name="order[comment][customer_note]" rows="2" cols="15"><?php echo $this->getCommentNote() ?></textarea>
<script type="text/javascript">
	require(["Magento_Sales/order/create/form"], function(){
		order.commentFieldsBind('order-comment')
	});
</script>
