<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="page-create-order">
    <script>
    require(["Magento_Sales/order/create/form"], function(){
        order.setCurrencySymbol('<?php echo $block->getCurrencySymbol($block->getCurrentCurrencyCode()) ?>')
    });
</script>
    <?php if ($block->getCustomerId()): ?>
    <div class="order-sidebar">
        <div class="store-switcher order-currency">
            <label for="currency_switcher"><?php echo __('Order Currency:') ?></label>
            <select id="currency_switcher" name="order[currency]" onchange="order.setCurrencyId(this.value); order.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
                <?php foreach ($block->getAvailableCurrencies() as $_code): ?>
                    <option value="<?php echo $_code ?>"<?php if ($_code == $block->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?> symbol="<?php echo $block->getCurrencySymbol($_code) ?>">
                        <?php echo $block->getCurrencyName($_code) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="customer-current-activity" id="order-sidebar">
            <?php echo $block->getChildHtml('sidebar') ?>
        </div>
    </div>
    <?php endif; ?>
    <div class="order-details<?php if ($block->getCustomerId()): ?> order-details-existing-customer<?php endif; ?>">
        <div class="order-details-inner">
            <div id="order-additional_area" style="display:none" class="fieldset-wrapper order-additional-area"><?php echo $block->getChildHtml('additional_area') ?></div>
            <div id="order-search" style="display:none" class="fieldset-wrapper order-search-items"><?php echo $block->getChildHtml('search') ?></div>
            <div id="order-items" class="order-items fieldset-wrapper" data-mage-init='{"loader": {}}'><?php echo $block->getChildHtml('items') ?></div>
            <div id="order-errors" class="order-errors"><?php echo $block->getChildHtml('errors') ?></div>
            <div id="order-form_account" class="order-account-information fieldset-wrapper"><?php echo $block->getChildHtml('form_account') ?></div>

            <div id="order-addresses" class="order-addresses">
                <div id="order-billing_address" class="order-billing-address"><?php echo $block->getChildHtml('billing_address') ?></div>
                <div id="order-shipping_address" class="order-shipping-address"><?php echo $block->getChildHtml('shipping_address') ?></div>
            </div>

            <div id="order-methods" class="order-methods">
                <div class="order-billing-method">
                    <div class="fieldset-wrapper" id="order-billing_method">
                        <?php echo $block->getChildHtml('billing_method') ?>
                    </div>
                </div>
                <div class="order-shipping-method">
                    <div class="fieldset-wrapper" id="order-shipping_method">
                        <?php echo $block->getChildHtml('shipping_method') ?>
                    </div>
                </div>
            </div>

            <?php if ($block->getChildBlock('card_validation')): ?>
                <div class="order-card-validation" id="order-card_validation">
                    <?php echo $block->getChildHtml('card_validation') ?>
                </div>
            <?php endif; ?>

            <?php echo $block->getChildHtml('gift_options') ?>

            <div class="order-summary">
                <div class="order-history">
                    <fieldset class="fieldset" id="order-comment">
                         <legend class="legend"><span><?php echo __('Order History') ?></span></legend>
                        <?php echo $block->getChildHtml('comment') ?>
                    </fieldset>
                </div>
                <div class="order-totals">
                    <fieldset id="order-totals" class="order-totals-content fieldset">
                        <?php echo $block->getChildHtml('totals') ?>
                    </fieldset>
                </div>
            </div>

        </div>
    </div>
</div>
