<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Adminhtml\Order\Create\Form $block */
?>
<form id="edit_form" data-order-config='<?php echo $block->getOrderDataJson() ?>' data-load-base-url="<?php echo $block->getLoadBlockUrl() ?>" action="<?php echo $block->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <?php echo $block->getBlockHtml('formkey')?>
    <div id="order-message">
        <?php echo $block->getChildHtml('message') ?>
    </div>
    <div id="order-customer-selector" class="fieldset-wrapper order-customer-selector" style="display:<?php echo $block->getCustomerSelectorDisplay() ?>">
        <?php echo $block->getChildHtml('customer.grid.container') ?>
    </div>
    <div id="order-store-selector" class="fieldset-wrapper" style="display:<?php echo $block->getStoreSelectorDisplay() ?>">
        <?php echo $block->getChildHtml('store') ?>
    </div>
    <div id="order-data" style="display:<?php echo $block->getDataSelectorDisplay() ?>">
        <?php echo $block->getChildHtml('data') ?>
    </div>
</form>
