<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Sales\Block\Adminhtml\Order\Create\Form $this */
?>
<form id="edit_form" data-order-config='<?php echo $this->getOrderDataJson() ?>' data-load-base-url="<?php echo $this->getLoadBlockUrl() ?>" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <div id="order-message">
        <?php echo $this->getChildHtml('message') ?>
    </div>
    <div id="order-customer-selector" class="fieldset-wrapper order-customer-selector" style="display:<?php echo $this->getCustomerSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('customer.grid.container') ?>
    </div>
    <div id="order-store-selector" class="fieldset-wrapper" style="display:<?php echo $this->getStoreSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('store') ?>
    </div>
    <div id="order-data" style="display:<?php echo $this->getDataSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('data') ?>
    </div>
</form>
