<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($this->helper('Magento\GiftMessage\Helper\Message')->getIsMessagesAvailable('main', $this->getQuote(), $this->getStoreId())): ?>
<?php $_items = $this->getItems(); ?>
<div id="order-giftmessage" class="giftmessage-order-create box-left">
    <fieldset>
        <legend><?php echo __('Gift Message for the Entire Order') ?></legend>
        <br />
        <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->getIsMessagesAvailable('main', $this->getQuote(), $this->getStoreId())): ?>
            <div class="giftmessage-entire-order">
                <p><?php echo __('If you don\'t want to leave a gift message for the entire order, leave this box blank.') ?></p>
                <?php echo $this->getFormHtml($this->getQuote(), 'main') ?>
            </div>
        <?php endif; ?>
    </fieldset>
    <script type="text/javascript">
require(['Magento_Sales/order/create/form'], function(){

    order.giftmessageFieldsBind('order-giftmessage');
});
</script>
</div>
<?php endif; ?>
