<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Sales\Block\Adminhtml\Order\Create\Items;

/** @var Escaper $escaper */
/** @var Items $block */
?>
<div class="admin__page-section-title">
    <strong class="title"><?= $escaper->escapeHtml($block->getHeaderText()) ?></strong>
    <div class="actions">
        <?= $block->getButtonsHtml() ?>
    </div>
</div>
<?= $block->getChildHtml() ?>
