<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Downloadable product type
 *
 * @var $block \Magento\Downloadable\Block\Catalog\Product\View\Type
 */
?>
<?php $_product = $block->getProduct() ?>

<?php if ($_product->getIsSalable()): ?>
    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
    </div>
<?php else: ?>
    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
    </div>
<?php endif; ?>
<?= $block->getChildHtml() ?>
