<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="dashboard-diagram">
    <div class="dashboard-diagram-switcher">
        <label for="order_<?php echo $this->getHtmlId() ?>_period"><?php echo __('Select Range:') ?></label>
        <select name="period" id="order_<?php echo $this->getHtmlId() ?>_period" onchange="changeDiagramsPeriod(this);">
            <?php foreach ($this->helper('Magento\Backend\Helper\Dashboard\Data')->getDatePeriods() as $value => $label): ?>
                <?php if (in_array($value, ['custom'])) {
    continue;
} ?>
                <option value="<?php echo $value ?>" <?php if ($this->getRequest()->getParam('period') == $value): ?> selected="selected"<?php endif; ?>><?php echo $label ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php if ($this->getCount()): ?>
    <div class="dashboard-diagram-image">
        <img src="<?php echo $this->getChartUrl(false) ?>" class="dashboard-diagram-chart" alt="Chart" title="Chart" />
    </div>
    <?php else: ?>
    <div class="dashboard-diagram-nodata">
        <span><?php echo __('No Data Found') ?></span>
    </div>
    <?php endif; ?>
</div>
