<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div style="padding:5px;">
<?php if (count($this->getCollection()->getItems()) > 0): ?>
    <?php foreach ($this->getCollection()->getItems() as $item): ?>
    <span><?php echo $item->getQueryText() ?></span><br />
    <?php endforeach; ?>
<?php else: ?>
<div class="a-center"><?php echo __('There are no search keywords.') ?></div>
<?php endif; ?>
</div>
