<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if (count($block->getTotals()) > 0) : ?>
<div class="dashboard-totals" id="dashboard_diagram_totals">
    <ul class="dashboard-totals-list">
        <?php foreach ($block->getTotals() as $_total) : ?>
            <li class="dashboard-totals-item">
                <span class="dashboard-totals-label"><?= $block->escapeHtml($_total['label']) ?></span>
                <strong class="dashboard-totals-value">
                    <?= /* @noEscape */ $_total['value'] ?>
                    <span class="dashboard-totals-decimals"><?= /* @noEscape */ $_total['decimals'] ?></span>
                </strong>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
