<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if (sizeof($this->getTotals()) > 0): ?>
<div class="dashboard-totals" id="dashboard_diagram_totals">
    <ul class="dashboard-totals-list">
        <?php foreach ($this->getTotals() as $_total): ?>
            <li class="dashboard-totals-item">
                <span class="dashboard-totals-label"><?php echo $_total['label'] ?></span>
                <strong class="dashboard-totals-value">
                    <?php echo $_total['value'] ?>
                    <span class="dashboard-totals-decimals"><?php echo $_total['decimals'] ?></span>
                </strong>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
