<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Eav\Block\Adminhtml\Attribute\Edit\Js $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "eavInputTypes": {
                "inputTypes": <?= /* @noEscape */ json_encode($block->getComaptibleInputTypes())?>,
                "hints": <?= /* @noEscape */ json_encode($block->getInputTypeHints())?>
            }
        }
    }
</script>
