<?php
/**
 * Copyright 2018 Adobe
 * All Rights Reserved.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="breadcrumbs"></div>
<?php
$widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($viewModel->getJsonConfigurationHtmlEscaped());
$widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['breadcrumbs']);
?>
<script type="text/x-magento-init">
    {
        ".breadcrumbs": {
            "breadcrumbs": <?= /* @noEscape */ $widgetOptions ?>
        }
    }
</script>
