<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image"
     style="width:<?php echo $block->getProductImageView()->getWidth()?>px;
     height:<?php echo $block->getProductImageView()->getHeight()?>px;"
     <?php echo $block->getAddAttribute(); ?>
     src="<?php echo $block->getProductImageView()->getUrl() ?>"
     alt="<?php echo $block->stripTags($block->getProductImageView()->getLabel(), null, true) ?>" />
