<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image <?= $block->escapeHtmlAttr($block->getClass()) ?>"
    <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
        <?php if ($name !== 'class'): ?>
            <?= $block->escapeHtmlAttr($name) ?>="<?= $block->escapeHtmlAttr($value) ?>"
        <?php endif; ?>
    <?php endforeach; ?>
    src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
    width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>" />
