<?php
/**
 * Copyright 2020 Adobe
 * All Rights Reserved.
 */
if ($block->getFormKeyProvider()->isFullPageCacheEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_PageCache/js/form-key-provider": {
                    "isPaginationCacheEnabled":
                        <?= /* @noEscape */ (int)$block->getFormKeyProvider()->isPaginationCacheEnabled() ?>
                }
            }
        }
    </script>
<?php endif; ?>
