<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<div class="block account-nav">
    <div class="title">
        <strong><?php echo $block->escapeHtml(__('My Account')); ?></strong>
    </div>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <?php echo $block->getChildHtml(); ?>
            </ul>
        </nav>
    </div>
</div>
